### ISSUE TITLE
Support of Symbol emojis

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#10]
![image](https://cloud.githubusercontent.com/assets/1673303/24291097/884f323a-10c2-11e7-807a-59943899712d.png)
https://www.webpagefx.com/tools/emoji-cheat-sheet/

It would be nice if we can support `:one:` `:zero:` etc because I hope to use them show the depth of a topic. Numbers are preferable than stars due to their fixed width.

However, even github doesn't seem to support them.
What is the possibility of supporting custom emojis?

**Comment by Gisonrg** [comment]
I think this is probably an issue with unicode as I can't see number emojis in both my editor and Chrome as well (Github replace emoji with pic instead...)

![screen shot 2017-03-25 at 2 37 38 am](https://cloud.githubusercontent.com/assets/4332224/24308694/097ab8ac-1104-11e7-9fcb-d35e1c39710a.png)
As you can see in the above screenshot from the emoji definition list, seems the numbers are not compatible with the OS? Browser?

**Comment by Gisonrg** [comment]
Two solutions possible:
1. Replace numbers with images by writing some logics.
2. We could try use [twemoji](https://github.com/twitter/twemoji) instead of OS native one

**Comment by damithc** [comment]
We don't need a lot of emojis but the few we need should be a good fit.
Ideally, 
1. would like to use names that match our intent e.g. `:1: :extra: :low:`
2. would like to use custom icons if the standard set doesn't have suitable ones. 

Again, not sure how close we can get to the ideal.

**Comment by Gisonrg** [comment]
Added support for number emojis such as `:1:`, `:0:` in `markbind-cli` release 1.2.5. Replaced number emojis with images.
