### ISSUE TITLE
Support tooltip indicator for italic text

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#100]
It seems tooltip/popover/modal indicator (i.e. the dotted underline) does not appear if the text in concern is bold/italic etc.

**Comment by acjh** [comment]
Where does this occur? No problem [here](https://nus-cs2103.github.io/website/):

> For all weeks → Important info about using this website → Using the textbook →
> 
> **Dotted underlines indicate tool tips** (activated by hovering over it) and **dashed underlines indicate modal windows** (activated by clicking) containing additional information.

**Comment by damithc** [comment]
Yup, just realized it works with bold. In that case may be it was the italics that was problematic. It happened y'day, but I didn't have time to post it.

**Comment by damithc** [comment]
It works if I use it this way `_<tooltip>word</tooltip>_` but not if I use it this way `<tooltip>_word_</tooltip>`

**Comment by rachx** [comment]
I think it is due to https://github.com/MarkBind/vue-strap/blob/master/src/Tooltip.vue#L48.
Is there any reason why we only support pure text (i.e. the trigger must have no children)?

**Comment by Gisonrg** [comment]
> Is there any reason why we only support pure text

I think one of the result is pure text is easier to support styling with, and it is less complex to handle.
