### ISSUE TITLE
Dev Guide: Add documentation for currently used markdown-it plugins and rules

### ISSUE THREAD

**Issue by nbriannl** [MarkBind/markbind#1012]
**Is your request related to a problem?**

Currently, we are using quite a significant number of markdown-it plugins and rules for current features, and will be using more plugins and rules for future features (especially for fenced code blocks). It would be difficult to keep track of which plugins are used and for which functionality. 

**Describe the solution you'd like**

Documentation of the plugins would be nice to have. Just a brief overview of
- What plugins/rules we have
- Which plugins/rule enable which functionality.

**Describe alternatives you've considered**

Currently I have to search through the past and current issues and PRs to get an overview. So this is simply a nice-to-have feature.

**Comment by le0tan** [comment]
I can have a try - just one question, all plugins and rules are written in `src/lib/markbind/src/lib/markdown-it/index.js` right?

**Comment by nbriannl** [comment]
To the best of my knowledge, yes. It's a mix of plugins that other people made, and some rules that we made ourselves.

**Comment by nbriannl** [comment]
Are you still on this @le0tan

**Comment by le0tan** [comment]
Nope, I'm not currently working on this. Are you planning to make a PR on this? @nbriannl

**Comment by nbriannl** [comment]
Not anytime soon. Have other PRs ongoing now.
