### ISSUE TITLE
Add indentation support for components

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1015]
When using MarkBind, I find myself needing to indent panels/boxes to match the surrounding contents. 
![image](https://user-images.githubusercontent.com/1673303/73626877-7d007c80-4685-11ea-93cc-e0fdfc49aee6.png)

Normally I do that by wrapping a `<div>` around the component but it does add noise to the code somewhat. I'm wondering if we can provide a attribute such as `indent="20"` to indicate the indentation level for the whole component.

I'm not sure if the same can be achieved using the current `add-class` mechanism; it cannot be used to indent the whole component, right?

ADD: Another place where this feature can be useful is `<include>`

**Comment by acjh** [comment]
Yes, the same can be achieved using `add-class` for `<box>` and `<panel>` etc.

Since `<include>`  does not wrap the contents, it cannot. Instead, do it in the included file.

**Comment by damithc** [comment]
My code:
```html
<box>

Some text
</box>

<div class="indented-level2">
<box>

Some text
</box>
</div>

<box add-class="indented-level2">

Some text
</box>
```
```css
.indented-level2 {
    padding-left: 40px;
}
```
Output:
![image](https://user-images.githubusercontent.com/1673303/73854282-3ec5b180-486d-11ea-8d9c-b7994c2dc8e8.png)

What I want to achieve is the middle one. `add-class` applies the indentation to the box content, not the box itself. Should I use a different css code?

**Comment by acjh** [comment]
Yes, use `margin-left` CSS property instead of `padding-left` .

From https://developer.mozilla.org/en-US/docs/Web/CSS/padding:

> **Note**: Padding creates extra space within an element. In contrast, [`margin`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin) creates extra space around an element.

**Comment by damithc** [comment]
> Yes, use `margin-left` CSS property instead of `padding-left` .

Nice 👍 
In fact, we can use [bootstrap built-in util classes](https://getbootstrap.com/docs/4.4/utilities/spacing/) instead of writing our own (e.g., `box add-clas="ml-2">`, as long as the indentation we want is not too deep.

Let's leave this issue open until we document this as a tip/trick somewhere in the user guide.

**Comment by damithc** [comment]
> Yes, use `margin-left` CSS property instead of `padding-left` .

Works for boxes but not for panels 🤔  perhaps panels override the margin properties?

**Comment by acjh** [comment]
You need to add `d-block` class too, as panel's `card-container` is an inline `<span>`.

**Comment by damithc** [comment]
> You need to add `d-block` class too, as panel's `card-container` is an inline `<span>`.

Got it. Thx 👍
