### ISSUE TITLE
Add markdown support for dropdown header

### ISSUE THREAD

**Issue by le0tan** [MarkBind/markbind#1028]
**Is your request related to a problem?**

https://github.com/MarkBind/markbind/pull/1013#pullrequestreview-354233446

**Describe the solution you'd like**

Support Markdown syntax in `header` attribute of dropdown, keep the behavior of `text` unchanged (i.e. rendered as raw HTML) so that we can get the best of both worlds.

**Note: ** I manually set `text` to take priority over `header`.

Component PR: https://github.com/MarkBind/vue-strap/pull/128

**Comment by ang-zeyu** [comment]
The slot header aside which is still under discussion, I think the `header` attribute should take priority over `text` since we've standardised these sort of attributes #36

**Comment by le0tan** [comment]
> The slot header aside which is still under discussion
I think it's OK if we keep this feature alive - the user doesn't have to make use of it though. 
* if markbind syntax is enough: use `header` attr
* if one-line HTML is needed: use `text` attr
* if complicated HTML is needed: use `header` slot

**Comment by ang-zeyu** [comment]
> > The slot header aside which is still under discussion
> 
> I think it's OK if we keep this feature alive - the user doesn't have to make use of it though.
> 
> * if markbind syntax is enough: use `header` attr
> * if one-line HTML is needed: use `text` attr
> * if complicated HTML is needed: use `header` slot

The 

<div>
<i><strong><span style="color:#FF0000;">R  </span><span style="color:#FF7F00;">A  </span>
      <span style="color:#FFFF00;">I  </span>
      <span style="color:#00FF00;">N  </span>
      <span style="color:#0000FF;">B  </span>
      <span style="color:#4B0082;">O  </span>
      <span style="color:#9400D3;">W  </span>
    </strong></i></div>

in the docs might be a good example use case for it.

On another note, you can use inline html in any attribute that supports markdown as well ( [md-it playground](https://jsfiddle.net/9ukc8dy6/) ).
On these lines, perhaps it'd be nice to add inline md rendering for `text` as well, especially since we have only recently started to deprecate it; and as we shouldn't encourage users raw html in attributes, as mentioned in the comment you linked.

**Comment by le0tan** [comment]
So is it better if we plan the feature like this:

* `text` is the same as `header`, which supports inline markdown, but `text` is labeled as deprecated in the doc
* provide `header` slot for user to do complicated HTML stuff

**Comment by ang-zeyu** [comment]
> So is it better if we plan the feature like this:
> 
> * `text` is the same as `header`, which supports inline markdown, but `text` is labeled as deprecated in the doc
> * provide `header` slot for user to do complicated HTML stuff

Yup, sounds good 👍 

I only just recalled the example use case in the docs; Something like that should look good on the dropdown. @yamgent What do you think?

**Comment by le0tan** [comment]
I implemented the requested changes in https://github.com/MarkBind/markbind/pull/1029
Corresponding vue-strap PR is in https://github.com/MarkBind/vue-strap/pull/128

**Comment by yamgent** [comment]
> @yamgent What do you think?

Yeah sounds fine to me.

**Comment by le0tan** [comment]
Closed in #1029
