### ISSUE TITLE
<box>: Allow slot support for icons

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1030]
Maybe we should add `slot` support for `icon` property? That way, we can
* change color of the icon
* use thumbnails as icons

**Comment by le0tan** [comment]
Probably changing color of the icon can be a property for <box>?

**Comment by damithc** [comment]
> Probably changing color of the icon can be a property for ?

slot is more flexible, right? But I don't know how difficult it is to implement and also if there are other downsides.

**Comment by le0tan** [comment]
Then the feature is already present, just not documented. Will create a PR to add documentation on that.
