### ISSUE TITLE
Plugins not used on included content

### ISSUE THREAD

**Issue by openorclose** [MarkBind/markbind#1032]
**What did you do? Please include the actual source code causing the issue.**

```html
//index.md
<panel src="inc.md"></panel>
<panel><span heading><b>header</b></span> Content of panel</panel>



//inc.md
<panel><span heading><b>header</b></span> Content of panel</panel>
```

**What did you expect to happen?**

Both the contentful panels should look the same.

**What actually happened? Please include the actual, raw output.**
![image](https://user-images.githubusercontent.com/3646725/74080508-a05d6a00-4a7f-11ea-82be-d043b49173e7.png)

This happens because plugins are not rendered on included files.

Should this be documented, or is this a bug?

**Comment by ang-zeyu** [comment]
To be more precise, it's not rendered on dynamic includes ( `<panel>` or `<include dynamic>` ),
but for static `<include>`s it is

**Comment by damithc** [comment]
> Should this be documented, or is this a bug?

I don't think that is intentional. Dynamic panels should look the same as other panels except the content will not be loaded until they are expanded.
