### ISSUE TITLE
Show collapse button for dynamic panels/includes by default

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#104]
For the moment I've done a mass find-and-replace to add `bottom-switch` to all dynamic panels/includes. But I think the longer term solution is to show it by default, just like normal panels.

**Comment by acjh** [comment]
This is actually [enabled](https://github.com/MarkBind/vue-strap/pull/4/files#diff-da693401ef605f3ebdc915c8d01bebfa) for `dynamic-panel` by default.

I'm not sure how differently a dynamic `include` works.
Does a dynamic `include` result in a panel? If so, what makes it different from a `dynamic-panel`?

@Gisonrg Please advise.

**Comment by Gisonrg** [comment]
Try make the bottomSwitch default = true?

**Comment by damithc** [comment]
An `<include src="..." dynamic/>` results in a expandable panel in the rendered view, similar to a `<dyanmic-panel ... />`

**Comment by acjh** [comment]
1. Similar, or equivalent? Having both is difficult to maintain and debug.
1. Where should I look to verify if @Gisonrg's suggestion might work?

**Comment by damithc** [comment]
> Similar, or equivalent? Having both is difficult to maintain and debug.

They just look the same as far as I can tell. Not sure how it is handled internally.

> Where should I look to verify if @Gisonrg's suggestion might work?

Try this code (currently, it will not get a collapse button):
`<include src="test.md" dynamic/>`
Same for this one
`<dynamic-panel src="test.md" />`

**Comment by acjh** [comment]
`default: true` works for
- `<include src="test.md" dynamic />`

but not
- `<dynamic-panel src="test.md" />`

😕

**Comment by acjh** [comment]
So the [enabled](https://github.com/MarkBind/vue-strap/pull/4/files#diff-da693401ef605f3ebdc915c8d01bebfa)-by-default for `dynamic-panel` works only in the [demo](http://rawgit.com/acjh/vue-strap/23-panel-add-collapse-at-bottom/#accordion).

**Comment by damithc** [comment]
@acjh what's the best way forward from what you have tried so far? It's ok if you want to spend more time to try out different things. I can use the `bottom-switch` for the time being. Also, I can use `dynamic-panel` instead of `<include src="test.md" dynamic />` because the latter is just a shortcut.

**Comment by acjh** [comment]
> `default: true` works for
> - `<include src="test.md" dynamic />`
>
> but not
> - `<dynamic-panel src="test.md" />`

Ignore that - I tried again and both work. Can you verify on your side?

Published: `npm i -g markbind-cli@1.4.2`

**Comment by acjh** [comment]
Okay, I found where dynamic `include` is converted to `dynamic-panel` ([lib/parser.js#L44-L55](https://github.com/MarkBind/markbind/blob/d0a849622643bf25a778287c9584223df57ddd04/lib/parser.js#L44-L55))
and where `dynamic-panel` is converted to `panel` ([lib/parser.js#L192-L208](https://github.com/MarkBind/markbind/blob/d0a849622643bf25a778287c9584223df57ddd04/lib/parser.js#L192-L208)) for future reference.

Moving forward, I feel that dynamic `include` should be deprecated in favor of maintainability.
Of course, I will leave it alone for now and existing usage can be converted after the semester.

**Comment by damithc** [comment]
Tried it and it's working. 👍 💯

**Comment by damithc** [comment]
> Moving forward, I feel that dynamic include should be deprecated in favor of maintainability.

Yes, I'm fine with that. As far as I can see, it's just a shortcut.
