### ISSUE TITLE
Implement warning logging when inconsistent or deprecated attributes are used

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1048]
**Is your request related to a problem?**

Discussion here https://github.com/MarkBind/vue-strap/pull/118#discussion_r378933607

We can warn the user at compile time of inconsistent attributes / slots used in components simultaneously.

**Describe the solution you'd like**

Implement warning logging in for various components

- Boxes
  - `light` vs `seamless` option
  - `no-xx` vs `xx` attributes ( e.g. `no-icon` + `icon` )
  - `no-background/border` and `seamless` option
- All components
  - warn about deprecated attributes
  - warn about inconsistent `slot` + `attribute` ( that also translates to the slot ) choices ( e.g. using `content` attribute and `content` slot for popovers at the same time )

**Comment by damithc** [comment]
@ang-zeyu is there a way to disable deprecation warnings?

**Comment by nbriannl** [comment]
@damithc There isn't a current way to disable.

**Comment by damithc** [comment]
> @damithc There isn't a current way to disable.

OK. No worries.
