### ISSUE TITLE
Support modals within modals

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#105]
Is it possible to allow modals to work within other modals?

![image](https://user-images.githubusercontent.com/1673303/31708456-9bd28da4-b421-11e7-89f3-b28f0a77e18a.png)

**Comment by rachx** [comment]
I was able to get modal working within modals
```html
<trigger for="modal:modal-example" trigger="click">modal windows</trigger>

<modal title="Modal Example" id="modal:modal-example">
  Additional info
  <trigger for="modal:second" trigger="click">second modal</trigger>
</modal>

<modal title="Modal Second" id="modal:second">
  Second
</modal>
```

**Comment by damithc** [comment]
🤔 This is not possible if the the model content is coming for another file, right? in that case the second modal will be inside the first modal.

```html
<trigger for="modal:modal-example" trigger="click">modal windows</trigger>

<modal title="Modal Example" id="modal:modal-example">
  <include src="foo.md"/>
</modal>
```
foo.md:
```html
Additional info
<trigger for="modal:second" trigger="click">second modal</trigger>

<modal title="Modal Second" id="modal:second">
  Second
</modal>
```

**Comment by nusjzx** [comment]
This syntax is not working. 
`<trigger for="modal:modal-example" trigger="click">modal windows</trigger>

            <modal title="Modal Example" id="modal:modal-example">
                Additional info
                <trigger for="modal:second" trigger="click">second modal</trigger>
                <modal title="Modal Second" id="modal:second">
                    Second
                </modal>
            </modal>
`

**Comment by nusjzx** [comment]
The following syntax is not working.
`
<trigger for="modal:modal-example" trigger="click">modal windows</trigger>

            <modal title="Modal Example" id="modal:modal-example">
                Additional info
                <trigger for="modal:second" trigger="click">second modal</trigger>
                <modal title="Modal Second" id="modal:second">
                    Second
                </modal>
            </modal>
`

**Comment by nusjzx** [comment]
The following code is not working .
```
<trigger for="modal:modal-example" trigger="click">modal windows</trigger>

            <modal title="Modal Example" id="modal:modal-example">
                Additional info
                <trigger for="modal:second" trigger="click">second modal</trigger>
                <modal title="Modal Second" id="modal:second">
                    Second
                </modal>
            </modal>
```
