### ISSUE TITLE
puml files not rendered under some conditions

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1050]
Steps:
* Run https://github.com/nus-cs2103/website-base in the master branch (note: need to pull the submodule as well)
* The same section shows puml files in one place but not in another place.

/website/schedule/week6/topics.html
![image](https://user-images.githubusercontent.com/1673303/75007442-1c0fdb80-54b0-11ea-8019-0ecd42317e04.png)

/website/se-book-adapted/chapters/uml.html#calls-to-static-methods
![image](https://user-images.githubusercontent.com/1673303/75007545-714bed00-54b0-11ea-9fae-10227888f31c.png)

**Comment by ang-zeyu** [comment]
Is this related to #1032? ( plugins not used on dynamic includes / panels )

**Comment by damithc** [comment]
Yes, looks like it. It doesn't happen if I use a regular `include` instead of providing the source location as the `src` of the panel.

**Comment by damithc** [comment]
I've pushed a workaround to the `book` submodule for the time being. To reproduce the bug, need to go back a few commits in the `book` submodule.

**Comment by ang-zeyu** [comment]
> I've pushed a workaround to the `book` submodule for the time being. To reproduce the bug, need to go back a few commits in the `book` submodule.

Noted 👍 

I've looked at the original PR #474 that introduced plugins but couldnt find anything that mentioned why plugins were omitted from dynamic dependencies.
Might have just been an oversight, but would be good to investigate more

@openorclose are you working on this?

**Comment by openorclose** [comment]
> > I've pushed a workaround to the `book` submodule for the time being. To reproduce the bug, need to go back a few commits in the `book` submodule.
> 
> Noted +1
> 
> I've looked at the original PR #474 that introduced plugins but couldnt find anything that mentioned why plugins were omitted from dynamic dependencies.
> Might have just been an oversight, but would be good to investigate more
> 
> @openorclose are you working on this?

I'll open a pr for it!
