### ISSUE TITLE
Tool tips and popovers should be indicated by dotted lines, not dashed lines

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1053]
v2.11.0
![image](https://user-images.githubusercontent.com/1673303/75214811-bc744180-57c9-11ea-89fa-ac2c092706b4.png)

Problem: tooltips/popovers should be indicated by dotted underlines while dashed underlines are to be used for indicating modal windows.

**Comment by yash-chowdhary** [comment]
We already seem to use the `underline dotted` style for tooltips and popovers. 
For triggers, however, we only use the `dotted` style for triggers that are not `click` triggers. 

A fix for this issue would just involve enforcing `underline dashed` style for all triggers -

<img width="176" alt="Screenshot 2020-02-25 at 2 17 30 PM" src="https://user-images.githubusercontent.com/21968718/75230400-90f95300-57d9-11ea-9a7b-d895dc2749a1.png">

**Comment by damithc** [comment]
By the way, modal links don't seem to show the hand icon when hovered over, which is important to indicate that the link is clickable.

**Comment by alyip98** [comment]
Are we differentiating the style by the type of content it supports (modal/tooltip/popover), or the type of trigger (hover/click)?

From a UX perspective it might make more sense to style elements by the type of trigger rather than the type of content. For example, a user should expect all underline dotted to be clickable and underline dashed to be hover-able.

**Comment by damithc** [comment]
> From a UX perspective it might make more sense to style elements by the type of trigger rather than the type of content. For example, a user should expect all underline dotted to be clickable and underline dashed to be hover-able.

Good point. I guess because I never change the default trigger type, I tend to equate the content type to the trigger type. The correct thing to do is to match the style to the trigger type; dots for hover and dash for click.

**Comment by openorclose** [comment]
> > From a UX perspective it might make more sense to style elements by the type of trigger rather than the type of content. For example, a user should expect all underline dotted to be clickable and underline dashed to be hover-able.
> 
> Good point. I guess because I never change the default trigger type, I tend to equate the content type to the trigger type. The correct thing to do is to match the style to the trigger type; dots for hover and dash for click.

This was already the case in previous markbind versions (hover had underline dotted and click had underline dashed), but during the migration to bootstrap-vue the correct styles were not set for click triggers.

**Comment by damithc** [comment]
Reopening as the problem is still there.

**Comment by openorclose** [comment]
> Reopening as the problem is still there.

Probably a regression, opened another PR to fix it.
