### ISSUE TITLE
Add pageNav to the Using Plugins Page

### ISSUE THREAD

**Issue by Tejas2805** [MarkBind/markbind#1059]
**Is your request related to a problem?**

The Using Plugins Page is long and doens't have a pageNav like other long pages. This makes it difficult to navigate the page

**Describe the solution you'd like**

Let's add a pageNav to the page.

**Describe alternatives you've considered**

N.A.

**Additional context**

N.A.

**Comment by nbriannl** [comment]
Fixed by #1062
