### ISSUE TITLE
 Importing logger from componentParser.js cause parser.test.js to fail

### ISSUE THREAD

**Issue by nbriannl** [MarkBind/markbind#1060]
**Is your request related to a problem?**

In MarkBind Version: 2.11.0, I have an issue when importing logger from componentParser.js cause parser.test.js to fail.
For example, calling it accordingly as here https://github.com/MarkBind/markbind/blob/8005582e60e8f917c2629d5f81742b103133659f/src/lib/markbind/src/parsers/componentParser.js#L7

will cause `parser.test.js` to fail as shown below. 
![image](https://user-images.githubusercontent.com/27397021/75412021-26bceb80-595c-11ea-9f00-dfcf0979425c.png)

As @ang-zeyu has pointed out, this occurs for parser.js as well, which is likely the reason logger isn't used in there as well.

The issue is that parser.test.js mocks the whole fs module, which causes the DailyRotateFile constructor to fail automatically in finding the directory.

**Describe the solution you'd like**

A simple fix would be to only mock the specific functions of fs relavant to parser.test.js

(Describe your proposed solution here.)

**Describe alternatives you've considered**

(Write your answer here.)

**Additional context**

(Write your answer here.)

**Comment by ang-zeyu** [comment]
Occurs for `parser.js` as well, which is likely the reason `logger` isn't used in there as well.

Issue is that `parser.test.js` mocks the whole `fs` module, which causes the `DailyRotateFile` constructor to fail automatically in finding the directory.
A simple fix would be to only mock the specific functions of `fs` relavant to `parser.test.js`

Perhaps this issue could be renamed as such

Thereafter a new issue could be opened `Standardise usage of console.log and logger.log`, which would also move the logger file to the markbind lib

**Comment by nbriannl** [comment]
What shall i renamed the issue as?

**Comment by nbriannl** [comment]
This behavior no longer appears due to the mocking of the entire logger module in #1117, However, it would be more ideal if we use mocked and unmocked instances of `fs` in appropriate sections.

**Comment by ang-zeyu** [comment]
Resolved by #1207
