### ISSUE TITLE
Code/Output mismatch in siteNav section

### ISSUE THREAD

**Issue by Tejas2805** [MarkBind/markbind#1064]
**Tell us about your environment**

MacOS

* **MarkBind Version:**

Latest(2.11.0)

**What did you do? Please include the actual source code causing the issue.**
![Screen Shot 2020-02-28 at 3 20 01 AM](https://user-images.githubusercontent.com/35946746/75479159-03d11c80-59da-11ea-8bc4-0dba8486762a.png)

**What did you expect to happen?**
Expected  Contact to also be present

**What actually happened? Please include the actual, raw output.**
![Screen Shot 2020-02-28 at 3 20 15 AM](https://user-images.githubusercontent.com/35946746/75479197-10ee0b80-59da-11ea-86da-7cb6d6bdb53a.png)

**Comment by nbriannl** [comment]
Thanks for raising this up. This is a documentation issue in `siteNavigationMenus.mbdf`.
