### ISSUE TITLE
Upgrade js-beautify and provide a site configuration option to turn it on

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1067]
**Is your request related to a problem?**

Performance of markbind

**Describe the solution you'd like**

Build times for 2103 site:

Before: **98s**
Removing js-beautify: **76s**
Upgrading js-beautify: **85s**

There's a significant benefit to build times in either option.

If we remove it, editing html post build would be less friendly for the user ( do we want them to edit it post build though? @damithc ), and on the other hand inspecting test output when updating test files may also be harder for us.
The performance benefits are clear in this case though, and its also one less tool in the page build process to consider when maintaining.

Upgrading it would be the other option here, which apart from performance benefits ( also quite significant ) has a few bug fixes. ( https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md ) ( we are on `1.7.5` currently )

**Edit:** Third option [first comment](https://github.com/MarkBind/markbind/issues/1067#issuecomment-592910308)

Upgrade js-beautify, but also provide a configuration option in `site.json` to turn on js-beautify for html files, which would be off by default.
For our test_sites, we could keep it turned on to make it easier to review changes to expected test files in PRs.

Which should we go with?

**Describe alternatives you've considered**
na

**Additional context**
Inspecting the annotations and commit history for `js-beautify`, it seems this was added in the very early stages of markbind.
Over time a lot of functionality has been added though, which increased the overhead of beautifying html files significantly.

If we don't want editing html files post build to be as user friendly as possible ( mainly the indents, picture below ), removing it at this stage may be the better option.

![indentgone](https://user-images.githubusercontent.com/3306138/75602602-d8e1e800-5b01-11ea-89cc-07f9f64f1552.png)

**Comment by damithc** [comment]
> If we remove it, editing html post build would be less friendly for the user ( do we want them to edit it post build though? @damithc ), and on the other hand inspecting test output when updating test files may also be harder for us.

We don't expect users to edit the generated html files but I do happen to look at the generated files for debugging purposes, on rare occasions. 
I don't mind removing it. The alternative is to upgrade but disable by default. Not sure if it is worth the effort though.

**Comment by ang-zeyu** [comment]
> We don't expect users to edit the generated html files but I do happen to look at the generated files for debugging purposes, on rare occasions.
> I don't mind removing it. The alternative is to upgrade but disable by default. Not sure if it is worth the effort though.

Good idea, it would be pretty simple to implement it as a new configuration option in `site.json`, and we can keep this toggled on for our functional test sites, getting the best of both options.

**Comment by yash-chowdhary** [comment]
I'd like to take a look at this
