### ISSUE TITLE
Support multiple inclusions of a modal

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#107]
Currently, the following code in a single file will cause problems if `foo.md` has  modal in it. The reason is the same trigger id is used twice in the same file. --> clicking on the modal link will behave erratically.
```html
...
<include src="foo.md"/>
...
<include src="foo.md"/>
```

**Comment by damithc** [comment]
Raising priority because this has no workaround.

**Comment by rachx** [comment]
I am trying to fix this.
What do you mean by behave erratically?
From what I observe, multiple modals get triggered and then they all have to be closed individually

**Comment by damithc** [comment]
> From what I observe, multiple modals get triggered and then they all have to be closed individually

Even if the modal link appears multiple times in a page, when I click on one of those modal links, only one modal should pop up, right?

**Comment by rachx** [comment]
Yes. I was asking if that was the only erratic behavior. Probably can make a PR soon

**Comment by damithc** [comment]
> Yes. I was asking if that was the only erratic behavior. Probably can make a PR soon

Correct. That's the 'erratic' behavior.
