### ISSUE TITLE
Anchor navigation in panel not working properly with fixed header

### ISSUE THREAD

**Issue by le0tan** [MarkBind/markbind#1071]
**Tell us about your environment**

* **MarkBind Version:**2.11.0

**What did you do? Please include the actual source code causing the issue.**
1. Fix the header with `<header class="header-fixed">` in `header.md`
2. Include the following content
```html
<panel header="## Hello">
</panel>
```

**What did you expect to happen?**

Anchor navigation on "Hello" should work properly.

**What actually happened? Please include the actual, raw output.**

Clicking the anchor would place the title under the top navbar.

**Comment by le0tan** [comment]
@marvinchin help wanted: looks like the dummy span is correctly inserted but why the navigation breaks in this case?

**Comment by marvinchin** [comment]
@le0tan Seems like `const headingElement = document.getElementById(window.location.hash.slice(1));` is getting us the wrong element.
<img width="305" alt="Screenshot 2020-03-01 at 9 20 18 PM" src="https://user-images.githubusercontent.com/17447681/75626447-a0760300-5c02-11ea-8186-a8a9d44b135a.png">
