### ISSUE TITLE
Built-in Variable timestamp: support specifying a time zone

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1072]
Current: [the variable](https://markbind.org/userGuide/reusingContents.html#built-in-variable-timestamp) is always in GMT

Suggestion: give a way to output the timestamp in a specific timezone

Rationale: If the website is specific to a location e.g., our own module websites, it makes more sense to use the local time in the timestamp

**Comment by yash-chowdhary** [comment]
Would it be advisable to ask the user to set the variable in `site.json` like so - 
```json
{
"timeZone": "Australia/Brisbane"
}
```
We could also enable customization of the locale (using a `"locale"` key in the above file).

The other option for setting the locale would be that we fix it. The main options are `en-US` and `en-GB`.

E.g. `en-US` (12H system) would look like:
`Sun, Mar 1, 2020, 9:02:49 PM GMT+10` 
Singapore time would thus be -
`Sun, Mar 1, 2020, 7:01:08 PM GMT+8`

vs `en-GB` (24H system) :
`Sun, 1 Mar 2020, 21:03:05 GMT+10`
Singapore time would thus be -
`Sun, 1 Mar 2020, 19:01:28 GMT+8`

I will proceed based on the feedback.

**Comment by crphang** [comment]
> Would it be advisable to ask the user to set the variable in `site.json` like so -

sounds alright to me
