### ISSUE TITLE
Support visualizing code patches

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1080]
I wonder if it is useful for our target users to be able to visualize code patches in their pages e.g.,
![image](https://user-images.githubusercontent.com/1673303/75734002-bafaca00-5d31-11ea-92c0-5a014f0949cf.png)

For example, when writing a programming tutorial and want to show how to modify the code from the previous step.

**Comment by acjh** [comment]
What we want that a Markdown diff block does not have?

Input:

````
```diff
- const time = ...
+ const timeZone = ...
```
````

Output:

```diff
- const time = ...
+ const timeZone = ...
```

**Comment by damithc** [comment]
> What do we want that a Markdown diff block does not have?

Oh, didn't realize that existed.  Nice.
