### ISSUE TITLE
Difference in the way shown to the user

### ISSUE THREAD

**Issue by Tejas2805** [MarkBind/markbind#1091]
**Tell us about your environment**
MacOs

* **MarkBind Version:**
Latest(Master)

**What did you do? Please include the actual source code causing the issue.**
The page - `Tweaking the page structure` shows the same format differently. Let's make it consistent. 
![Screen Shot 2020-03-07 at 12 14 36 AM](https://user-images.githubusercontent.com/35946746/76101039-b58ad180-6008-11ea-8a82-ea6dd6cc90e4.png)

![Screen Shot 2020-03-07 at 12 14 46 AM](https://user-images.githubusercontent.com/35946746/76101045-b7549500-6008-11ea-8be7-2a243141d795.png)

**What did you expect to happen?**
Both to have same format.

**What actually happened? Please include the actual, raw output.**
N.A/

**Comment by Tejas2805** [comment]
Which is the better way to show? Will create a PR accordingly.

**Comment by damithc** [comment]
After https://github.com/MarkBind/markbind/pull/1034 is released, we can use headers for code blocks.

**Comment by Tejas2805** [comment]
Fixed by #1086
