### ISSUE TITLE
User Guide: remove line numbers from some code blocks 

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1093]
I think there is no need for line numbers when the code block is not actually showing code e.g.,
![image](https://user-images.githubusercontent.com/1673303/76142302-37313c80-60a7-11ea-951b-76234a99cc43.png)

**Comment by nbriannl** [comment]
I think issue could be expanded to updating the User Guide to utilize the new code block features when appropriate.
For example
![image](https://user-images.githubusercontent.com/27397021/76317906-df4d3c80-6317-11ea-96b2-6d0b92e4a99c.png)
Could be update to put the file names as code block headings.

**Comment by damithc** [comment]
I don't think we want these line numbers too (@crphang ?):
![image](https://user-images.githubusercontent.com/1673303/77556630-ba4df180-6ef3-11ea-83fa-2ec400d278ff.png)

**Comment by crphang** [comment]
Yes, those should ideally not have line number :+1:
