### ISSUE TITLE
Octicons: support different modes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1095]
Octicon seems to have three modes dark/light/grid. Is there any way to support those modes? Not important though.

**Comment by le0tan** [comment]
I'm not seeing Octicon supporting these modes in their documentation. Could you please post a link to where you see that?
Meanwhile, I can add class support to these icons: `:octicon-git-pull-request~close:` will add `class="close"` to the generated SVG.

**Comment by damithc** [comment]
I was guessing, based on this:
![image](https://user-images.githubusercontent.com/1673303/76675350-3cd0da00-65f3-11ea-97df-ef00f0772778.png)

**Comment by le0tan** [comment]
![image](https://user-images.githubusercontent.com/28982486/76675373-83263900-65f3-11ea-9fcb-5baaa2547ad8.png)

Looks like it's changing the class of the wrapper div. Adding class support to the icons should do the same, I think.

**Comment by damithc** [comment]
> Meanwhile, I can add class support to these icons: `:octicon-git-pull-request~close:` will add `class="close"` to the generated SVG.

For fontawsome, the mode is added in front (e.g., `:far-home:` vs `:fas-home:`). It's better if this can be similar from user POV.
