### ISSUE TITLE
Incomplete pageNav in tweaking the page structure page

### ISSUE THREAD

**Issue by Tejas2805** [MarkBind/markbind#1097]
* **MarkBind Version:**
Latest master

**What did you do? Please include the actual source code causing the issue.**
N.A.

**What did you expect to happen?**
Expected `filterTags` to be displayed in the pageNav.

**What actually happened? Please include the actual, raw output.**
`filterTags` is not displayed in the pageNav. 

![Screen Shot 2020-03-08 at 5 46 08 AM](https://user-images.githubusercontent.com/35946746/76152941-4bedee80-6100-11ea-98bc-1e8eed3d01c7.png)

**Comment by damithc** [comment]
I guess the level of the heading needs to be raised, and the heading probably needs to be shortened too (to match other headings).
