### ISSUE TITLE
How to use multiple features for code blocks

### ISSUE THREAD

**Issue by Tejas2805** [MarkBind/markbind#1098]
**Is your request related to a problem?**
Nope. It is a request for documentation.

There is no example shown regarding how to use multiple features with code blocks.

**Describe the solution you'd like**

Give an example using multiple feature of code blocks so that it becomes easier for the 
user to see and understand. 

**Describe alternatives you've considered**

N.A.

**Additional context**

N.A.

**Comment by damithc** [comment]
I guess the level of the heading needs to be raised, and the heading probably needs to be shortened too (to match other headings).

**Comment by Tejas2805** [comment]
@damithc Sorry a bit confused. Is your comment for Issue #1097 ?
