### ISSUE TITLE
Special Tags have parsing issues when closed with <tag /> instead of <tag></tag>

### ISSUE THREAD

**Issue by crphang** [MarkBind/markbind#1099]
**Tell us about your environment**
Latest Master

* **MarkBind Version:**
2.11.0
**What did you do? Please include the actual source code causing the issue.**

For any plugin, register a special tag:
```
getSpecialTags: () => ['testtag'],
```

In any markbind document, we could write normally as:

```
<testtag />

<testtag>
Some document
</testtag>
```

**What did you expect to happen?**

When running markbind build: The produced result remain as:

```
<testtag />

<testtag>
Some document
</testtag>
```
regardless of whether it is a special tag.

**What actually happened? Please include the actual, raw output.**

The second testtag's closing bracket is removed, leading to some parsing error downstream from cheerio.

![image](https://user-images.githubusercontent.com/4986717/76160072-ce5aca80-6161-11ea-924d-2d67581420bf.png)

** More examples **

See #1100:
In the case of using puml as a special tag, existing usages of having:
```
<puml src="a.puml" />

<puml src="b.puml" />

<puml src="c.puml" />
```

would not work as only the other puml tags will not be parsed accordingly from cheerio.

**Comment by ang-zeyu** [comment]
Hmm, this is actually the standard behaviour for `script/style` tags ( spec does not allow `<script ... />` ).

I could either
- allow this for script / style tags as well ( less performance heavy, but it would break once in the browser )
- or include more code to allow special self closing tags for the injected tags only.
- or necessitate opening/closing tags for special tags, e.g. inline puml would have another `<puml-inline>` tag

Which should we go with? @crphang

**Comment by crphang** [comment]
Thanks for quick response @ang-zeyu  :tada: 

Option (2) seems like the best. Would be great if you already have an approach for it.

Option (3) can be done, but I would suppose it could get awkward when we would have to handle inline and src differently for all other plugins going forward

**Comment by ang-zeyu** [comment]
I went with option 2 #1101; The approach also turned out to be less problematic than I expected! ( though a little hard-coding was involved ( but documented ))
