### ISSUE TITLE
Stronger support for popovers

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#11]
This is what I'm trying to achieve. The current popover needs some enhancements before we can achieve this level.

![image](https://cloud.githubusercontent.com/assets/1673303/24292273/944a8170-10c7-11e7-9dba-e39d81ed4c15.png)

On the code side, something like this would be ideal but not sure how close we can get.

```markdown
These solutions are collectively known as _design patterns_, a term popularized 
by the seminal book *Design Patterns: Elements of Reusable Object-Oriented Software* 
the so-called {{“Gang of Four”}}(gof-tip) (GoF): Eric Gamma, Richard Helm, 
Ralph Johnson and John Vlissides. 
```
Somewhere else in the file ...
```
<popover-content id="gof-tip">
<pic src="introduction/book-designpatterns.jpg" width="400px">
Lorem ipsum dolor sit ...
</popover-content>

OR

<popover-content id="gof-tip" src="gof-tip.md"/>
```

**Comment by Gisonrg** [comment]
`trigger` should fix the issue now, though we haven't implement the markdown syntax for it.
