### ISSUE TITLE
Document multiple markdown-it-attrs for users

### ISSUE THREAD

**Issue by Tejas2805** [MarkBind/markbind#1106]
**Tell us about your environment**

MacOS

* **MarkBind Version:**
Latest master

**What did you do? Please include the actual source code causing the issue.**

````html
```xml {heading="Heading title", highlight-lines="2"}
<foo>
  <bar type="name">goo</bar>
</foo>
```
````

**What did you expect to happen?**

The `,` shouldn't have appeared in the heading title.

**What actually happened? Please include the actual, raw output.**
![Screen Shot 2020-03-09 at 3 24 34 PM](https://user-images.githubusercontent.com/35946746/76191404-3ff64f80-621a-11ea-856f-f03de0f3069c.png)

Can check PR #1105

**Comment by damithc** [comment]
> The `,` shouldn't have appeared in the heading title.

Should there be a comma in the code in the first place?
I was trying this feature earlier, and in the absence of documentation, 
I ended up using `{heading="x" highlight-lines="2"}` which seems to work.

@openorclose @nbriannl what's the correct syntax to use? comma or just space?

**Comment by nbriannl** [comment]
Just a space. I see that there's an issue raised regarding documentation, I will work on that soon if noone is on it.

**Comment by nbriannl** [comment]
Having that said, this is not a bug. The syntax for multiple code-block features does not include a comma, just a space.

**Comment by ang-zeyu** [comment]
Same goes for other markdown using `markdown-it-attrs` as well
https://www.npmjs.com/package/markdown-it-attrs
Supported syntax: `{.class #identifier attr=value attr2="spaced value"}`

Perhaps a documentation update regarding markbind's use of `markdown-it-attrs` is due though, since its used for many other things besides code blocks

**Comment by nbriannl** [comment]
Are there other markbind features where multiple `markdown-it-attrs` are used, other than code blocks?

**Comment by Tejas2805** [comment]
Maybe this can be added to `tips and tricks`?

**Comment by ang-zeyu** [comment]
> Are there other markbind features where multiple `markdown-it-attrs` are used, other than code blocks?

Any markdown can use it ( paragraphs, lists, code blocks, inline markdown, etc. ), its sort of an unmentioned feature.

> Maybe this can be added to `tips and tricks`?

Perhaps a sub-section under `formatting contents` would be better, since its a feature with quite a few use cases we don't want the user to miss.

**Comment by Tejas2805** [comment]
Changing issue name accordingly.

**Comment by ang-zeyu** [comment]
@Tejas2805 are you working on this?

I've raised it to medium priority as use of `markdown-it-attrs` is rather obscure compared to nunjucks, and can cause apparent bugs to the user that is actually expected behaviour ( see #1196 )

**Comment by Tejas2805** [comment]
Sure. Will have a PR up shortly.
