### ISSUE TITLE
Code blocks: support specifying a starting line number

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1114]
Suggestion: for code blocks, support specifying a starting line number.
Reason: 
* When there are multiple code blocks in a near vicinity, this feature will allow the a code block line numbers to continue from the previous code block. e.g., first code block has lines 1-5, the second one can be set to start from 6. 
* Also, it is useful when quoting a subset of lines from a longer code block that is already in the page (the sub set of lines can be set to follow the same line numbers they had in the longer code block.

**Comment by damithc** [comment]
IIRC, I think this was originally suggested by @alyip98 (?) somewhere in an earlier thread.

**Comment by acjh** [comment]
Yes, in https://github.com/MarkBind/markbind/pull/991#issuecomment-577279808.
