### ISSUE TITLE
code blocks header: need a margin on top?

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1124]
https://nus-cs2113-ay1920s2.github.io/website/schedule/week9/tutorial.html
![image](https://user-images.githubusercontent.com/1673303/76698467-31a6a880-66de-11ea-81aa-185847f67149.png)

Is this something we should fix on MarkBind side?

**Comment by Tejas2805** [comment]
I feel either we should fix this from our side or mention it in the UG - padding might be required. This will prevent the user from being caught unaware.

**Comment by nbriannl** [comment]
May I know how to reproduce this? 

````
- Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam

```html {heading="Not html}
<foo>
  <bar type="name">goo</bar>
</foo>
```
````

Gives me
![image](https://user-images.githubusercontent.com/27397021/77224453-b858fb00-6ba0-11ea-8990-70b6e2637788.png)

**Comment by damithc** [comment]
code block is part of the bullet point. Try this:
```html
- Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam
  ```html {heading="Not html}
  <foo>
    <bar type="name">goo</bar>
  </foo>
  `` `
```
If this is the only way to reproduce this problem, not sure if it is worth a fix.

**Comment by Tejas2805** [comment]
If the code block (with heading) is written without any box or boilerplate, this issue will occur with cause no padding is provided to the whole code block as such.

**Comment by ang-zeyu** [comment]
The problem is not with lists particularly; It's just that the text inside the list also has no bottom margin. We use code blocks most oftenly after paragraphs which have a large bottom margin so don't really notice this.

Adding a little margin shouldn't hurt though
