### ISSUE TITLE
Copying code in code blocks not working properly

### ISSUE THREAD

**Issue by openorclose** [MarkBind/markbind#1125]
**Tell us about your environment**

* **MarkBind Version: 2.12**

Ubuntu 18.04

**What did you do? Please include the actual source code causing the issue.**

````
line1
line2
line3
````

then `markbind serve` (or copy any of the code examples from https://markbind.org/userGuide/fullSyntaxReference.html)
**What did you expect to happen?**
When pasting into a text editor, line breaks are preserved.

**What actually happened? Please include the actual, raw output.**
```
line1line2line3
```

**Comment by damithc** [comment]
Do you mean copying with Ctrl+C?
Are you sure? I tried (Windows, notepad) and the line breaks are preserved.

**Comment by openorclose** [comment]
> Do you mean copying with Ctrl+C?
Yes
> Are you sure? I tried (Windows, notepad) and the line breaks are preserved.
I tested it on Ubuntu 18.04, I'll try Windows.

**Comment by openorclose** [comment]
I just tested it, works on Windows for me. 

Doesn't copy the line breaks for Android 10 also.

**Comment by nbriannl** [comment]
Works on Windows 10 for me too.
