### ISSUE TITLE
Remove OK button from modals

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1126]
v2.12.0
Looks like an `OK` button has gotten into modals (by accident?). As we already have an `X` button, do we need the `OK` button too?

![image](https://user-images.githubusercontent.com/1673303/76700756-991c2280-66f5-11ea-9543-3f6d3f81b41b.png)

**Comment by openorclose** [comment]
Not really, I'll remove them.

**Comment by openorclose** [comment]
![image](https://user-images.githubusercontent.com/3646725/76970893-785b0380-6967-11ea-8127-41c221a9dd00.png)

Actually, the docs seem to suggest that there should be an OK button, and that you can customise it with `ok-text`. Should we keep or remove the OK button?

**Comment by damithc** [comment]
I think the difference is that previously it was not the default.; the button appeared only if the ok-text property is present (that's what I suspect; never used that before). Can we go back to that?
