### ISSUE TITLE
PlantUML diagrams always "update" on updating test sites

### ISSUE THREAD

**Issue by yash-chowdhary** [MarkBind/markbind#1130]
**Tell us about your environment**

* **MarkBind Version:** 2.12.0

**What did you do? Please include the actual source code causing the issue.**
* Branched off of `master`
* Ran `npm run updatetest`

**What did you expect to happen?**
Since it's a newly created branch w/o any changes, nothing should be affected.

**What actually happened? Please include the actual, raw output.**
All PUML diagrams in `test/functional/test_site/expected/diagrams` are "updated". 
Specifically, the size of the `.png` files is affected -
- before running `updatetest` (on `master` branch) -

  ![image](https://user-images.githubusercontent.com/21968718/76828158-45c3e480-685b-11ea-95a9-87d6537901c0.png)

- after running `updatetest` (on the newly created branch) -

  ![image](https://user-images.githubusercontent.com/21968718/76828178-56745a80-685b-11ea-8a21-fd46b5997d20.png)

**Comment by alyip98** [comment]
The reason this happens is because PlantUML includes the language of the OS running it in the metadata of the generated PNG. The difference is due to the sets being generated with en-US and en-SG (I forgot which is which).
