### ISSUE TITLE
Move fixed bugs out of test\functional\test_site\bugs\index.md

### ISSUE THREAD

**Issue by nbriannl** [MarkBind/markbind#1140]
**Is your request related to a problem?**

Some bugs in the open bugs page have already been fixed, for example #469  We may intend to encourage bug reporters to utilize `test_site/bugs` as a platform to reproduce bugs, 

**Describe the solution you'd like**

Therefore I would be good to tidy up and remove fixed bugs from `test\functional\test_site\bugs\index.md`

In order to make sure that these we do not regress and have these bugs again, add these cases as tests in appropriate `test_site` markdown files, or create new markdown files if nothing suitable is present.

**Describe alternatives you've considered**

(Write your answer here.)

**Additional context**

#792 is another issue related to junk in our testing suite.

**Comment by Tejas2805** [comment]
Alright! Looking into it.
