### ISSUE TITLE
Extra lines when code-fence variable is passed to a boilerplate 

### ISSUE THREAD

**Issue by nbriannl** [MarkBind/markbind#1162]
# Solution:
As @ang-zeyu pointed out, the extra lines are due to subtle /n characters.

Writing the follow fixes the issue

````
<variable name="myVar">```html
<foo>
  <bar type="name">goo</bar>
</foo>
```</variable>
````

-------

**Tell us about your environment**

* **MarkBind Version:** v2.12.0

**What did you do? Please include the actual source code causing the issue.**

When trying to solve #1159, I declared a variable, and the variable contained fenced code block Markdown/MarkBind code.

````
##### Sample User Guide Section
To reproduce, in the main MarkDown file i.e. `index.md`, have a variable defined as fenced code, i.e. `myVar`. Then, in the boilerplate `outputBox.md`, the variable as rendered markdown is rendered correctly as expected, but as raw Markdown has addtional spans, henced showing up as blank lines in the code block.
<include src="outputBox.md" boilerplate >
<variable name="myVar">
```html
<foo>
  <bar type="name">goo</bar>
</foo>
```
</variable>
</span>
</include>
````

It was passed into the boilerplate `outputBox.md`.

`````

%%CODE:%%
<div class="indented">

````{.no-line-numbers}
{{ myVar | safe }}
````
</div>

%%OUTPUT:%%
<div class="indented">

<box border-left-color="grey" background-color="white">

{{ myVar | safe }}
</box>
</div>
`````

The 'Output' renders correctly (the output of the render), but the source code of the render 'Code' has a blank line in the front and the back. 

![image](https://user-images.githubusercontent.com/27397021/77850927-68191300-7208-11ea-8ca8-1a4a4e3ce94c.png)

**What did you expect to happen?**

I expected there not be two extra lines in my code block. 

PR that reproduces issue at #1163

**Comment by ang-zeyu** [comment]
Its functioning as expected; The extra two lines are due to the subtle newlines here

<pre>
&lt;variable name="myVar">here
```html
<foo>
  <bar type="name">goo</bar>
</foo>
```
andhere&lt;/variable>
</pre>

You could fix it by squashing those 😄

**Comment by nbriannl** [comment]
Oh! I see, thanks!

**Comment by nbriannl** [comment]
> Its functioning as expected; The extra two lines are due to the subtle newlines here
> 
> <variable name="myVar">here
> ```html
> 
>   goo
> 
> ```
> andhere</variable>
> You could fix it by squashing those 😄

What do you mean by squashing?

**Comment by ang-zeyu** [comment]
<blockquote>

````
<variable name="myVar">```html
<foo>
  <bar type="name">goo</bar>
</foo>
```</variable>
````
</blockquote>

^ 'squashing the lines', my bad

**Comment by nbriannl** [comment]
I see. What I had in thought too. I guess this niche case needs to be mentioned in some advance usage somewhere.
