### ISSUE TITLE
Question: Variable definitions via span and id

### ISSUE THREAD

**Issue by nbriannl** [MarkBind/markbind#1165]
In documentation, I have come across a way of declaring what seems to be variables via `<span id="...">` but I cannot find the corresponding documentation in the documentation https://markbind.org/userGuide/reusingContents.html#variables

For example, in `docs\userGuide\syntax\headings.mbdf`
````
<include src="outputBox.md" boilerplate >
<span id="code">

```markdown
### Heading level 3
...
###### Heading level 6
```
</span>
<span id="output">

### Heading level 3
...
###### Heading level 6
</span>
</include>
</span>
````

Is this a deprecated way of defining variable?

**Comment by damithc** [comment]
Every span by default can be retrieved from another place using `<include src="page.md#span-id" />`span id (even within the same page), but the original span itself will be visible to the reader (unless you set it to hidden using css). 

Did you try page variables? https://markbind.org/userGuide/reusingContents.html#page-variables

**Comment by nbriannl** [comment]
I see, but in this case, the boilerplate `outputBox.md` used it as follows

`````

%%CODE:%%
<div class="indented">

{{ code | safe }}
</div>

%%OUTPUT:%%
<div class="indented">

<box border-left-color="grey" background-color="white">

{{ output | safe }}
</box>
</div>
````

**Comment by damithc** [comment]
I think it is using this technique https://markbind.org/userGuide/reusingContents.html#specifying-variables-in-an-and-lt-include-and-gt

Not sure if the technique works even if `span`s were used instead of `variable`s

**Comment by nbriannl** [comment]
I see. Yeah, I'm aware of the functionality of including variables within includes (and hence boilerplates) I was just very confused at the usage of `span`s instead of `variable`s, which is undocumented.

**Comment by tlylt** [comment]
Closing this issue in favor of the more recent & similar one at #1847
