### ISSUE TITLE
User Guide: Update members in About Us

### ISSUE THREAD

**Issue by yash-chowdhary** [MarkBind/markbind#1171]
We can -
1. Add new members to the list
1. Update the status for Marvin: _Project Mentor_ since Jan 2020
1. Move inactive/ex-3281 members to the Past members section -
   * Lin Si Jie: _Project Member_ since Jan 2019
   * Lu Yang Kenneth: _Project Member_ since Jan 2019
   * Maddi Aadyaa: _Project Member_ since Jan 2019
   * Tan Zhen Yong: _Project Member_ since Jan 2019

Is there anyone I missed out?

**Comment by nbriannl** [comment]
Nope. LGTM.
