### ISSUE TITLE
Box icon sizes skewed or cropped with custom content

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1172]
**Tell us about your environment**

* **MarkBind Version:**
2.13.1

**What did you do? Please include the actual source code causing the issue.**

Visit https://markbind.org/userGuide/usingComponents.html#rich-formatting-in-headings-titles

**What actually happened? Please include the actual, raw output.**

![iconsizes](https://user-images.githubusercontent.com/3306138/78155168-b419c100-746f-11ea-9090-daa70be82646.png)

**What did you expect to happen?**
Box icons size should not be skewed or cropped

**Comment by yash-chowdhary** [comment]
Have you tried this - [comment from #1123](https://github.com/MarkBind/markbind/pull/1123#issuecomment-607576960)? 
`icon-size` can be used here. 
It's a compromise, considering that we want the icons to be aligned and have a fixed width for readability.

**Comment by ang-zeyu** [comment]
since it's a flex wrapper, how about using `min-width`?
this would preserve fixed alignment for the standard set of font icons, while allowing it to scale for custom content
