### ISSUE TITLE
Extra unprintable chars in code blocks

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1173]
When I copy-paste python code from this section, intellij indicates there are some unprintable chars.
https://nus-te3201.github.io/2020/schedule/week10/topics-py.html#appendix-d-unit-testing

![image](https://user-images.githubusercontent.com/1673303/78158017-525b5600-7473-11ea-8e25-1842477e9a0c.png)

I wonder if they have been added by MarkBind. The code in the source file doesn't seem to have the same chars. https://github.com/nus-te3201/2020/blob/te3201/programming/unittesting/text.md

**Comment by openorclose** [comment]
It was caused by the line numbers pr #991, where an unprintable character was added to empty lines.

I'll submit a pr in the morning.
