### ISSUE TITLE
Minimized panels have low text contrast when hovering over it

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1177]
**Tell us about your environment**

* **MarkBind Version:** 2.13.1

**What did you do? Please include the actual source code causing the issue.**

![panel-contrast](https://user-images.githubusercontent.com/3306138/78267166-3e7a2780-7539-11ea-8c79-bd18a8a05e36.gif)

**What did you expect to happen?**
The text color should shift to something with better contrast when hovering over the minimized panel

**Comment by damithc** [comment]
IIRC, this happens only when the heading text is dimmed. e.g., `%%Heading Text%%`

**Comment by ang-zeyu** [comment]
Ah didn't notice this. Would be a non-issue then
