### ISSUE TITLE
Code blocks: unexplained content movement over hover

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1179]
Windows, Chrome:
Steps: Go to https://nus-cs2113-ay1920s2.github.io/website/admin/tp-deliverables.html#deliverable-demo and hover over the fenced code block shown below.

![image](https://user-images.githubusercontent.com/1673303/78419287-eba68a00-7676-11ea-852b-e9db4028f1aa.png)

There is some movement of content although there should not be any.

**Comment by openorclose** [comment]
![image](https://user-images.githubusercontent.com/3646725/78986577-2704f500-7b5e-11ea-9edf-a712419fab85.png)

If we unset the width style of `icon-wrapper`, the issue goes away.

**Comment by openorclose** [comment]
Oh, seems to be fixed by https://github.com/MarkBind/vue-strap/pull/142

**Comment by openorclose** [comment]
This looks fixed, @damithc can confirm?

**Comment by damithc** [comment]
> This looks fixed, @damithc can confirm?

I still see the content moving about. See the same link (it's using the latest MarkBind)

**Comment by openorclose** [comment]
Previously there was a left-right movement and wrapping of the code block on hover. 

Now it's only due to the wrapping of the code block on hover.

**Comment by damithc** [comment]
> Previously there was a left-right movement and wrapping of the code block on hover.
> 
> Now it's only due to the wrapping of the code block on hover.

Still though, there should not be any movement as there is no need for wrapping, right?

**Comment by damithc** [comment]
> Still though, there should not be any movement as there is no need for wrapping, right?

While on the topic, perhaps we should make the wrapping an icon rather than do it on hover? This kind of slight movements is not going to be a problem if it happens only on command. After seeing it for a while, seems 'wrap on hover' is not a nice UX.

**Comment by openorclose** [comment]
Ah yes, the text should not wrap. I noticed the left right movement and thought that was what you were referring to. At least that part's fixed.

**Comment by openorclose** [comment]
> > Still though, there should not be any movement as there is no need for wrapping, right?
> 
> While on the topic, after seeing it for a while, seems 'wrap on hover' is not a nice UX. Perhaps we should perform wrapping if the user clicks an icon? This kind of slight movements is not going to be a problem if it happens only on command.

Should we revert the hover wrap functionality first then?

**Comment by damithc** [comment]
> Should we revert the hover wrap functionality first then?

I don't mind, but if there is code to be salvaged, do document that somewhere (may be in a new issue) so that the replacement feature can reuse that code if possible. The ability to wrap is a useful feature, just that it's better to do it on demand than on hover.
