### ISSUE TITLE
Footnotes are being duplicated

### ISSUE THREAD

**Issue by yash-chowdhary** [MarkBind/markbind#1183]
**Tell us about your environment**

* **MarkBind Version:**  2.13.1

**What did you do? Please include the actual source code causing the issue.**
Went to MarkBind's website

**What did you expect to happen?**
Footnotes should only appear "once", as seen here - 
<kbd>
<img width="810" alt="Screenshot 2020-04-05 at 9 19 29 PM" src="https://user-images.githubusercontent.com/21968718/78499420-30b7e280-7783-11ea-95c4-0fd5d0fbca41.png">
</kbd>

**What actually happened? Please include the actual, raw output.**

Footnotes are being duplicated, as seen in the [MarkBind website](https://markbind.org/userGuide/formattingContents.html#footnote1) - 
<kbd>
<img width="814" alt="Screenshot 2020-04-05 at 9 12 14 PM" src="https://user-images.githubusercontent.com/21968718/78499443-5644ec00-7783-11ea-93cc-c1a242fd0593.png">
</kbd>

**Comment by openorclose** [comment]
https://deploy-preview-1155--markbind-master.netlify.com/userguide/formattingcontents#footnote1

Should be fixed by this #1155

**Comment by yash-chowdhary** [comment]
Great! 🙂
Will close it once it's merged
