### ISSUE TITLE
Bold checkbox and radio bold content not spaced correctly.

### ISSUE THREAD

**Issue by nicholaschuayunzhi** [MarkBind/markbind#119]
#### Input

```md
- ( ) test1
- ( ) test2
- [ ] test3
- ( ) **test1**
- [ ] **test2**
```
#### Output
![image](https://user-images.githubusercontent.com/22221132/35178762-6dc048ac-fdc8-11e7-80e4-69cb6cc725f4.png)

Whitespace is not pre-pended to the text when parsed into html.

**Comment by damithc** [comment]
This problem is not limited to here. There is a wider problem is leading spaces getting stripped out when applying formatting (e.g. `some text %%some text%%`, although it doesn't happen at every place.
