### ISSUE TITLE
Error in SiteNav of DG

### ISSUE THREAD

**Issue by Tejas2805** [MarkBind/markbind#1198]
**Tell us about your environment**
MacOS

* **MarkBind Version:**
Latest

**What did you do? Please include the actual source code causing the issue.**
N.A

**What did you expect to happen?**
Expected `Code of Conduct` to be in the same indentation level as others

**What actually happened? Please include the actual, raw output.**
![Screen Shot 2020-04-12 at 6 49 22 PM](https://user-images.githubusercontent.com/35946746/79066969-66624b80-7cee-11ea-868f-da86905db0e3.png)

**Comment by ang-zeyu** [comment]
I think this is intended, from the indents in the navigation file. Could confirm with @nbriannl

**Comment by nbriannl** [comment]
This is intended. I modelled it after Gatsby, which also puts the code of conduct under the contributing section.

**Comment by Tejas2805** [comment]
Ah okay. I felt it was a bug because the code of conduct on the siteNav opens up a new page and doesn't refer to the one below the DG section.

**Comment by Tejas2805** [comment]
If not, do close it.

**Comment by ang-zeyu** [comment]
> Ah okay. I felt it was a bug because the code of conduct on the siteNav opens up a new page and doesn't refer to the one below the DG section.

Ah did you mean something like?

```
Contributing (caret)
  introduction
  code of conduct
```

would certainly be a welcome change!

**Comment by nbriannl** [comment]
> > Ah okay. I felt it was a bug because the code of conduct on the siteNav opens up a new page and doesn't refer to the one below the DG section.
> 
> Ah did you mean something like?
> 
> ```
> Contributing (caret)
>   introduction
>   code of conduct
> ```
> 
> would certainly be a welcome change!

Ah. If that's the case. I welcome the change too.

**Comment by nbriannl** [comment]
Was thinking about it. Then should the directory structure change? I.e. put contributing.md under the contributing folder?

**Comment by ang-zeyu** [comment]
> Was thinking about it. Then should the directory structure change? I.e. put contributing.md under the contributing folder?

could expand the scope of the PR while at it since its a rather minor change and reorganise the rest of the developer guide, maybe something like

```
contributing
  ...
developer guide
  ...
maintainer guide
  merging PRs
  doing a release

```

**Comment by Tejas2805** [comment]
Ya had something like this in mind. Surely, can do.
