### ISSUE TITLE
Weird movement when toggling expandables (Safari Browser)

### ISSUE THREAD

**Issue by jamessspanggg** [MarkBind/markbind#1200]
**Tell us about your environment**
* **Browser Version:**
Safari 13.1
* **MarkBind Version:**
MarkBind 2.13.1 
**What did you do? Please include the actual source code causing the issue.**
N.A

**What did you expect to happen?**
What expandable should just expand and show content within (without additional movements).

**What actually happened? Please include the actual, raw output.**
The expandable opens, closes, and re-opens again. [Link to reproduce](https://nus-cs2103-ay1920s2.github.io/website/se-book-adapted/chapters/modeling.html#class-diagrams-intermediate). Snippet shown below:

![Kapture 2020-04-15 at 14 56 23](https://user-images.githubusercontent.com/32864116/79307508-99dcea00-7f29-11ea-98cf-5ba244e2cf1f.gif)

**Comment by ang-zeyu** [comment]
Should be fixed in the `2.14` ( just published ), could you double check?

**Comment by jamessspanggg** [comment]
> Should be fixed in the 2.14 ( just published ), could you double check?

Yep, can confirm. Will close this.
