### ISSUE TITLE
Improve minimized design for panels

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1201]
**Is your request related to a problem?**

![minimalpanelminimized](https://user-images.githubusercontent.com/3306138/79480627-ef57ea80-8040-11ea-9adb-bc7162bf07aa.png)

**Describe the solution you'd like**

Starting to think that simply removing the border would be better. ( so you could have it sit in a paragraph seamlessly )

Some extra signifiers could be placed beside it so the user knows it can be clicked as well. ( e.g. mouse icon )

**Describe alternatives you've considered**
na

**Additional context**
na

**Comment by damithc** [comment]
Yes, it would be good to have a different visualization for collapsed panels.
Note that collapsed panels we have are not a common thing. Ideally, it should appear different from other things. Right now they appear like buttons, which is not ideal either. They shouldn't appear like normal links either.

**Comment by ang-zeyu** [comment]
🤔 perhaps we could borrow the design of tipbox icons here in place of the 'mouse icon' for all the designs. If there's no suitable ones, we could find more from `fas/octicons`
So each button would be borderless, and just paired with an icon of some type, maybe with some color / opacity as well.

Something along these lines that gives it a unique feel

**Comment by damithc** [comment]
On the other hand, collapsed panels are used a lot in CS2103 website to embed content taken from elsewhere in the site. e.g.,
![image](https://user-images.githubusercontent.com/1673303/79490439-71e7a680-804f-11ea-952d-ad33de399300.png)

For those cases, the panel should not be too seamless so that embedded content can be easily spotted and not mistaken for native (i.e., not embedded) content.

**Comment by KendrickAng** [comment]
Hi, @ang-zeyu @damithc, I'd like to try taking this as my first issue, would that be fine?

**Comment by ang-zeyu** [comment]
Yes, sure!

Note that the frontend workflow we have been following up till now is manually copying the bundle (`components.min.js`) to the output directory of the site everytime we change source files, which is quite cumbersome. (though I think we all became pretty efficient at it =X)

I'll try to get #1306 (preferably with a review) in and add live / hot reload by this weekend (something like `markbind s -d`) if you prefer to wait, otherwise you could get started using the above workflow, or peek around some back end issues!

**Comment by KendrickAng** [comment]
In that case, I'll try working on another issue first! But could I ask how copying `components.min.js` simulates hot reloading? Not too familiar with this aspect of things. Thank you!

**Comment by ang-zeyu** [comment]
> In that case, I'll try working on another issue first! But could I ask how copying `components.min.js` simulates hot reloading? Not too familiar with this aspect of things. Thank you!

It dosen't, live / hot reload are both _automatic_. Our workflow currently is still manual =C
