### ISSUE TITLE
Polish inline code and fenced code blocks patch for htmlparser2

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1205]
According to [commonmark spec](https://spec.commonmark.org/0.28/#fenced-code-blocks) ( which markdown-it follows ),
1. A code fence is a sequence of at least three consecutive backtick characters (`) or tildes (~). (Tildes and backticks cannot be mixed.) A fenced code block begins with a code fence, indented no more than three spaces. ... ( among many other behaviours )
2. A backtick string is a string of one or more backtick characters (`) that is neither preceded nor followed by a backtick. ...

Currently however, the patch follows the following behaviour:
1. On encountering `backtick`, switch parser state to `markdown`
2. On encountering `backtick`, again, switch back to `text` state again.

Hence, the patch will only work on an odd number of backticks, causing the tags inside this to be parsed as html, not as `markdown` by htmlparser2, which may cause issues when traversing the dom

~~~
``<div>parsed as html</div>``

````
<div>also parsed as html</div>
````
~~~

Also, there are a few more use cases / specs that conflicts with the current patch
- the closing sequence of backticks need only be at least as long as the opening sequence
- a longer opening sequence of backticks than what is encountered after causes what is encountered after to be treated as text ( we use this in our docs - though there isn't any html in such usages currently )
- ability to use tildes `~` in fenced code blocks but not in inline code ( likely difficult )

**Comment by openorclose** [comment]
Looks fixed now on chrome, @damithc can check and close this?

**Comment by ang-zeyu** [comment]
Closing, unneeded once #1353 is done, and then a few more prs to always render **markdown before html**
