### ISSUE TITLE
VueStrap: Investigate using Storybook

### ISSUE THREAD

**Issue by nbriannl** [MarkBind/markbind#1212]
**Is your request related to a problem?**

Currently, developing on vue-strap is quite troublesome.
Right now, 

- We make changes
- Build the vue-strap dist
- Copy it over to markbind
- Serve a markbind site to see our changes

It would be nice if we had a way to view and develop the components independently without building the dist for every change 

**Describe the solution you'd like**

We can consider investigating using [Storybook](https://storybook.js.org/) as a development tool for vue-strap.

As you can see a sample Storybook for vue components:
https://storybookjs.netlify.app/vue-kitchen-sink/?path=/story/welcome--welcome

It would be nice to have one for vue-strap as well

**Describe alternatives you've considered**

(Write your answer here.)

**Additional context**

I have yet to know the full capabilities and limitations so I need to play around with the tool. 

And any rendering that is MarkBind specific within vue-strap components would likely not be covered by Storybook.

**Comment by nbriannl** [comment]
Given the update to VueStrap dependencies https://github.com/MarkBind/vue-strap/pull/130 we can now consider using Storybook.

Additionally, the issue https://github.com/MarkBind/markbind/issues/409 is now possible in case anyone misses it.

**Comment by nbriannl** [comment]
Issue seems not to be necessary since we are going with MarkBind/markbind#981.
https://www.npmjs.com/package/@markbind-dummy/vue-components

**Comment by kaixin-hc** [comment]
Issue seems stale and no longer relevant, closing.
