### ISSUE TITLE
Some pageNav links don't work, possibly due to the use of colon

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1217]
Steps:
1. Go to https://nus-cs2113-ay1920s2.github.io/website/admin/tp-deliverables.html
2. Click on one of these links
   ![image](https://user-images.githubusercontent.com/1673303/80790693-1f1afc80-8bc2-11ea-9527-313bff0d8ba2.png)

Problem: the page doesn't scroll to the relevant heading. No such problem with the other links in the PageNav. Is it something to do with the use of `:` in the heading?

**Comment by ang-zeyu** [comment]
The headings inside the `Practical Exam that will be done at v2.1` modal are getting indexed, will get a fix out
