### ISSUE TITLE
Auto-convert intra-site .md links to .html

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1227]
Current: intra-site links needs to be specified as .html e.g., `[about us](aboutUs.html)`

Suggestion: auto-convert intra-site .md and .mbd links to .html when generating the site

Reason: this way, the link will go to the .md file when browsing the source files (i.e., as rendered by GitHub) but will go to the .html page when when browsing the generated site. Also, this seems to be how Jekyll behaves. I suspect other static site generators work the same way.

Concerns: what if we actually wanted to link to the .md file?

**Comment by ang-zeyu** [comment]
I don't think we should go with this by default, for the concern above but also consistency. (its one more special case to keep in mind)

We could easily make it a plugin though, would that be good? @damithc

**Comment by damithc** [comment]
I'm unsure of which should be the rule and which is the exception. Converting is almost always the right choice (that's probably why Jekyll auto-converts by default). The user might want to preserve the .md link only for very special case, and only for a specific link rather than the entire site. Perhaps users can use a dirty workaround for such cases (e.g., give the link text without the file extension and ask the reader to add `.md`  manually). I'm more inclined to follow Jekyll in this case and I suspect other static site generators do the same (can check a few other widely used ones to confirm).

**Comment by ang-zeyu** [comment]
Seems like docusaurus does it too; Since it seems to be the convention and linking `md` files is the edge case, how about this as a workaround?

```
[...](link) {.no-convert}
<a href="link" no-convert />
```

**Comment by damithc** [comment]
> Seems like docusaurus does it too; Since it seems to be the convention and linking `md` files is the edge case, how about this as a workaround?
> 
> ```
> [...](link) {.no-convert}
> <a href="link" no-convert />
> ```

Sounds good. The workaround can even be a separate PR.
