### ISSUE TITLE
Extend live preview to layout scripts and stylesheets

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1229]
Steps:
1. serve a site locally 
1. modify a css file inside _markbind/layouts

Problem: the changes are not reflected by the live preview

**Comment by ang-zeyu** [comment]
this occurs with the `scripts.js` file as well, and any user added script / css files in the head of `<frontmatter>` as well.
I suppose it wasn't a priority when implementing these features back then

Would be nice if we extend this to user added `<script>` tags (pointing to local script files) too

**Comment by KendrickAng** [comment]
@ang-zeyu I'd like to take on this issue!

**Comment by ang-zeyu** [comment]
sure, you may want to take a look at #1308 instead though, which looks at revamping the layout code, but its quite a big issue. (after a few more PRs maybe)

But I'm happy with accepting a hotfix here in the meantime as well : )

**Comment by KendrickAng** [comment]
Thanks! As of right now, I'll only be able to provide a hotfix since I'm still unfamiliar with the overall structure, but will definitely look into that issue moving ahead.
