### ISSUE TITLE
Document the -s flag

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1230]
A `-s` flag was added to the CLI in #440 
This flag doesn't seem to be documented in user docs.

**Comment by ang-zeyu** [comment]
In the options panel, I organised the options under commands during #1038 as the list was getting long. Maybe we could use a table instead =O

![Untitled](https://user-images.githubusercontent.com/3306138/83654646-fc7c6900-a5ef-11ea-9147-722c628bfa11.png)

**Comment by damithc** [comment]
> In the options panel, I organised the options under commands during #1038 as the list was getting long. Maybe we could use a table instead =O

I'm OK with either format. The downside of the panel is that it requires an extra click (and gets in the way of locating an option using CTRL+F)
