### ISSUE TITLE
Adopt "difficulty.very low/low/medium/high" labels instead of "good first issue"

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1235]
**Is your request related to a problem?**

Some issues tagged under the "good first issue" label are "blocked" from being tackled by second time+ developers.
Having a difficulty classification of issues can also help in estimating the amount of time / effort required to solve an issue.

**Describe the solution you'd like**

Let's
- replace "good first issue" with `difficulty.low` labels - these issues should generally be able to be solved by only tackling 1-3 areas of the code, and are pretty much self contained
- add a `difficulty.very low` label - this is for "chore" type of issues, such as updating documentation, fixing typos, changing directory structure, etc.
- `difficulty.medium` label - this is for slightly more involved areas (e.g. where the overall architecture can affect something that is _seemingly_ self contained) that require a better understanding of the architecture
- `difficulty.high` - this is for "epic" type (though not necessarily labelled with`epic` as well) issues that require substantial additions / changes. The implementation / feature set should also generally be discussed before proceeding with a first PR.

**Comment by ang-zeyu** [comment]
@damithc @openorclose @marvinchin

**Comment by crphang** [comment]
My experience on this is that having a ready pool of "first issues" is still very helpful for developer on boarding. Perhaps the naming can be changed from `first` to `beginner` for developers that needs more issues to gain better understanding of the project.

That aside, being able to tag the difficulty of problems can definitely help different developers of different background/experience to take on the problem. Except that sometimes difficult problems do not easily surface themselves initially as hard ones.

Priority could be used additionally to decide whether a problem should tagged (and "reserved) as a beginner problem as there could be an arbitrarily long time that would be picked up.

**Comment by ang-zeyu** [comment]
I like the `beginner` idea. To clarify, it's meant to "unblock" (but also "discourage" tackling) for second time+ developers right?
How about adopting that along with the difficulty labels?

Not too sure if we should go with a `chore` label (seems to be the convention in many open source repos) instead of `difficulty.very low` as well (if we go with diffculty labels).

**Comment by damithc** [comment]
I don't mind refining the labels for difficulty classification. 

For reference, [here](https://oss-generic.github.io/process/docs/DefiningLabels.html) are some guidelines we wrote long ago. I'll be migrating it over to https://se-education.org/guides this summer. Can be refined if necessary.

BTW, also relevant is GitHub's recent introduction of [a special treatment for `good first issue`  labels ](https://help.github.com/en/github/building-a-strong-community/encouraging-helpful-contributions-to-your-project-with-labels)

**Comment by ang-zeyu** [comment]
> BTW, also relevant is GitHub's recent introduction of a special treatment for good first issue labels

Hmm, I guess it's better to leave it as `good first issue` then.

> For reference, here are

I didn't note that our labels were from this page actually. Since we are using a one letter prefix convention `d/e/a/...`, I think making the text after the `d. ...` more informative could be better.

How about
```
d.chore
 .beginner
 .intermediate
 .expert
```
? (https://github.com/MunGell/awesome-for-beginners)

**Comment by damithc** [comment]
> For reference, [here](https://oss-generic.github.io/process/docs/DefiningLabels.html) are some guidelines we wrote long ago. I'll be migrating it over to https://se-education.org/guides this summer. Can be refined if necessary.

Migrated to https://se-education.org/guides/guidelines/labels.html

> How about
> 
> ```
> d.chore
>  .beginner
>  .intermediate
>  .expert
> ```

As `d` refers to difficulty, we can also consider `Easy`, `Moderate`, `Hard`, `VeryHard` as the members of the label group.  That's what I have used in the updated guidelines. But you can deviate if it makes sense. We can always rename labels later if things don't work out. There's no one right answer.

`chore` feels like a type of work rather than a difficulty? i.e., `c.Chore`

**Comment by damithc** [comment]
> ? (https://github.com/MunGell/awesome-for-beginners)

TEAMMATES in that list. We can also request them to add MarkBind and RepoSense.

**Comment by ang-zeyu** [comment]
> Migrated to https://se-education.org/guides/guidelines/labels.html

Looks neat 👍

> `chore` feels like a type of work rather than a difficulty? i.e., `c.Chore`

ahh yes that makes more sense. 

> There's no one right answer.

I'm not too sure what is most appropriate right now as well. I think as we begin classifying the issues we can figure out if the labels need changing. Let's go with `easy/moderate/hard/very hard` as a first then
