### ISSUE TITLE
User guide: document how to make the topNav sticky

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1244]
i.e., `<header class="header-fixed">`

**Comment by damithc** [comment]
@le0tan is this feature stable enough to go public? I remember there were some quirks to be fixed first

**Comment by ang-zeyu** [comment]
documented (`<header fixed>`) and fixed in #1191. It was added to the user guide as well, I haven't seen any issues so far

**Comment by damithc** [comment]
Oh, nice. Thanks both.

**Comment by le0tan** [comment]
@damithc I added the feature to the documentation to indicate that it’s ready for use. Ping me if you experienced any issue related to it. Thanks!

**Comment by damithc** [comment]
> @damithc I added the feature to the documentation to indicate that it’s ready for use. Ping me if you experienced any issue related to it. Thanks!

Got it. Thanks @le0tan 
Need your help with #1252 though
