### ISSUE TITLE
Add diagrams for design documents

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1247]
Suggestion: add some diagrams (e.g., plantUML diagrams) to developer documents to make the design easier to understand but also to showcase MarkBind's inbuilt support for diagramming

**Comment by damithc** [comment]
I recall seeing someone using puml diagrams to describe MarkBind parser workflow. @ang-zeyu @alyip98 @openorclose was it any of you?

**Comment by ang-zeyu** [comment]
put it #1224 on hold for now pending (possibly) a few more refactors.
I noticed the page generation activity diagram was far too low-level still as well, which necessitates frequent changes to the dev docs. Aiming to replace that with a somewhat more high level one!

**Comment by damithc** [comment]
> put it #1224 on hold for now pending (possibly) a few more refactors.
> I noticed the page generation activity diagram was far too low-level still as well, which necessitates frequent changes to the dev docs. Aiming to replace that with a somewhat more high level one!

Makes sense 👍

**Comment by ang-zeyu** [comment]
closed with #1224
