### ISSUE TITLE
fixed TopNav hides content from above {{ MAIN_CONTENT_BODY }}

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1252]
Supposed there is some content above the `{{ MAIN_CONTENT_BODY }}` in the page layout. 
e.g., `_markbind\layouts\default\page.md`
```html
Some text I want to see at the top of every page
{{ MAIN_CONTENT_BODY }}
```

If I use the `fixed` attribute for the topNav, the content above `{{ MAIN_CONTENT_BODY }}` will be hidden. e.g.,

Without `fixed`:
![image](https://user-images.githubusercontent.com/1673303/84634117-ee014c00-af23-11ea-981b-eaffa88a3b0b.png)

With `fixed`:
![image](https://user-images.githubusercontent.com/1673303/84634176-083b2a00-af24-11ea-82ed-6676798f8e87.png)

**Comment by damithc** [comment]
@le0tan any thoughts?

**Comment by le0tan** [comment]
@damithc will look into this soon when I find some free time. Thanks for the report!

**Comment by le0tan** [comment]
@damithc sorry for the (extremely) late reply but I can't seem to reproduce this bug:

![image](https://user-images.githubusercontent.com/28982486/95557743-d1939d00-0a47-11eb-9afb-59d5f96b665b.png)

![image](https://user-images.githubusercontent.com/28982486/95557755-d5bfba80-0a47-11eb-9d2b-14b7b1e27e38.png)

![temp](https://user-images.githubusercontent.com/28982486/95557707-c3458100-0a47-11eb-9d7b-060bafbe8099.gif)

**Comment by damithc** [comment]
yup, seems to be fixed now. Closing.
