### ISSUE TITLE
filter tags doesn't work when no blank line between two spans

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1257]
When filtering for `["-m--*", "m--cs2103"]` i.e., exclude all except `m--cs2103`,
this one works i.e., only the first chunk appear
```html
<span tags="m--cs2103">
  * In-lecture quiz:
    * Answered at least 80% of the questions correctly: 2 points
</span>

<span tags="m--cs2113">
  * Programming exercise (if any):
    * Submitted correct solutions at least 75% of the exercises: 3 points
</span>
```
But this one doesn't i.e., both chunks appear
```html
<span tags="m--cs2103">
  * In-lecture quiz:
    * Answered at least 80% of the questions correctly: 2 points
</span>
<span tags="m--cs2113">
  * Programming exercise (if any):
    * Submitted correct solutions at least 75% of the exercises: 3 points
</span>
```
The only difference is the extra blank line between the two chunks.

**Comment by KendrickAng** [comment]
I tried to reproduce this on my Windows 10 laptop, using both Firefox and Chrome, but couldn't do so. Could I check if this issue still appears for you @damithc ?

**Comment by damithc** [comment]
Yes, I can't repro it either. Closing. Thanks for checking @KendrickAng
