### ISSUE TITLE
Allow custom names for PlantUML images

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1270]
Current: PlantUML images generated have a random image name e.g., 28cbb283cd45fc38969e2bb467826f6a.png

Suggestion: Allow specifying a name for the generated image so that the generated images can be reused from other places.

e.g., `<puml name="timeline.png">`

**Comment by ang-zeyu** [comment]
added by @crphang https://markbind.org/userGuide/puml.html#usage

**Comment by damithc** [comment]
Nice. It's cool that MarkBind has features that even I don't know about. @crphang kudos for your forethought.
