### ISSUE TITLE
Document syntax features missing from the user guide

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1276]
Realized that these features are supported but are missing in our documentation. Some of which are shown in https://markdown-it.github.io/

`~subscript~`
`^superscript^`

Starting a list with a given number:
```
52. item
1. item
1. item
```

**Comment by ang-zeyu** [comment]
Here https://markbind.org/userGuide/formattingContents.html#text-styles

We do need to document markdown-it-attrs though, but it has it's own issue already I guess #1106

**Comment by damithc** [comment]
> Here https://markbind.org/userGuide/formattingContents.html#text-styles

Thx. Didn't realize it's already in. That leaves just the list numbering trick to add.
