### ISSUE TITLE
Make the copy button more subtle

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1278]
Currently, the button attracts too much attention.
![image](https://user-images.githubusercontent.com/1673303/87439333-3bf09900-c623-11ea-8fe9-801717683043.png)

Can we make it more subtle?

**Comment by KendrickAng** [comment]
@ang-zeyu Is this issue still relevant? I tried to find the [cs2103/T website](https://nus-cs2103-ay2021s1.github.io/website/se-book-adapted/projectDuke/index.html#a-moreoop) to play with and noticed that the copy button no longer exists:
![image](https://user-images.githubusercontent.com/38814428/95011482-979b5300-0663-11eb-8c60-a0da9328a024.png)

**Comment by ang-zeyu** [comment]
I think it (plugin) may have been toggled off there, you can refer to the ug for how to toggle it on https://markbind.org/userGuide/usingPlugins.html#plugin-codeblockcopybuttons

**Comment by KendrickAng** [comment]
I was reading an article about button UI https://uxdesign.cc/ui-cheat-sheets-buttons-7329ed9d6112 and thought that a line button might be what we want here; what do you think?

![image](https://user-images.githubusercontent.com/38814428/95459651-8a090480-09a6-11eb-90e0-3b01c65d051d.png)

**Comment by damithc** [comment]
> I was reading an article about button UI https://uxdesign.cc/ui-cheat-sheets-buttons-7329ed9d6112 and thought that a line button might be what we want here; what do you think?

Also, appear only on hover?

**Comment by KendrickAng** [comment]
Hmm if the button appears only on hover, how would the user know the copy button is there?

**Comment by ang-zeyu** [comment]
> Also, appear only on hover?

This might make the button redundant I think, the reader's first instinct would then be to just drag-and-ctrl-c the code 

> I was reading an article about button UI https://uxdesign.cc/ui-cheat-sheets-buttons-7329ed9d6112 and thought that a line button might be what we want here; what do you think?

Sounds good, or just leave the copy icon, anything to avoid drawing too much attention to the buttons

Something to keep in mind when styling it: #1355

**Comment by KendrickAng** [comment]
To add on to ^ zeyu's comment, from https://javascript.info/dom-nodes:

![image](https://user-images.githubusercontent.com/38814428/95464821-fab31f80-09ac-11eb-9f06-90ac46486c33.png)
