### ISSUE TITLE
Possible to change the background color of a panel body?

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1280]
I'm wondering if it is possible to change the background color of a `<panel>` body, may be using the `add-class` feature.

Similar to https://getbootstrap.com/docs/4.0/components/card/#background-and-color

**Comment by ang-zeyu** [comment]
yup but in a rather targeted way

```
.your-class .card-collapse {
  background-color: ...;
}
```

on `add-class`, actually, was there a reason for introducing this and not just using `class`? (vue automatically forwards `class` to the root element of the component) If not maybe we could deprecate that by `v3.0` as well

**Comment by damithc** [comment]
> yup but in a rather targeted way (in the sense that if someone changes `card-collapse` later on then it breaks)

Thx @ang-zeyu Will give it a try.
