### ISSUE TITLE
Questions: checking is not applicable for some questions

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1293]
I have some legacy questions that doesn't require the user to enter an answer and hence `Check` does not make sense.
![image](https://user-images.githubusercontent.com/1673303/88786114-ad544e00-d1c4-11ea-8c3d-c30b81f6d73a.png)

It would be nice if I can switch-off the border around the question as well, as it's not necessary in cases like this. But this one is lower priority.

**Comment by ang-zeyu** [comment]
questions without answers? it should still show even if there is no answer input required, but an answer is provided by the author

**Comment by damithc** [comment]
This example doesn't have an answer. It's just a question with a hint. No user input required and no answer provided.

**Comment by ang-zeyu** [comment]
> I have some legacy questions that doesn't require the user to enter an answer

yup, thought you meant that shouldn't show in all legacy questions (which don't strictly require user input)
