### ISSUE TITLE
Support reusing tooltips

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#13]
Repeating tool tip everywhere the term is used is redundant. Inline definition of tooltips breaks the flow of the content.
The ideal is to be able to write something like this and the code to pull the definition from a standard location such as `root/definitions.md`.  

```markdown
When we want to reduce {{coupling}}, we should ...
```

**Comment by Gisonrg** [comment]
Closing this as we have introduced `<trigger>`
