### ISSUE TITLE
Tweak seamless box style for headers

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1304]
Current:
![image](https://user-images.githubusercontent.com/1673303/89104535-97f15500-d44c-11ea-908b-23c6002c6c39.png)

Suggested: 
![image](https://user-images.githubusercontent.com/1673303/89104513-7a23f000-d44c-11ea-93f8-85435e42ddaf.png)

Reason: More consistent with the style used when there is no header.

**Comment by le0tan** [comment]
I suppose this change affects non-seamless styles for boxes as well?

**Comment by damithc** [comment]
> I suppose this change affects non-seamless styles for boxes as well?

Possibly, but the change in the line from horizontal to vertical is specific to seamless type only.

**Comment by daongochieu2810** [comment]
Hi I have made changes to the UI as suggested, but the tests are failing because of outdated snapshots. Can I  still submit the PR? Thanks
