### ISSUE TITLE
Support large-text style for boxes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1315]
![image](https://user-images.githubusercontent.com/1673303/89550472-3bbb7600-d83c-11ea-8293-fc3fbca33196.png)

Should we support this style for boxes? i.e., large bold text

Rationale: Some writers use these to emphasize some key parts of the content. Usually, it's a repetition of the same text in the main body.

**Comment by ang-zeyu** [comment]
This feels very similar to https://github.com/MarkBind/markbind/issues/28. I don't think it's worth implementing large / bold just for boxes though.

**Comment by damithc** [comment]
> This feels very similar to #28. I don't think it's worth implementing large / bold just for boxes though.

You are right. #28 would cover this case as well.
