### ISSUE TITLE
[Question] Outer eslint.rc file causing lint errors in top-level files in /vue-components, in WebStorm

### ISSUE THREAD

**Issue by KendrickAng** [MarkBind/markbind#1323]
**Tell us about your environment**
Windows 10, node v12.18.3, npm v6.14.6

* **MarkBind Version:**
2.15.2 (taken from lerna.json, is this how I'm supposed to get markbind's version?)

**What did you do? Please include the actual source code causing the issue.**
1. I configured Webstorm to use the root eslintrc file:
![image](https://user-images.githubusercontent.com/38814428/90095158-718fbb80-dd62-11ea-8e25-269caf7accd0.png)

2. This caused files in /vue-components 's root level to be listed as linted incorrectly:
![image](https://user-images.githubusercontent.com/38814428/90095220-94ba6b00-dd62-11ea-9f24-f05abc2b7dfc.png)

Could I have some advice on how I should approach fixing this? Should I simply fix the eslint issues with `eslint --fix` ?

```html

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output.**

**Comment by ang-zeyu** [comment]
hmm does `Automatic ESLint configuration` / `Automatic Search` work? eslint configurations cascade and inherit each other by design (we have multiple `eslintrcs`), specifying the configuration file in this case would (I suspect) stop this behaviour

**Comment by KendrickAng** [comment]
yes, that solved the issue! It seems manual configuration of eslint was causing this to act up. Thanks!
