### ISSUE TITLE
Logging for Site operations

### ISSUE THREAD

**Issue by nicholaschuayunzhi** [MarkBind/markbind#133]
Found this as a todo in `Site.js` in `markbind-cli`

https://github.com/MarkBind/markbind-cli/blob/25b595df8e91ac97f626004f1d9b770dca4adf2a/lib/Site.js#L80-L86

Just collating all the required operations to be logged for user feedback. A loading bar of sorts would be helpful as well. 

#### Build
- build start
- build info
  1. collect baseUrl
  2. build assets
  3. build source files
     - generate pages
  4. copy markbind asset
- build end + timing (speed)
#### Live Reload
- live reload start
- reload info
  - number of pages rebuilt
- live reload end + timing + ready to inspect changes

**Comment by acjh** [comment]
- Verbosity should be one of the [options](https://github.com/MarkBind/markbind-cli#usage).
- Related: #117 (Provide timestamp in logging)

**Comment by acjh** [comment]
https://github.com/MarkBind/markbind/issues/183#issuecomment-377523330:

> At some point we should adopt a proper logging framework so that we can increase logging verbosity when we want to capture more info.

**Comment by ang-zeyu** [comment]
Closing this issue as the lower level details are unapplicable at this point, moved to #1715
