### ISSUE TITLE
Link to User Guide Not working

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1339]
**Tell us about your environment**
Windows
Chrome

**What did you do? Please include the actual source code causing the issue.**
The hyperlink to user guide on the [Developer Guide](https://markbind.org/devdocs/devGuide/devGuide.html) Page is not working. It directs to https://markbind.org/devdocs/userGuide/ and on that page it shows "Page not found" Error.
The correct link seems to be this: https://markbind.org/userGuide/gettingStarted.html
**What did you expect to happen?**
View the user guide

**What actually happened? Please include the actual, raw output.**
Page not found

**Comment by ang-zeyu** [comment]
@tlylt thanks!
