### ISSUE TITLE
Popovers don't work if they are inside a collapsed panel

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1347]
Consider this popover
```html
More about <trigger for="pop:trigger_id">trigger</trigger>.
<popover id="pop:trigger_id" content="This popover is triggered by a trigger"></popover>
<br>
```
It doesn't work if placed inside a panel that is collapsed at page load (but works if the panel is expanded at page load i.e., `expanded` used)

something to do with triggers?

**Comment by ang-zeyu** [comment]
yikes, this likely needs a rewrite of the popover/modal/trigger implementation

the current implementation relies on popovers / modals / tooltips having been loaded before vue even tries to render it, which is not the case when they are in panels / modals / components that don't immediately load the content

I'll try to get to this the next weekend or the one after, then get a release out. unless anyone is interested in this : -) @KendrickAng @ryoarmanda @wxwxwxwx9

**Comment by ang-zeyu** [comment]
Found an alternative fix much smaller than what I had in mind originally

Triggers are moved back into a Vue component so we have full control over when the search for popovers / modals / tooltips occur (which now only occurs during trigger activation), so we have guarantee that the popovers / modals / tooltips are already loaded

Should also slightly improve the readability with one less compile time based transformation component

**Comment by damithc** [comment]
> Found an alternative fix much smaller than what I had in mind originally

Great. Thanks @ang-zeyu
