### ISSUE TITLE
Use MarkBind for the MarkBind website

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#135]
At some point we should use MarkBind for the MarkBind website :-)

> I don't think end users need to know there are two types of syntax. It would be good to document all syntax in one place, at least a summary.

> It would be cool if MarkBind itself can solve this problem of integrating documentation of markdown, vue, and markbind. :-)

Sub-issues:
- [x] #82: Document the `<include>` tag
- [x] #84: Document question body syntax, e.g. syntax for check boxes, radio buttons

**Comment by nicholaschuayunzhi** [comment]
Would it be possible to incorporate the test site mentioned in #121 int our main website.

Components and functionality can be documented like in https://markbind.github.io/vue-strap/

**Comment by acjh** [comment]
Updated issue description.

**Comment by damithc** [comment]
Some relevant points:
1. It is preferable that user docs are updated only when a feature is released, not when it is merged. Otherwise users will see features that are not available to them. We can do that with Markbind i.e., we run the deploy command only when a new release is made.
2. By right MarkBind is able to live-integrate (pull content from) another website. We may be able to live-integrate content from the vuestrap website into the main site so that users only need to go to one website.
