### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1354]
Error during `markbind deploy`
The deployment seems to succeed though

>v2.16.0                                                                            error:  message=Cannot read property 'trim' of undefined, stack=TypeError: Cannot r ead property 'trim' of undefined                                                        at C:\Users\damithch\AppData\Roaming\npm\node_modules\markbind-cli\node_modules \@markbind\core\src\Site\index.js:1385:34                                               at tryCatcher (C:\Users\damithch\AppData\Roaming\npm\node_modules\markbind-cli\ node_modules\bluebird\js\release\util.js:16:23)                                         at Promise._settlePromiseFromHandler (C:\Users\damithch\AppData\Roaming\npm\nod e_modules\markbind-cli\node_modules\bluebird\js\release\promise.js:547:31)              at Promise._settlePromise (C:\Users\damithch\AppData\Roaming\npm\node_modules\m arkbind-cli\node_modules\bluebird\js\release\promise.js:604:18)                         at Promise._settlePromise0 (C:\Users\damithch\AppData\Roaming\npm\node_modules\ markbind-cli\node_modules\bluebird\js\release\promise.js:649:10)                        at Promise._settlePromises (C:\Users\damithch\AppData\Roaming\npm\node_modules\ markbind-cli\node_modules\bluebird\js\release\promise.js:729:18)                        at Promise._fulfill (C:\Users\damithch\AppData\Roaming\npm\node_modules\markbin d-cli\node_modules\bluebird\js\release\promise.js:673:18)                               at PromiseArray._resolve (C:\Users\damithch\AppData\Roaming\npm\node_modules\ma rkbind-cli\node_modules\bluebird\js\release\promise_array.js:127:19)                    at PromiseArray._promiseFulfilled (C:\Users\damithch\AppData\Roaming\npm\node_m odules\markbind-cli\node_modules\bluebird\js\release\promise_array.js:145:14)           at Promise._settlePromise (C:\Users\damithch\AppData\Roaming\npm\node_modules\m arkbind-cli\node_modules\bluebird\js\release\promise.js:609:26)                         at Promise._settlePromise0 (C:\Users\damithch\AppData\Roaming\npm\node_modules\ markbind-cli\node_modules\bluebird\js\release\promise.js:649:10)                        at Promise._settlePromises (C:\Users\damithch\AppData\Roaming\npm\node_modules\ markbind-cli\node_modules\bluebird\js\release\promise.js:729:18)                        at _drainQueueStep (C:\Users\damithch\AppData\Roaming\npm\node_modules\markbind -cli\node_modules\bluebird\js\release\async.js:93:12)                                   at _drainQueue (C:\Users\damithch\AppData\Roaming\npm\node_modules\markbind-cli \node_modules\bluebird\js\release\async.js:86:9)                                        at Async._drainQueues (C:\Users\damithch\AppData\Roaming\npm\node_modules\markb ind-cli\node_modules\bluebird\js\release\async.js:102:5)                                at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\damithch\AppData\Roa ming\npm\node_modules\markbind-cli\node_modules\bluebird\js\release\async.js:15:14)
--

**Comment by damithc** [comment]
I rolled back to the previous version for the time being. Are you guys able to repro this or it's just me?

**Comment by ang-zeyu** [comment]
its harmless, just that the deployment url wont get logged

maybe @KendrickAng could take a look at it

**Comment by damithc** [comment]
I see. Thx for the investigation @ang-zeyu 
@KendrickAng let's fix it as it looks scary to the user although harmless.

**Comment by KendrickAng** [comment]
Just to check, this issue occurs when deploying from the current master branch?

**Comment by damithc** [comment]
> Just to check, this issue occurs when deploying from the current master branch?

I was using the most recent released version, not the master branch.

**Comment by KendrickAng** [comment]
Apologies, I'm not too familiar with the workload in debugging a released branch (and set it up locally). Am I correct to say that I pull in the branch tagged v2.16.0 and debug that branch, and make a PR to the master branch once I've figured it out?
@ang-zeyu could you advise?

**Comment by ang-zeyu** [comment]
its the same workflow; we don't have release / feature branches, just one main branch with `vx.x.x` tags 
the released version is just the package we publish to npm at the time of the tagged commit

**Comment by KendrickAng** [comment]
got it, thanks!
