### ISSUE TITLE
Modal/tooltip markers too fine to distinguish

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1357]
![image](https://user-images.githubusercontent.com/1673303/93668826-d22cb980-fac1-11ea-8c14-94949129ce08.png)

The dotted line is so fine that it looks like a normal line. The dashes can be made bigger?

**Comment by damithc** [comment]
It's good if we can fix this by the next release as it's important to be able to distinguish between normal underline and tooltip marker.

**Comment by kimberlyohq** [comment]
Hi, I would like to work on this issue if it is still relevant? 😊

**Comment by damithc** [comment]
This is what I see on Chrome, based on the latest MarkBind version.

![image](https://user-images.githubusercontent.com/1673303/124374061-9a96a300-dcca-11eb-9e1e-f639168094e2.png)

I think the two look different enough. Closing this issue now. Thanks for looking into this @kimberlyohq
