### ISSUE TITLE
Support a shorter alias for <markdown> tag

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#136]
`<md>`?
Given that this is a "workaround" tag, the less verbose it is, the better it is.

**Comment by acjh** [comment]
⚠ See https://github.com/MarkBind/markbind/issues/132#issuecomment-364014063:

> - `<markdown>` can be used for rendering markdown as block elements
> - `<md>` shorthand tag can be used for rendering markdown as in-line elements
