### ISSUE TITLE
Use light style for code blocks in our own documentation

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1376]
Our documentation was written when we only had the light style for fenced code blocks, and hence, the documentation doesn't look nice in the dark style (too many dark boxes within a page because we use a lot of in-line code).
Shall we set it to the light style?

I'm also wondering if we should allow controlling the inline style independently from the non-inline code blocks? Would people want to use light style for inline but dark style for non-inline?

**Comment by damithc** [comment]
@ryoarmanda what do you think?

**Comment by ryoarmanda** [comment]
Oh yeah, I just saw the dev documentation. Having too many of the dark-style inline code makes the site look patch-y, I think it fits best when the whole site is dark-style too (if that's what we're going to do in the future). I agree with using light-style for these.

I don't mind if the fenced code blocks should be switched to light too. Personally as a user I'm okay with the dark fenced code blocks over light site, but it's understandable to be overwhelmed when there are too many at a time (like say a code block after only a single line of text)

I think for the time being we can switch the documentation to light style as a whole.

> I'm also wondering if we should allow controlling the inline style independently from the non-inline code blocks?

Hmm, I'm not sure on this. On one side, I don't think there will be a lot of people wanting to do something like it in the general sense. But if we're not going to support this, there will always be problems like the current documentations if we switch to dark style, making the whole dark style option annoying/unusable for projects with similar situations. Maybe we can ask others inputs for this.

**Comment by damithc** [comment]
> I think for the time being we can switch the documentation to light style as a whole.

Let's do that.

> Hmm, I'm not sure on this. On one side, I don't think there will be a lot of people wanting to do something like it in the general sense. But if we're not going to support this, there will always be problems like the current documentations if we switch to dark style, making the whole dark style option annoying/less available for projects with similar situations. Maybe we can ask others inputs for this.

yes, probably no need.

**Comment by damithc** [comment]
@ryoarmanda this needs to be done before the next release.

**Comment by ryoarmanda** [comment]
Got it, will do it shortly!
