### ISSUE TITLE
Consider merge two repos for better dependency management

### ISSUE THREAD

**Issue by Gisonrg** [MarkBind/markbind#139]
Currently the `markbind` and `markbind-cli` are two separate repos. The initial thought is we could reuse the core library (renderer) as dependency for other projects, such as used in plugins for the editor (https://github.com/MarkBind/atom-markbind-helper, outdated).
However, this starts to bring extra project dependency issues. For example, for a change that needs to update both core library and CLI module, we have to update the core library, publish it, update CLI dependency, and make the corresponding change. Eventually, they should be in the same repo, and we could still separately publish them (I believe there are ways to do so). This could make our dependency easier to manage (no need to manually update version) and lead to improved workflow.
I think we should think about merging them into single repo.😕  Thoughts?

**Comment by acjh** [comment]
Meaning that markbind-cli would be packaged with a copy of markbind, rather than depend on a version?

**Comment by acjh** [comment]
@Gisonrg

**Comment by Gisonrg** [comment]
Sorry about the late reply, was extremely busy these weeks...

>Meaning that markbind-cli would be packaged with a copy of markbind, rather than depend on a version?
Yea I think so, and I believe we could still release `markbind` as a separate repo as well. This should simply the dependency.

**Comment by acjh** [comment]
Sure, I'll work on this.
