### ISSUE TITLE
Highlighting in headings overlap the previous line

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1395]
v2.16.0

![image](https://user-images.githubusercontent.com/1673303/99909250-4eda4f00-2d22-11eb-937b-7f3101d04978.png)

https://nus-cs3281.github.io/website/admin/cs3282.html

**Comment by damithc** [comment]
Not limited to headings e.g.,
![image](https://user-images.githubusercontent.com/1673303/103483985-3469ba00-4e26-11eb-837b-21234828ac7b.png)

**Comment by jovyntls** [comment]
I tried testing this on Chrome and Safari (if it helps, I am using MacOS), but wasn't able to replicate the issue - it looks like this for me:
![image](https://user-images.githubusercontent.com/61113575/152568065-f058c93c-abcd-41cb-8e37-774d7c5011b2.png)

* Headings: Looks like there's no overlap with the previous line, but the highlights on different lines do touch each other.
* Lists: No overlaps
* Paragraphs: No overlaps

**Comment by damithc** [comment]
Yup, seems to be OK now (Windows, Edge). Thanks for investigating @jovyntls
