### ISSUE TITLE
highlight.js EOL

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1396]
I see this when I deploy a site. Is this something we should take action on?
>Version 9 of Highlight.js has reached EOL and is no longer supported.
Please upgrade or ask whatever dependency you are using to upgrade.
https://github.com/highlightjs/highlight.js/issues/2877

**Comment by ang-zeyu** [comment]
Likely, seems like v10 has better highlighting in general

**Comment by joshgoebel** [comment]
To be clear now v9 also has potentially serious security issues for anyone using it to highlight user provided content:

https://github.com/highlightjs/highlight.js/security/advisories/GHSA-7wwv-vh3v-89cq
