### ISSUE TITLE
Questions inside seamless panels don't display well

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#14]
Here is an example:

![image](https://cloud.githubusercontent.com/assets/1673303/24294425/54dded24-10d1-11e7-842e-0d860e50f32a.png)

Compared to how the same question appears in a normal panel

![image](https://cloud.githubusercontent.com/assets/1673303/24294456/7ae3e46a-10d1-11e7-901f-58275836bd0a.png)

**Comment by Gisonrg** [comment]
Fixed in release 1.2.6
