### ISSUE TITLE
Support using markdown headers in panel header attribute

### ISSUE THREAD

**Issue by rachx** [MarkBind/markbind#140]
Currently, it is not possible to use markdown headers in the panel header attributes.
`<panel header= "## Introduction"> </panel>` will render "## Introduction" on the html page.

We use markdown-it `renderInline` to parse the panel's header attribute and it ignores all block elements. Perhaps, we can use `render` instead.

Proposed vs original:
![image](https://user-images.githubusercontent.com/16644412/35905248-52d1a858-0c21-11e8-9a86-25108362ab9c.png)

This gives the user the option to emphasize text in the panel header without using any workaround.

**Comment by damithc** [comment]
Indeed it will be good feature to have 👍 
Especially if we can get it working for seamless panels.
