### ISSUE TITLE
Add mention for node version configuration in netlify setup

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1400]
Noticed se-edu/se-book PRs failing netlify preview e.g., https://app.netlify.com/sites/se-edu-se-book/deploys/5fc3ac712225840008236464

Is this a problem related to the new MarkBind version?

**Comment by ang-zeyu** [comment]
`notsup Unsupported engine for fs-extra@9.0.1: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})`

nope, you'll need to upgrade the node version netlify is using

https://docs.netlify.com/configure-builds/manage-dependencies/

**Comment by damithc** [comment]
Thanks. Is this mentioned (or should we mention it) in our own documentation of setting up Netlify for MarkBind?

**Comment by ang-zeyu** [comment]
nope as well, let's add it in 👍

**Comment by acjh** [comment]
The `fs-extra` dependency was introduced in #1351 (released in 2.17.0).

The [User Guide](https://markbind.org/userGuide/gettingStarted.html) does mention the Node.js version in the Prerequisites:

> Node.js v10.13.0 or higher installed

The mention was added in #953 (released in 2.8.0), where I commented:

> Node.js v8 is reaching End-of-life on 2019-12-31: https://nodejs.org/en/about/releases/
> That's less than 3 weeks from now.
> Let's recommend v10.13.0 (LTS) or higher; v10 will only reach End-of-life on 2021-04-30.

**Comment by ang-zeyu** [comment]
I think @damithc was referring to an explicit step / warning box to set the NODE_VERSION in netlify, since we have a guide for that. Could add that in.

https://markbind.org/userGuide/deployingTheSite.html#deploying-to-netlify

**Comment by damithc** [comment]
> nope, you'll need to upgrade the node version netlify is using
> 
> https://docs.netlify.com/configure-builds/manage-dependencies/

Managed to fix the build. Spews out a lot of intra-link warning though. Intended? https://app.netlify.com/sites/se-edu-se-book/deploys/5fc784bb3bd97f6acf27bf9e

**Comment by raysonkoh** [comment]
Hi guys, is this issue still valid? I can take up this issue if no one is doing it.

**Comment by ang-zeyu** [comment]
Sure 👍

**Comment by raysonkoh** [comment]
My PR is ready for review.
