### ISSUE TITLE
Deploy script fails if deploying to different repos

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#141]
If an author has multiple markbind sites, the deploy script will fail. The resolution is given below:
>If the deployment failed due to a 'caching' issue, try deleting the the cache generated by the previous deploy command (on Windows, the cache can be found in /c/Users/{user-name}/AppData/Roaming/npm/node_modules/markbind-cli/node_modules/gh-pages/.cache)

I wonder if this can be avoided.

**Comment by nicholaschuayunzhi** [comment]
Seems like this issue has been addressed upstream in https://github.com/tschaub/gh-pages/pull/173
The changes made in the latest release:
https://github.com/tschaub/gh-pages/releases/tag/v1.0.0
