### ISSUE TITLE
Improve broken link reporting

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1418]
MarkBind reports broken intra-site links during the build process (e.g., `markbind serve` command). Following improvements are suggested (can do in separate PRs):

- [x] Report each broken link only once (priority.Medium) (d.moderate)
- [x] Support validating `#hashes` for `<a>` tags _efficiently_ (priority.Medium) (d.moderate / high)
- [x] Provide a way to disable broken link reporting (priority.High)
- [x] Provide a way to suppress the warning for specific pages or links (priority.Low)
- [x] Restore broken link reporting for pics (disabled earlier due to #1416) (priority.Low)

**Comment by ang-zeyu** [comment]
`<pic>` link checks are only disabled for v2.7.x (separate branch), and remains in the current working branch without issues.

it's certainly fixable in v2.7.x, but would require a moderate amount of effort

**Comment by damithc** [comment]
@wxwxwxwx9 Any thoughts on this item?
>- [ ] Provide a way to disable broken link reporting (priority.High)

**Comment by wxwxwxwx9** [comment]
> @wxwxwxwx9 Any thoughts on this item?
> 
> > * [ ]  Provide a way to disable broken link reporting (priority.High)

@damithc I think this is quite do-able. To implement this, I'm thinking of adding a new field in "site.json". Maybe something called "validateIntralink" as a key with a boolean as the value. 

As the "site.json" is read and transformed into "SiteConfig", we can pass down "validateIntralink" to "linkProcessor" to indicate whether we should even validate any link(s) in the first place. I think this should be quite straightforward. 

@ang-zeyu is there anything else I should take note of?

**Comment by jovyntls** [comment]
Hello! For this part:

> Report each broken link only once (priority.Medium) (d.moderate)

Could I check what counts as a duplicated broken link? i.e. If the same (broken) intralink is on two different pages, should it be reported twice or only once? Should we report all pages where a broken link has been found?

Implementation wise, I was thinking of maintaining a set of links that have been validated, and only validate links if it is not already in the set.

**Comment by damithc** [comment]
> Could I check what counts as a duplicated broken link? i.e. If the same (broken) intralink is on two different pages, should it be reported twice or only once? Should we report all pages where a broken link has been found?

Currently, if a certain markdown file has a broken link but that file is being included in many different places, is the problem reported once or for each of those inclusions?

Technically, the number of broken-links reported should match the number of fixes required, but not sure if we can achieve that.

**Comment by jovyntls** [comment]
@damithc  If a certain markdown file has a broken link but that file is being included in many different places, currently it is reported for each of these inclusions. If a broken link appears multiple times on the same page, it is also reported multiple times.

**Comment by damithc** [comment]
> @damithc If a certain markdown file has a broken link but that file is being included in many different places, currently it is reported for each of these inclusions. If a broken link appears multiple times on the same page, it is also reported multiple times.

I see. Thanks for investigating @jovyntls
It's that sort of duplication that we can try to get rid of.

**Comment by jovyntls** [comment]
Ok! Just to clarify, the desired behaviour should be:

* A broken link occurs multiple times on the same page (no inclusion) => Report this multiple times, to match the number of fixes required
* A broken link occurs on a page, which is included in many pages => Report this once, because only one fix is needed (on the original page)

**Comment by damithc** [comment]
> Ok! Just to clarify, the desired behaviour should be:
> 
> * A broken link occurs multiple times on the same page (no inclusion) => Report this multiple times, to match the number of fixes required
> * A broken link occurs on a page, which is included in many pages => Report this once, because only one fix is needed (on the original page)

Yes, that's my current thinking. Other suggestions are welcome too.

**Comment by ang-zeyu** [comment]
How about:
- report all broken links at once, at the end, once all pages have finished building (minimize disjointed messages, should be simpler to implement as well)
- for any given source file, report all its broken links, and the count of broken links only once

**Comment by tlylt** [comment]
We may also want to consolidate the various reasons (not sure if there are any left) for false positives, and resolve them if possible.

**Comment by jovyntls** [comment]
> * [ ]  Support validating `#hashes` for `<a>` tags _efficiently_ (priority.Medium) (d.moderate / high)

I'm thinking of the following approach:
- As we process nodes, 
	- collect all ID attribute values into SiteLinkManager. We can map the filepaths to a set of IDs that are contained in the file, i.e. map of {filepath: string => Ids: Set<string>}
	- collect all hashes from `<a>` tags to validate into SiteLinkManager
	- This should incur no additional time complexity since we avoid loading the entire page as we do for `includes`. There is cost from storing the IDs, but I think this should not be a significant time cost?
- After all nodes have been processed (and thus all IDs have been collected), validate the hashes from `<a>` tags that we have collected

Looking for feedback/comments on this approach!

**Comment by ang-zeyu** [comment]
sounds good 👍

**Comment by yiwen101** [comment]
> > * [ ]   Support validating `#hashes` for `<a>` tags _efficiently_ (priority.Medium) (d.moderate / high)
> 
> I'm thinking of the following approach:
> 
> * As we process nodes,
>   
>   * collect all ID attribute values into SiteLinkManager. We can map the filepaths to a set of IDs that are contained in the file, i.e. map of {filepath: string => Ids: Set}
>   * collect all hashes from `<a>` tags to validate into SiteLinkManager
>   * This should incur no additional time complexity since we avoid loading the entire page as we do for `includes`. There is cost from storing the IDs, but I think this should not be a significant time cost?
> * After all nodes have been processed (and thus all IDs have been collected), validate the hashes from `<a>` tags that we have collected
> 
> Looking for feedback/comments on this approach!

Thanks for the idea; will try to implement this.

**Comment by kaixin-hc** [comment]
The PR by @yiwen101 seems to have resolved the last of the issues here, thanks again! Closing this for now.
