### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1424]
Guys, the search box doesn't seem to work in v2.16 onwards e.g., https://se-education.org/se-book/

I didn't notice it as I was using v2.15.* until recently

Let me know if you can't reproduce

**Comment by ang-zeyu** [comment]
yikes, algolia plugin regression from https://github.com/MarkBind/markbind/commit/dbbe9d84e7452183a6b8b9c175a39d36223d0758

I've released a quick fix: https://www.npmjs.com/package/markbind-cli/v/2.17.2

Could you retest? (don't have an algolia key)

**Comment by damithc** [comment]
Yup, that worked. Thanks @ang-zeyu
