### ISSUE TITLE
Support user-defined variables

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#143]
Currently we support a special variable `{{baseUrl}}`
It would be useful to allow the user to define more such variables where the value can be any markbind-compliant code fragment.

e.g., we can have a file called `_system\variables.md` which has a format like this:
```
<span id="year">2018</span>

<span id="options">
* yes
* no
* maybe
</span>
```
And the normal files can use `{{year}}` `{{options}}` etc.

A feature like this can help to reduce the verbosity of the code.

**Comment by rachx** [comment]
I am working on this. My current idea is to use regex to match and replace the content before parsing is done.
How about
```
{{options}}
<span id="options">
<markdown>
* yes
* no
* maybe
</markdown>
</span>
{{/options}}
```

**Comment by damithc** [comment]
If we enforce that all variables for a site will be in a known location `[root]\_system\variables.md`, we don't need the tags `{{options}}..{{/options}}`?. We can simply go by span/div IDs to identify the variables and their values. Would that work?

**Comment by acjh** [comment]
> My current idea is to use regex to match and replace the content before parsing is done.

Use [`nunjucks.renderString`](https://mozilla.github.io/nunjucks/api.html#renderstring) instead of regex:

https://github.com/MarkBind/markbind/blob/921753440d8e38f77bbe0d183695b4cda5a7664e/lib/parser.js#L494

> We can simply go by span/div IDs to identify the variables and their values. Would that work?

Seems possible with [cheerio](https://github.com/cheeriojs/cheerio), which MarkBind is already using. More work, but definitely cleaner.

**Comment by damithc** [comment]
Started used this feature. Defined this text that appears several times in [this website](https://nus-te3201.github.io/website/programming/index.html)
```html
<span style="float:right">[<span class="glyphicon glyphicon-home" aria-hidden="true"></span> ↑](../index.html)</span>
```
that shows this 'back to home' link
![image](https://user-images.githubusercontent.com/1673303/37272064-6faa2ac8-2610-11e8-8244-7ad4b56eb034.png)
as variable`{{home↑}}`
It worked despite the use of the arrow. Nice. 💯
