### ISSUE TITLE
Support live preview for changes in imported nunjucks files

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1442]
This may be not easy to implement but it would be great if the live preview can be rebuilt/refreshed when the author modifies a file that the current page depends on via a nunjucks `import`.
If the above can be supported, most likely the author doesn't need to restart the server at all during an authoring session.

A shortcut: Rebuild the page if _any_ page containing nunjucks code is modified? I don't think it would hinder the author too much if we did that.

**Comment by ang-zeyu** [comment]
Should be present as part of #1353's requirements already. Could you confirm?

also works for every nunjucks tag that references a file (include / import / extends / ...)

**Comment by damithc** [comment]
I'm using the latest released version and I don't see this feature yet. At least, there are cases where I update a nunjucks macro but the live preview doesn't reflect it. Perhaps some complicated dependencies are not captured? For example, previewing file F1 that includes a fragment from F2 that imports a macro from F3 but F3 imports a variable from F4. Will F1 live preview reflect changes done to the variable in F4?

**Comment by ang-zeyu** [comment]
just tested the scenario you described, it works isolated;

I'm guessing it does not work when some other file also references f2 / f3 / f4 (though it would still refresh up to f2). (is this the case?)

**Comment by damithc** [comment]
> I'm guessing it does not work when some other file also references f2 / f3 / f4 (though it would still refresh up to f2). (is this the case?)

This is possible. You know how complicated the CS2103 website is :-p I can give the exact steps to reproduce when I go home later tonight.

**Comment by ang-zeyu** [comment]
>I'm guessing it does not work when some other file also references f2 / f3 / f4 (though it would still refresh up to f2). (is this the case?)

nvm just tested and works as well 🤔 

I'll wait for the steps =P

**Comment by damithc** [comment]
One place where I could reproduce the problem involves the following `include` which is calculated dynamically (in `admin/lectures.md`).
`<include src="../_module-{{ module | lower }}/timetables.mbdf#lectures-s{{ S }}" inline />`

I guess the above is a rare case and OK to not cater for. I'm almost sure there were other cases but can't remember them now. I'll post when I encounter another next time.

**Comment by ang-zeyu** [comment]
which site is this?

I couldn't find any nunjucks tags `{% ... %}` in the various `timetables.mbdf` [here](https://github.com/nus-cs2103-AY2021S1/website)

**Comment by damithc** [comment]
> I couldn't find any nunjucks tags `{% ... %}` in the various `timetables.mbdf` [here](https://github.com/nus-cs2103-AY2021S1/website)

This case is not related to nunjucks imports. I suspect it is because MarkBind can't figure out which file is being included as the `src` attribute contains nunjucks variables. Is that the case?
However, I noticed that the page indeed gets refreshed when I edit the timetables.mbdf but the edit doesn't get reflected in the refreshed page.

**Comment by ang-zeyu** [comment]
hmm it should be able to as nunjucks is processed first, even in `v2.7.x`;

does manually refreshing once more work? I've noticed sometimes the page appears to refresh, but needs another manual refresh to actually show the changes.

but this would be a separate issue eitherway

**Comment by damithc** [comment]
> does manually refreshing once more work? I've noticed sometimes the page appears to refresh, but needs another manual refresh to actually show the changes.

Tried just now. Doesn't seem to work.

> but this would be a separate issue eitherway

Yup.

**Comment by ang-zeyu** [comment]
its occuring due as our filepaths checks are case sensitive: 
you can temporarily remove the `lower` filter in `<include src="../_module-{{ module | lower }}/... />`

this should be fixed, though.

are the other cases similar? (not concerning nunjucks tags)

**Comment by damithc** [comment]
> its occuring as our filepaths checks are case sensitive:
> you can temporarily remove the `lower` filter in `<include src="../_module-{{ module | lower }}/... />`

Darn. Didn't realize because I'm using Windows. The `lower` shouldn't be there in the first place. Thanks for the catch.

> are the other cases similar? (not concerning nunjucks tags)

Will let you know when I encounter it again.  Can even close this issue for now. I'll reopen if I encounter it again.

**Comment by ang-zeyu** [comment]
👍

closing
