### ISSUE TITLE
Inquiry on PlantUML diagrams rendering with surge/netlify previews

### ISSUE THREAD

**Issue by rolandyuwy** [MarkBind/markbind#1459]
**Tell us about your environment**

* **MarkBind Version:** 2.17.3

**What did you do? Please include the actual source code causing the issue.**

- With reference to https://github.com/reposense/RepoSense/issues/1427, some PlantUML diagrams do not render for the **surge preview** of PR https://github.com/reposense/RepoSense/pull/1406, which replaces images in the Developer Guide with PlantUML diagrams.

Code in .md file:
```
<puml src="../diagrams/ReportArchitecture.puml"/>
```
Code in .puml file:
```
@startuml
hide footbox
skinparam monochrome true
skinparam Shadowing false

rectangle "main.js\n(window.app)" as main
rectangle "v_zoom.js" as v_zoom
rectangle "v_ramp.js" as v_ramp
rectangle "v_summary.js" as v_summary
rectangle "v_authorship.js" as v_authorship
rectangle "v_segment.js" as v_segment
database "api.js\n" as api

main -down-> v_summary
v_summary -down-> v_zoom
v_summary -> v_ramp
v_zoom -> v_ramp

main -down-> v_authorship
v_authorship -down-> v_segment

api -down--> main : summary.json
api -down-> v_summary : projectName/commits.json
api -down-> v_authorship : projectName/authorship.json
@enduml
```

**What did you expect to happen?**
All .puml diagrams should render in the surge preview.

**What actually happened? Please include the actual, raw output.**
- Only component diagrams failed to render.
- With reference to https://stackoverflow.com/questions/54413962/cant-render-component-diagram-in-plantuml-intllij, it seems Graphviz installation is required for rendering of PlantUML **component diagrams**. **Sequence and activity diagrams** (ReportArchitectureAuthorship.puml and ReportArchitectureSummary.puml) work without Graphviz installation.
- I would like to inquire if PlantUML diagrams for MarkBind sites will work with surge/netlify previews.

**Comment by ang-zeyu** [comment]
It would work as long you can install / have java and graphviz in the ci platform.

Looks like netlify comes with graphviz by default, but I may have misread this: https://www.netlify.com/blog/2018/08/23/how-to-easily-visualize-a-projects-dependency-graph-with-dependency-cruiser/

From the comments in the original puml PR https://github.com/MarkBind/markbind/pull/887 there dosen't seem to be any issues with the netlify deploy as well.

Not too sure on surge
