### ISSUE TITLE
Remove extra space in links

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#147]
e.g., `[[link text](https://github.com)]`
expected [[link text](https://github.com)]
actual (note the extra space in front) [ [link text](https://github.com)]

Real example :
![image](https://user-images.githubusercontent.com/1673303/36195316-0dc04b7a-11a8-11e8-82f8-d62b43e18340.png)

**Comment by yamgent** [comment]
Can reproduce the spacing problem, but only under the conditions that:

* The link is on a separate line on its own, but must still be connected to the previous line (i.e. no empty lines between the two lines).
* There must not be any additional text before the link.

Otherwise, the extra space will not appear.

Sample content that generates the problematic spacing:

```markdown
The quick brown fox jumps over the lazy dog
[[link to github](https://github.com)].
```

Produces:

```
The quick brown fox jumps over the lazy dog [ link to github].
```

**Comment by damithc** [comment]
Is it the line break that is being transformed into a space?

**Comment by yamgent** [comment]
> Is it the line break that is being transformed into a space?

That would actually be the space before the `[`, not after the `[`. But something in our build process is adding another line break after the `[`. In my findings so far, it doesn't seem to be the markdown parser that is adding the line break (I played around with the vanilla parser library, it didn't add in any extra whitespace/breaks).

Also the character need not be `[`. It can be any other character/word and it will still have this problem:

Input:
```markdown
The quick brown fox jumps over the lazy dog
sometextbefore[link to github](https://github.com).
```

Expected Output:
```
The quick brown fox jumps over the lazy dog sometextbeforelink to github.
```

Actual Output:
```
The quick brown fox jumps over the lazy dog sometextbefore link to github.
```

**Comment by yamgent** [comment]
We narrowed it down to the library that caused the line break: `js-beautify` library.


Before | After
-- | --
<img width=350 src="https://user-images.githubusercontent.com/3168908/40168215-83237e06-59f5-11e8-9367-6fa213beb33a.png" /> | <img width=300 src="https://user-images.githubusercontent.com/3168908/40168217-86222c74-59f5-11e8-9018-a434ce74ac6c.png" />

**Comment by acjh** [comment]
I recommend closing this issue as <kbd>c.Wontfix</kbd> as it's inefficient for MarkBind to handle this edge case.

Workaround:

```html
Abcdef
<span></span>[[link text](https://github.com)]
```

Produces:
```html
<p>Abcdef
  <span></span>[<a href="https://github.com">link text</a>]</p>
```

**Comment by damithc** [comment]
Some documentation of this workaround could be useful, may be under a 'known problems' section.
