### ISSUE TITLE
Support a simple font coloring markdown syntax?

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1475]
**Is your request related to a problem?**

Inspiration from the `lineSpec` parameter matlab's plot function https://www.mathworks.com/help/matlab/ref/plot.html

I personally found being able to edit various plot properties with a single character really convenient.

**Describe the solution you'd like**

We could support something along the lines of:

```
#r#...some text...## // red color
#g#...some text...## // green color
...
```

Should save a lot of typing `<span style="font-color:red">...</span>` or `<span class="your-red-class / bootstrap text classes">...</span>` too.

Concerns:
- not very semantic=P
- ❔ 

**Describe alternatives you've considered**

**Additional context**

**Comment by damithc** [comment]
Seems useful. I don't have any objections myself.
