### ISSUE TITLE
<body> tag in included HTML causes formatting errors 

### ISSUE THREAD

**Issue by danielbrzn** [MarkBind/markbind#148]
Wrapping the content of a HTML document within a `<body>` tag disrupts the formatting of the entire site. 

Actual:
![image](https://user-images.githubusercontent.com/251231/36197337-74527fa6-11ae-11e8-8e26-b20c2a711035.png)

HTML:
```
<body><p>This is a HTML document.</p></body>
```

Expected:
![image](https://user-images.githubusercontent.com/251231/36197396-92bdf600-11ae-11e8-99bd-abdc9736939d.png)

HTML:
```
<p>This is a HTML document.</p>
```

**Comment by acjh** [comment]
Why would you do that?

Read: https://stackoverflow.com/questions/2035462/multiple-htmlbody-html-body-in-same-file

**Comment by nicholaschuayunzhi** [comment]
I think what @danielbrzn means is that it could be a potential user error which will lead to these formatting errors. Maybe we could document this or warn the user about this?

**Comment by danielbrzn** [comment]
Yeah I meant it could be a user error (as I encountered it myself) because a standalone HTML document may include the  <body> tag and as such a user may be wondering why the formatting is messed up when he/she tries to include the HTML file.

Yes it should be possible to warn the user, perhaps with a message that states that the formatting of the website may not be as intended.
