### ISSUE TITLE
Format rendered tables similar to regular markdown

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#149]
Current formatting
![image](https://user-images.githubusercontent.com/1673303/36338355-a176cc22-13e7-11e8-8508-70635a9b3a12.png)

Lack of vertical lines can be a problem at times. It's preferred if the formatting of tables follow that of normal markdown (e.g., as seen in GitHub markdown pages)

![image](https://user-images.githubusercontent.com/1673303/36338362-d35a6cc6-13e7-11e8-8c54-e10d47a23011.png)

**Comment by nicholaschuayunzhi** [comment]
Hi prof @damithc would you prefer compact tables
![image](https://user-images.githubusercontent.com/22221132/36930745-9dc50b24-1ee2-11e8-846c-198f98f5aa14.png)


or tables that fill the width of the brower (bootstrap behaviour, but with github markdown styling):
![image](https://user-images.githubusercontent.com/22221132/36930750-b3dd9dcc-1ee2-11e8-809d-c10ac05a6bb3.png)

**Comment by damithc** [comment]
I think compact tables are better. No point wasting space when cell boundaries are clearly marked.
