### ISSUE TITLE
Support syntax coloring for code examples

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#15]
![image](https://cloud.githubusercontent.com/assets/1673303/24294516/c240c864-10d1-11e7-986e-b5883313fd98.png)

**Comment by Gisonrg** [comment]
![screen shot 2017-03-25 at 2 28 00 am](https://cloud.githubusercontent.com/assets/4332224/24308373/ae2c6596-1102-11e7-8b63-ecff37c3e52d.png)

Implemented with Highlight.js.
