### ISSUE TITLE
Dropdown header color suspected to be incorrect

### ISSUE THREAD

**Issue by wxwxwxwx9** [MarkBind/markbind#1503]
<img width="421" alt="Screen Shot 2021-03-05 at 12 18 25 AM" src="https://user-images.githubusercontent.com/37920115/109994477-50b3a580-7d48-11eb-9917-ebb76aa1d7da.png">

EDIT: Ignore the last empty dropdown, it is a known bug, raised up in #1472.

In the image above, we can see that the "Action" header font color is black.

![Screen Shot 2021-03-05 at 12 20 42 AM](https://user-images.githubusercontent.com/37920115/109994797-9ff9d600-7d48-11eb-846c-0757637dc759.png)

It used to be white color as seen in the picture above (gotten from the current Markbind website). 

![Screen Shot 2021-03-05 at 12 21 39 AM](https://user-images.githubusercontent.com/37920115/109994935-c3248580-7d48-11eb-9fe8-af2fec9a951d.png)

After poking around, I found that the `color: inherit` is causing the above to happen. 

@jonahtanjz can I check if you know anything about this? Was it meant to be like this?

**Comment by jonahtanjz** [comment]
> @jonahtanjz can I check if you know anything about this? Was it meant to be like this?

It seems this was changed in #1451 to fix an issue related to dropdowns not showing up when using themes #1444. Somehow this has an undesired effect on all dropdowns. I believe this can be rectify by only applying this css rule to only dropdowns in navbar instead.

**Comment by wxwxwxwx9** [comment]
@jonahtanjz thanks so much for providing the context! I think that solution sounds good. 

@raysonkoh what do you think about the solution suggested? Would be great to have your input as well :-)
