### ISSUE TITLE
Fully deprecate some component attributes

### ISSUE THREAD

**Issue by wxwxwxwx9** [MarkBind/markbind#1504]
While working on some issues related to dropdown, I realised that we are still processing the `text` attribute for dropdown. However, the `text` attribute is currently stated to be deprecated in the user guide. For code maintenance purposes, should we fully remove any processing code related to `text` attribute?

**Comment by ang-zeyu** [comment]
@damithc should we deprecate these attributes for v3 as well?

If its too much changes could postpone https://github.com/MarkBind/markbind/pull/975

> dropdowns - "text" -> "header"
> boxes - "heading" -> "header"
> popovers - "title" -> "header"
> modals - "title" -> "header"

**Comment by damithc** [comment]
> @damithc should we deprecate these attributes for v3 as well?

Sure. Does that mean there will be a warning message or those will be ignored altogether?

**Comment by ang-zeyu** [comment]
Ignored altogether

**Comment by damithc** [comment]
The current version gives a warning already, correct? In that case should be fine as I've dealt with those warnings already.

**Comment by ang-zeyu** [comment]
> The current version gives a warning already, correct? In that case should be fine as I've dealt with those warnings already.

yup

**Comment by ang-zeyu** [comment]
For context:  V3 has deprecated these attributes on the changelog front but the implementation remains.

We should remove the implementation completely for V4
