### ISSUE TITLE
Implement a search bar for easier navigation

### ISSUE THREAD

**Issue by danielbrzn** [MarkBind/markbind#151]
Currently it's quite difficult to find a particular page in a Markbind site as there is no search function to do so. I propose adding a search bar to the right of the top navigation bar so that users will be able to easily search for the information they require in a short amount of time. We could use the page titles in `site.json` to achieve this.

It could possibly be implemented with [typeahead.js](https://www.npmjs.com/package/typeahead.js).

**Comment by damithc** [comment]
Good idea. In fact it is nice if we have this feature in MarkBind itself, given that we are likely to convert docs to MarkBind anyway.
