### ISSUE TITLE
Support showing .md links

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1516]
We need a way to give a .md link in a MarkBind site
As of now, all .md links are auto-converted to .htm

**Comment by wxwxwxwx9** [comment]
Hi Prof! We currently can insert an attribute to prevent the auto-conversion of `.md` links. 

However, the one shown on user guide currently is the erroneous one, pending to be fixed by #1494.

Can you try the following syntax? This should work. 

`Click [here](index.md){no-convert}`

**Comment by damithc** [comment]
> Can you try the following syntax? This should work.
> 
> `Click [here](index.md){no-convert}`

Ah, nice. Forgot we had something like that already. Will try it soon. Thanks for the follow up @wxwxwxwx9

**Comment by damithc** [comment]
BTW, the error in the UG is likely caused by the fact that we use a dot in other cases. So, should we make it `{.no-convert}` (for consistency) or keep `{no-convert}`?
Related questions: Is there an internal reason for using two styles? If there is, does it still make sense to end-users? If no, should we 'force' a consistent style for the sake of making things easier for users.

**Comment by wxwxwxwx9** [comment]
Hmm I think we can make it into `{.no-convert}` (with the dot) for consistency across MarkBind. I don't think there is a strong internal reason (if any) to use two styles. @ang-zeyu what do you think? Am I missing out on anything?

**Comment by ang-zeyu** [comment]
> Hmm I think we can make it into `{.no-convert}` (with the dot) for consistency across MarkBind. I don't think there is a strong internal reason (if any) to use two styles. @ang-zeyu what do you think? Am I missing out on anything?

hmm let's go with the attribute. that way it makes more sense when using it on `<a href="..." no-convert />`. (`<a href="..." class="no-convert" />` is a little awkward)

I'll fix the error in the published UG shortly. (only the attribute should work currently)
