### ISSUE TITLE
Display problems with codeAndOutput.md

### ISSUE THREAD

**Issue by raysonkoh** [MarkBind/markbind#1517]
`codeAndOutput.md` is a boilerplate file which is referenced several times in the userGuide. However, there seems to be some errors in the "displayed code" in the current Markbind-master when referenced against the Markbind.org userguide.

Examples:

## In markbind-master (actual)
<details>
<summary>Footer section</summary>

![image](https://user-images.githubusercontent.com/16506539/111752024-22999e00-88d0-11eb-9bbb-bc809eed6f84.png)
</details>

<details>
<summary>Tips and Tricks section</summary>

![image](https://user-images.githubusercontent.com/16506539/111752284-7906dc80-88d0-11eb-9f84-404cf671f040.png)
</details>

## In markbind.org (expected)
<details>
<summary>Footer section</summary>

![image](https://user-images.githubusercontent.com/16506539/111752108-3fce6c80-88d0-11eb-9473-cdd69525c392.png)
</details>
<details>
<summary>Tips and Tricks section</summary>

![image](https://user-images.githubusercontent.com/16506539/111752324-84f29e80-88d0-11eb-9ecb-dc35f00d9409.png)
</details>

**Comment by ang-zeyu** [comment]
Thanks for the catch. Related to #1500 (another occurence)
