### ISSUE TITLE
Documentation Bug: link to emoji-cheat-sheet is broken

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1528]
**Tell us about your environment**
Windows
**MarkBind Version:**
MarkBind 2.18.1
**What did you do? Please include the actual source code causing the issue.**
Clicking on the link for list of supported emoji at https://markbind.org/userGuide/formattingContents.html#emoji opened a Github 404 page
![image](https://user-images.githubusercontent.com/41845017/112925202-102b2a00-9144-11eb-8635-b4d6a13b8d4b.png)

**What did you expect to happen?**
Expect to show this: https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md

**What actually happened? Please include the actual, raw output.**
Actually show this:
![image](https://user-images.githubusercontent.com/41845017/112925298-3a7ce780-9144-11eb-9e6d-d386eb4d0446.png)

**Comment by ryoarmanda** [comment]
👀 Looks like we missed this. Thanks for the catch @tlylt ! We'll do the fix shortly :)

**Comment by ong6** [comment]
This issue seems to be fixed, maybe one of the devs can close it @damithc?
