### ISSUE TITLE
User Guide: Next button skips a few chapters

### ISSUE THREAD

**Issue by ptvrajsk** [MarkBind/markbind#1542]
**Tell us about your environment**
*Brave Browser*

* **MarkBind Version: NIL**

**What did you do? Please include the actual source code causing the issue.**

*Not sure if this is a bug but,*

![image](https://user-images.githubusercontent.com/39243082/114261388-de03ad00-9a0c-11eb-9f51-1a65781719cb.png)

*I noticed that the the next section button skips over the sections highlighted in green.*

**What did you expect to happen?**

*It should link to `Tweaking the Page Structure` since its the next immediate section*

**What actually happened? Please include the actual, raw output.**

*It didn't.*

**Comment by wxwxwxwx9** [comment]
Hi @ptvrajsk, thanks for raising this up! It is indeed a documentation error as you mentioned. We will look to fix it accordingly :-)
