### ISSUE TITLE
Inline code renderer still uses deprecated HighlightJS API

### ISSUE THREAD

**Issue by ryoarmanda** [MarkBind/markbind#1549]
Using MarkBind `master` branch. After #1521, deprecated warning of HighlightJS `highlight` API still shows up when navigating `docs/userGuide/syntaxCheatsheet`:

![image](https://user-images.githubusercontent.com/24468110/115612651-14e79600-a31e-11eb-81b4-fd6acdf82ad6.png)

Quick search shows that while the main fenced code-block is already using the updated API, the inline code rendered is still using the old one. While the old API still works, we should migrate fully on using the new API.

**Comment by raysonkoh** [comment]
Thanks for raising this, I will look into it!

**Comment by ryoarmanda** [comment]
@raysonkoh are you working on this? I might take it on if you haven't. The deprecated logs kind of clutter our CLI logs a bit.
