### ISSUE TITLE
Add hamburger transitions for mobile site / page nav icons

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1558]
https://codepen.io/designcouch/pen/Atyop

Something like that.

**Comment by kimberlyohq** [comment]
Hi @ang-zeyu, I am currently working on this and I have a few questions. While trying to implement the “icon” using a similar approach in the link, it seems like I have to hardcode quite a few variables such as width, height. Is this expected or is there a workaround? 😅 This is what I have currently 

https://user-images.githubusercontent.com/60393696/122719519-dc722300-d2a0-11eb-847c-f89c38163706.mp4

Regarding the hamburger transitions for the page nav icons, is the transition effect similar to the one for site nav icons? A rough implementation:

https://user-images.githubusercontent.com/60393696/122719635-0b889480-d2a1-11eb-93eb-9c5c0cf3a04e.mp4

**Comment by ang-zeyu** [comment]
@kimberlyohq "hardcoding" widths and heights with `px` (I'm assuming) is fine (and in fact very common) if it ultimately still results in appropriate responsive design.

But I may be missing something 😛, will need to take a look at your PR to figure out the specifics for this case.

**Comment by kimberlyohq** [comment]
@ang-zeyu okay! I will clean up the code and send a PR soon😊
