### ISSUE TITLE
site-nav: link highlighting doesn't work if the link is generated by a script

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1567]
Not sure if this is fixable but reporting here for the record.

Problem: if the links in the site-nav is generated by a nunjucks script (e.g., https://raw.githubusercontent.com/reposense/RepoSense/master/docs/_markbind/navigation/ugSiteNav.md), the current page loaded will not be highlighted as expected.

![image](https://user-images.githubusercontent.com/1673303/119360071-d6f2de80-bcdc-11eb-8105-144a5a69c22b.png)

**Comment by jonahtanjz** [comment]
Similar to https://github.com/MarkBind/markbind/issues/1566#issuecomment-848457493, the current master branch should resolve this issue as the checking of the current link is now done in the vue component (after all the links have been processed by Markbind).

**Comment by damithc** [comment]
> the current master branch should resolve this issue

Thanks for checking @jonahtanjz Should be fine if fixed already in the master branch. Closing.
