### ISSUE TITLE
Support ability to indent tip-boxes and panels

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#157]
In some cases tip-boxes and panels need to be indented. It would be nice if we can support that.

![image](https://user-images.githubusercontent.com/1673303/36933240-8fab7356-1f10-11e8-8a96-47cdb62369f7.png)

**Comment by nicholaschuayunzhi** [comment]
Hi prof @damithc
Currently tip boxes are indented with the list item
![image](https://user-images.githubusercontent.com/22221132/37239107-4c73ec98-2470-11e8-93e4-832c97252d65.png)

```md
# List

- Item 1 <panel>Indented Panel</panel>
- Item 2 <tip-box>Indented Tip-Box</tip-box>
    - SubItem 1 <panel>Indented Panel</panel>
    - SubItem 2 <tip-box>Indented Tip-Box</tip-box>
```

For the example provided, you can achieve this by doing:
```md
1. **Documentation for _developer-as-user_**: Software components are written by developers and used by other developers. Therefore, there is a need to document how the components are to be used. 
    - API documents form the bulk of this category. Writing documentation of this kind is easier because a component with a well-defined API exposes functionality in small-sized, independent and easy-to-use chunks. 
    - Tutorial-style instructional documentation: In addition to explaining functions/methods independently, some higher-level explanations of how to use an API can be useful <tip-box>Examples of such documentation can be found in the [Java API](http://download.oracle.com/javase/8/docs/api/).</tip-box>

```
To get:
![image](https://user-images.githubusercontent.com/22221132/37239152-0b470f24-2471-11e8-9c60-5799ef92ab58.png)

NOTE: tip-box is part of the 2nd list item to get that indentation.

Would it better to have it as a another list item? eg:

![image](https://user-images.githubusercontent.com/22221132/37239167-5c8496f4-2471-11e8-9894-cbbe66a4bcc7.png)

**Comment by damithc** [comment]
So, the whole tipbox/panel needs to be single-lined?
Isn't it a bit too restrictive? e.g., A tipbox content might have markdown content that require line breaks e.g., another list.

**Comment by nicholaschuayunzhi** [comment]
Lists are supported in these tipboxes.

```md
1. **Documentation for _developer-as-user_**: Software components are written by developers and used by other developers. Therefore, there is a need to document how the components are to be used. 
    - API documents form the bulk of this category. Writing documentation of this kind is easier because a component with a well-defined API exposes functionality in small-sized, independent and easy-to-use chunks. 
    - Tutorial-style instructional documentation: In addition to explaining functions/methods independently, some higher-level explanations of how to use an API can be useful 
    <tip-box>   
        - Examples of such documentation can be 
        - found in the [Java API](http://download.oracle.com/javase/8/docs/api/).
            - additional list item
    </tip-box>
```
Generates: 

![image](https://user-images.githubusercontent.com/22221132/37239517-6c7bf7d0-2478-11e8-9b2a-be40b69954af.png)

However new lines in indented tipboxes go haywire.  Will look into that.

```md
1. **Documentation for _developer-as-user_**: Software components are written by developers and used by other developers. Therefore, there is a need to document how the components are to be used. 
    - API documents form the bulk of this category. Writing documentation of this kind is easier because a component with a well-defined API exposes functionality in small-sized, independent and easy-to-use chunks. 
    - Tutorial-style instructional documentation: In addition to explaining functions/methods independently, some higher-level explanations of how to use an API can be useful 
    <tip-box>   
        Some comments
    
        Comment in a new line
    </tip-box>
```

Generates:
![image](https://user-images.githubusercontent.com/22221132/37239542-cbd6ed16-2478-11e8-8c84-978b27a5fc96.png)

**Comment by damithc** [comment]
Also note that content inside a tip-box cannot be indented to the level of the list item because all the time because markdown interprets indentation as having different meanings. For example, tables cannot be indented at all. If the tip box has a table, the code for the table needs to start at the start of the line.
```
* item
  * item
    <tip-box>
col1| col2
--- | ---
a | 1
b | 2
   </tip-box>
```

**Comment by nicholaschuayunzhi** [comment]
I'm able to get a table in the tip box though 🤔

```md
* item
  * item
  <tip-box>
    col1| col2
    --- | ---
    a | 1
    b | 2
  </tip-box>
```

![image](https://user-images.githubusercontent.com/22221132/37240126-24298a1a-2482-11e8-8e03-25c26320073a.png)

**Comment by damithc** [comment]
yup, looks like most things work, as long as there are no blank lines or html code inside the tip-box.

**Comment by Chng-Zhi-Xuan** [comment]
@damithc , can the issue be closed? Seems like it is resolved.

**Comment by damithc** [comment]
> Or is there a related enhancement you would like?

At the moment I have to resort to writing my own css classes to indent when other techniques don't work. Can we provide some in-built classes instead? e.g.,
```html
<div class="indent-level2">
...
</div>
```

**Comment by Chng-Zhi-Xuan** [comment]
Issue superseded by #878
