### ISSUE TITLE
<site-nav> doesn't support includes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1582]
v3.0.1

While it is possible to use an `<include>` inside a `<site-nav>`, the output doesn't seem to be as expected.

```html
<site-nav>
<include src="../navigation/adminSiteNav.md" />
</site-nav>
```
Expected (if the content were inserted directly):
![image](https://user-images.githubusercontent.com/1673303/121816650-67568a80-ccaf-11eb-8df3-911b8fc00fc8.png)

Actual:
![image](https://user-images.githubusercontent.com/1673303/121816664-7c331e00-ccaf-11eb-82be-b16d5dffc5d4.png)

May be related: The `<site-nav>` tag seems highly sensitive to leading blank lines. For example, if there are 2 leading blank lines (example below), the output is not as expected:

```html
<site-nav>


* **Authoring Contents** :expanded:
  * [Overview]({{baseUrl}}/userGuide/authoringContents.html)
  * [Adding Pages]({{baseUrl}}/userGuide/addingPages.html)
</site-nav>
```
Actual:
![image](https://user-images.githubusercontent.com/1673303/121816715-c5836d80-ccaf-11eb-9752-59b50b8878d7.png)

**Comment by damithc** [comment]
> May be related: The `<site-nav>` tag seems highly sensitive to leading blank lines.

Same applies to blank lines inside the bullet list.
```html
<site-nav>
* **Authoring Contents** :expanded:
  * [Overview]({{baseUrl}}/userGuide/authoringContents.html)
  * [Adding Pages]({{baseUrl}}/userGuide/addingPages.html)
 
* **Another heading**
  * [Overview]({{baseUrl}}/userGuide/authoringContents.html)
  * [Adding Pages]({{baseUrl}}/userGuide/addingPages.html)
</site-nav>
```

While not a big problem, it's nice if the feature can be insensitive to such blank lines. For one thing, nunjucks can insert extra blank lines e.g., if a `for` loop is used to generate the items in the list.

**Comment by ang-zeyu** [comment]
This is expected behaviour,

As `<include />` is WYSIWYG, when you write this,
```
<site-nav>
<include src="../navigation/adminSiteNav.md" />
</site-nav>

//adminSiteNav.md
- link 1
- link 2
- link 3
```

what you're actually writing is something along these lines:
```
<site-nav>
<div>
  <ul>
    <li>link 1</li>
    <li>link 2</li>
    <li>link 3</li>
  </ul>
</div>
</site-nav>
```

You can
- use nunjucks `{% include %}` (which is processed before everything else) to include the markdown as is, or
- move the `<site-nav>` itself down to adminSiteNav.md

We really do need better documentation for how MarkBind's `<include />` functions in general and differs from nunjucks' though.

**Comment by damithc** [comment]
> * move the `<site-nav>` itself down to adminSiteNav.md

Yup, this works. Thanks for the clarification @ang-zeyu 

We can document this difference between `<include>` and `{% include %}` somewhere in https://markbind.org/userGuide/reusingContents.html#includes
