### ISSUE TITLE
se-book migration to V3: error while generating site

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1586]
Guys, I need help with troubleshooting this problem. I did the layout migration but can't figure out another error that popped up. I can't figure out where the error is coming from.

Steps:
1. Clone https://github.com/damithc/se-book
2. Run `markbind serve`

Problem: A bunch of 'no such file' errors appear and the site cannot be served.
![image](https://user-images.githubusercontent.com/1673303/121857382-25b5f600-cd28-11eb-8d8f-331918a60a12.png)

**Comment by ang-zeyu** [comment]
Fixed, and tests added.
