### ISSUE TITLE
se-book: panels/modals don't work in some pages

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1588]
Code: https://github.com/damithc/se-book

Dynamic elements such as panels, modals, tooltips don't seem to work in some page. Here is an example:

![image](https://user-images.githubusercontent.com/1673303/122236529-2d74c680-cef1-11eb-8ad1-0ecaa02a9ffa.png)

Can't figure out the reason. They seem to work in other pages e.g., if I add a panel in the root page index.md, it seems to work.

**Comment by ang-zeyu** [comment]
![Untitled](https://user-images.githubusercontent.com/3306138/122241591-41bac280-cef5-11eb-9db6-24bd24b4dd74.png)

@wxwxwxwx9 could you check this out? (removing popovers does the trick)
again, likely something site specific as it it seems to be working in markbind.org

**Comment by wxwxwxwx9** [comment]
@ang-zeyu sorry for the late reply! Missed this during the weekday, will look into this!

**Comment by wxwxwxwx9** [comment]
![Screen Shot 2021-06-19 at 5 47 43 PM](https://user-images.githubusercontent.com/37920115/122638404-7cf00800-d126-11eb-99af-b344696ab6d2.png)

@ang-zeyu It's a careless mistake from my side -- missed out adding the methods to the Vue initialization for sites which are not setup with search. Will make a PR to fix it!

@damithc thanks for raising this up!
