### ISSUE TITLE
boilerplates: allow multiple boilerplates with similar names

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#159]
Building on the current boilerplates mechanism, we can support a syntax like this:

`<include src="*/foo/bar.md" />`

`*` indicates that it is a boilerplate. The benefit of this is the reader of the code can immediately identify this as a reference to a boilerplate file rather than a normal file.

This also allows us to support multiple boilerplates with the same name. e.g., `*/full/index.md` vs `*/print/index.md`.

**Comment by rachx** [comment]
How will you specify for/distinguish the above case with
```html
<panel type="info" header="`W8.3c` Can identify client-server architectural style :star::star::star:" expanded no-close>
  <include src="../../book/architecture/architecturalStyles/clientServer/what/full.md" />
<!-- TODO: add evidence -->
</panel>
```

where `full.md` is a boilerplate file and you want the location sensitive reference to be `"../../book/architecture/architecturalStyles/clientServer/what/full.md"`

**Comment by damithc** [comment]
This is what I was thinking:
```html
<panel type="info" header="`W8.3c` some text" expanded no-close>
  <include src="../../book/architecture/architecturalStyles/clientServer/what/*/full.md" />
</panel>
```
In this case it will take `_boilerplates/full.md` file and act as if `full.md` was in the `....clientServer/what/` folder. i.e., same as current behavior but `*` makes it clear that we are referring to a boilerplate file.

```html
<panel type="info" header="`W8.3c` some text" expanded no-close>
  <include src="../../book/architecture/architecturalStyles/clientServer/what/*/print/full.md" />
</panel>
```
In this case it will take the `_boilerplates/print/full.md` file and act as if `full.md` was in the `....clientServer/what/` folder.

That is, folder structure inside the `_boilerplates` folder is just a way to distinguish between different boilerplates with the same file name. We could have used different files names instead too (e.g., `_boilerplates/full.md` and `_boilerplates/print_full.md` but that technique doesn't work for `index.md` which needs to be named `index`.

What do you think? Too much work for too little gain? We can also support `*` to indicate boilerplate files just to improve readability but not support sub folders inside it. In that case index.md files cannot benefit from boilerplate mechanism fully.

**Comment by rachx** [comment]
I was trying to implement it.

While testing, I notice that it is hard to replace all the references in the 2103 website. Although we report missing references for static include, it doesn't report for dynamic include and it took me a while to find it. 
Also since this is a md file, everything after * might be italicized in some editors (Atom).

How about
```html
<panel type="info" header="`W8.3c` some text" expanded no-close>
  <include src="book/architecture/architecturalStyles/clientServer/what/full.md" boilerplate-src="folder/full.md" />
</panel>
```
(or a shorter/better name for boilerplate-src)

It can support the folder structure, clearly distinguish between both types of files and I think it might be easier to implement.

**Comment by damithc** [comment]
If we go this route, there is no need to support sub-folders. How about this?

```html
<panel type="info" header="`W8.3c` some text" expanded no-close>
  <include src="book/architecture/architecturalStyles/clientServer/what/index.md" boilerplate="print-index.md" />
</panel>
```
This will take `_boilerplates/print-index.md` and use it as `.../what/index.md`

Optionally, we can support this:
```html
<panel type="info" header="`W8.3c` some text" expanded no-close>
  <include src="book/architecture/architecturalStyles/clientServer/what/index.md" boilerplate />
</panel>
```
`boilerplate` indicates we are using a boilerplate file here. It will improve clarity of the code.
