### ISSUE TITLE
se-book: Some MarkBind syntax not rendered correctly

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1591]
Code: https://github.com/damithc/se-book

![image](https://user-images.githubusercontent.com/1673303/122426720-0e466980-cfc3-11eb-8331-5086d5d46c0e.png)

**Comment by wxwxwxwx9** [comment]
Hi Prof! I've investigated the issue and here are some fixes/suggestions/clarifications (all under the `variables.md` file):

1) For the "click" issue, I'm still looking into what causes this behavior. The problem should be something to do with the icon that was used for that line (tried using some other icons and some "fixed" the problem). Give me some time to look into this behavior more :-)

2) For the ":glyphicon-ok-sign:", can you try wrapping it with `<md>` tag? 

<img width="595" alt="Screen Shot 2021-06-19 at 7 30 38 PM" src="https://user-images.githubusercontent.com/37920115/122640955-d4957000-d134-11eb-8290-1cfe6864d445.png">

3) Also, another issue I realised is that there's a typo for `<smal>`. I think you wanted to use `<small>` instead right? Unrecognized tags would cause problems with SSR (and cause page to load slower as it would have to abort SSR and execute full CSR). 

<img width="663" alt="Screen Shot 2021-06-19 at 7 31 25 PM" src="https://user-images.githubusercontent.com/37920115/122640975-f131a800-d134-11eb-933d-d927b2b04774.png">

**Comment by ang-zeyu** [comment]
@wxwxwxwx9 1 & 2 are due to the new inline tags whitelist in the markdown rule, should be fixed by adding just `<md>` in (as it also precedes the ctrl+click example inside the variable)

**Comment by damithc** [comment]
Wrapping with `<md>` tags solved the problem here:
![image](https://user-images.githubusercontent.com/1673303/122646308-1c29f500-d151-11eb-9f17-1b4f0301bff2.png)


But I can't explain why an `<md>` tag is needed here:
![image](https://user-images.githubusercontent.com/1673303/122646214-9d34bc80-d150-11eb-901c-161f3b98d475.png)
`{{ icon_new_window }}` has the value `<span id="icon_new_window"><md>:glyphicon-new-window:</md></span>`

**Comment by ang-zeyu** [comment]
@wxwxwxwx9 @damithc 
> should be fixed by adding just <md> in (as it also precedes the ctrl+click example inside the variable)

sorry, meant adding it in here https://github.com/MarkBind/markbind/blob/master/packages/core/src/lib/markdown-it/patches/custom-component/inlineTags.js

The reason is that markdown-it treats all unrecognised tags (`<md>` for example) as "block" tags by default. The patch from vuepress in #1548 reverses that.

**Comment by damithc** [comment]
> sorry, meant adding it in here https://github.com/MarkBind/markbind/blob/master/packages/core/src/lib/markdown-it/patches/custom-component/inlineTags.js

@wxwxwxwx9 Will you be sending a PR for this issue?

**Comment by wxwxwxwx9** [comment]
> > sorry, meant adding it in here https://github.com/MarkBind/markbind/blob/master/packages/core/src/lib/markdown-it/patches/custom-component/inlineTags.js
> 
> 
> 
> @wxwxwxwx9 Will you be sending a PR for this issue?

Yup! Will send a PR for this :-)
