### ISSUE TITLE
Typo in using components page of user guide

### ISSUE THREAD

**Issue by samuelfangjw** [MarkBind/markbind#1597]
Hi, I found a small typo in the using components page of the user guide at https://markbind.org/userGuide/usingComponents.html.

<img width="556" alt="Screenshot 2021-06-26 at 12 43 06 AM" src="https://user-images.githubusercontent.com/60355570/123458328-82ae8780-d617-11eb-81da-b88f90fc6c52.png">

I believe "PlanUML" should be "PlantUML" instead.

**Comment by ryoarmanda** [comment]
Thank you for the heads up, @samuelfangjw! Should be fairly simple to fix, if anyone wants to take this on 😃

**Comment by samuelfangjw** [comment]
I would like to take this on if possible!
