### ISSUE TITLE
Documentation bug: outdated directories

### ISSUE THREAD

**Issue by ming-00** [MarkBind/markbind#1599]
I believe that some of the the directories specified in the [Project Structure](https://markbind.org/devdocs/devGuide/design/projectStructure.html) section of the developer's guide might be outdated: 
<br>
<img width="788" alt="Screenshot 2021-06-27 at 12 22 32 AM" src="https://user-images.githubusercontent.com/59130765/123519418-c5d32e00-d6dd-11eb-9a53-8f677ecc79b6.png"> 
The CLI application should reside in the `packages/cli/` directory.

<br>
<img width="803" alt="Screenshot 2021-06-27 at 12 23 54 AM" src="https://user-images.githubusercontent.com/59130765/123519470-f74bf980-d6dd-11eb-9ff9-a1128ba87194.png">
There is no src/Parser directory in the core library.

**Comment by ang-zeyu** [comment]
Thanks for the catch @ming-00. This portion should be rewritten into an introduction of sorts with the more detailed architecture diagram now available.
