### ISSUE TITLE
Nested <md> tags interfere with rendering

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1604]
v3.0.3

```html
<panel type="seamless">
<span slot="header"><md>%%{{ icon_video }}: How do focus groups work?%%</md></span>
...
</panel>
```
output:
![image](https://user-images.githubusercontent.com/1673303/123580554-ae469300-d80c-11eb-8201-c963cb3b6dc3.png)

The problem is the `icon_video` already has an `<md>` tag in it.
```html
<variable name="icon_video"><md>:glyphicon-facetime-video:</md></variable>
```

Not sure if we can even get this 'nested `<md>` tags' to work but posting here in case there is a solution. If not, I can tweak the code to avoid the nesting, although not as convenient as the current code. Still, not a big issue.

**Comment by ang-zeyu** [comment]
This is a little difficult.

I added `<md>` to the list of "special tags" (recall `<puml>`) for v3, allowing it to contain this:

```
i.e. this shouldn't pose a problem to the htmlparser even without patching it now
I have <md>`invalid <html> within html!`</md>`
```

the consequence is that this makes nested `md` tags impossible 
```
<md>%%The first md tag<md>terminates at the first closing md tag by definition</md>, so the `%%` pattern is broken into two %%</md>
```

the (user) solution would be to 
1. know your markdown rules
2. avoid using `<md>` in variables.md 

less convenient at first glance but equally usable with enough markdown knowledge.

you can still do this, for example

```
// variables.md
<variable name="foo">:glyphicon-facetime-video:</variable>

// something.md

<panel type="seamless">
<span slot="header"><md>%%{{ icon_video }}: How do focus groups work?%%</md></span>
...
</panel>

a markdown paragraph which renders inline "tokens" like {{ icon_video }} without needing <md> already anyway

> same thing {{ icon_video}} here with blockquotes

etcetc.
```

**Comment by ang-zeyu** [comment]
I think this is subjective ultimately but my personal opinion here is that we should stick with the new behaviour as
1. it encourages knowing the markdown spec and not spewing `<md>` everywhere as a hotfix to things
   - this should only be used where it is *deeply inconvenient* to adjust the content to meet the commonmark + gfmd spec
2. its more inline with the nunjucks -> markdown -> html processing flow (`<md/markdown>` is processed recursively)

**Comment by ang-zeyu** [comment]
3. just a conjecture but there should be overhead that matters when doing many separate `<md>` calls versus just one ("economies of scale")

**Comment by damithc** [comment]
Got it. Yes let's leave things be for this case.
