### ISSUE TITLE
Replace deprecated highlight.js syntax

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1606]
v3.0.3

Saw this message in the MarkBind console:
>Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277

**Comment by ryoarmanda** [comment]
Thanks for the heads up prof, this was already raised in #1549. The deprecated method can still work but it would be best if we can adopt the new one sooner.

**Comment by damithc** [comment]
Oops. Thanks for checking @ryoarmanda
