### ISSUE TITLE
Page-nav items behaving oddly if inline includes are combined with  spans

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1607]
v3.0.3

Expected: page-nav should detect the current topic in view e.g., (from V2)
![image](https://user-images.githubusercontent.com/1673303/123611757-82d79e80-d834-11eb-8777-8b864bf21310.png)

Actual:
![image](https://user-images.githubusercontent.com/1673303/123611844-97b43200-d834-11eb-9067-3ea9ff45e5a0.png)

Example:
https://se-education.org/se-book/designFundamentals/index.html

**Comment by ang-zeyu** [comment]
👀 

to add, it seems page specific:
e.g. not ok here https://se-education.org/se-book/designFundamentals/index.html
but ok here https://se-education.org/se-book/about/usage.html (I think our docs as well)

**Comment by damithc** [comment]
> to add, it seems page specific:

Yes, I noticed that too, later. Probably something to do with the headings being inside panel components in those pages.
![image](https://user-images.githubusercontent.com/1673303/123669955-407f8300-d86f-11eb-8254-5afe6a5cb2c8.png)

There's a chance that this was like that in V2 too.

**Comment by damithc** [comment]
An update:

The relevant source code is in https://raw.githubusercontent.com/se-edu/se-book/master/_markbind/boilerplates/container-inParent-asPanel.md

```html
<panel type="seamless" expanded>
  <span slot="header" class="card-title"><markdown>## <include src="text.md#title" inline /></markdown></span>
  <include src="text.md#body" />
</panel>
```

Strangely, if I add some chars between `##` and `<include ...`, it starts working again.
```html
<panel type="seamless" expanded>
  <span slot="header" class="card-title"><markdown>## topic: <include src="text.md#title" inline /></markdown></span>
  <include src="text.md#body" />
</panel>
```
![image](https://user-images.githubusercontent.com/1673303/123751392-48c8d400-d8ea-11eb-8014-8fd34b9d4318.png)

**Comment by damithc** [comment]
This problem cropped up in another place, albeit in a slightly different form:

See https://nus-cs2103-ay2122s1.github.io/website/schedule/week3/project.html

Note how the pageNav items appear out of order.
![image](https://user-images.githubusercontent.com/1673303/125795050-f2bfe3c1-58d0-4f99-bd62-79cbfaf07d85.png)

I managed to narrow down the problem to the following sample code.

```html
<frontmatter>
pageNav: 4
pageNavTitle: "Sample page"
</frontmatter>

# Shows

## <span class="text-danger">1</span> Rick and Morty

## <span class="text-danger">2</span> <include src="topic2.md#name" inline trim/>

## <span class="text-danger">x</span> <include src="topic2.md#name" inline trim/>

## y <span class="text-danger">4</span> <include src="topic2.md#name" inline trim/>

```
Note how one pageNav item appears out of order.

![image](https://user-images.githubusercontent.com/1673303/125796181-66b0f69d-9d74-4b5b-933c-b78d05833782.png)

What I observed:
* It happens when a heading has an inline include, combined with a `<span>`, and doesn't contain anything else. Note how adding a simple `x` in front prevents the problem. However, putting a symbol instead e.g., `.` doesn't work.
* Furthermore, it happens only if the span content is a number i.e., `x` will not cause the problem but `2` will.

**Comment by damithc** [comment]
Raising severity as the new symptom is more noticeable to the reader.

**Comment by damithc** [comment]
Given the strange behavior involving numbers/symbols, I wonder if a regular expression is behind it all 🤔

**Comment by damithc** [comment]
Let's try to fix this before the semester starts. In the worst case, I can use the hack of adding some text in front, but not ideal.

**Comment by ang-zeyu** [comment]
Thanks for the examples, I published a fix for the first part of the issue (pagenav not working without some "pretext"). It might fix the second part as well @damithc

**Comment by damithc** [comment]
Thanks for the fix @ang-zeyu 
The _second_ (and more severe) problem seems to be fixed now. Great!
![image](https://user-images.githubusercontent.com/1673303/126060260-68748b8d-50a8-4323-a1ba-3e8c4591c5fc.png)


The first problem seems to remain though.
![image](https://user-images.githubusercontent.com/1673303/126060223-0aa75b3e-0e3e-48e6-bbe2-b52a3c3962f7.png)

**Comment by ang-zeyu** [comment]
🎉
