### ISSUE TITLE
[V3] including a span by id results in empty contents in some cases

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1608]
Consider this `foo.mbdf`:
```html
<span id="bar1">text1</span>
<span id="bar2">

text2
</span>
```

Suppose `<include src="foo.mbdf#bar2" />` appears in another file.
Expected: `text2`
Actual: (nothing to see, and no errors)

However, it works as expected if I use a `div` instead of a `span`
```html
<span id="bar1">text1</span>
<div id="bar2">

text2
</div>
```
or remove the leading blank line inside the `span`
```html
<span id="bar1">text1</span>
<span id="bar2">
text2
</span>
```
or add a blank line between the spans
```html
<span id="bar1">text1</span>

<span id="bar2">

text2
</span>
```
🤔  This wasn't the case in V2 though.

**Comment by ang-zeyu** [comment]
v3 is a lot more spec compliant in general.

```
// writing this
<span id="bar1">text1</span>
<span id="bar2">

text2
</span>

// actually gives this (try it with the github markdown renderer)
<p>
<span id="user-content-bar1">text1</span><br>
<span id="user-content-bar2"></span>
</p>

<p>
text2<br>
</p>
```

**Comment by damithc** [comment]
I see. I guess better to use `div` then. Thanks for checking @ang-zeyu
