### ISSUE TITLE
<span> not allowed in site-nav

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1611]
Previously, I was able to do this kind of styling e.g., use badges/colors in the site-nav using `<span>` elements. 

![image](https://user-images.githubusercontent.com/1673303/123655013-32c30100-d861-11eb-8215-83e0d4c0901b.png)

Is it not allowed anymore? The `<span>` tags in site-nav items seem to be ignored now.

Not a deal-breaker but just checking if it is allowed.

**Comment by ang-zeyu** [comment]
should still be allowed, will need the source

**Comment by damithc** [comment]
Example:

`* [text1 <span class="text-danger">text2</span>]()`

![image](https://user-images.githubusercontent.com/1673303/123665857-3f4c5700-d86b-11eb-8666-4b08be54511d.png)

**Comment by damithc** [comment]
It's working now. Thanks for the fix @ang-zeyu
