### ISSUE TITLE
Page nav title: add padding before the title

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1614]
Add a bit of padding here by default?
![image](https://user-images.githubusercontent.com/1673303/123732235-2aec7680-d8cc-11eb-8624-908e5ea84b3e.png)

**Comment by kimberlyohq** [comment]
Hi prof, I would like to take on this if possible😊

**Comment by damithc** [comment]
@kimberlyohq let's leave this for a first-timer. @MarkBind/active-devs I assumed this is easy enough for a first-timer. Please remove the label if that's not the case.
