### ISSUE TITLE
PlantUML diagram in modal missing when lazy-load live-previewing

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1618]
When running the command `markbind serve -o`:

![image](https://user-images.githubusercontent.com/1673303/123759125-318de480-d8f2-11eb-9bf4-de5b366e68fc.png)

Code of the modal:
```html
<modal large header="Grade breakdown" id="modal:expectations-gradeBreakdown">
  <pic src="gradeBreakdown.png" no-validation />
</modal>
```

However, `gradeBreakdown.png` is to be built from PUML code in another page (let's call that the _parent page_ and the one containing the modal the _modal page_).
```html
<puml name="gradeBreakdown.png">
@startwbs
...
@endwbs
</puml>
```

I assume the image was never built because the parent page hasn't been visited yet? Sure enough, after visiting the parent page once, the image appears in the modal when visiting the modal page again.

I'm not sure if this kind of complicated dependency relationship can be catered in the lazy loading though.

**Comment by ang-zeyu** [comment]
> I'm not sure if this kind of complicated dependency relationship can be catered in the lazy loading though.

It's indeed not possible. The image in the first file is being treated as an asset. Without building the second page there's no way to know what `gradeBreakdown.png` is supposed to be.

But as always you could extract the source material down into a common file then `<include />` it, or just use `.puml` files. I would suppose the use case for inline puml's is more of a "one-time" thing.

**Comment by damithc** [comment]
Got it. I think we can live with the current status quo.
