### ISSUE TITLE
Improve resilience of live reloading to temp IDE files

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#163]
A console message noticed during live reloading (when using Intellij). May be useful for improving live reloading.

>info: Reload for file deletion: C:\repos\nus-te3201\website\programming\files-paths\text.md___jb_tmp___
error: EPERM: operation not permitted, unlink 'C:\repos\nus-te3201\website\_site\programming\files-paths\text.md___jb_tmp___'

This message did not crash the build though.

At another time the build crashed when it tried to access a file `{some path}/.temp/{some path}`
>error: EPERM: operation not permitted, open 'C:\repos\nus-te3201\website\programming\.temp\toc\expressions-types-variables.md'

**Comment by damithc** [comment]
More errors messages shown during live reloading (these are nothing new; just see if they can be reduced).
>Error: EPERM: operation not permitted, stat 'C:\repos\nus-te3201\website\programming\_site\toc\files.html'
error: EPERM: operation not permitted, open 'C:\repos\nus-te3201\website\programming\.temp\toc\strings.md'
EPERM: operation not permitted, unlink 'C:\repos\nus-te3201\website\programming\_site\files-reading\text.md___jb_tmp___

**Comment by damithc** [comment]
In addition to ignoring certain file changes, another strategy we can try is to abandon the current build gracefully (instead of crashing) and retry one more time. Some of the temporary problems with files might no longer exist during the second try.

**Comment by damithc** [comment]
Observation: Copy-pasting a file inside Intellij usually result in a build crash.

**Comment by rachx** [comment]
I ignored some of the IDE files in https://github.com/MarkBind/markbind-cli/pull/31.

**Comment by damithc** [comment]
Haven't noticed this recently. Closing.
