### ISSUE TITLE
Update octicon version

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1639]
Some of these octicons don't seem to be available (or looks different) e.g., https://primer.style/octicons/file-diff-16

Perhaps we need to update our octicon version?

**Comment by wxwxwxwx9** [comment]
Our version is indeed rather outdated 😓

**Comment by ong6** [comment]
Hi after doing some light testing, it seems the fix for this is simply running `lerna add @primer/octicons packages/core` not sure if this is worth a individual PR? Should I add it to my PR at #1647 ?

**Comment by wxwxwxwx9** [comment]
@ong6 Hi there! Thanks for taking a look at this. 

I think it will be better if we create a new PR for this :-)

It will be more in line with the guideline set our here below. 

https://se-education.org/guides/guidelines/PRs.html

**Comment by ong6** [comment]
@wxwxwxwx9 Thanks for the clarification! Was not sure if a one line update warranted a PR XD
