### ISSUE TITLE
Deploy failing with cache error

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#164]
Deploy failing with this error:
>error: fatal: destination path '..\..\..\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\gh-pages\.cache\aHR0cHM6Ly9kYW1pdGhjQGdpdGh1Yi5jb20vbnVzLXRlMzIwMS93ZWJzaXRlLmdpdA' already exists and is not an empty directory.

It didn't fail for another repo when I tried y'day.  To reproduce, try these:
* deploy to multiple sites
* deploy a site that has sub-modules e.g., https://github.com/nus-te3201/website

**Comment by damithc** [comment]
I deployed the same website https://github.com/nus-te3201/website from home computer but cannot deploy now from office computer, so I suspect the error happens when I try to deploy multiple repos from the same computer. The site I deployed from home did not work however on gh-pages for some reason. It gave the error `Your site is having problems building: Worker killed while processing job`

**Comment by damithc** [comment]
I tried reverting back to 1.5.0 but I get this error when I try to build:
>C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\markbind\lib\parser.js:380
      const userDefinedVariables = config.userDefinedVariablesMap[fileBase];
                                                                 ^
>
>TypeError: Cannot read property 'C:\repos\nus-te3201\website' of undefined
    at fs.readFile (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\markbind\lib\parser.js:380:66)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by rachx** [comment]
The error seems related to my support user-defined variables PR.
The latest version of markbind needs the latest version of markbind-cli (1.6)

**Comment by damithc** [comment]
> The error seems related to my support user-defined variables PR.
> The latest version of markbind needs the latest version of markbind-cli (1.6)

Installing markbind is same as installing markbind-cli right? I usually run `npm i markbind-cli@1.x.x` to install. I ran `npm i markbind-cli@1.5.0` to rollback to the previous version. should I have done something else?

**Comment by rachx** [comment]
I think you will have to revert the markbind version too (to 1.2.1)


Actually, this might be because of how our `package.json` is defined
In markbind-cli `1.5.0`, we require `^1.2.1`.
After you installed `1.6.0`, markbind will be automatically updated to `1.3.0`.
This version is still acceptable in cli (`^1.2.1` means anything >= 1.2.1 but <2.0.0)
But markbind 1.3.0 is not compatible with cli `1.5.0`, hence the error.

Perhaps, we should specify a single version and not a range in `package.json`.

**Comment by acjh** [comment]
We can consider using a tilde (~): https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json

To install a specific version of dependency:

```shell
npm i -g markbind-cli@1.5.0 markbind@1.2.1
```

**Comment by Gisonrg** [comment]
I felt sooner or later we will need to resolve #139 to avoid version mismatch issue.

**Comment by nicholaschuayunzhi** [comment]
Closing this: considering that deployment has been resolved on slack and the discussion about versioning has been address in #170.
