### ISSUE TITLE
Line ending issues when developing in Windows environment

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1640]
**Tell us about your environment**
Windows 10 Home

**MarkBind Version:**
3.0.6

**What did you do? Please include the actual source code causing the issue.**
Hello,

I am trying to set up markbind locally following the contributing guide. As I am using a Windows machine and according to #777, line endings are set as "CRLF" when I cloned it locally. I am using VSCode btw.

**What did you expect to happen?**
After installing dependencies, I expect to run the test cases via `npm run test`. 

**What actually happened? Please include the actual, raw output.**
However, I am greeted with this lint [error](https://eslint.org/docs/rules/linebreak-style)  all over the place. 
>Expected linebreaks to be 'LF' but found 'CRLF'.eslintlinebreak-style

I assume this is not an uncommon issue but I could not find out what's the recommended practice in the repo's past issues (I found #777 and #1213 though). I suppose according to #777, all line endings will be checked in as LF, and it should be converted back to CRLF if a developer checkouts out to a Windows machine. This is because of `* text=auto`. If that is the case, how does one bypass the Eslint error locally in a Windows machine?

My temporary fix is to add `"linebreak-style": 0` within `.eslinrc.js`... I would love to hear from the devs if I missed out on something or am I doing something wrong here?

Thanks!

**Comment by jonahtanjz** [comment]
Hi, thanks for your interest in contributing to MarkBind @tlylt :) This issue can be resolved by running `npm run lintfix` before running the test scripts.

**Comment by tlylt** [comment]
Hi @jonahtanjz , 

`npm run lintfix` does seem to work. According to the [article](https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/) referred in #777 and [this](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings), I take it that it is recommended to have autocrlf set to true. In that case, I am wondering if we could perhaps ignore the Eslint linebreak-style to make it easier? Since `* text=auto` in `.gitattributes` will already ensure files will be checked in with LF. 

Anyway just a thought, I will go with the lint fix for now.

**Comment by jonahtanjz** [comment]
> In that case, I am wondering if we could perhaps ignore the Eslint linebreak-style to make it easier? Since * text=auto in .gitattributes will already ensure files will be checked in with LF.

Yup this sounds good. We can probably reopen and reuse this issue.

**Comment by tlylt** [comment]
Ok, I will reopen this to see if there are any interests/further inquiries/related discussions from others to proceed with the suggestion:)

**Comment by ang-zeyu** [comment]
Thanks for bringing this up, have been using vscode / webstorm's save on lint to deflect this for quite a while 😄 

Removing `linebreak-style` sounds good, maybe let's do that for the main `.eslint.rc` only though, then create a separate "`.eslint.test.rc`" for our test scripts so line endings are still checked there. We had a couple of misaligned line endings committed in the past even with the git settings. (likely from odd git clients / global overrides)

**Comment by tlylt** [comment]
> Thanks for bringing this up, have been using vscode / webstorm's save on lint to deflect this for quite a while 😄
> 
> Removing `linebreak-style` sounds good, maybe let's do that for the main `.eslint.rc` only though, then create a separate "`.eslint.test.rc`" for our test scripts so line endings are still checked there. We had a couple of misaligned line endings committed in the past even with the git settings. (likely from odd git clients / global overrides)

Hi @ang-zeyu , sure I think it's indeed a good fail-safe to keep the test scripts checking on. 
May I work on this?

**Comment by ang-zeyu** [comment]
sure, thanks! @tlylt
