### ISSUE TITLE
Upgrade `commander` version to improve code quality

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1648]
**Is your request related to a problem?**

Main trigger for raising this issue is the following comment found in `package/cli/index.js`:
```js
// We want to customize the help message to print MarkBind's header,
// but commander.js does not provide an API directly for doing so.
// Hence we override commander's outputHelp() completely.
program.defaultOutputHelp = program.outputHelp;
program.outputHelp = function (cb) {
  printHeader();
  this.defaultOutputHelp(cb);
};
```

After some exploration of the existing commander.js [documentation](https://www.npmjs.com/package/commander#automated-help), new functionalities have been added in recent versions (v7 or up) that allowed for things like customizing help messages, such as via `.addHelpText()` function. 

**Describe the solution you'd like**

Perhaps upgrade commandjs from the current "^3.0.2" to latest version available.
In addition, I think some refactoring work might be good to improve code quality for cli code. Some issues that be can addressed:
- configure help message with `.addHelpText()` or `.configureOutput()`
- print Markbind header via pre-action hooks instead of duplicating it in every command
- reduce long methods in "serve" command
- other misc refactorings

**Describe alternatives you've considered**

Pros:
- make use of the newly added features in commander.js instead of hacky fixes
- could take this opportunity to refactor the code for better readability

Cons:
- v3 to v8, might need to handle breaking changes with care

**Additional context**

I would like to work on this if @MarkBind/active-devs are agreeable to proceed (Or if you have other comments, please do let me know)

@wxwxwxwx9 Sorry for tagging, but errr nope I am not able to ping anyone with `@MarkBind/active-devs`, as seen above that it is greyed out 😂

**Comment by wxwxwxwx9** [comment]
> @wxwxwxwx9 Sorry for tagging, but errr nope I am not able to ping anyone with @MarkBind/active-devs, as seen above that it is greyed out 😂

@tlylt Ahh I see, no worries!

Yup, this seems like the right direction to go towards. You can proceed with this issue :-)
