### ISSUE TITLE
Use of optional chaining operator

### ISSUE THREAD

**Issue by riyadh-h** [MarkBind/markbind#1664]
Hello there!

While writing some code for a plugin, I used JavaScript's optional chaining operator (`?.`) in a function like so:

![Function's code](https://user-images.githubusercontent.com/69278589/132133355-22c90844-9e44-499d-a6d7-a9034cc13a21.png)

However, when I ran `npm run test`, `eslint` flagged the `.` of the operator as an "unexpected token":

![Error message](https://user-images.githubusercontent.com/69278589/132133331-1ee2c64b-a4d6-4a71-81cc-f4fbdce0b0be.png)

Thus, I'm wondering if it's okay to use optional chaining in our code.
I tried searching for a rule regarding the use of such an operator in [Airbnb's style guide](https://github.com/airbnb/javascript/blob/master/README.md) (the guide we're using), but I couldn't find anything.

**Comment by tlylt** [comment]
Hi @riyadh-h,

I did some preliminary checking and indeed optional chaining is flagged by Eslint.
Some further searching got me to [here](https://newbedev.com/eslint-optional-chaining-error-with-vscode), which points the culprit to our outdated Eslint version. When version 7.5 and above is installed, the above issue no longer appears. 

But the following issue caused by the Eslint update will show up:
>Unable to resolve path to module 'chokidar'.eslintimport/no-unresolved

So when updating Eslint, some more work might need to be done to tweak the settings to ensure other code are not wrongly flagged as erroneous.

That's all I have investigated.

**Comment by riyadh-h** [comment]
Ah, so it is an ESLint issue.
I guess I'll try to update ESLint and fix any issues along the way then, so that the code (and future code, hopefully) can pass all the tests. 👍

Thank you so much for the help, @tlylt! 😄

**Comment by ang-zeyu** [comment]
@riyadh-h the project is following the release version / timelines [here](https://markbind.org/userGuide/gettingStarted.html#getting-started) [and here](https://nodejs.org/en/about/releases/), unfortunately `?.` hasn't reached the oldest version yet =X.

side note: you can also refer to the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) at the bottom of most mdn doc pages to check for specific version compatibilities.

**Comment by riyadh-h** [comment]
Oh, I see. Thanks for the clarification, @ang-zeyu! 👍 
And sorry for overlooking these requirements.

> unfortunately ?. hasn't reached the oldest version yet =X.

So, would it be fine to update ESLint (see PR #1665) but not use optional chaining in our code until that happens, or is it better to postpone updating ESLint in order to avoid `?.` slipping into MarkBind's code?

**Comment by ang-zeyu** [comment]
Np, sorry for the late input as well. :frowning_face: 

> or is it better to postpone updating ESLint in order to avoid ?. slipping into MarkBind's code?

As you've reasoned, let's postpone updating the configuration. I would guess by the time `.?` becomes a "not new-and-shiny feature" eslint itself would update its defaults to allow `?.` operators too.

**Comment by riyadh-h** [comment]
No worries 👍
Okay, I'll close the PR for now; we can reopen it later if necessary.
Thanks for the feedback, @ang-zeyu! 😄
