### ISSUE TITLE
deploy command declares success prematurely

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1667]
It seems `markbind deploy` command shows the `Deployed at ...` message before the actual deployment is completed?
The reason for my suspicion is that the console stays busy for a quite while after that message is displayed.

![image](https://user-images.githubusercontent.com/1673303/132977756-5435969e-c3fa-49b7-b1f1-40a4ada7b8f3.png)

**Comment by ong6** [comment]
I've experienced this issue as well. Might be something to do with the async functions in index.js of cli. I will spend some time trying to fix this issue and report back.

**Comment by ong6** [comment]
@damithc Hi, please help me close this issue as I forgot to tag this issue as 'To close' in my PR. Sorry for the inconvenience!
