### ISSUE TITLE
Load non critical resources last

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1670]
![Untitled2](https://user-images.githubusercontent.com/3306138/133895240-4823363b-d968-4495-891f-96a7466201ef.png)

A lot of these probably don't need to be loaded up front, it results in the "blank white screen" issue at times.

the page render function was introduced [here](https://github.com/MarkBind/markbind/pull/1512/files), and should be nicely "moveable" down below, as is `vue` and `markbind.min.js`.

Not too sure if jquery performs any relevant side effects at this point of loading in the html though.

**Related**

Goes hand in hand with #1560 to hopefully, completely remove fouc

**Comment by riyadh-h** [comment]
Hi there!

>
> it results in the "blank white screen" issue at times

Can I get some steps on how to reproduce this issue, please?

**Comment by ang-zeyu** [comment]
@riyadh-h anything to slow your network speed (+ disable cache) would do.

the chrome inspector has a convenient option:
![inspector](https://user-images.githubusercontent.com/3306138/140296430-d57eb331-8125-47ee-b23d-324d33e5e10d.png)

**Comment by ang-zeyu** [comment]
Another more intrusive (but performant) implementation we can also explore is using the [defer](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) (and maybe async) attribute for script tags.

The execution order is a little more difficult to reason with (we'll likely have to look into adding `defer` into all of our scripts (plugin / external / layout scripts)).

We can of course go with the simpler option of just moving the tags around first and see if its good enough though.

**Comment by riyadh-h** [comment]
Thanks for the instructions!
It seems that this issue stays on for a while before a page loads with these settings.

I timed the loading process of new projects' default landing page three times before and after moving the `script` tags to the bottom:
* When the scripts were at the top, the page took 16.32s on average to display the page's contents (27.80s on average to fully load).
* When the scripts were at the bottom, the page took 11.87s on average to display the page's contents (24.49 to fully load).
    * **Side note**: when the contents were displayed, FOUC happened instantly when the scripts were at the top, but it took some time after the contents were displayed when the scripts were at the bottom.
        * The time was measured with no regards to FOUC though.

However, I'm not sure if this difference is considered significant or not. (maybe we can try this on the CS2103 website?)

**Comment by riyadh-h** [comment]
>
> Apologies for the wording here, realised I used "FOUC" as a misnomer. (was referring to unstyled content as the blank white screen / "loading times" more generally)

Ah, I see. No worries 😄 

>
> That's interesting nonetheless, I didn't expect any change to FOUC from this movement. (the page is pre-rendered, and with the css files loaded upfront there should be no changes)

I'll need to check the code and run a few tests again, but I'm hypothesizing that some jQuery stuff that modify the styling of some elements isn't run until the jQuery `script` is loaded.

>
> Will likely need to take a look at a PR + some reproduction instructions.

Sure, I'll get one up soon 👍
The reproduction instructions will be included with the PR once it's created.
