### ISSUE TITLE
Query about site deployment

### ISSUE THREAD

**Issue by HCY123902** [MarkBind/markbind#1677]
I am currently attempting to deploy RepoSense documentation to the github organization base URL, which is `https://reposense.org/`. However, when `baseURL` in `site.json` is set to empty, it seems that `markbind deploy` will still deploy the site to the link with the default repository, which is  `https://reposense.org/RepoSense`.

![image](https://user-images.githubusercontent.com/54735123/135241245-42cf13bf-7355-479c-b47f-a551ba235c30.png)

 Can I check whether there is any way to handle this situation? Many thanks

**Comment by damithc** [comment]
Probably not related to MarkBind. Will followup with @HCY123902 and reopen if related to MarkBind.
