### ISSUE TITLE
Build/live reload fails if a page/dynamically included file is missing

### ISSUE THREAD

**Issue by rachx** [MarkBind/markbind#168]
Pages such as `book/common/definitions.md` and `book/common/outcomes.md` may be missing (e.g. temporarily removed by IDE)

This causes a file not found error. The `.temp` and `_site` folders are subsequently removed. 

The site will not be served if this is the first build. If a serve is ongoing, there will be multiple permission errors. Subsequent live-reload does not work.

Ideally, we can show an error message and continue.

**Comment by nicholaschuayunzhi** [comment]
Based on further investigation: this arises from the error handling for pages. (a dynamically included file is treated the same way as a page in this regard). If a static include is not found, an error element will be generated for it. This is all handled within `markbind`'s parser. However, when a page/dynamically included file is missing, the error is handled by `markbind-cli` and the folders are removed.

**Comment by rachx** [comment]
Missing src for dynamically included files should be handled after https://github.com/MarkBind/markbind/commit/34a42ae0d56609f0edc3971152e1e0143e3c6df0
