### ISSUE TITLE
Installation error: Markbind command shows long text instead of ASCII

### ISSUE THREAD

**Issue by NicolasCwy** [MarkBind/markbind#1704]
**Tell us about your environment**

* **MarkBind Version:**3.0.6
* Node: v16.4.0
* NPM: 7.18.1

**What did you do? Please include the actual source code causing the issue.**
Ran `markbind` in a random folder
Tried `markbind serve` in root folder of project containing site.json

**What did you expect to happen?**
Markbind ASCII to be shown

**Steps tried**
- `npm install -g markbind-cl`
- Uninstalled and reinstalled markbind

**What actually happened? Please include the actual, raw output.**

https://user-images.githubusercontent.com/25302138/148723340-c2fdf3be-e16c-4423-8b80-e511dbe84f0e.mov

**Comment by damithc** [comment]
I think this is likely the culprit :-p https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected 

Same as #1703

**Comment by NicolasCwy** [comment]
Ah I see, will leave the issue open in case someone searches for the same problem
