### ISSUE TITLE
Extra line break in bullet point

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#171]
Can't figure out the reason for this 🤔 
![image](https://user-images.githubusercontent.com/1673303/37575561-c8e01bd2-2b62-11e8-87d1-997eacdb95b2.png)

Location https://nus-te3201.github.io/website/book-adapted/index.html#implementing-class-level-members

A similar code seems to work correctly in another place :-p

![image](https://user-images.githubusercontent.com/1673303/37575619-0efb3322-2b63-11e8-868d-6ad14eb1af63.png)

**Comment by damithc** [comment]
Is it a Windows thing? I built the site just now and the problem is still there?

Chrome:
![image](https://user-images.githubusercontent.com/1673303/40035408-32c39012-5834-11e8-87c2-0312c645edb5.png)

Firefox:
![image](https://user-images.githubusercontent.com/1673303/40035602-11f7dbd0-5835-11e8-989e-aeb9492cea79.png)


HTML code:

```html
<tab header="Python">

  <li>
    <p><a href="https://nus-te3201.github.io/website/programming/toc/oop.html#class-level-members">Python Programming Basics: OOP: Class-Level Members</a></p>
  </li>

  <p></p>
</tab>
```

**Comment by yamgent** [comment]
> But @yamgent has different results on Windows.

On Windows, indenting the bullets or not always produces the same result - the buggy one.

**Comment by yamgent** [comment]
I managed to get it working by doing the two steps inside `book\oopImplementation\classLevelMembers\text.md`:

1. Indent the bullets for both.
1. Removing the extra spaces at the end of the Java's tab section:

![fix-1](https://user-images.githubusercontent.com/3168908/40039203-fcc784f0-5847-11e8-8489-5847a0fa66f7.png)

---

So the final result should look like this:

![fix-2](https://user-images.githubusercontent.com/3168908/40039261-4cd4e0f0-5848-11e8-83aa-a3ad4da6b837.png)

**Comment by kaixin-hc** [comment]
Closing as this seems stale and with a solution; if this is an issue do let me know!
