### ISSUE TITLE
Vue 3 migration

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1716]
Nice to have for v4.

*May* be a little too large to achieve by then, but good to keep in view

**Comment by jonahtanjz** [comment]
https://github.com/bootstrap-vue/bootstrap-vue/issues/5196

Same issue with `bootstrap-vue` not supporting Vue 3 as of now.

**Comment by tlylt** [comment]
Duplicate, closing in favor of the latest #2084
