### ISSUE TITLE
Allow a way to ping active-devs for comments on issues/PRs

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1717]
**Is your request related to a problem?**
Related to dev experience.

I think because of permission settings, myself and other new devs are unable to ping/tag active developers/maintainers, which is possible as seen:
![image](https://user-images.githubusercontent.com/41845017/149609363-0ee09e80-1403-4fc6-8794-ac85f9a4b46c.png)

If I were to write it, it looks like this (not tagging):
![image](https://user-images.githubusercontent.com/41845017/149609386-99b8cd3d-fa1a-4fc0-a27c-58831c20bbe5.png)

**Describe the solution you'd like**

Maybe it can be solved with some configuration?

**Describe alternatives you've considered**

Maybe we can create a team for each batch of the 3281/3282 students?

**Additional context**
While I think the active developers will be watching the repo and looking at issues, I feel that having a way to mention them (in my case, the 3282 and other active senior devs) will be useful when clarifying old issues or just requesting general attention from any of the senior devs. This is especially when the issue/PR is not targeted to one single person and I feel bad to just be tagging ze yu or others alone when any of the senior devs could chip in.

**Comment by jonahtanjz** [comment]
I believe this is because the teams in Markbind organization is not set to public so only members within the organization can tag/mention teams. I think this can be solved once you all are added to the organization. Perhaps Prof @damithc or @ang-zeyu can assist in this as I do not have the permission to add new members.

**Comment by damithc** [comment]
> Perhaps Prof @damithc or @ang-zeyu can assist in this as I do not have the permission to add new members.

Invite all four to the org @kaixin-hc @jovyntls @tlylt @ong6
