### ISSUE TITLE
Page Navigation Menus not working with titles that contain `{{ content }}`

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1720]
**Tell us about your environment**
Windows
* **MarkBind Version:**
v.3.1.0
**What did you do? Please include the actual source code causing the issue.**
While working on PR #1719, I decided to turn on the page nav menus for the tips and tricks page and it resulted in the following screenshot:
![image](https://user-images.githubusercontent.com/41845017/149618713-b8120b1c-616e-41d8-9d3e-279821887ae3.png)

Snippet of the `tipsAndTricks.md` page below:
```md
{% set title = "Tips & Tricks" %}
<span id="title" class="d-none">{{ title }}</span>

<frontmatter>
  title: "User Guide: {{ title | safe }}"
  layout: userGuide.md
  pageNav: 5
</frontmatter>

# {{ title | safe }}

<span id="escapingCharacters">

##### :fas-lightbulb: Escaping Characters

For Markdown syntax: To display a literal character that are normally used for Markdown formatting, add a backslash (`\`) in front of the character.

<include src="codeAndOutput.md" boilerplate >
<variable name="highlightStyle">markdown</variable>
<variable name="code">
\* item 1

* item 1 
</variable>
</span>

<small>More info: [https://www.markdownguide.org/basic-syntax#escaping-characters](https://www.markdownguide.org/basic-syntax#escaping-characters)</small>

</span>

{% raw %}

##### :fas-lightbulb: Using {% raw %}{% endraw %} to display `{{ content }}`


To display the raw variable interpolation syntax using `{% raw %}{% endraw %}`, you would also need to add
the `v-pre` attribute using markdown-it-attrs or as a html attribute.

```

**What did you expect to happen?**
I expected the page side nav to show the formatted text of ":fas-lightbulb: Using {% raw %}{% endraw %} to display `{{ content }}`",

**What actually happened? Please include the actual, raw output.**
The last part "`{{ content }}`" disappeared. On the console, it is being rendered as `&lrm;` :
![image](https://user-images.githubusercontent.com/41845017/149618792-8734efb9-680a-4a84-a942-32a488ffc514.png)
In the console, there is an error message:
![image](https://user-images.githubusercontent.com/41845017/149618820-da087c26-bc4a-4c06-9ba8-60daa81bd60d.png)

The bug example can be viewed at this deploy preview [page](https://deploy-preview-1719--markbind-master.netlify.app/userguide/tipsandtricks)

**Comment by jonahtanjz** [comment]
Seems like this is due to Vue treating the double curly braces as [text interpolation](https://vuejs.org/v2/guide/syntax.html#Text). Will probably need to process these curly braces in the [_collectNavigableHeadings method](https://github.com/MarkBind/markbind/blob/ed2f323325b1005ce9f578bd94a4227bfdf73d92/packages/core/src/Page/index.js#L189) and wrap them in [`<span v-pre>{{ content }}</span>`](https://v3.vuejs.org/api/directives.html#v-pre) to treat it as raw text.

**Comment by tlylt** [comment]
> Seems like this is due to Vue treating the double curly braces as [text interpolation](https://vuejs.org/v2/guide/syntax.html#Text). Will probably need to process these curly braces in the [_collectNavigableHeadings method](https://github.com/MarkBind/markbind/blob/ed2f323325b1005ce9f578bd94a4227bfdf73d92/packages/core/src/Page/index.js#L189) and wrap them in [`<span v-pre>{{ content }}</span>`](https://v3.vuejs.org/api/directives.html#v-pre) to treat it as raw text.

I see, thanks for the diagnosis! Will put up a fix for this in a while:)
