### ISSUE TITLE
When using the convert feature, an extra newline is generated 

### ISSUE THREAD

**Issue by ong6** [MarkBind/markbind#1726]
**Is your request related to a problem?**

When using `markbind init -convert` the pages on site-nav do not generate properly.

Example:
![image](https://user-images.githubusercontent.com/19247856/149973749-c5a35852-2fc3-48a2-99af-cbc4e770d7cc.png)

This causes an issue when the user tries to serve the webpage as markbind cannot accurately determine the closing tags.

Example:
![image](https://user-images.githubusercontent.com/19247856/149973887-340d821b-ce4c-4b2e-96b8-d65f45ab72e0.png)

**Describe the solution you'd like**

Make it so that when generating the individual pages, there is no newline. 

or

Somehow allow the closing tags to be parsed accurately.

**Comment by damithc** [comment]
IIRC, deep indentation causes markdown parsers to treat text as a code block. e.g.,
![image](https://user-images.githubusercontent.com/1673303/149985288-31b63dad-ee8b-480a-9aad-193c6c97291e.png)

**Comment by ong6** [comment]
> IIRC, deep indentation causes markdown parsers to treat text as a code block. e.g., ![image](https://user-images.githubusercontent.com/1673303/149985288-31b63dad-ee8b-480a-9aad-193c6c97291e.png)

Yeah, not sure how to fix this other than to fix the newline part of it. I was looking into how to make markdown parsers ignore the empty spaces but it has not yielded any results yet. 

But now with these 2 issues resolved, convert now works buttery smooth. No editing required.

**Comment by damithc** [comment]
> I was looking into how to make markdown parsers ignore the empty spaces but it has not yielded any results yet.

When writing code manually, I use 2-spaces indentation instead of 4-spaces and omit indentations in some places altogether, due to this problem.
