### ISSUE TITLE
Update Algolia plugin

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1729]
I'm having trouble getting the Algolia plugin to work with the latest search indexes provided by them (note that they migrated to a new infra recently).

Steps: 
1. Go to https://codesandbox.io/s/currying-leaf-qwo9k?file=/src/index.js  (this is a sandbox provided by Algolia devs to us)
2. Change 2021 to 2022 as indicated below
    ![image](https://user-images.githubusercontent.com/1673303/150136048-b386ab77-e706-403a-a795-be84e2ec70ed.png)
3. Use the right-hand side to confirm the search is working

Now, I have trouble using the same config parameters with our algolia plugin. This is how my config looks like:
```json
    "algolia": {
      "apiKey": "a3fef7e2d9dea07c0fa2d8ed521057aa",
      "appId": "3DU4XTBX4T",
      "indexName": "nus-tic-cs",
      "algoliaOptions": { "hitsPerPage": 10 },
      "facetFilters": ["site:nus-tic2002-2022.github.io"],
      "debug": false
    }
```
Perhaps some updates needed to our Algolia plugin?

**Comment by jonahtanjz** [comment]
Seems like Algolia now requires `appId` to be specified if not it will return a 403 error as shown.

![image](https://user-images.githubusercontent.com/47470981/150165580-739eab09-e5f9-40f8-ad0d-a0f3a09ff114.png)

Our current implementation does not include the `appId`. Not sure if this was missed out or a new requirement by Algolia. 

![image](https://user-images.githubusercontent.com/47470981/150166072-48f86517-7bee-47a1-af54-b1dd1dbfbe0d.png)
[Code reference here](https://github.com/MarkBind/markbind/blob/master/packages/core/src/plugins/algolia.js#L9)

Adding the `appId` here should resolve the issue. I think it's also a good idea to take this chance to upgrade Algolia to v3 as v2 is now a legacy version and no longer actively maintained.

**Comment by damithc** [comment]
Thanks for the investigation @jonahtanjz 
Let's fix it soon so that I can start using Algolia again.
