### ISSUE TITLE
Embeds do not scale, causing overflow on mobile

### ISSUE THREAD

**Issue by ryoarmanda** [MarkBind/markbind#1731]
**Tell us about your environment**
Windows

**MarkBind Version:**
v3.1.0

**What did you do? Please include the actual source code causing the issue.**
From default template (via `markbind init`), serve the site and observe it on mobile dimensions (e.g. through Chrome's device emulation).

**What did you expect to happen?**
Everything is scaled appropriately

**What actually happened? Please include the actual, raw output.**
Embeds do not scale along, causing horizontal overflow, which is not ideal on mobile environment. The overflow negatively impacts the navbar, pushing the search bar out of the viewport and thus scrolling is required to access it.

This is largely due to the iframes that contain the embedded media have fixed width and height (default is 640x390). Making responsive iframe container is a little finicky, but [possible](http://jsfiddle.net/omarjuvera/8zkunqxy/2/) (found in [StackOverflow](https://stackoverflow.com/questions/17838607/making-an-iframe-responsive)). I think it's good to explore whether this can be done on our end, be it with the default or custom dimensions.

![image](https://user-images.githubusercontent.com/24468110/150361516-578d70bf-9c48-4794-8cf9-c21b99d199d5.png)

![image](https://user-images.githubusercontent.com/24468110/150363010-2b17691e-d2ec-4fc9-ac10-b46faad6e368.png)

**Comment by ong6** [comment]
I was looking into investigating this issue but it seems as though my media embed does not overflow but instead causes the whole page to be scaled down.

![image](https://user-images.githubusercontent.com/19247856/151908811-82b915fe-96e9-48a0-94de-bdc1304d5e96.png)

I'm not sure if this is the same issue as what you mentioned but I think a fix could be to force the width to a view-width instead

**Comment by ang-zeyu** [comment]
@ong6 you could also try looking into #1741, although it fixes only the header.

> Embeds do not scale along, causing horizontal overflow, which is not ideal on mobile environment. The overflow negatively impacts the navbar, pushing the search bar out of the viewport and thus scrolling is required to access it.

> I was looking into investigating this issue but it seems as though my media embed does not overflow but instead causes the whole page to be scaled down.

I'm encountering something closer to @ryoarmanda's description instead. (the default viewport width is nicely lined up with the main text, although the embeds and headers overflow).

Try opening a new browser instance to the same link and see if the issue persists. (for me the zoom persisted across refreshes, which may causing your issue)
