### ISSUE TITLE
`npm run updatetest` and `npm build` files different

### ISSUE THREAD

**Issue by ong6** [MarkBind/markbind#1737]
**Tell us about your environment**
Windows 10

* **MarkBind Version:**
v3.1.1

**What did you do? Please include the actual source code causing the issue.**

When generating tests with `npm run updatetest`, the files generated are completely different from the actual `markbind build` files, making `npm run test` fail. 

Example:
![image](https://user-images.githubusercontent.com/19247856/151293704-1722f39f-96b2-4763-8b1f-a862eb2cb060.png)

To note: this is for generation of completely new files. I created the test folders and `updatetest` is supposed to generate the expected files generated.

**What did you expect to happen?**

Expected the files to be the same since the expected file was generated by `npm run updatetest`

**What actually happened? Please include the actual, raw output.**

Comparing the 2 files below, one has indentation and the other does not.

Test files:
[build_generated.txt](https://github.com/MarkBind/markbind/files/7948011/build_generated.txt)
[test_generated.txt](https://github.com/MarkBind/markbind/files/7948021/test_generated.txt)

**Comment by jonahtanjz** [comment]
Can you try changing your git config to `git config core.eol lf` and `git config core.autocrlf input`?

**Comment by ang-zeyu** [comment]
@ong6  This is intentional, there are 2 major differences between `npm run updatetest` and `npm build`:
- `js-beautify` is run on the html output to help with PR reviewing the file diffs
- the functional tests are not run through ssr as the diff is far harder to review (components are expanded into html tags)

**Comment by ong6** [comment]
> @ong6 This is intentional, there are 2 major differences between `npm run updatetest` and `npm build`:
> 
> * `js-beautify` is run on the html output to help with PR reviewing the file diffs
> * the functional tests are not run through ssr as the diff is far harder to review (components are expanded into html tags)
> 
> https://github.com/MarkBind/markbind/blob/master/packages/core/src/Page/index.js#L519 https://github.com/MarkBind/markbind/blob/master/packages/core/src/Page/index.js#L531
> 
> Perhaps we could add a small note / tipbox into the relevant developer guide section 🙂

Ohh, thanks for the info, that clears things up. I will look into adding a tipbox to the dev guide when I do a documentation PR 👍 

But I still can't seem to get #1727 to work as intended due to the difference in file changes `npm run test` works locally so I can only debug it on the github ci.

I have tried:

1. npm run setup
2. npm run updatetest in 'packages/cli'
3. npm run test in 'packages/cli'
4. - passes on my computer but fails on gh due to the line differences.
