### ISSUE TITLE
Local CI test and Github's CI test produce different results

### ISSUE THREAD

**Issue by jonahtanjz** [MarkBind/markbind#1740]
**Tell us about your environment**
Windows 10

* **MarkBind Version:**
3.1.1

**What did you do? Please include the actual source code causing the issue.**
Discovered by @ong6 when attempting PR #1727. After modifying test files, `npm run updatetest` is run to update the expected test files. Subsequent `npm run test` inside local repo passes.

![image](https://user-images.githubusercontent.com/47470981/151569598-609e157a-3885-4963-9aba-ca11e6e3c97f.png)

**What did you expect to happen?**
Github CI should pass after opening PR.

**What actually happened? Please include the actual, raw output.**
Diff found in files.

![image](https://user-images.githubusercontent.com/47470981/151569550-273f31dc-5ec6-4dea-b80b-a363cbc58a59.png)

Reproduced in #1739. Not sure if this is only happening on Windows. Maybe someone with a Mac can try to pull the branch in and run `npm run test` to see if this is happening on other OS as well?

**Comment by ang-zeyu** [comment]
@jonahtanjz @ong6 this is may be due to #1736 instead (`%5C/`'s in the screenshot)

Couldn't produce any line ending differences on ubuntu & wsl as well (do try to set this up for debugging os-specific issues!).

---

On a separate note, the colours in the diffs seem to be broken (`%5C/` should be highlighted green/red). 🤔

**Comment by ong6** [comment]
> @jonahtanjz @ong6 this may be due to #1736 instead (`%5C/`'s in the screenshot)
> 
> Couldn't produce any line ending differences on ubuntu & wsl as well (do try to set this up for debugging os-specific issues!).
> 
> ---
> 
> On a separate note, the colours in the diffs seem to be broken (`%5C/` should be highlighted green/red). 🤔 

Theres a chance, I will be working on fix for the / issue.

**Comment by ong6** [comment]
@ang-zeyu @jonahtanjz PROBLEM SOLVED! Turns out it really was the %5C/ issue! I updated my PR now the tests are working fine!
