### ISSUE TITLE
Popover components are not accessible

### ISSUE THREAD

**Issue by jovyntls** [MarkBind/markbind#1745]
**Tell us about your environment**
MacOS Monterey 12.0.1

* **MarkBind Version:**
v3.1.1

**What did you do? Please include the actual source code causing the issue.**
Create a popover component without a trigger component, 
e.g. `<popover content="Lorem ipsum dolor sit amet" triggers="focus">Popover on top</popover>`

**What did you expect to happen?**
For accessibility purposes, the popover should be open-able from the keyboard to cater to keyboard-only users.

**What actually happened? Please include the actual, raw output.**
The popover content (in the above example, "Popover on top") is not focus-able by keyboard even when the `triggers` attribute is set to `focus`.
Furthermore, when a trigger method is not specified, currently MarkBind defaults to `hover`. However, this poses accessibility issues as `hover` is [impossible to trigger for keyboard-only users](https://bootstrap-vue.org/docs/directives/popover#making-popovers-work-for-keyboard-and-assistive-technology-users). 

Suggestion: Maybe we could set the default value of `triggers` to `"hover focus"`? This would maintain the expected hover behaviour, and also allow for accessibility for keyboard-only users. I think such a change would not be noticeable for most users, but would be helpful in terms of accessibility.

**Comment by ong6** [comment]
This issue exists on windows as well.  Furthermore, this issue also exists for mobile users as they won't be able to hover but instead must press and hold (which might not work also) to read the popover text.

I think Jovyn's solution makes sense and should be implemented as it may potentially help those on mobile version as well.

**Comment by jovyntls** [comment]
I'll work on this after #1748 since there's some refactoring of the Popover/Tooltip components there!
