### ISSUE TITLE
Lazy build taking too long?

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1751]
Guys, today I noticed the lazy build of the CS2103 website is taking 2 minutes. Earlier, it used to be in the order of 10-15 seconds IIRC.

![image](https://user-images.githubusercontent.com/1673303/152671413-3e4917b3-f37c-4f3e-9f6a-301cda49e15b.png)

Is it me or are you able to reproduce it as well?

CS2103 website is at ~~https://github.com/nus-cs2103/website-base~~ https://github.com/nus-cs2103-AY2122S2/website
Follow the instructions in the README to set up.
After that, checkout `cs2103` branch before running MarkBind

**Comment by tlylt** [comment]
Hi @damithc 
Are you using v3.1.1 from the released version of markbind, or markbind from the master branch?

I just pulled the repo and tried `markbind serve -o` on the master branch, looks ok (I'm on the lastest master branch version of markbind):
![image](https://user-images.githubusercontent.com/41845017/152673482-cdb32bab-faae-4216-9b79-842375e53e7c.png)

When I checkout to cs2103 branch and do `markbind serve -o` I am faced with errors, not too sure if I am doing anything wrong. I did run `Run git submodule update --init --recursive to pull the content of the submodule.` according to the README.
![image](https://user-images.githubusercontent.com/41845017/152673509-5b643e62-b86e-4e2f-bb8c-bda0185c022f.png)

**Comment by damithc** [comment]
@tlylt I'm using the released version, not the master branch.

**Comment by damithc** [comment]
@tlylt after switching to c2103 branch, confirm if the latest commit is recent (timestamp within last week)

**Comment by tlylt** [comment]
> @tlylt after switching to c2103 branch, confirm if the latest commit is recent (timestamp within last week)

Hi prof,
the latest commits I see is from 1 year ago, can't find the branch that is recent (besides master)
![image](https://user-images.githubusercontent.com/41845017/152673969-4f0e8098-dea7-41f5-98ba-50b6c41ee8b9.png)

**Comment by tlylt** [comment]
> > the latest commits I see is from 1 year ago, can't find the branch that is recent (besides master)
> 
> Oops sorry, use this instead [nus-cs2103-AY2122S2/website](https://github.com/nus-cs2103-AY2122S2/website)

Unable to reproduce (I have switched to the released version)
- I am using Windows 10, perhaps someone else can double-check on their machine as well

![image](https://user-images.githubusercontent.com/41845017/152674938-33c0dbd7-2918-4635-971a-263e826bf843.png)

**Comment by damithc** [comment]
I'm using Windows 10 too. Can reproduce in Git bash (121 seconds) and DOS terminal (108 seconds).
For now, we established that the build should be faster than what I'm experiencing. Still not sure what is causing my build to be slower though.

**Comment by damithc** [comment]
log:
```
2022-02-06T09:35:01.733Z - info: Website generation (lazy) started at 5:34:57 pm
2022-02-06T09:35:56.295Z - info: Building assets...
2022-02-06T09:36:43.909Z - info: Assets built
2022-02-06T09:36:43.909Z - info: Generating landing page...
2022-02-06T09:36:45.316Z - info: Landing page built, other pages will be built as you navigate to them!
2022-02-06T09:36:46.310Z - info: Site data built
2022-02-06T09:36:46.311Z - info: Website generation (lazy) complete! Total build time: 108.82s
2022-02-06T09:36:47.199Z - info: Serving "C:\repos\nus-cs2103\cs2103-website-base\_site" at http://127.0.0.1:8080
2022-02-06T09:36:47.199Z - info: Press CTRL+C to stop ...
```

**Comment by tlylt** [comment]
> I'm using Windows 10 too. Can reproduce in Git bash (121 seconds) and DOS terminal (108 seconds). For now, we established that the build should be faster than what I'm experiencing. Still not sure what is causing my build to be slower though.

Works around 3s for gitbash/cmd for me. I observe that CPU usage reaches spike of 50% for me when running the command, perhaps can check on the CPU stats to see if the computer is too heavily utilized before running the command?
![image](https://user-images.githubusercontent.com/41845017/152675906-c108c432-dfa6-4430-946b-13da0ceb90d2.png)

**Comment by damithc** [comment]
When the build is ongoing:

![image](https://user-images.githubusercontent.com/1673303/152676150-6c753f79-65d3-44b6-99cf-f74db4b4ee34.png)

after shutting down the server:

![image](https://user-images.githubusercontent.com/1673303/152676230-29ead8ff-aba2-44f8-b45e-e99ee0490b3c.png)

**Comment by jonahtanjz** [comment]
I've tested it out with the released version on windows 10. I'm not able to reproduce as well.

![image](https://user-images.githubusercontent.com/47470981/152680684-767a0184-9c96-43b7-a272-063eb5bf2e90.png)

**Comment by damithc** [comment]
Could be due to some Windows update, as this was a sudden change today and other things remain same.

**Comment by ong6** [comment]
I've also tried it, running windows 10 on i7-10700K, I am unable to reproduce it as well.

![image](https://user-images.githubusercontent.com/19247856/152722453-28f27d25-d666-41fa-8385-c582950ee78b.png)

**Comment by jovyntls** [comment]
I can't reproduce either (running MacOS 12.0.1 on Intel Mac), for both the MarkBind latest master and last release:
![image](https://user-images.githubusercontent.com/61113575/152725731-22b06fe9-45be-437a-87e3-751f67a5c455.png)

**Comment by tlylt** [comment]
Perhaps @damithc can help check if the lazy loading functionality works on some other pages by:
- `markbind serve -o index.md` (the default, but now index.md is specified)
- `markbind serve -o se-book-adapted/index.md` (build and open the index.md page of the book folder)
- `markbind serve -o schedule/index.md` (build and open the index.md page of the schedule folder)

In all above cases, it takes about 3s for me.

**Comment by damithc** [comment]
> Perhaps @damithc can help check if the lazy loading functionality works on some other pages by:
> 
> * `markbind serve -o index.md` (the default, but now index.md is specified)
> * `markbind serve -o se-book-adapted/index.md` (build and open the index.md page of the book folder)
> * `markbind serve -o schedule/index.md` (build and open the index.md page of the schedule folder)
> 
> In all above cases, it takes about 3s for me.

Same result. But I managed to get a better result by following one of you guys' suggestion (@ong6 ?) to use a fresh clone. It took 13s but that's more like the normal state of affairs compared to 110s. So, it is something to do with my old project folder :-p

**Comment by damithc** [comment]
Turns out it's a git problem after all. My .git folder was 2.6 Gb! Reduced to 366 Mb after running `git gc --aggressive --prune=now` and the build time is reduced to previous levels. Thanks everyone for helping me troubleshoot this. 💯
