### ISSUE TITLE
Support style files for .puml

### ISSUE THREAD

**Issue by kaixin-hc** [MarkBind/markbind#1752]
**Tell us about your environment**
MacOS version 12.1

* **MarkBind Version:**
v3.11 is the latest release
**What did you do? Please include the actual source code causing the issue.**
When .puml files use a `style.puml` document, this .puml code cannot be processed by markbind automatically.

packageDiagram.puml
```
@startuml
!include style.puml
...
@enduml
```
Code to include puml diagram: `<puml src="diagrams/packageDiagram.puml"></puml>`

**What did you expect to happen?**

I expected the puml diagram to render on the website. This would be a hinderance if converting existing project documentation, as the existing .puml diagrams would need to be rewritten in order to include .puml instead of an image of the diagram

**What actually happened? Please include the actual, raw output.**
An error message is produced
<img width="718" alt="Screenshot 2022-02-07 at 11 17 53 AM" src="https://user-images.githubusercontent.com/59471320/152719141-b512f6b9-5ec2-4100-9c90-543b10f01412.png">

You can reproduce this issue here: https://github.com/kaixin-hc/teammates on the design.md file by changing `![Package Diagram](images/packageDiagram.png)` to `<puml src="diagrams/packageDiagram.puml"></puml>`

**Comment by tlylt** [comment]
Hi @kaixin-hc,

Indeed it doesn't work with the original "diagrams/packageDiagram.puml" file . 
However, the include support is not broken.
If you adjust the puml:
```puml
@startuml
!include style.puml
...
@enduml
```
to
```puml
@startuml
!include diagrams/style.puml
...
@enduml
```

It should work as expected:
e.g
![image](https://user-images.githubusercontent.com/41845017/152729989-ad388e0b-eae4-433a-888c-4711d9c3bf21.png)

**Comment by kaixin-hc** [comment]
Thanks! Good catch. I'll close this issue now.

**Comment by ang-zeyu** [comment]
Nice catch @kaixin-hc @tlylt 

Reopening this even though there's a workaround as its likely unintended. (relative file paths should be computed from where the puml source is written)

This problem is also likely present in inline `<puml>` tags.

**Comment by tlylt** [comment]
> Nice catch @kaixin-hc @tlylt
> 
> Reopening this even though there's a workaround as its likely unintended. (relative file paths should be computed from where the puml source is written)
> 
> This problem is also likely present in inline `<puml>` tags.

@ang-zeyu Good catch.
While the support for include feature is there, it is unable to fetch the correct file possibly due to how we process the puml dsl to image.
As a quick workaround, one can use URL include to link a shared resource until this bug is fixed.
For example, replacing `style.puml` with the URL to its content will work:
```
@startuml
!include https://raw.githubusercontent.com/kaixin-hc/teammates/master/docs/diagrams/style.puml
skinparam componentBackgroundColor MODEL_COLOR_T1
skinparam componentFontColor #FFFFFF
skinparam folderBackgroundColor #FFFFFF
skinparam rectangleBackgroundColor MODEL_COLOR
skinparam arrowColor #000000

// ....
@enduml
```

**Comment by tlylt** [comment]
relevant:
- https://plantuml.com/preprocessing#4d03410776ebc180
- https://forum.plantuml.net/4567/how-to-include-the-current-folder-in-the-search-path?show=4567#q4567
