### ISSUE TITLE
Support $$ as delimiter for math formula

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1754]
**Is your request related to a problem?**

When trying to import some content that I authored using a markdown editor with mathjax support, I discovered that the `$ $` `$$ $$` delimiters are not working due to the choice of brackets over dollars as a delimiter in PR #1335.
This was with the consideration that `$$ $$` was planned to serve as delimiters for underline. However, in issue #28, `!! !!` was chosen for underline instead.

Since we have freed up `$$$$`, perhaps we can allow user to configure the delimiter of their choice for better support for math related content.

**Describe the solution you'd like**

Allow users to specify the delimiter of their choice in `site.json`

**Describe alternatives you've considered**

Since I am not sure the exact proportion of people who use brackets as delimiters for tex, I guess the default delimiter can stay as it is. The alternative is for authors to convert their syntax from dollars to brackets, which as acknowledged in this https://github.com/MarkBind/markbind/issues/28#issuecomment-784007166 ...is not very user friendly.

**Comment by damithc** [comment]
Thanks for bringing this up @tlylt No strong views from my side, as I don't use math formulae in MarkBind sites. Others are welcome to give inputs.

**Comment by jonahtanjz** [comment]
@tlylt I think allowing the use of `$$` for math notation is a good idea since this is a commonly used delimiter.

> Allow users to specify the delimiter of their choice in site.json

I'm not too sure about this as allowing users to specify their own delimiter can cause some issues in the future when MarkBind introduces new delimiters for new features (e.g the `!!` for underline). Existing users that have conflicting delimiters will have to choose a new delimiter and update all the usages in their files. In this case I feel that having fixed/reserved delimiters for specific feature can prevent this issue from happening.

**Comment by tlylt** [comment]
> I'm not too sure about this as allowing users to specify their own delimiter can cause some issues in the future when MarkBind introduces new delimiters for new features (e.g the `!!` for underline). Existing users that have conflicting delimiters will have to choose a new delimiter and update all the usages in their files. In this case I feel that having fixed/reserved delimiters for specific feature can prevent this issue from happening.

Yup agree on this. Based on the delimiters supported by markdown-it-texmath, I am thinking it would be nice if we can support dollars and brackets at the very least....either interchangeably or users can specify one of them in 'site.json'.
![image](https://user-images.githubusercontent.com/41845017/152933866-94496098-16b7-4e95-a1c9-5b083fc32e69.png)

**Comment by jonahtanjz** [comment]
> Based on the delimiters supported by markdown-it-texmath, I am thinking it would be nice if we can support dollars and brackets at the very least....either interchangeably or users can specify one of them in 'site.json'.

Ahh I see. I prefer supporting them interchangeably since both the dollars and brackets delimiters will be reserved for this specific function. I don't really see a benefit for users to specify one of them in `site.json` since they won't be able to use the other for some other purposes? (this also adds an extra step for the user if they want to use the `$$` delimiter).

**Comment by tlylt** [comment]
Hi @jonahtanjz, I am able to support both syntaxes by loading the plugin `markdown-it-texmath` twice to include the default dollar sign delimiter.
```js
markdownIt.use(require('markdown-it-mark'))
	//...
  .use(require('markdown-it-texmath'), { engine: katex, delimiters: 'brackets' })
  .use(require('markdown-it-texmath'))
```
On the functionality side, it looks ok but I'm not sure if there's anything to be concerned about for performance or otherwise. Any thoughts? Couldn't really find anything related to loading a plugin twice. If this works then it's probably the least expensive change required.

![image](https://user-images.githubusercontent.com/41845017/155513298-7388ffde-b586-4daa-a618-6217c5e6e25e.png)

**Comment by jonahtanjz** [comment]
> On the functionality side, it looks ok but I'm not sure if there's anything to be concerned about for performance or otherwise. Any thoughts?

Seems like including the plugin twice works quite well although it looks quite "hacky" 🤣 Performance wise shouldn't be too much overhead from what I can see (the largest one is probably importing the [katex package](https://github.com/goessner/markdown-it-texmath/blob/master/texmath.js#L28)).

The other alternative is to patch it to allow for `delimiters` to hold multiple values. The plugin does not seem too complex and does not have very frequent releases so patching is not too bad as well.

**Comment by tlylt** [comment]
> Seems like including the plugin twice works quite well although it looks a little "hacky" 🤣 Performance wise shouldn't be too much overhead from what I can see (the largest one is probably importing the [katex package](https://github.com/goessner/markdown-it-texmath/blob/master/texmath.js?rgh-link-date=2022-02-24T15%3A02%3A06Z#L28)).

Based on [this](https://stackoverflow.com/a/26703392/13725861) and [this](https://nodejs.org/docs/latest/api/modules.html#caching), seems like the import statement should not be too problematic as explained below:
> Modules are cached after the first time they are loaded. 
> Provided require.cache is not modified, multiple calls to require('foo') will not cause the module code to be executed multiple times.

**Comment by tlylt** [comment]
@jonahtanjz I am planning to implement the "hacky" solution as an optional plugin that users can choose to turn on if needed. The reason is that we already support one syntax for math formulae and this is more of customization for anyone who needs it. 
Do you think this is fine?

**Comment by jonahtanjz** [comment]
> I am planning to implement the "hacky" solution as an optional plugin that users can choose to turn on if needed. The reason is that we already support one syntax for math formulae and this is more of customization for anyone who needs it.
Do you think this approach is fine?

Since the overhead is not too problematic and it is an optional plugin that user can include, then I think this approach is fine.
