### ISSUE TITLE
Include command does not work

### ISSUE THREAD

**Issue by danielbrzn** [MarkBind/markbind#177]
On the latest version (v1.6.2), the `include` command does not work. The error is as follows:

```
C:\Users\Daniel\Desktop\CS3281\markbind\lib\markbind\lib\parser.js:379
      const fileBase = path.resolve(calculateNewBaseUrl(file, config.rootPath, config.baseUrlMap).relative);
                                                                     ^

TypeError: Cannot read property 'rootPath' of undefined
    at fs.readFile (C:\Users\Daniel\Desktop\CS3281\markbind\lib\markbind\lib\parser.js:379:70)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by damithc** [comment]
Doesn't work anywhere? That sounds serious but how come I didn't notice is so far. I've been using 1.6.2 for  a couple of days now.

**Comment by danielbrzn** [comment]
The command itself doesn't work, but for our other commands like serve/build, it works fine. The root cause is that in the command itself, the `include` method is missing a parameter. However, in other uses of the `include` method, the parameters are passed correctly, which is why there's no major disruption to how pages are rendered.

**Comment by nicholaschuayunzhi** [comment]
I've confirmed this behaviour.

> Also, shouldn't a test fail if this is the case?

Currently we do a site diff after using `markbind build` so this was not caught. Will consider this in the unit tests that I'm implementing.

**Comment by damithc** [comment]
> The command itself doesn't work, but for our other commands like serve/build, it works fine.

Oh, the include command. I've never used that before. Glad to hear build/server/deploy are unaffected :-)
