### ISSUE TITLE
Update browsers list package?

### ISSUE THREAD

**Issue by ong6** [MarkBind/markbind#1770]
**Is your request related to a problem?**

![image](https://user-images.githubusercontent.com/19247856/153789683-129de442-c065-4185-b46b-179d5fa22f72.png)

I got this log when running `npm run build`. Should we update the browsers list package? 

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

(Write your answer here.)

**Additional context**
n/a

(Write your answer here.)

**Comment by jonahtanjz** [comment]
Thanks for the suggestion @ong6. Seems like browserslist is a nested dependency. Will need to check if updating it will affect the main dependency using this (or update the main dependency itself if possible).

**Comment by tlylt** [comment]
> I got this log when running `npm run build`. Should we update the browsers list package?

@ong6 is `npm run build` ran within `packages/core-web`? I just tried running it locally and I don't see the warning anymore.

**Comment by ong6** [comment]
@tlylt Yeah, Yeah, I think it got fixed along the way, I don't get the warning either.
