### ISSUE TITLE
How to handle changes to `.min` files which are not `markbind.min`

### ISSUE THREAD

**Issue by ong6** [MarkBind/markbind#1771]
**Is your request related to a problem?**

After running `npm run build`, I end up with a few .min files that are not markbind.min files. Since the dev guide mentions that the markbind.min.js and markbind.min.css are updated during bundle release only, how do we handle updates to other .min files in the core-web package? Are they also only updated during a bundle release as well?

Referenced section in docs:
![image](https://user-images.githubusercontent.com/19247856/153797679-436083e1-e39f-4b9d-bba7-331debc924f4.png)

**Comment by jonahtanjz** [comment]
Are you referring to the `vueCommonAppFactory` .min files? Running `npm run build` should only update the .min files in `core-web/dist` folder. You only need to worry about this when doing a release (Eg. copying the markbind.min.css and markbind.min.js to the respective test folders. Can refer to steps 3 and 5 [here](https://markbind-master.netlify.app/devguide/projectmanagement#doing-a-release)). For a PR, you do not need to commit these changes.

**Comment by ong6** [comment]
> Are you referring to the `vueCommonAppFactory` .min files? Running `npm run build` should only update the .min files in `core-web/dist` folder. You only need to worry about this when doing a release (Eg. copying the markbind.min.css and markbind.min.js to the respective test folders. Can refer to steps 3 and 5 [here](https://markbind-master.netlify.app/devguide/projectmanagement#doing-a-release)). For a PR, you do not need to commit these changes.

Ok thanks!
