### ISSUE TITLE
Upgrade PlantUML version

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1792]
Our current PlantUML version seems quite old. Perhaps time to upgrade?
But need to check if there are breaking changes in the new version.

**Comment by tlylt** [comment]
Seems like there are at least some minor style updates in the latest version, not sure if it's fine?
E.g. 

![image](https://user-images.githubusercontent.com/41845017/163520473-795158bf-5982-474a-9414-fc8b80f14258.png)
![image](https://user-images.githubusercontent.com/41845017/163520556-9c6cf54f-dc08-4798-8644-7abe54d1b06e.png)

![image](https://user-images.githubusercontent.com/41845017/163520728-240d5d65-2ae8-4576-90be-dfbf46027753.png)
![image](https://user-images.githubusercontent.com/41845017/163520669-4b9c37b6-76f6-4c11-89d0-14f16a591f75.png)

**Comment by damithc** [comment]
I think it should be fine. In fact, there are changes in the placement logic as well (i.e., the layout of the diagram generated by the new version could be different from the old one), but I guess no choice but to upgrade and tweak the diagrams later, if necessary.

**Comment by lesterong** [comment]
Hi, I would like to take up this issue 🙂 . May i know if we are going ahead with the new theme after the dependency update?

**Comment by tlylt** [comment]
> Hi, I would like to take up this issue 🙂 . May i know if we are going ahead with the new theme after the dependency update?

@damithc any preference?

**Comment by damithc** [comment]
@tlylt @lesterong We can go with the default theme. Those who want to use the old theme can do that manually using `skin rose` inside their PlantUML code.
