### ISSUE TITLE
Replace the use of deprecated <big> tag in docs

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1799]
**Tell us about your environment**
Windows
**MarkBind Version:**
v3.1.1

**What did you do? Please include the actual source code causing the issue.**
Found usage of `<big>` in our documentations

**What did you expect to happen?**
I think these should be replaced with `++Large++` to make use of the markdown [text styles](https://markbind.org/userGuide/formattingContents.html#text-styles) or, via CSS styling.

It seems like the use of `<big>` is not a documented markbind feature and referring to the HTML spec, it is [no longer supported](https://www.w3schools.com/tags/tag_big.asp)

Interestingly, the use of `<small>` is still OK:
- [Why \<big\> is not in HTML 5 Tag list while \<small\> is?](https://stackoverflow.com/questions/2260024/why-big-is-not-in-html-5-tag-list-while-small-is)
- [Why Do Some HTML Elements Become Deprecated?](https://css-tricks.com/why-do-some-html-elements-become-deprecated/)

**What actually happened? Please include the actual, raw output.**
![image](https://user-images.githubusercontent.com/41845017/156863234-7dfc57dc-ca8e-4a93-a4e0-c9cf38331936.png)

**Comment by damithc** [comment]
Yes, I think we used `<big>` as a workaround before we started supporting `++`. It's time to get rid of those tags now.
