### ISSUE TITLE
Broken link in About Us

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1800]
**Tell us about your environment**
Windows
* **MarkBind Version:**
* v3.1.1

**What did you do? Please include the actual source code causing the issue.**
https://markbind.org/about.html
The link to [NUS Center for Development of Teaching and Learning](http://www.cdtl.nus.edu.sg/) is broken.
**What did you expect to happen?**
No broken links.

**What actually happened? Please include the actual, raw output.**
The reference NUS site seems to be down/shifted. Not sure what's the latest URL for it. 

Btw this seems to also affect other NUS OSS projects, e.g TEAMMATES.

**Comment by damithc** [comment]
Correct link https://nus.edu.sg/cdtl
