### ISSUE TITLE
UG/DG index.md filepath appears in search results

### ISSUE THREAD

**Issue by jovyntls** [MarkBind/markbind#1803]
**Tell us about your environment**
MacOS Monterey 12.0.1

* **MarkBind Version:** 3.1.1

**What did you do? Please include the actual source code causing the issue.**
Search for `userGuide/index.md` or `devGuide/index.md` in the MarkBind UG or DG search bar (respectively).

**What did you expect to happen?**
`userGuide/index.md` and `devGuide/index.md` should not appear as search results.

**What actually happened? Please include the actual, raw output.**
<img width="936" alt="Screenshot 2022-03-06 at 7 00 38 PM" src="https://user-images.githubusercontent.com/61113575/156920486-e6f164d2-4fe5-4074-8969-af70a56adfcc.png">

`userGuide/index.md` appears as a search result. Clicking on this result redirects to "Getting Started".

Same for the DG:
<img width="938" alt="Screenshot 2022-03-06 at 7 06 21 PM" src="https://user-images.githubusercontent.com/61113575/156920512-f022cdff-0b3e-4f8a-a1dc-581014ae10fd.png">

It seems weird that `userGuide/index.md` and `devGuide/index.md` appear as search results, since these are filepaths and not page headings or page titles.

**Comment by tlylt** [comment]
Not too sure if it's related, it seems like these pages are also set to `searchable: no`, hence more reason why they should not show up?

![image](https://user-images.githubusercontent.com/41845017/156926383-90bd9e5a-42ef-4631-a113-38d5c082cd06.png)

**Comment by kaixin-hc** [comment]
Thanks for that! Looking at the files more closely, the issue is that index.md and userGuide/index.md are not the same file (and also not the same as devGuide/index.md). I made a quick PR which seems to fix the issue:  #1805

**Comment by jovyntls** [comment]
> EDIT: Actually the search result seems correct to me... it shows a match of page titles, which 'userguide-index' is the title of that index.md page (which happens to be the file path because the title is not specified)

Thanks for looking into this!

Makes sense, I guess this behaviour is correct. I think the user shouldn't see a search result like "userGuide/index.md" though - maybe renaming to fit the other titles (e.g. "User Guide: XXX") would work better?

<img width="502" alt="Screenshot 2022-03-07 at 12 52 26 AM" src="https://user-images.githubusercontent.com/61113575/156933192-5f85c72a-ec22-4a94-aa34-142b85c7d64c.png">

**Comment by damithc** [comment]
> Makes sense, it looks like this behaviour is correct. I think the user shouldn't see a search result like "userGuide/index.md" though - maybe renaming to fit the other titles (e.g. "User Guide: XXX") would work better?

If the author has not specified a tile for that page, are we able to come up with a suitable tile ourselves, in a reliable way? If you fall back on the file name, I think we should at least replace .md with .html?

**Comment by kaixin-hc** [comment]
I think it would be best to make these indexes non-searchable, because  userGuide/index.md is the User Guide: Getting Started page, and devGuide/index.md is the Contributing page.

But I agree with Prof Damith's suggestion that we should auto-format default titles a bit better. I think it would be best to just remove the file format ending.

**Comment by jonahtanjz** [comment]
Reopened for auto-formatting default titles
