### ISSUE TITLE
Markbind documentation for teammates

### ISSUE THREAD

**Issue by kaixin-hc** [MarkBind/markbind#1806]
As discussed during the initial onboarding meeting, one additional goal for Markbind might be to onboard more of the other NUS OSS projects into using markbind for documentation. To this end, and improving upon our product demo of Teammates at the start of this term, we have converted the Teammates developer guide to use markbind.

The [fork's PR is found here:](https://github.com/kaixin-hc/teammates/pull/5) and the sample website is found [here](https://kaixin-hc.github.io/teammates/index.html)

A summary of changes is found in the PR (mainly adaptations made to the documentation to use markbind features and the adding of markbind specific files).

Prof Damith suggested I make an issue so we can draft how we present this website as a group and get feedback from senior developers.

**Draft**

> Hi Teammates team! 
> 
> As discussed previously, we've converted the current developer documentation into a MarkBind website which can be hosted with Github pages directly on the teammates repository.
> 
> The current example of how the developer guide would look can be found at [here](https://kaixin-hc.github.io/teammates/index.html). Maintaining the developer guide should be simple via auto-deployment with Github actions every time a PR is merged with the master. MarkBind is a variant on Markdown, and minor updates to docs can be done with no knowledge of MarkBind. Markbind supports all markdown and git flavoured markdown users are familiar with and is unlikely to make maintaining documentation much harder
> 
> The benefits of using a MarkBind website instead of documents in the github repository are:
> * Easier navigation between different files and a more intuitive understanding of how doc files relate to each other, making it significantly easier to read through the developer docs
> * Enabling of search function in the website to look up relevant documentation
> * No need to manually update "table of contents" as headers in a file change
> * Directly integrate .puml files, instead of saving as image
> * Ability to use MarkBind features such as panels (to hide less relevant information), include (to view information from another relevant file on the same page without duplicating the text), and visual augmentation (tip boxes, emojis, and tool-tips to highlight definitions and key information)
> 
> The possible cons I predict would be
> * Additional barrier to entry when updating documentation, as MarkBind should be installed to check that changes are as reflected. MarkBind is not difficult to learn, but it is an additional thing for new contributors to consider.
> * Additional dependency on MarkBind for developer documentation. As MarkBind is also maintained by NUS, and the original markdown files can be viewed in Github anyway, I think this risk is minimal
> 
> Possible extensions:
> * Including the teammates-ops repository in the developer docs, or converting a separate website for it
> * Incorporating netlify or similar previews to enable PR-previews of documentation (with the con that netlify has a troublesome payment model, and the maintenance of this feature may be more trouble than it is worth)

**Comment by damithc** [comment]
Good work @kaixin-hc Some suggestions:
* Best not to open by saying something negative about the current documentation. That usually put the reader in a defensive mode right away.
* Point to the new section on documentation so that they can see how that aspect will change?
* Can mention that as MarkBind is a variant of Markdown, most minor updates to docs can be done without knowing MarkBind or doing a local preview.
* broken link 
  ![image](https://user-images.githubusercontent.com/1673303/156987134-0ecec83d-01eb-4e50-92bf-7b92cae6bfeb.png)
* For this, I think using a font-based icon e.g., fontawesome is better as the color can be matched to the box type and the graphic will be the same in every browser (emojis' look change based on the browser)
  ![image](https://user-images.githubusercontent.com/1673303/156987400-88bc4aee-5d22-471a-991f-a2c491a0851e.png)

Inputs from others welcome.

**Comment by damithc** [comment]
BTW, the top navigation bar can use the dark theme, to match TEAMMATES own top nav bar? Or better to use a different color to easily distinguish?

You can also add a favicon to match their main site.
![image](https://user-images.githubusercontent.com/1673303/156989694-ac0c5acf-8c27-441b-83ef-3d47ca49daf1.png)


Add something like this (on the right of the logo) to distinguish from the product website?
![image](https://user-images.githubusercontent.com/1673303/156990432-fac9deee-8594-4ce1-9d7b-412b30acff8d.png)

**Comment by jonahtanjz** [comment]
Thanks @kaixin-hc! Overall it looks good. Good job 👍 

Just a couple of suggestions:

* I believe this, in the site-nav, should be "About Teammates" instead:
![image](https://user-images.githubusercontent.com/47470981/158320890-70ccc6b9-b43e-4bb7-9b1f-b989445f0ac5.png)

* For the documentation guide [page](https://kaixin-hc.github.io/teammates/documentation.html), perhaps can add a bit more details in? Right now the guide is a little vague and the tutorial site does not really have a lot of details either. Maybe can include a few examples (can include code and output as well) of the important functionalities such as:
    * Adding new pages
    * Editing the site navigation
    * Deploying the site to Github pages

* Currently the titles in the search are based on their directory and file names. Would be nice to give them more appropriate titles in the `frontmatter` for each of the pages. For example, in the image below, "Best Practices: Coding" would be better.
![image](https://user-images.githubusercontent.com/47470981/158322672-e030a782-bccc-401d-aff7-685a4373b331.png)

**Comment by kaixin-hc** [comment]
Thanks for catching all that! I've made the changes as suggested. Here's the [link to the documentation page](https://kaixin-hc.github.io/teammates/documentation.html) for your convenience.

**Comment by tlylt** [comment]
Closing per https://github.com/TEAMMATES/teammates/pull/11680, great job @kaixin-hc 🎉
