### ISSUE TITLE
Turn on automatic deletion of branches after merge

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1808]
**Is your request related to a problem?**
Currently, the PR branches(located in MarkBind) after merging are not automatically deleted.
Would be useful to auto delete branches, especially from all-contributors-bot, after a contributor update PR is merged.

**Describe the solution you'd like**
Let's turn that repo setting on(if not already done) to keep the branches clean.
Github docs [reference](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches)

**Describe alternatives you've considered**
nil

**Additional context**
nil

**Comment by jonahtanjz** [comment]
Thanks for the suggestion @tlylt. I have enabled the auto deletion of merged branches 👍
