### ISSUE TITLE
Emails are wrongly validated as links

### ISSUE THREAD

**Issue by jovyntls** [MarkBind/markbind#1820]
**Tell us about your environment**
MacOS Monterey 12.0.1
* **MarkBind Version:** v3.1.1

**What did you do? Please include the actual source code causing the issue.**
Place emails in any markdown file, e.g.:
```html
email@gmail.com
student@u.nus.edu
with.dot@mail.sg
```

**What did you expect to happen?**
The emails should not be logged as warnings for invalid intralinks.

**What actually happened? Please include the actual, raw output.**
![Screenshot 2022-03-11 at 8 25 33 PM](https://user-images.githubusercontent.com/61113575/157868105-41cdaa22-feb3-4bd5-9df3-a65ee6d4b467.png)

The email is prepended with a filepath (e.g. `userGuide/mailto:`), which is confusing since this prefix does not appear in the source files at all, and doing a search on `userGuide/mailto:email@gmail.com` will not give any results for an author trying to find where the invalid link is.

This is because `convertRelativeLinks` is called on all links, including emails, so a filepath is prepended onto emails. 
I think a possible fix would be to check for emails (conveniently, they can be identified by a `mailto:` prefix) and not convert them to relative links, and possibly exclude them from `validateIntralink` calls.

**Comment by tlylt** [comment]
I think excluding it altogether would be gd(don't think there's any utility in validating an email address like that)

**Comment by ryoarmanda** [comment]
The email address, as it is a link, is contained as the `href` attribute of an `<a>` node. That prompts `linkProcessor` to do its job on trying to convert relative links from the attribute.

Currently we only have a select conditions that we use to "stop" the conversion, like if it's an URL, a hash, etc. Would be nice if we add a condition to filter out emails too as described.

**Comment by tlylt** [comment]
@jovyntls May I check if #1819 addresses this issue? (also the part on phone numbers), if yes I think we can close this.
