### ISSUE TITLE
Avoid processing nunjucks in fenced code blocks?

### ISSUE THREAD

**Issue by kaixin-hc** [MarkBind/markbind#1835]
I found that including nunjucks code in a fenced code block caused the nunjucks code to disappear:

<img width="1246" alt="fencedcodeblocks nunjucks disappears" src="https://user-images.githubusercontent.com/59471320/158769461-9e06857c-d6b1-4cf3-9b30-d1a13c716036.png">

I believe this is because 'the code is processed for Nunjucks syntax before the rest of the MarkBind syntax are processed'.

**Comment by tlylt** [comment]
This trick in [here](https://markbind.org/userGuide/tipsAndTricks.html#using-raw-endraw-to-display-content) seems to work:
```markdown
{% raw %}{% set title= "your title here" %}{% endraw %}
hello
```
![image](https://user-images.githubusercontent.com/41845017/158771125-171fbb9f-a9b3-4c86-b391-c3de87e602cc.png)

**Comment by damithc** [comment]
> This trick in [here](https://markbind.org/userGuide/tipsAndTricks.html#using-raw-endraw-to-display-content) seems to work:

The documentation of that trick can be made more reader-friendly :-)

**Comment by kaixin-hc** [comment]
Thanks for the fix! Yep, I'll keep including the raw code snippet in mind. In terms of making the trick more reader friendly... maybe the best solution would be to include a similar example + include this tip under the code section of the documentation, maybe in an expandable panel.
