### ISSUE TITLE
Stray space in modal trigger text

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#184]
![image](https://user-images.githubusercontent.com/1673303/38130532-129d1d20-3436-11e8-8f0b-fd21c4d29c66.png)

The code doesn't have such a space.
`[<trigger trigger="click" for="modal:finalSubmission-classDiagram">example</trigger>]`

**Comment by rachx** [comment]
I think you can get rid of the stray space by surrounding it with `md` tags. E.g. 
`<md>[<trigger trigger="click" for="modal:finalSubmission-classDiagram">example</trigger>]</md>`

**Comment by damithc** [comment]
> I think you can get rid of the stray space by surrounding it with `md` tags

That's a useful workaround until we find a solution that is invisible to the author. Thanks @rachx
