### ISSUE TITLE
Remove the use and mention of `<seg>`

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1846]
**Is your request related to a problem?**
There is a mention of `<seg>` in the [Includes](https://markbind.org/userGuide/reusingContents.html#includes) section of the UG. `<seg>` is said to be used similar to `<div>` and `<span>`. However, I can't seem to find any reference of `<seg>` as a valid HTML, and the only thing I can find is this post: https://stackoverflow.com/q/37084310/13725861

Mixing non-HTML elements with other HTML elements could possibly result in invalid HTML markup.

**Describe the solution you'd like**
Perhaps we can remove the mention of this non-HTML element. Doing a brief search in our repo, it also appears in some test cases: `packages\core\test\unit\html\includePanelProcessor.test.js`. These could be replaced as well.

![image](https://user-images.githubusercontent.com/41845017/159445988-217b6fd1-6221-41c2-a8b7-8f0c98cc57c1.png)

**Describe alternatives you've considered**
nil
**Additional context**
nil

**Comment by benluiwj** [comment]
Hello, I would like to contribute to Markbind and I saw this issue with a `good first issue` label and thought this would be a good starting point. Currently I have set up the environment with MarkBind based on the documentation. I have also started to remove the `<seg>` tags as well. However, Webstorm is telling me that there is now repeated code in `includePanelProcessor.test.js`

<img width="1136" alt="Screenshot 2022-07-14 at 2 00 23 PM" src="https://user-images.githubusercontent.com/67570985/178910866-44c5f61f-e1b4-4cc4-a349-0e871850cc7e.png">

**Comment by tlylt** [comment]
> Hello, I would like to contribute to Markbind and I saw this issue with a `good first issue` label and thought this would be a good starting point. Currently I have set up the environment with MarkBind based on the documentation. I have also started to remove the `<seg>` tags as well. However, Webstorm is telling me that there is now repeated code in `includePanelProcessor.test.js`
> 
> <img alt="Screenshot 2022-07-14 at 2 00 23 PM" width="1136" src="https://user-images.githubusercontent.com/67570985/178910866-44c5f61f-e1b4-4cc4-a349-0e871850cc7e.png">

Hi @benluiwj, thank you for contributing:)
Yes, I think that is indeed a duplication. I am not sure of the initial context but my personal take is that slight duplication in the context of unit testing is fine. 
> Instead of  being completely DRY, test code should  often strive to be [DAMP](https://oreil.ly/5VPs2)—that is, to promote "Descriptive And Meaningful Phrases." A little bit of duplication is OK in tests so long as that duplication makes the test simpler and clearer.

See the following chapters from Software Engineering at Google for more explanation
> Make Your Tests Complete and Concise https://abseil.io/resources/swe-book/html/ch12.html#make_your_tests_complete_and_concise
Tests and Code Sharing: DAMP, Not DRY https://abseil.io/resources/swe-book/html/ch12.html#tests_and_code_sharing_dampcomma_not_dr

Besides duplication on its own, if you find that the test cases can be written in a more concise & complete manner, please feel free to raise an issue for discussion :)
