### ISSUE TITLE
Support a shorter syntax for glyphicons

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#185]
Currently we can use [glyphicons](https://getbootstrap.com/docs/3.3/components/#glyphicons) but the syntax is a bit long. 
`<span class="glyphicon glyphicon-search" aria-hidden="true"></span>`

The easier solution is to add all of them as built-in variables e.g., `{{glyphicon-search}}` although our variables don't seem to support dashes at the moment.

**Comment by rachx** [comment]
Currently, we use nunjuck sto resolve `{{baseUrl}}` and user defined variables.

It does a lot more than we currently need (i.e. substituting variables). For example, it supports math operations. Hence `gly-search` is not treated as a string/key. Instead, it is treated as the math minus symbol.

Mustache.js / Handlebars.js might work
