### ISSUE TITLE
Alternative syntax for frontmatter

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1851]
Currently, the frontmatter part appears at the top, when a MarkDown file is viewed on GitHub (through GitHub markdown preview).
Not a big problem, but not pretty either.

e.g.,
![image](https://user-images.githubusercontent.com/1673303/159849473-12e09df0-ced1-4716-84dd-99688d331c46.png)

I wonder if supporting an alternative syntax that is ignored by GitHub rendering is useful. e.g.,

```html
<!-- frontmatter>
title: "Python Basics: Error Handling"
layout: python-layout.md
pageNav: 4
</frontmatter -->
```

**Comment by jonahtanjz** [comment]
We can also consider [markdown-it-front-matter](https://github.com/ParkSB/markdown-it-front-matter), which uses three dashes, `---`, to indicate frontmatter.
```
---
  title: "Python Basics: Error Handling"
  layout: python-layout.md
  pageNav: 4
---
```
Although this will not hide the content of the frontmatter, it will show up nicely in a table format.

![image](https://user-images.githubusercontent.com/47470981/159958817-ce6832f2-ea3f-457c-b969-43bc8140e7fa.png)

**Comment by damithc** [comment]
> We can also consider [markdown-it-front-matter](https://github.com/ParkSB/markdown-it-front-matter), which uses three dashes, `---`, to indicate frontmatter.
> 
> ```
> ---
> title: "Python Basics: Error Handling"
> layout: python-layout.md
> pageNav: 4
> ---
> ```

I like it :+1:  Probably better than what I suggested above.

**Comment by tlylt** [comment]
>

> We can also consider [markdown-it-front-matter](https://github.com/ParkSB/markdown-it-front-matter), which uses three dashes, `---`, to indicate frontmatter.
> 
> ```
> ---
> title: "Python Basics: Error Handling"
> layout: python-layout.md
> pageNav: 4
> ---

[Gatsby](https://www.gatsbyjs.com/docs/how-to/routing/adding-markdown-pages/#frontmatter-for-metadata-in-markdown-files) also uses this syntax.

**Comment by tlylt** [comment]
Somehow managed to find the previous discussion on `<frontmatter>` vs `---` when it was first introduced in this [PR](https://github.com/MarkBind/markbind/pull/175#issuecomment-375567474). Not sure if the previous concerns are still valid.

**Comment by damithc** [comment]
> Somehow managed to find the previous discussion on `<frontmatter>` vs `---` when it was first introduced in this [PR](https://github.com/MarkBind/markbind/pull/175#issuecomment-375567474). Not sure if the initial concerns are still valid.

Thanks for digging that up @tlylt For easier reference, could you also summarize the points raised there?

**Comment by tlylt** [comment]
> > Somehow managed to find the previous discussion on `<frontmatter>` vs `---` when it was first introduced in this [PR](https://github.com/MarkBind/markbind/pull/175#issuecomment-375567474). Not sure if the initial concerns are still valid.
> 
> Thanks for digging that up @tlylt For easier reference, could you also summarize the points raised there?

I think there were a few points highlighted:
- consistency with other markbind syntax (hence `<frontmatter>`)
- concerns about whether the frontmatter and content within frontmatter can be reused/allow for reuse
- concerns about the migration of existing pages that use the old syntax

**Comment by damithc** [comment]
> I think there were a few points highlighted:
> 
> * consistency with other markbind syntax (hence `<frontmatter>`)
> * concerns about whether the frontmatter and content within frontmatter can be reused/allow for reuse
> * concerns about the migration of existing pages that use the old syntax

Thanks for this @tlylt 
If we allow both formats, the first and the last concern will not be affected, but I not sure how much extra work is required to support two formats and if there are other problems caused by doing so.

**Comment by jonahtanjz** [comment]
Another alternative could be a plugin that converts `---` to `<frontmatter>`. This should be quite simple to implement and will not affect point 2.

**Comment by ang-zeyu** [comment]
> Another alternative could be a plugin to convert `---` to `<frontmatter>`. This should be quite simple to implement and will not affect point 2.

Agreed on this.

In addition, `---` is quite a conventional frontmatter syntax that can ease migration / familiarisation with markbind.

Relabelling for now if no other objections / inputs.
