### ISSUE TITLE
Inconsistency with frontmatter vs frontMatter

### ISSUE THREAD

**Issue by kaixin-hc** [MarkBind/markbind#1859]
**Is your request related to a problem?**

Throughout the MarkBind documentation and implementation, both `frontmatter` and `frontMatter` are used. It is not clear which is preferable.

**Describe the solution you'd like**

Ideally, it would be great to standardise the use of one or the other.

Minimally, this page: https://markbind.org/userGuide/siteJsonFile.html should be edited to correct the following typo in the specification for the fields which pages take.
 
> frontMatter: Specifies properties to add to the front matter of a page or glob of pages. Overrides any existing properties if they have the same name, and overrides any front matter properties specified in globalOverride.

The all-lowercase version has to be used, because that is what is supported in site.json .

**Describe alternatives you've considered**

Between changing all the names to follow camelCase or all lowercase, I'm inclined to prefer camelCase for consistency.

Considering that there are many all-lowercase, cases, one could also standardise to all lowercase.

**Additional context**

(Write your answer here.)

**Comment by tlylt** [comment]
I think there's a mixed use of "Front Matter"/ "frontmatter" etc, we can probably keep it all lowercase, and standardize throughout

Some links:
https://mdxjs.com/guides/frontmatter/
https://gohugo.io/content-management/front-matter/
https://www.gatsbyjs.com/docs/how-to/routing/adding-markdown-pages/#frontmatter-for-metadata-in-markdown-files
https://jekyllrb.com/docs/front-matter/

**Comment by vigneshsankariyer1234567890** [comment]
Hey, I would like to take this issue, if it is still open!

**Comment by tlylt** [comment]
Hi @vigneshsankariyer1234567890 please feel free to tackle one of the good first issues to get started, if they are open they should be relevant. Do not do more than one such 'new-comers issue' though...so that others have a chance as well.
