### ISSUE TITLE
Upgrade node.js to v14

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1862]
**Is your request related to a problem?**
According to the [schedule](https://nodejs.org/en/about/releases/), v12 is coming to the end of life at the end of April (about one month later). I think we can put this issue up for tracking (& discussion if any) before we move to v14.

**Describe the solution you'd like**
Upgrade node.js and affected documentation.

**Describe alternatives you've considered**
nil
**Additional context**
nil

**Comment by yhtMinceraft1010X** [comment]
I've done [something similar for RepoSense](https://github.com/reposense/RepoSense/pull/1714) although my aim there is to reach v16. Should we move directly to v16 if we can since v16 has longer support?

**Comment by tlylt** [comment]
Hi Yi Hsuen, at the moment MarkBind is supporting node version according to this point in our [UG](https://markbind.org/userGuide/gettingStarted.html)
![image](https://user-images.githubusercontent.com/41845017/164452586-ae9f682d-87f2-49fa-b68b-9fafc249b5f2.png)
