### ISSUE TITLE
Support generating a timestamp

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#187]
It may be useful to be able insert a timestamp in the generated website.

e.g.,

`{{timestamp}}`
-->
><sub>[Generated by [MarkBind]() at 2018.03.30 22.50.34 UTC]</sub>

**Comment by damithc** [comment]
1. Should we also force-insert this as a footer at the bottom of the landing page of the site generated? Is there something similar in other tools such as mkdocs?
2. May be use `<small>` tag instead of `<sub>`?

**Comment by Chng-Zhi-Xuan** [comment]
1. Other tools (mkdocs, jerkyll) doesn't have timestamp templates nor they force a timestamp.
2. Here are the changes when using `<small>` tag, I feel it looks better too.

`<small>` |
--- |
![timestamp-small](https://user-images.githubusercontent.com/31084833/40225421-8c9c686e-5abb-11e8-86a6-e84aa3e33e1d.PNG) |

**Comment by damithc** [comment]
One approach:
1. When initializing a markbind site, generate a footer.md in the `_markbind` folder. That file will contain out "plug" i.e., the `Generated by ...` 
2. If the `footer.md` is found in the `_markbind` folder, add it to the bottom of every page.

Users can customize the footer.md as they wish and they can delete it entirely if they don't want our footer to appear in their website.
