### ISSUE TITLE
Change checklist to dropdown in issue templates

### ISSUE THREAD

**Issue by jonahtanjz** [MarkBind/markbind#1871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently for the question on "Is there an existing issue for this?", it is using a checkbox.

![image](https://user-images.githubusercontent.com/47470981/161435258-6c99fc81-fe1d-4160-ac84-17d288fc0f72.png)

This creates a "task done" label on the issue.

![image](https://user-images.githubusercontent.com/47470981/161435407-9a1da647-b427-430c-8baf-bf3c588cb495.png)

I feel that this is a little misleading as this is not a task that needs to be done, especially for issues that are using the checkboxes to keep track of the different tasks. 

![image](https://user-images.githubusercontent.com/47470981/161435433-74a8a5c6-5d11-4edc-8f10-e0313fd82bf4.png)

### Describe the solution you'd like

Maybe a dropdown selection will be better in this case? It will output as text instead.

![image](https://user-images.githubusercontent.com/47470981/161435489-e0395756-4af6-4d2e-a9d8-1465754e2d2d.png)

### Additional context

Reference taken from [Gutenberg issue template](https://github.com/WordPress/gutenberg/issues/new?assignees=&labels=&template=Bug_report.yml).

**Comment by tlylt** [comment]
Agree that we can make this tweak.
In a sense, this is a "task" in the same fashion as the "tasks" in our PR issue template. But unlike tasks in a PR, it might indeed cause some confusion if there are other legitimate tasks in an issue.

**Comment by kaixin-hc** [comment]
Yes, I also think this would be a useful change.
