### ISSUE TITLE
Previous/next page boilerplate in MarkBind docs files (DG)

### ISSUE THREAD

**Issue by kaixin-hc** [MarkBind/markbind#1879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Any related issues?

NA

### Tell us about your environment

MacOS Monterey

### MarkBind version

3.1.1

### What did you do? Describe the bug

The MarkBind doc files have the following line copy pasted at the top of most documents: 

`<span id="title" class="d-none">{{ title }}</span>`

I believe this line is unnecessary; deleting it seems to lead to no difference in the served files.

### Anything else?

Does this code actually have utility? It might have been a change made for a previous version that is no longer applicable, or applying some function I didn't see.

Otherwise I propose removing it on all pages.

**Comment by tlylt** [comment]
Could be related to #1847

**Comment by damithc** [comment]
@kaixin-hc do a site-wide search for `#title` to see if this span is being referred to from somewhere.

**Comment by kaixin-hc** [comment]
Thanks @damithc, that helps clarify matters. It seems that it is being used by `common.njk` in order to enable the previous page and next page functionality, and this is included in the User Guide files. However, the line of code is used in the developer guide files, even though this functionality is not being used.

I think to proceed, either the previous and next page formatting should be added to the devGuide files, or these lines of code should be removed in some future commit (partial to the latter as the previous and next buttons must be manually added into the code, which causes additional maintenance costs)

**Comment by tlylt** [comment]
> Thanks @damithc, that helps clarify matters. It seems that it is being used by `common.njk` in order to enable the previous page and next page functionality, and this is included in the User Guide files. However, the line of code is used in the developer guide files, even though this functionality is not being used.
> 
> I think to proceed, either the previous and next page formatting should be added to the devGuide files, or these lines of code should be removed in some future commit (partial to the latter as the previous and next buttons must be manually added into the code, which causes additional maintenance costs)

Having Prev/Next button seems like a good improvement for our DG. Additionally, perhaps we can also consider abstracting these out as components that users can utilize easily.
