### ISSUE TITLE
Searchbar "Code & Example" is not showing

### ISSUE THREAD

**Issue by jovyntls** [MarkBind/markbind#1887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tell us about your environment

MacOS Monterey

### MarkBind version

Any commit from https://github.com/MarkBind/markbind/commit/0e37eafb onwards

### What did you do? Describe the bug

Serve MarkBind locally, and and visit the Search Bar components page (http://127.0.0.1:8080/userGuide/components/navigation.html#search-bars). Under the "Code and Output" section, the code and output are empty.

### Steps to reproduce

Serve the latest version of the master branch of MarkBind locally (not the v3.1.1 release)

### Expected behavior

The "Code and Output" section should display the searchbar component examples. This is screenshot is from our v3.1.1 release:
![image](https://user-images.githubusercontent.com/61113575/162364826-369b4db8-f3cc-45a3-8f5c-41556bc146db.png)

### Actual behavior

Empty "Code and Output" section:
![image](https://user-images.githubusercontent.com/61113575/162364667-1e37170b-59d0-46e2-8989-6df5bb7cc7ac.png)

### Anything else?

Seems to have been introduced in https://github.com/MarkBind/markbind/commit/0e37eafb

**Comment by tlylt** [comment]
The bug is visible in the UG for the latest development branch [here](https://markbind-master.netlify.app/userguide/components/navigation) could be caused by the issue of `span` to `div` replacement if it is affected by the said PR
