### ISSUE TITLE
Off-center NavBar items

### ISSUE THREAD

**Issue by jovyntls** [MarkBind/markbind#1895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tell us about your environment

MacOS Monterey

### MarkBind version

3.1.1

### What did you do? Describe the bug

The NavBar items are not vertically centered. 
![Screenshot 2022-04-12 at 12 43 57 AM](https://user-images.githubusercontent.com/61113575/162790617-0d6946cc-c60f-4d48-9134-73850d72137b.png)

Annotated image: The centreline of the site logo (red box) should align with the centre of the NavBar items (blue box). However, the nav items are a little too low.

![Screenshot 2022-04-12 at 12 43 57 AM 2](https://user-images.githubusercontent.com/61113575/162790976-434e477e-acd0-4ba4-bb38-6ac8d8fe8a7b.png)

### Steps to reproduce

Open MarkBind in a window that is small enough such that the lower navbar appears, but large enough such that the NavBar remains expanded (items don't collapse into a new row).

### Expected behavior

Site logo and nav items should be vertically centered. Green box shows the correct (vertically centered) position of the nav items: 
![Screenshot 2022-04-12 at 12 43 57 AM 2](https://user-images.githubusercontent.com/61113575/162791506-f7fe1877-a45a-4035-b323-327774c6fb25.png)

### Actual behavior

(Screenshot above)

**Comment by ong6** [comment]
Wow, nice spot! Also the menu bar directly below the logo looks like its not aligned in the center of the white space too.
