### ISSUE TITLE
Allow setting of customized 404 page

### ISSUE THREAD

**Issue by jovyntls** [MarkBind/markbind#1899]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Reader Usability

### Is your feature request related to a problem? Please describe.

Currently, when a user visits a broken link, they are served a 404 page from the hosting service (e.g. Github Pages, Netlify).

<table>
<tr>
	<td>e.g. for Github Pages:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/61113575/162902886-bdcd8ff8-6b71-4fc8-9484-fc8cc5edcb86.png">
	<td>e.g. for Netlify:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/61113575/162903075-1557803c-2e04-4f78-8c0f-1de794315823.png">
</table>

This is a little jarring for users. The site would also look more polished if it had its own 404 page without exposing a "view" from its hosting service.
 

### Describe the solution you'd like

I think it could be a nice touch to allow for a custom 404 page served to users that visit a broken link on the site! Many static site generators (e.g. [in Gatsby](https://www.gatsbyjs.com/docs/how-to/adding-common-features/add-404-page/), [Hugo](https://gohugo.io/templates/404/), [Jekyll](https://jekyllrb.com/tutorials/custom-404-page/)) allow authors to create a custom `404.html` page that is served to readers when they visit an invalid link on the site.

### Describe alternatives you've considered

Allow authors to automatically redirect invalid links to a specified page. However, I think this may be confusing for readers.

**Comment by jovyntls** [comment]
> I think this idea is great. We can either add a default `404.md` file (always there) which users can configure to create their own `404.html`, or have the default `404.html` constructed behind the scene and if a user wishes to customize it, they can choose to create a `404.md` file.
> 
> Edit: Hmm in a sense this feature is already supported (as in if a user would want to create a custom 404 page they can, but we are not providing one as a default at the moment)? I think if that's the case we can at least document it.

Thanks for looking into this! I agree, I think we can provide a default `404.md` and document: 1) how users can customise this file, 2) a way for users to choose another file to use as their `404.md`.

**Comment by EltonGohJH** [comment]
@tlylt 
I am keen to give this a try.
You mention that this feature is already supported. I attempted to create a 404.md but it does not go to that page when I go to another broken link. Is it possible for you to kindly point me to the right direction?

> Edit: Hmm in a sense this feature is already supported (as in if a user would want to create a custom 404 page they can, but we are not providing one as a default at the moment)? I think if that's the case we can at least document it.

**Comment by ang-zeyu** [comment]
> Currently, when a user visits a broken link, they are served a 404 page from the hosting service (e.g. Github Pages, Netlify).

@EltonGohJH is this on the local development server? Iirc there isn't any routing logic inside it to redirect to a 404.html (maybe we can add it in sometime), try one of these ^ if possible for now.

You can adapt our `deploy-docs` job inside `.github/workflows/ci.yml` for your fork, or create a minimal site with `markbind build` on another repo (w/ github pages / netlify).

**Comment by EltonGohJH** [comment]
@ang-zeyu 
I was quoting @tlylt on the routing logic. 
I see. So, there is no routing logic now. I am still quite lost so I am suppose to implement the 404.html routing for this issue?

"You can adapt our deploy-docs job inside .github/workflows/ci.yml for your fork, or create a minimal site with markbind build on another repo (w/ github pages / netlify)."
Can I clarify what you mean by this?

**Comment by ang-zeyu** [comment]
> I was quoting @tlylt on the routing logic.

Apologies for the misleading quote, my reply follows @tlylt and your reply as well. The quote is just info from OP for your understanding. 

> I see. So, there is no routing logic now. I am still quite lost so I am suppose to implement the 404.html routing for this issue?

You don't need to implement the routing for this issue, rather just what @tlylt and @jovyntls described ⬇️:

>  a default 404.md file (always there) which users can configure to create their own 404.html

> 1) how users can customise this file, (document in ug) 2) a way for users to choose another file to use as their 404.md.

Though, I prefer to hold off on @jovyntls's 2nd extension until we find there's a tangible need for it.

I think minimally, we could add such a `404.md` into the default template sites (inside `packages/core/template`) and document it.

Routing in production is something that is out of our control (depends on your static site host + configuration over there), although the convention usually is that such servers would automatically route to a "404.html".

Implementing routing for our development server is do-able (and perhaps somewhat useful for the author), but much lower priority. It would be quite complex as well as we currently have a fair bit of custom routing logic that involves quite a few application requirements surrounding the `markbind serve -o` option: https://github.com/MarkBind/markbind/blob/master/packages/cli/src/lib/live-server/index.js (though, feel free to dig around if you have the time!)

**Comment by tlylt** [comment]
@EltonGohJH sorry for the late reply. Yes, @ang-zeyu 's comment above is what I meant. The routing to 404.HTML logic is usually a "supported" default of popular static hosting services, so I was referring to the fact that on our end, we can provide a template and/or documentation to guide users in creating a 404 page if required. The routing logic is not handled.

**Comment by EltonGohJH** [comment]
@tlylt 
Thanks for the help.  I initially thought that we already supported routing to 404 html locally. Sorry for the confusion. On hindsight, I should have realised that you were referring to the fact that 404.html routing is supported by the hosting services.
