### ISSUE TITLE
PUML not working on CI deployment (Teammates) due to lack of graphviz

### ISSUE THREAD

**Issue by kaixin-hc** [MarkBind/markbind#1903]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

See [Teammates issue](https://github.com/TEAMMATES/teammates/issues/11732) and [reposense issue](https://github.com/reposense/RepoSense/issues/1759)

### Tell us about your environment

Live Deployed version

### MarkBind version

3.1.1

### What did you do? Describe the bug

After deployment, puml diagrams seem to be missing and have thrown an error.
![image](https://user-images.githubusercontent.com/59471320/163318797-3e6c8fef-e9e8-41a1-bc7a-441b32b55c13.png)

### Steps to reproduce

Unable to reproduce manually on local serve or on manual deployment on a forked branch

### Expected behavior

.puml diagrams should display

### Anything else?

Hypothesis: This is related to CI, and building .puml files during CI is the problem. CI may not have graphviz.

Observation: For MarkBind docs puml diagrams, we **actually never use the <puml> tags within the website**. Instead, we have saved the .puml as equivalent .pngs, and displayed the .png instead (see `diagrams.md`) Found this PR #917 explaining the reason is to avoid installing graphviz.

Graphviz related .puml errors: #1459, and the reposense: [#1406 Replace images as PUML diagrams PR](https://github.com/reposense/RepoSense/pull/1406) leading to #916 which was marked as fixed. Also consider reposense [1427 on the PUML diagrams not rendering](https://github.com/reposense/RepoSense/issues/1427)

Suggestions? What should we do about this issue?

**Comment by tlylt** [comment]
Putting some details of the investigation that I have done here for reference:
- Graphviz does not seem to be required for sequence and activity diagrams, so it should be fine for anyone to refer to .puml files directly in CI (They might still need to ensure that Java is available for puml plugin to work). This is mentioned in the original [puml PR](https://github.com/MarkBind/markbind/pull/887#pullrequestreview-254595590), but was requested to change to "all diagrams", which is what we state in our UG at the moment. Perhaps we should consider specifying it as is (that some diagrams work out of the box)
  - ![image](https://user-images.githubusercontent.com/41845017/163331949-bf92fccc-fa66-41e4-b499-cb9c65499700.png)

**Comment by damithc** [comment]
Thanks for the investigation so far @tlylt 
The ideal would be to support _all_ PUML diagrams on GitHub Actions, if there is a way to do that. Otherwise we have to ask users to save a copy of the generate images locally, which goes against our claim of supporting PUML out of the box.

**Comment by tlylt** [comment]
> Thanks for the investigation so far @tlylt The ideal would be to support _all_ PUML diagrams on GitHub Actions, if there is a way to do that. Otherwise we have to ask users to save a copy of the generate images locally, which goes against our claim of supporting PUML out of the box.

Yes @damithc, I just tested it and it seems like as long as we do install java and Graphviz on CI (which is doable), then the images will be generated accordingly. I will drop a message in teammates' repo to ask if they wish to have this done (modifying the CI script) or hosting the images (the current changes by @kaixin-hc)

I think on our end we do need to put in a note in our deploy section, to inform users that if they are using puml diagrams, especially if they do continuous integration, they will have to ensure that their CI environment satisfy the required dependencies (Java and Graphviz).

**Comment by damithc** [comment]
> Yes @damithc, I just tested it and it seems like as long as we do install java and Graphviz on CI (which is doable), then the images will be generated accordingly. I will drop a message in teammates' repo to ask if they wish to have this done (modifying the CI script) or hosting the images (the current changes by @kaixin-hc)
> 
> I think on our end we do need to put in a note in our deploy section, to inform users that if they are using puml diagrams, especially if they do continuous integration, they will have to ensure that their CI environment satisfy the required dependencies (Java and Graphviz).

Great. Thanks for the quick action @tlylt

**Comment by wkurniawan07** [comment]
> Given that we do not install Graphviz in our CI environment, in fact our existing functional tests (in test_site) are "broken". Some of the puml images generated are broken but because they are still generated and we only compare existence of the files, we thought that those files are generated correctly, when they are not (they are images containing similar error as the screenshot in the issue description).

If I may add, the fact that this does not fail the CI build is itself a red flag.

**Comment by ang-zeyu** [comment]
Related to #1863.

In short, we've been (again presumably - I don't have context) prioritising usability of `markbind serve` over this.

@tlylt referring to https://github.com/MarkBind/markbind/pull/1245#issuecomment-1101084722 as well, we can also aim to keep the current behaviour for `markbind serve` (show the puml error image), but fail hard for `build`. (for consistency with the `createErrorNode` function)

> Given that we do not install Graphviz in our CI environment, in fact our existing functional tests (in test_site) are "broken". Some of the puml images generated are broken but because they are still generated and we only compare existence of the files, we thought that those files are generated correctly, when they are not (they are images containing similar error as the screenshot in the issue description).

Iirc this was discussed and acknowledged verbally (or maybe in some PR 👀) among us 2 years back. The rationale (not too big of an issue) is as we aim to test only the _file paths_ we supply to the puml process.

Having the puml images error out would still generate error images, which is plenty sufficient for verifying said file paths. (we assume puml would do its things correctly, and leave testing that to the puml team)

In the case of graphviz errors, we assume the author has knowledge that it is required, which we've also documented quite clearly since the original PR by @alyip98.

https://markbind.org/userGuide/components/imagesAndDiagrams.html#diagrams

**Comment by kaixin-hc** [comment]
Based on the work done on this issue + the two original issues that flagged now being fixed, I think this issue can be closed now. If anyone else has any thoughts on this, let me know : )
