### ISSUE TITLE
Fully adapt core package and associated tests to TypeScript

### ISSUE THREAD

**Issue by ryoarmanda** [MarkBind/markbind#1913]
**(Updated as of 21/04/2022)**

This is an epic-type issue to track of our TypeScript migration of the `core` package. Feel free to edit this as we go along.

Interested migration developers can get started by checking out the [Migrating to TypeScript](https://markbind.org/devdocs/devGuide/migratingToTypeScript.html) page in our developer's guide.

## Dependency graph of remaining `js` files

(There are some files not presented that are still under consideration on whether to be adapted to TypeScript or leave as-is)

Click the image to view it all full resolution:

![graph](https://user-images.githubusercontent.com/24468110/164284427-54953286-eede-4c62-9a02-31c25508e1fc.png)

The green files are ones that do not have any _static_ dependencies to another file and are **highly recommended** to migrate first. However, the graph is not 100% accurate, as there are green files that have _dynamic_ imports (like in Plugin.js) or have constants documented to be typed as other files' classes (like PageConfig.js and SiteConfig.js)

## Which one should I adapt first?

As mentioned, it is **highly recommended** that we go through files that do not have any dependencies, and collectively work through the dependency graph upwards until the root, meaning that we perform the migration in topological order.

> Though possible to migrate not in topological order, the effort will be much more as you have to be able to infer simple types as a "stand-in" of the dependencies that are not yet migrated.

You can adapt multiple _related_ files residing in the same folder in one migration. For example, you might adapt Plugin.js and PluginManager.js together.

Note that when you adapt a file, you also have to adapt the associated tests as well. For example, adapt linkProcessor.js together with  linkProcessor.test.js.

## Files checklist

(There are some files not presented that are still under consideration on whether to be adapted to TypeScript or leave as-is)

### package root

- [x] index.js

### `src`

- [x] errors (#1877)
  - [x] CyclicReferenceError.js
  - [x] index.js
- [x] External
  - [x] External.js
  - [x] ExternalManager.js
- [x] html
  - [x] codeblockProcessor.js
  - [x] constants.js
  - [x] Context.js
  - [x] elements.js
  - [x] FootnoteProcessor.js
  - [x] headerProcessor.js
  - [x] includePanelProcessor.js
  - [x] linkProcessor.js
  - [x] MarkdownProcessor.js
  - [x] MdAttributeRenderer.js
  - [x] NodeProcessor.js
  - [x] scriptAndStyleTagProcessor.js
  - [x] siteAndPageNavProcessor.js
  - [x] SiteLinkManager.js
  - [x] vueSlotSyntaxProcessor.js
  - [x] warnings.js
- [x] Layout (partial work done in this closed PR https://github.com/MarkBind/markbind/pull/2164)
  - [x] index.js
  - [x] Layout.js
  - [x] LayoutManager.js
- [x] Page
  - [x] index.js
  - [x] PageConfig.js
  - [x] PageSources.js
  - [x] PageVueServerRenderer.js
- [x] lib/markdown-it
  - [x] index.js
  - [x] utils/index.js
  - [x] highlight directory
  - [x] plugins/markdown-it-icons
  - [ ] the rest are plugins that has a huge proportion (> 95% source) adapted from somewhere, we originally discussed not to adapt to maintian easy reference. They are also fairly isolated so benefits of TS may not be that great. But this is revisitable.
- [x] plugins
  - [x] Plugin.js
  - [x] PluginManager.js
  - [x] all the plugins (feel free to expand it on an edit)
	- [x] algolia.js
	- [x] disqus.js
	- [x] filterTags.js
	- [x] googleAnalytics.js
	- [x] mathDelimiters.js
	- [x] codeBlockCopyButtons.js
	- [x] codeBlockWrapButtons.js
	- [x] default
		- [x] markbind-plugin-plantuml.js
		- [x] markbind-plugin-anchors.js
		- [x] markbind-plugin-shorthandSyntax.js
		- [x] markbind-plugin-tree.css
		- [x] markbind-plugin-tree.js
- [x] Site
  - [x] constants.js
  - [x] index.js
  - [x] SiteConfig.js
- [x] utils (#1877)
  - [x] async.js
  - [x] delay.js
  - [x] fsUtil.js
  - [x] git.js
  - [x] logger.js
  - [x] urlUtil.js
- [x] variables
  - [x] VariableProcessor.js
  - [x] VariableRenderer.js
- [x] constants.js

### `template`

- [x] template.js

### `test/unit`
- [x] `html`
	- [x] includePanelProcessor.test.js
	- [x] linkProcessor.test.js
	- [x] NodeProcessor.data.js
	- [x] NodeProcessor.test.js
	- [x] SiteLinkManager.test.js
- [x] `plugins/default`
	- [x] anchor.test.js
	- [x] plantuml.test.js
	- [x] shorthandSyntax.test.js
	- [x] tree.test.js
- [x] `lib/nunjucks-extensions`
	- [x] nunjucks-date.test.js
	- [x] set-external.test.js
- [x] `utils`
	- [x] data.js
	- [x] utils.js
- [x] markdown-it-icons.test.js
- [x] Site.test.js

**Comment by ang-zeyu** [comment]
@MarkBind/active-devs please help to tackle this ticket if you are interested. Just check any unchecked boxes above, and start implementing away.

Type safety is a very nice prequisite to have to performing larger scale refactors, and can serve as good documentation in of itself. Amongst many other things.

**Comment by raysonkoh** [comment]
3281 students feel free to help tackle this too! I think it isn't very difficult and it would be a great way to learn the codebase and suggest ways in which it can be improved.

Process-wise, in order to prevent a conflict in work done, you can either open a `WIP` draft PR, or update the list above with your name.

**Comment by yiwen101** [comment]
Could I have a try; I wish to try completing the #2164 , migrate the layout to typescript

**Comment by yiwen101** [comment]
Migration completed excepts for plugins that were decided to not migrate to typescript.
