### ISSUE TITLE
Screenshots of the sample configurations for WebStorm are blurry 

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1916]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

Master branch

### What did you do? Describe the bug

Visit the dev guide, found a few images in the modal are blurry

### Steps to reproduce

https://markbind.org/devdocs/devGuide/workflow.html
Click on "WebStorm"

### Expected behavior

Images not blurry

### Actual behavior

![image](https://user-images.githubusercontent.com/41845017/165329568-fec5a48e-998e-4f6d-bc9e-0e97bf6c3e8f.png)

### Anything else?

Side note:
- [x] When the modal is triggered, the scroll bar appears to come about from the center of the screen and shifts immediately to the right, a little weird to see that.

**Comment by kaixin-hc** [comment]
<img width="1463" alt="Screenshot 2024-03-03 at 11 37 56 PM" src="https://github.com/MarkBind/markbind/assets/59471320/412f2107-38a0-48da-bde2-ee4cce36a0df">
<img width="1419" alt="Screenshot 2024-03-03 at 11 38 33 PM" src="https://github.com/MarkBind/markbind/assets/59471320/47803bb3-ed1c-4823-894d-b93c3050e3c7">

Cannot replicate on Chrome or Firefox...

**Comment by kaixin-hc** [comment]
Closing due to being unable to replicate for now

**Comment by tlylt** [comment]
@kaixin-hc it's still burry for me on Windows 10 Chrome: 
![image](https://github.com/MarkBind/markbind/assets/41845017/8ba27bb1-11a3-4a56-a307-9847fc425154)

**Comment by yucheng11122017** [comment]
@tlylt @kaixin-hc mine looks ok on windows 10 chrome
![image](https://github.com/MarkBind/markbind/assets/77204346/d9bcc1fc-2abb-4bb1-a846-35e84bf7385b)

**Comment by EltonGohJH** [comment]
@tlylt @kaixin-hc 
Same on my end too. (Windows 11 Firefox)
![image](https://github.com/MarkBind/markbind/assets/75515229/4f3802f3-4746-4310-a1de-40eda56964c7)

**Comment by tlylt** [comment]
> @tlylt @kaixin-hc mine looks ok on windows 10 chrome
> 
> ![image](https://github.com/MarkBind/markbind/assets/77204346/d9bcc1fc-2abb-4bb1-a846-35e84bf7385b)
> 

Hmm in that case maybe it's my monitor's resolution/aspect ratio causing this, ok to close since others don't have this issue.
