### ISSUE TITLE
Untidy tail in tooltips/popovers

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1969]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

n/a

### MarkBind version

4.*

### What did you do? Describe the bug

Tooltips and popovers have an untidy tail 

![image](https://user-images.githubusercontent.com/1673303/179789691-fc06fb42-672d-46a8-9d77-45ca276a0279.png)

### Steps to reproduce

Possibly related to V4 (i.e., Bootstrap 5) as this only started after upgrading MarkBind to V4

### Expected behavior

-

### Actual behavior

-

### Anything else?

-

**Comment by tlylt** [comment]
Looks like it's expected behavior due to improved a11y 
- https://github.com/Akryum/floating-vue/issues/848
