### ISSUE TITLE
Search results show the same thing in both columns

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1972]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

n/a

### MarkBind version

v4.*

### What did you do? Describe the bug

The two columns of the search results almost always show the exact same content? Is that intended?
![image](https://user-images.githubusercontent.com/1673303/180277500-e394a1d1-8e9a-4ea5-9880-463d632f0c7f.png)

### Steps to reproduce

Go to https://markbind.org/ and search for some keywords using the search feature of the site.

### Expected behavior

-

### Actual behavior

-

### Anything else?

-

**Comment by ang-zeyu** [comment]
- noting as well we can defer / improve this in #205 (e.g. display preview of body text)
- or some quick fixes:
  - fully expand the (left) heading to fill the entire row (might be visually inconsistent if there are keywords though)
  - use an "..." ellipses
  - ❔👀
