### ISSUE TITLE
Support bootstrap built-in icons

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1977]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Author Usability

### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like

Unlike previous versions, Bootstrap 5 comes with built-in icon support. Now that we have moved to Bootstrap 5, shall we extend our icons feature to cover Bootstrap icons as well?

**Comment by kaixin-hc** [comment]
Closed by #2494
