### ISSUE TITLE
Existing screenshots of the code copy & wrap functionalities are outdated

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1982]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#1949

### Tell us about your environment

Windows 10

### MarkBind version

4.0.0

### What did you do? Describe the bug

What's described in UG:
- https://markbind-master.netlify.app/userguide/usingplugins#plugin-codeblockcopybuttons
![image](https://user-images.githubusercontent.com/41845017/182295814-677c3c64-a72b-47b5-be33-1d7b1b020780.png)

Actual:
![image](https://user-images.githubusercontent.com/41845017/182295544-ed7b0d29-b19b-4adf-b13f-b734560c9c0a.png)

### Steps to reproduce

Try the following on a test MarkBind site.
1. Add the following to the `site.json`
```
  "plugins": ["codeBlockWrapButtons", "codeBlockCopyButtons"],
```
2. Add a sample code block:
```
**A `code` example:**

```html
<foo>
  <bar type="name">goo</bar><bar type="name">goo</bar><bar type="name">goo</bar><bar type="name">goo</bar><bar type="name">goo</bar><bar type="name">goo</bar><bar type="name">goo</bar><bar type="name">goo</bar>
</foo>
```

### Expected behavior

UG to describe the behavior of the buttons accurately.

### Actual behavior

Screenshots are outdated.

### Anything else?

Likely a leftover from #1949, (@elroygohjy feel free to pick this up if you are interested 🦾)

**Comment by domlimm** [comment]
Hello @tlylt! I could pick this up if no one is going to 👍🏻
