### ISSUE TITLE
Explore using Turborepo to improve build system

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1984]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Other

### Is your feature request related to a problem? Please describe.

Nothing specific, but thought that we could explore using [turborepo](https://github.com/vercel/turborepo) for the benefit of task running and caching.
https://turborepo.org/docs/guides/migrate-from-lerna
![image](https://user-images.githubusercontent.com/41845017/182345719-4200ea63-25a5-4073-b948-5862857dc108.png)

### Describe the solution you'd like

Adopt Turborepo if useful

### Additional context

Lerna, which I thought is no longer an active project, (hence the incentive to try out new monorepo toolings) appears to be back again:
https://blog.nrwl.io/lerna-5-1-new-website-new-guides-new-lerna-example-repo-distributed-caching-support-and-speed-64d66410bec7

**Comment by ong6** [comment]
I think it's a good idea to make the switch to Turborepo as well.

Heres is my reasoning:
1. Turborepo's task scheduler is more powerful than Lerna's. Hence, Turborepo reduces idle CPUs and leads to faster overall builds.
2. Has a more active community than Learna atm and has really good documentation. 
3. Super easy to setup and use + a easy way to migrate from Learna

**Comment by EltonGohJH** [comment]
Related to #2162 (Lerna depdendencies being outdated for Node 19)

Since Lerna is now an active project and has cool new features. Moreover, it has an updated task scheduler with nx too. It should be easier to update from Lerna 4 to Lerna 6 than Turborepo so we should explore that instead.

**Comment by raysonkoh** [comment]
@EltonGohJH, might be good to also explore using [NPM workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) too and see if it is worth switching. 

Context: https://lerna.js.org/docs/features/legacy-package-management

> However, now that we find ourselves in late 2022, the fact is that - for many years now - the package managers we know and love (npm, yarn and pnpm) all fully support that concept of workspaces as a first-class use-case.
... lead maintainer of Lerna, Daniel, has been encouraging folks to strongly reconsider their use of the legacy package management commands in lerna, and instead leverage their package manager of choice to do what it does best.

**Comment by EltonGohJH** [comment]
@raysonkoh 
NPM workspaces is interesting. I will look into that too! Thank you so much!

**Comment by EltonGohJH** [comment]
@raysonkoh 
Do you mean completely switching to npm workspaces or use Lerna alongside with workspaces.
From that article, Lerna actually wants us to stop using their deprecated options and use workspaces alongside of Lerna.

I think since the deprecated options will be deprecated in Lerna 7 and workspaces seems easy to setup. I see no reason to not update Lerna and while doing so update to use workspaces too.

**Comment by raysonkoh** [comment]
>  Do you mean completely switching to npm workspaces or use Lerna alongside with workspaces.

I was thinking of completely switching to npm workspaces, because it seems that workspaces is able to do the things that we are using Lerna to do currently (i.e. linking packages, hoisting dependencies, etc). 

I think that with Lerna v7 the new features are mainly speed-related like better caching (correct me if I'm wrong), so at most it is going to have limited benefits on Markbind. Wdyt?

**Comment by EltonGohJH** [comment]
@raysonkoh 
I think nothing we are currently using is exclusive to Lerna. From what I read, npm workspaces support versioning and publishing to npm. I do think that Lerna makes it slightly easier to do so.

I have no idea how good the benefits of caching would be. I would be okay to explore. Honestly, I am kinda curious lol. Idm setting it up and if it is bad then we just go workspaces.

**Comment by raysonkoh** [comment]
Go for it @EltonGohJH! After experimenting a little we should be able to decide on:

1. Adopt workspaces & update Lerna to v7
2. Adopt workspaces and remove Lerna completely
3. (If (1) and (2) doesn't work for some reason) Find an alternative (like Turborepo?)

Whatever we decide on, it should at least be able to do:

- Linking of packages in monorepo
- Hoisting dependencies
- Versioning
- Publishing to npm
