### ISSUE TITLE
Essay questions: make the system message less prominent

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1998]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Reader Usability

### Is your feature request related to a problem? Please describe.

For essay questions, if there are no keywords, MarkBind shows the following message.
![image](https://user-images.githubusercontent.com/1673303/183809731-d280c58e-8ede-49af-8951-c07bf28a0dbd.png)

This message can appear more prominent than necessary, and might lead the reader to think something is wrong with the question.

### Describe the solution you'd like

Perhaps we omit that text altogether when there are no keywords provided.

**Comment by petermonky** [comment]
May I investigate this issue? 🙂

**Comment by tlylt** [comment]
> May I investigate this issue? 🙂

Sure 🚀
