### ISSUE TITLE
Optimize panel headers for printing

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#20]
Panel headers like this should be omitted from printing?
![image](https://cloud.githubusercontent.com/assets/1673303/24536570/d0cced9a-160d-11e7-983e-a2f092abe0df.png)

If expanded, the content should be printed but this heading should be omitted. 

Not sure if that is possible though.

**Comment by acjh** [comment]
We support an `alt` header to be used with the `minimized` attribute.

Resolved by [MarkBind/vue-strap@`43c8781`](https://github.com/MarkBind/vue-strap/commit/43c8781d2136ac5df893278d5cc547bcc6615c11#diff-cff700652fe9809decde1530de718713R63)

Current version: https://markbind.github.io/vue-strap/#accordion
