### ISSUE TITLE
Search bar overflows on mobile devices

### ISSUE THREAD

**Issue by jonahtanjz** [MarkBind/markbind#2002]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

4.0.0

### What did you do? Describe the bug

Go to https://markbind-master.netlify.app/index.html on mobile devices, the search bar exceeds the screen width.

![image](https://user-images.githubusercontent.com/47470981/184059867-80c0893a-c6b7-45e6-a77d-60609fbfe21f.png)

Let's try to resolve this before releasing 4.0.1.

### Steps to reproduce

Most likely due to setting a [`min-width` in `Searchbar.vue`](https://github.com/MarkBind/markbind/blob/master/packages/vue-components/src/Searchbar.vue#L266)

### Expected behavior

Search bar should not overflow

### Actual behavior

Search bar exceeds the screen width as shown above.

**Comment by domlimm** [comment]
Hello, may I please pick this issue up?

**Comment by jonahtanjz** [comment]
@domlimm Sure. Thanks for taking this :)

**Comment by domlimm** [comment]
Hey @jonahtanjz, is https://markbind-master.netlify.app/index.html the deployed `master` branch? I think the prod one is https://markbind.org/? Thank you!
