### ISSUE TITLE
FOUC in navbar due to search bar

### ISSUE THREAD

**Issue by jonahtanjz** [MarkBind/markbind#2003]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

4.0.0

### What did you do? Describe the bug

When navigating between pages, you can see that the navbar height expands first and then revert back to original size.

https://user-images.githubusercontent.com/47470981/184063267-20ea4c6b-7bd1-42eb-b392-62361b6e7d34.mp4

### Steps to reproduce

1. Go to https://markbind-master.netlify.app/userguide/gettingstarted
2. Navigate between the pages (especially between developer guide and user guide)
3. See the FOUC in the navbar

### Expected behavior

Navbar height remains the same

### Actual behavior

Navbar height changes during loading

### Anything else?

Most likely related to https://github.com/MarkBind/markbind/pull/1959#pullrequestreview-1041138318

**Comment by ang-zeyu** [comment]
@tlylt @jonahtanjz on a related note to FOUC, I worked on the second item in https://github.com/MarkBind/markbind/issues/1948 a while back but haven't had the time to finish verifying it.

The diff is [here](https://github.com/MarkBind/markbind/commit/b4eeb115daa9235146ea308632cb9f81636a4205), if anyone  is interested in completing it. 🙂 

It works by:
- always rendering the lower navbar
- using css to hide/show it in mobile naturally as needed (if there are no buttons inside then it naturally collapses to 0 height)
- at SSR + build time, do the detection of whether the site/page nav is present in the page and render the site / page nav buttons accordingly
- also use css to hide/show it in desktop vs mobile

**Comment by ang-zeyu** [comment]
@MarkBind/active-devs 
As a general rule of thumb, try to avoid/reconsider style detection in things that show upfront to the user during PRs unless absolutely necessary (so far there is often always a solution). Not very nice for UX.

Things like tooltips / modals / search dropdowns that show only after-interaction is mostly fine on the contrary since they require user interaction after the page has loaded and style detection has already run.
