### ISSUE TITLE
Longer Modal closes unexpectedly when interacting with the scrollbar

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2013]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#1909

### Tell us about your environment

Windows 10

### MarkBind version

4.0.0

### What did you do? Describe the bug

After the dual-modal issue is fixed, there's another problem of auto closing modal after an interaction with the scrollbar. This is less obvious as users can scroll via the mouse scroll wheel, which works fine.

### Steps to reproduce

- Open a modal with content longer than a page, which will render the scroll bar
- Click or drag the scrollbar
- See that the modal auto closes

Examples described below,

### Expected behavior

Seeing from one of the previous deployment previews, users can  use the scrollbar
https://deploy-preview-1795--markbind-master.netlify.app/userguide/syntaxcheatsheet
![w87Sl6rPX9](https://user-images.githubusercontent.com/41845017/185098480-84c79e68-354d-49d8-a658-b5ea30356ddd.gif)

### Actual behavior

https://deploy-preview-2012--markbind-master.netlify.app/userguide/syntaxcheatsheet
Modal auto closes once user releases his/her click on the scrollbar
![mqQoIkVh81](https://user-images.githubusercontent.com/41845017/185099011-d9c69fc8-7d0f-4f64-8d4b-669a90ba8426.gif)

the

**Comment by jonahtanjz** [comment]
Looks like this is related to [`vue-final-modal`'s click-to-close feature](https://vue-final-modal.org/guide/properties#click-to-close). Somehow the overlay extends over the scroll bar which triggers the above function when it is clicked.

**Comment by domlimm** [comment]
Hello guys! If no one's picking this up, I'd love to try and explore on this 👍🏻

**Comment by WillCWX** [comment]
hello @domlimm , are you still working on this issue?

**Comment by domlimm** [comment]
@WillCWX hey! Thanks for checking! Sorry I'm not, please go ahead thanks!

**Comment by WillCWX** [comment]
> @WillCWX hey! Thanks for checking! Sorry I'm not, please go ahead thanks!

Ok, thanks for the quick reply!

Hello @tlylt , can I be assigned this issue? Or would it be better to wait for vue3 migration?

**Comment by tlylt** [comment]
> > @WillCWX hey! Thanks for checking! Sorry I'm not, please go ahead thanks!
> 
> Ok, thanks for the quick reply!
> 
> Hello @tlylt , can I be assigned this issue? Or would it be better to wait for vue3 migration?

sorry for the late reply, it doesn't have to wait for vue3 migration.

**Comment by WillCWX** [comment]
> Looks like this is related to [`vue-final-modal`'s click-to-close feature](https://vue-final-modal.org/guide/properties#click-to-close). Somehow the overlay extends over the scroll bar which triggers the above function when it is clicked.

Sort of, the way the `click-to-close` works is that any pointer event in the `modal container` closes the entire modal. This includes the scroll bar as the `allow-overflow` css class is applied to the `modal container`. To prevent the modal from closing when clicking on the content, the `.modal-dialog` css class found in the `modal content` contains `pointers-event:none`.

I think we can just move the scrollbar / `allow-overflow` css class to the `modal content`, which will also fix the side note of #1916 as the scroll bar will no longer move to the side. 
![image](https://github.com/MarkBind/markbind/assets/55905659/6f5196e3-2ed6-4c21-b26e-666f0071d89d)
_the white bar is from snip and not from the website_

[link to vfm vue2 documentation](https://web.archive.org/web/20211203202729/https://vue-final-modal.org/guide/properties/#content-class)

Would this be ok?

**Comment by yucheng11122017** [comment]
> I think we can just move the scrollbar / `allow-overflow` css class to the `modal content`, which will also fix the side note of #1916 as the scroll bar will no longer move to the side. ![image](https://user-images.githubusercontent.com/55905659/249489491-6f5196e3-2ed6-4c21-b26e-666f0071d89d.png) _the white bar is from snip and not from the website_
> 
> [link to vfm vue2 documentation](https://web.archive.org/web/20211203202729/https://vue-final-modal.org/guide/properties/#content-class)
> 
> Would this be ok?

Hi @WillCWX, I think that sounds good! It looks good as well
Could you try it and see if it works? On my end, from some preliminary checking this seems to disable the scrolling. But please do try :)

**Comment by WillCWX** [comment]
> Hi @WillCWX, I think that sounds good! It looks good as well Could you try it and see if it works? On my end, from some preliminary checking this seems to disable the scrolling. But please do try :)

I confused myself and forgot that the scrolling should be added to our `div class="modal-content"` instead.
A limit to the `max-height` of our `div class="modal-content"` is needed as it is allowed to have an infinite `max-height` and thus goes beyond the webpage and disables scrolling.

I will open the PR so you can take a look if you want to. (I set `max-height=90vh` as it looks best to me)
