### ISSUE TITLE
Enhance search performance of algolia plugin

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2015]
https://docsearch.algolia.com/docs/DocSearch-v3#performance-optimization
Saw this point in the docs: 
![image](https://user-images.githubusercontent.com/41845017/185178506-5a62224c-994d-4249-b1c6-37b04cb0d3ed.png)

_Originally posted by @tlylt in https://github.com/MarkBind/markbind/pull/2014#pullrequestreview-1075958863_

**Comment by vigneshsankariyer1234567890** [comment]
Hey, I'd like to take this issue if it is still open and relevant.
