### ISSUE TITLE
Keywords included in a page's frontmatter are not taken into account in the search bar's results

### ISSUE THREAD

**Issue by weiquu** [MarkBind/markbind#2026]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#311

### Tell us about your environment

Mac

### MarkBind version

v4

### What did you do? Describe the bug

Adding keywords to a page's frontmatter should cause it to be included in the search results if that keyword is searched for. However, this does not seem to be the case (see steps to reproduce).

### Steps to reproduce

I added a new page as below:
```
<span id="title" class="d-none">Formatting Contents</span>

<frontmatter>
  title: "Formatting Contents"
  keywords: plugin
</frontmatter>
```

Following which, I searched for `plugin` in the search bar, which led to this result:
<img width="512" alt="Screenshot 2022-09-02 at 12 29 42 PM" src="https://user-images.githubusercontent.com/48304907/188120675-9ff92243-3cbf-45e9-9848-48379103e6ea.png">

### Expected behavior

The `Formatting Contents` page should have shown up as a search result as one of its keywords was searched for.

### Actual behavior

The `Formatting Contents` page did not show up.

**Comment by itsyme** [comment]
Hi @weiquu! May I look into this issue?

**Comment by weiquu** [comment]
sure, thanks!
