### ISSUE TITLE
How to deal with hydration issues for markdown linked images?

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2028]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

Master branch

### What did you do? Describe the bug

While working on the docs migration, I realized the following markdown triggers hydration issues:
```
[![CI Status](https://github.com/se-edu/addressbook-level3/workflows/Java%20CI/badge.svg)](https://github.com/se-edu/addressbook-level3/actions)
[![codecov](https://codecov.io/gh/se-edu/addressbook-level3/branch/master/graph/badge.svg)](https://codecov.io/gh/se-edu/addressbook-level3)

![Ui](images/Ui.png)
```
![image](https://user-images.githubusercontent.com/41845017/188258193-40d84036-1372-4fd8-abf6-07f805321ffc.png)

![image](https://user-images.githubusercontent.com/41845017/188258129-24059e7c-8407-48be-bbe5-705bf97f0839.png)

Not sure if we can somehow address this, because the linked images syntax seems like very common markdown usage

**Comment by ang-zeyu** [comment]
This seems to be a conflict in functionality between [markdown-it-linkify-images](https://www.npmjs.com/package/markdown-it-linkify-images) and "standard" markdown of `[![CI Status](https://github.com/se-edu/addressbook-level3/workflows/Java%20CI/badge.svg)](https://github.com/se-edu/addressbook-level3/actions)`.

Some ideas:

1.(I think preferably) We could somehow "disable" markdown-it-linkify-images for these edge cases so we can still use the convenient markdown syntax for images.

```
[![](...)](...)
[some text... ![](...)](...)
[**some text... ![](...)**](...)
...

<a href=...>![](...)</a>
```

In addition to introducing some build time validation (no anchors within anchors) for more explicit cases

```
// Content author should probably be fixing these cases manually, as the intention is clear
<a href="...">...<a href="...">should not be allowed</a></a>
```

Side note: realised we aren't documenting markdown-it-linkify-images currently, should do that regardless.

2.Port over the [source](https://github.com/crookedneighbor/markdown-it-linkify-images/blob/master/index.js), rewrite things using `span` and the appropriate accessibility labels, events handlers.

**Comment by tlylt** [comment]
@ang-zeyu thanks for the comment.

Indeed it seems to be a problem of having a `<a>` within a `<a>` immediately...due to conflicting functionality.

Searching on the web, I found this package [markdown-it-implicit-figures](https://github.com/arve0/markdown-it-implicit-figures) which is able to linkify images as well, and it states that:
> link: Put a link around the image if there is none yet.

which takes into account the existing link wrapping.

Looking into the code, it seems like we could possibly do something similar to skip the execution of image linkify if there's already a link.
https://github.com/arve0/markdown-it-implicit-figures/blob/c70911716c1d851c15330d4364fe818b4ab37310/index.js#L20

I think there are a few possible ways to deal with this at the markdown-it level as you mentioned, probably best if we don't need to do a file copy-paste from the linkify-images source.
