### ISSUE TITLE
Highlight separate words in the same line for code block

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2050]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Author Usability

### Is your feature request related to a problem? Please describe.

I am trying to highlight the two words `[Previous_Page_Filename]` and `[Next_Page_Filename]` in the following example and realized it seems not possible for now:

```html
<span id="title" class="d-none">[Name_Of_Section]</span>

{% from "njk/common.njk" import previous_next %}
{{ previous_next('[Previous_Page_Filename]', '[Next_Page_Filename]') }}
```

I tried the following and didn't work:
```js
{highlight-lines="4['[Previous_Page_Filename]'], 4['[Next_Page_Filename]']" // only highlights the first word
```

### Describe the solution you'd like

Possible syntax for consideration
```js
{highlight-lines="4['[Previous_Page_Filename]'], 4['[Next_Page_Filename]']"
{highlight-lines="4['[Previous_Page_Filename]'],'[Next_Page_Filename]']"
```

@damithc wonder if you
- ever needed (or might be useful in the future) for something like this in 2103 code examples
- know whether this can already be done (via syntax different from above)

### Additional context

The same can be said for separate partial text, not necessarily whole words

**Comment by damithc** [comment]
@tlylt Yes, I might need to highlight multiple words in the same line. I was able to reproduced the bug myself.

![image](https://user-images.githubusercontent.com/1673303/206827056-fa8ae635-6da7-46eb-b71d-a9a5fb29302d.png)

![image](https://user-images.githubusercontent.com/1673303/206827063-c5e0b454-f74c-48cf-9c2c-3c1d4105e69c.png)
