### ISSUE TITLE
Use a more noticeable color for highlight words in fenced code

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2051]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

n/a

### MarkBind version

4.0.2

### What did you do? Describe the bug

When the dark theme is used (which is the default) for fenced code, the highlighted words are not easy to spot.

![image](https://user-images.githubusercontent.com/1673303/206827133-67d774da-c6d1-4c0b-8bf0-2e01281c9c1b.png)

### Steps to reproduce

as above

### Expected behavior

Use a color more easily visible in both dark and light themes, or use different colors for the two different themes?

### Actual behavior

as abve

### Anything else?

n/a

**Comment by tlylt** [comment]
Agree that the contrast is not very high for the dark theme.
- For the light theme, it seems quite visible so perhaps no change is needed here.
![image](https://user-images.githubusercontent.com/41845017/207025212-c2a975fb-f1a6-46dd-ab1e-d11fc76fbfa9.png)

Need to experiment or possibly check out other existing projects that have code block functionality to see if there's a more suitable color.

**Comment by yucheng11122017** [comment]
The highlighting in other projects for the dark mode generally favors lighter colors such as [react-code-blocks](https://www.npmjs.com/package/react-code-blocks)
![image](https://user-images.githubusercontent.com/77204346/215501202-ce737416-f8b9-4494-9d10-69520604f467.png)

Is something like this ok? 
![image](https://user-images.githubusercontent.com/77204346/215505171-eb272015-3025-49ac-9b85-86164fc5c6ed.png)


I noticed it is also quite common for other projects to allow users to choose their theme beyond dark and light. Will Markbind also need this use case?

They also customize the theme of the code blocks for each block while Markbind is centralized to the site. Will Markbind also need this use case?

**Comment by damithc** [comment]
> The highlighting in other projects for the dark mode generally favors lighter colors such as [react-code-blocks](https://www.npmjs.com/package/react-code-blocks)
> ![image](https://user-images.githubusercontent.com/77204346/215501202-ce737416-f8b9-4494-9d10-69520604f467.png)

@yucheng11122017 Which part is highlighted in this screenshot? Or are you referring to syntax coloring (which is different from the highlighting feature mentioned in this issue)?

**Comment by yucheng11122017** [comment]
@damithc Oh sorry professor, I misintepreted the issue.

**Comment by yucheng11122017** [comment]
The dark and light themes already have different colors 474949 for their highlighting. (#474949 for dark and #e6e6fa for light)

[Docusaurus ](https://docusaurus.io/docs/markdown-features/code-blocks) uses a brighter color for their dark theme code highlighting (#646464). They allow users to override the default background color. 

Using that value, this is what the code highlighting looks like which does seem a bit too bright making it hard to read the text
![image](https://user-images.githubusercontent.com/77204346/215519554-d7c299b3-1563-4ca4-bffa-6367dcecab22.png) 

My suggestion would be to make the highlighting darker than the code, which makes the text stand out more by contrast. 
![image](https://user-images.githubusercontent.com/77204346/215521602-234003f7-1320-47db-852e-61c8213f97e0.png)
