### ISSUE TITLE
Add CS3203 course website to the showcase tab 

### ISSUE THREAD

**Issue by raysonkoh** [MarkBind/markbind#2070]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Documentation

### Is your feature request related to a problem? Please describe.

The CS3203 course website (https://nus-cs3203.github.io/course-website/) is currently powered by Markbind. Might be a good idea to add it to our showcase tab!

### Describe the solution you'd like

For new contributors, here's the relevant file to edit: `docs/showcase.md`. Make sure to run `markbind serve -d` in the `docs/` directory to verify the changes.

**Comment by damithc** [comment]
Oh, I wasn't aware they are using MarkBind for CS3203 website :-p

**Comment by c00kie123** [comment]
I can work on it!

**Comment by c00kie123** [comment]
I have created the PR but there seem to be some errors going on with the checks. Can you help me check what is wrong?

**Comment by jovyntls** [comment]
Seems that it was an error on Github's end - their [status](https://www.githubstatus.com/incidents/z2j6pjg527p6?utm_ts=1674093258) shows that actions were down for a while but I've rerun the jobs. They're working fine now! :)
