### ISSUE TITLE
Update placement of Onboarding doc to be more prominent

### ISSUE THREAD

**Issue by raysonkoh** [MarkBind/markbind#2071]
Currently, the onboarding doc is placed at the bottom of the site-nav (ss below).

I suggest moving it right below the "Contributing" section to be more prominent and visible for potentially new contributors.

![Screenshot 2023-01-14 at 4 38 50 PM](https://user-images.githubusercontent.com/16506539/212463983-f7abbcc2-7a3c-4c36-9601-f0c3dd9da676.png)

The relevant file is at `docs/_markbind/layouts/devGuide.md`.

**Comment by charandeepsinghb** [comment]
I want to work on this issue. I want to understand how can I get started, can you please explain how can I move this content of Onboarding Bootcamp section to the top. As much as I've understood this repository is a good project which uses Markdown syntax and extends it making it feature rich compilation to HTML, which is impressive.

I am very keen to work in open source.
I want to learn and continue to work on this project.
I'd really appreciate any kind of response to this comment.

Thank you

**Comment by raysonkoh** [comment]
Hi @charandeepsinghb , that's great! To get started, you should take a look at our developer docs (https://markbind.org/devdocs/devGuide/devGuide.html) and the onboarding documentation first. In particular, knowing how to update and serve a markbind site is good enough.

This issue involves editing the site-nav component, so you may want to take a look at this too: https://markbind.org/userGuide/components/navigation.html#site-navigation-menus. You only need to update the file located at `docs/_markbind/layouts/devGuide.md` (lines 26-31).

Let me know if you still run into any issues with this task. Looking forward to receiving your PR! :)

**Comment by charandeepsinghb** [comment]
@raysonkoh I've created the PR forget to add you as a reviewer (I'm new to this, sorry). I've understood a bit about how things work in this from the documentation and guidelines that are needed to be followed. Thank you. Her is the PR #2086

**Comment by jovyntls** [comment]
I personally would prefer for the on-boarding bootcamp to not be at the top, since developers would use it only once. I think 90% of the time, developers would not be looking for the bootcamp and it would be taking up the valuable real estate at the top of the page 😅

If we move it to the top, maybe we could have it un-expanded (so new developers can still find it easily, and it wouldn't take up too much space)? Or we could add a more prominent link on the landing page to lead developers to the Onboarding Bootcamp?

**Comment by raysonkoh** [comment]
> If we move it to the top, maybe we could have it un-expanded (so new developers can still find it easily, and it wouldn't take up too much space)? Or we could add a more prominent link on the landing page to lead developers to the Onboarding Bootcamp?

I think either way works! I'm leaning slightly towards the first suggestion for the reason that you listed. 

@charandeepsinghb thanks for the PR! Following the discussion above, could you make a slight change to your PR so that the onboarding section is collapsed instead of expanded?

**Comment by charandeepsinghb** [comment]
Sure, I will update the PR with onboarding section collapsed instead of expanded.

**Comment by charandeepsinghb** [comment]
Updated te PR for
- collapsed and expanded section
- next and previous buttons

**Comment by charandeepsinghb** [comment]
Hi, So what's the next progress of the PR. (Newbie 😅)

**Comment by raysonkoh** [comment]
Hey @charandeepsinghb, I have merged your PR 🥳 . Feel free to work on other issues!
