### ISSUE TITLE
Consider creating unified types for common variables

### ISSUE THREAD

**Issue by jovyntls** [MarkBind/markbind#2114]
As we continue with the TypeScript migration (#1913), we may want to create unified types to be used across common method arguments. One example could be creating a `Node` type that is used throughout different methods/classes when the `node` parameter is passed around. 

We'll need to decide:
- When we want to do it — after we have fully migrated, or while the migration is currently underway, or if we even want to standardise these types at all
- What the types should be (e.g. for Node, `cheerio.Element & DomElement` could be an option)
- How to handle applying types across the whole codebase

**Comment by jovyntls** [comment]
Some good discussion points from #2112 (thank you @raysonkoh and @tlylt): 

**Potential benefits**
- Immutability
- We can have functions to wrap common methods that we call on `node` - simplifies code and improves code quality

**When should we do it?**
- Consider waiting until we have more tests in the core package - currently not enough tests to detect potential subtle bugs when refactoring types
- Unifying the types early can simplify the TS migration by reducing the need for undefined/null checks 

**(How) should we do it?**
- `cheerio` has migrated to TS
- could be related to #2075

**Comment by ong6** [comment]
To continue this discussion, I think that we can set some guidelines for how to handle the types:

#### Unified Type Definitions
When defining types, we should consider using a type that represents the minimal set of properties and methods required by all the use cases. This helps prevent the types from becoming too specific or cumbersome to use. 

Maybe we should create a master thread for all the possible unified types that we can possibly implement once refactoring is done? 

#### When we should do it
I suggest we just wait till we finish the migration and then refactor all types based on the use case (it is more work but will reduce the risk of errors) 

#### How to safely implement this
- Use a code-checking tool, such as TypeScript's linter, to identify any type inconsistencies and ensure that the types are being used correctly. 
- Additionally, we can consider using a code generation tool to automatically generate type definitions for common use cases. This can help ensure that the types are consistent and up-to-date throughout the codebase.

**Comment by raysonkoh** [comment]
I am concerned whether these conventions / standards can be easily enforced by the linter (or maybe some other style check tool) 🤔 . Otherwise, the code base will become even more messy if someone forgets about whichever convention that we decide on in the future.

By the way, TS offers another way for dealing with cyclic imports: https://stackoverflow.com/questions/24444436/circular-type-references-in-typescript , which we could use in the meantime for TS migration.

**Comment by jovyntls** [comment]
Seeing that the TS migration for most files is completed and we now have a better idea of the types and operations that we perform, I'd like to propose a type wrapper for `node`:

```typescript
type Node = DomElement & cheerio.Element & {
  name: string,
  attribs: { [key: string]: any },
  children: Node[],
}
```
- This new Node type will be introduced as early as possible in NodeProcessor, and all subsequent operations will be done on this type (thus we will not have to deal with DomElement and cheerio.Element directly).
- We can define utility functions for the unavoidable cases where we use a method that requires a typecast to Node, to ensure that these typecasts are done safely. For instance, one such utility function may look like this: 
	```typescript
	function parseHTML(html: string) {
	    const node = cheerio.parseHTML(html)[0];
	    return node as unknown as Node;
	}
	```

### Rationale

Currently, we
1. Have several `as unknown as` typecasts, which we're using as a bit of a hack to perform typecasts on incompatible types
2. Have potentially unnecessary on `node` attributes to satisfy the TS linter. For instance, we often check `(if !node.name) return;`, which is often unnecessary because `node.name` should always exist, and if it doesn't, an error should be thrown earlier rather than later
3. Convert between `cheerio.Element` and `DomElement` almost interchangeably despite these being incompatible types

The above implementation allows us to deal with these issues by
1. Reducing the amount of `as unknown as` typecasts. Most of these are converting between `DomElement` and `cheerio.Element` because we mostly treat them as interchangeable. 
2. Enforcing that attributes that we should be present, are always present (e.g. `node.name`, `node.attribs`. Thus, we can reduce the amount of unnecessary checks for these attributes.
3. Formalising our view of the relationship between `cheerio.Element`, `DomElement`, and all the other attributes that we expect from a `node` variable. i.e., a `node` satisfies the type of `cheerio.Element` and `DomElement`, and also has a `name`, `attribs` (which may be empty), and `children` (which may be empty).

Additional benefits
- If we decide to switch to the parse5 library, it should be an easier migration since we now have a wrapper type on everything.


@MarkBind/active-devs please weigh in on this :)

**Comment by raysonkoh** [comment]
Thanks for the suggestion @jovyntls, I think this is a good start. My thoughts are that ideally it would be good if updating `cheerio` or `htmlparser2` or switching to `parse5` would solve this typing issue. Otherwise, I think your solution might work too, but I think it would be good to trial it with a small PR.

> from what point onwards should a node be immutable, or should it be immutable right from the start of parsing?

If we make `node` (or equivalent) type immutable, any function that tries to manipulate a `node` obj using side-effects is going to cause a compile error. So the ts compiler would be able to tell us which function needs to be updated.

**Comment by jovyntls** [comment]
@raysonkoh  I suspect that updating `cheerio` (and/or switching to `parse5`) wouldn't solve the typing issues since the interfaces remain largely the same. Updating cheerio would allow us to set the parser to use parse5 instead of htmlparser2, but if I'm not wrong, the cheerio methods and classes we use would still have the same typing issues. Same for using parse5 types in place of htmlparser2.DomElement, because much of our typing issues stem from requiring certain attributes from nodes that aren't always in these types.

I could do a small PR to preview the changes for this typing proposal :)

> If we make node (or equivalent) type immutable, any function that tries to manipulate a node obj using side-effects is going to cause a compile error. So the ts compiler would be able to tell us which function needs to be updated.

Agreed! I was referring to when we should introduce this type, i.e. at which point should we cast to this immutable Node type. For instance, we could start using it immediately once we do the first parse of the user-supplied markdown, or later on in `processNode`.

**Comment by raysonkoh** [comment]
> For instance, we could start using it immediately once we do the first parse of the user-supplied markdown, or later on in processNode.

For simplicity and barring any significant performance issues, I think we should go with the former.
