### ISSUE TITLE
Drop-down menus in navbar: support sub-menu items

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#212]
v1.7.2

current: drop down menus in the top nav bar supports only one level
e.g.,
![image](https://user-images.githubusercontent.com/1673303/40094832-bc20b4f8-58fb-11e8-88fe-1c9017681c9a.png)

suggested: support multiple levels

**Comment by jonahtanjz** [comment]
Hi Prof @damithc and @ang-zeyu, I'm interested in working on this feature. According to #1332, seems like nested dropdown is still relevant and a nice to have feature. I was thinking of creating a separate component for the nested dropdown say something like `<submenu>`.

For exmaple:
```
<dropdown>
    <li>...</li> // normal dropdown item
    <li>...</li>
    <submenu>
        <li>...</li> // nested dropdown item
        <li>...</li>
    </submenu>
</dropdown>
```

Is this approach recommended for creating a sub-menu item inside a dropdown?

**Comment by damithc** [comment]
> Is this approach recommended for creating a sub-menu item inside a dropdown?

No objections from me @jonahtanjz

**Comment by ang-zeyu** [comment]
sounds good @jonahtanjz 

wonder if we could / should do 

```
<dropdown>
    <li>...</li> // normal dropdown item
    <li>...</li>
    <dropdown>
        <li>...</li> // nested dropdown item
        <li>...</li>
    </dropdown>
</dropdown>
```

as well. less syntax to remember 🙂
