### ISSUE TITLE
User Guide: Tweak heading to match site navigation menu

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2150]
For example, consider the following heading:
![image](https://user-images.githubusercontent.com/1673303/217607748-bac4d18f-b365-4d5d-adc8-371db72f7e48.png)

Perhaps we can use `Using Components: Pop-Ups` instead, so that the two match?

Not a major issue. Just a cosmetic thing. 

Applies to some other pages as well.

**Comment by jovyntls** [comment]
@damithc What do you think about changing `Pop-Up Components` to just `Pop-Ups`? I find `Using Components: Pop-Ups` a little verbose 😅 It feels weird to be namespacing our page titles in this way (by including the navbar categories in page titles). Maybe when we have an auto-generated breadcrumbs feature we could use that to show the Components>Pop-ups relationship instead?
Looking at the Bootstrap docs, I think it might be cleaner without a "Components: " prefix:
<img width="491" alt="Screenshot 2023-02-12 at 7 00 42 PM" src="https://user-images.githubusercontent.com/61113575/218307135-55803c14-ccd2-44f8-aef8-d18ee1ca18fd.png">

> Applies to some other pages as well.

Agree with the inconsistency - the other pages (like Markbind CLI) could be clearer/cleaner if they match.

**Comment by damithc** [comment]
> @damithc What do you think about changing `Pop-Up Components` to just `Pop-Ups`?

@jovyntls That might be OK too.
