### ISSUE TITLE
Add some visual feedback when checking a <question> with no radio options selected

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#2156]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Is your feature request related to a problem? Please describe.

MCQ questions have no visual feedback when you click 'check' without having selected any options.

### Describe the solution you'd like

Design and implement some visual feedback.

**Comment by itsyme** [comment]
Hi @ang-zeyu! I feel that the current shake feedback may be more appropriate for not selecting any options. I was thinking of using shake for not selecting any options and maybe a red fill with high opacity for a wrong answer. What do you think?

**Comment by ang-zeyu** [comment]
Sorry for the late reply, I see the shake has been added to both places.

>  current shake feedback may be more appropriate

Do you still feel this way? (referencing the thread in the PR)

> red fill with low opacity or no animations

It's a little hard to picture this, did you have a prototype you could share? (or any other example on the web)

**Comment by ang-zeyu** [comment]
Off my head I agree with the sentiment a shake somewhat does the job for a wrong answer but I'm far from a UX expert. Feel free to open a new issue if you still have something in mind to improve it!
