### ISSUE TITLE
Node v19.6.0 incompatibility on Windows 10

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2162]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

Master branch

### Describe the bug and the steps to reproduce it

Reproduction:
- be on Windows 10 (not sure about other OS)
- install node v19.6.0
- run `npm run setup`

<details>
  <summary>npm run setup fails possibly due to node-gyp, expand for error log</summary>
$ npm run setup

> setup
> npm ci && npm run clean && lerna clean --yes && lerna bootstrap --hoist

npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated read-package-tree@5.3.1: The functionality that this package provided is now in @npmcli/arborist
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 1132 packages, and audited 1133 packages in 18s

134 packages are looking for funding
  run `npm fund` for details        

22 vulnerabilities (1 low, 7 moderate, 13 high, 1 critical)

To address issues that do not require attention, run:      
  npm audit fix

To address all issues (including breaking changes), run:   
  npm audit fix --force

Run `npm audit` for details.

> clean
> node ./scripts/clean.js

lerna notice cli v4.0.0
lerna info clean removing C:\Users\yong\Documents\GitHub\markbind\packages\cli\node_modules
lerna info clean removing C:\Users\yong\Documents\GitHub\markbind\packages\core-web\node_modules
lerna info clean removing C:\Users\yong\Documents\GitHub\markbind\packages\core\node_modules
lerna info clean removing C:\Users\yong\Documents\GitHub\markbind\packages\vue-components\node_modules
lerna success clean finished
lerna notice cli v4.0.0
lerna info Bootstrapping 4 packages
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna ERR! npm install exited 1 in 'root'
lerna ERR! npm install stderr:
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\Users\yong\Documents\GitHub\markbind\node_modules\deasync
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@5.1.1
npm ERR! gyp info using node@19.6.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.1 found at "C:\Users\yong\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\yong\Documents\GitHub\markbind\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Users\yong\Documents\GitHub\markbind\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\yong\Documents\GitHub\markbind\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\yong\Documents\GitHub\markbind\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Users\yong\Documents\GitHub\markbind\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Users\yong\Documents\GitHub\markbind\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\yong\Documents\GitHub\markbind\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\yong\\Documents\\GitHub\\markbind\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\yong\Documents\GitHub\markbind\node_modules\deasync
npm ERR! gyp ERR! node -v v19.6.0
npm ERR! gyp ERR! node-gyp -v v5.1.1
npm ERR! gyp ERR! not ok
npm ERR! Build failed

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yong\AppData\Local\npm-cache\_logs\2023-02-13T01_50_03_128Z-debug-0.log
lerna ERR! npm install exited 1 in 'root'
</details>

### Expected behavior

Expect to setup successfully.

**Comment by EltonGohJH** [comment]
Same error occurs when using  Node 19.0.1

**Comment by lhw-1** [comment]
Tested on Ubuntu 20.04:

- Same error occurs when using Node 19.0.0 (and above - also tested with Node 19.0.1 and all available Node 19.x.0), with the same logs.
- Setup is successful when using Node 18.14.0, meaning that we can likely narrow down the error to between Node 18.14.0 and Node 19.0.0.

As a side note, I found [this issue](https://github.com/nodejs/node-gyp/issues/2785) in the node-gyp repository that pointed to [this README](https://github.com/nodejs/node-gyp/blob/main/docs/README.md), I wonder if the issue is because we are using v5.1.1. for `node-gyp` which is implied to be outdated? Though it should be noted that the issue was opened by someone using Node 18.12.1, so it may not be as relevant.

**Comment by EltonGohJH** [comment]
I found the fix for this.
That would be to update node-gyp to the latest version (9.3.1) forcefully by adding it into the dependency in package.json and it works.

If we look at the dependencies tree, we see that node-gyp being outdated is due to Lerna being outdated.
├─┬ lerna@4.0.0
│ ├─┬ @lerna/add@4.0.0
│ │ └─┬ pacote@11.3.5
│ │   └─┬ @npmcli/run-script@1.8.6
│ │     └── node-gyp@7.1.2
│ └─┬ @lerna/bootstrap@4.0.0
│   └─┬ @lerna/run-lifecycle@4.0.0
│     └─┬ npm-lifecycle@3.1.5
│       └── node-gyp@5.1.1


@tlylt I think this calls for Lerna to be updated. Is there a way to update Lerna without running `npm i`. `npm i` is causes the formatting to change.
![image](https://user-images.githubusercontent.com/75515229/218420277-edeaeecb-2799-47aa-a712-e088d4bbec22.png)

**Comment by tlylt** [comment]
Sorry I missed the above comment. As discussed privately: the `npm i` issue is a non-blocker if it only affects the pretty formatted HTML that we use in test mode (for our functional test cases). Would be good to find a fix for the formatting change issue still.
