### ISSUE TITLE
Broken links introduced in UG

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2167]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

Master branch

### Describe the bug and the steps to reproduce it

> warn: You might have an invalid intra-link! Ignore this warning if it was intended.
'/userGuide/formattingcontents.html#classes-attributes-and-amp-identifiers' found in file 'C:\Users\User\Documents\GitHub\markbind\docs\userGuide\tipsAndTricks.md'
warn: You might have an invalid intra-link! Ignore this warning if it was intended.
'/userGuide/syntax/siteJsonFile.html#pagesexclude' found in file 'C:\Users\User\Documents\GitHub\markbind\docs\userGuide\syntax\includes.md'

- pagesExclude
https://markbind-master.netlify.app/userguide/reusingcontents#:~:text=In%20site.json%20we%20then%20exclude%20the%20fragment%20from%20the%20page%20generation%20with%20pagesExclude%3A
- markdown-it-attrs
  - this one is ok but the capitalization is different from the file name, triggering broken link warning
https://markbind-master.netlify.app/userguide/tipsandtricks#:~:text=For%20Markdown%20elements%2C%20the%20v%2Dpre%20attribute%20needs%20to%20be%20declared%20using%20markdown%2Dit%2Dattrs%2C%20which%20allows%20classes%2C%20identifiers%2C%20and%20attributed%20to%20be%20added%20to%20Markdown%20syntax%3A

**Comment by jovyntls** [comment]
> this one is ok but the capitalization is different from the file name, triggering broken link warning

Good find, sounds like we might want to do a case-insensitive check for broken link reporting? 🤔

**Comment by damithc** [comment]
Some Web servers (e.g., Github pages) are case sensitive.
