### ISSUE TITLE
Includes does not render markdown when fragment is a variable

### ISSUE THREAD

**Issue by yucheng11122017** [MarkBind/markbind#2211]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

V4.1.0

### Describe the bug and the steps to reproduce it

When using includes with hash, markdown is not rendering correctly

This is seen in the UG reader facing feature for classes attributes and identifiers and questions. 

![image](https://user-images.githubusercontent.com/77204346/224975430-ca1fd150-8170-48d0-b182-8b30f41d6f71.png)
![image](https://user-images.githubusercontent.com/77204346/224975468-be64606d-e178-4b50-b3c6-16ecbbd52ba4.png)

### Expected behavior

Expected markdown to render correctly when using includes

### Anything else?
Remove documentation in UG introduced in #2258 regarding this bug if fixed
_No response_

**Comment by damithc** [comment]
@yucheng11122017 The common reason for this problem is the lack of a blank line just above the start of the markdown text. I assume that's not the case here?

**Comment by damithc** [comment]
@yucheng11122017 I see. Thanks for checking. Looks like a regression that was introduced after the last release (i.e., I have not encountered this before).

**Comment by yucheng11122017** [comment]
@jovyntls Oh yes I think you are right! I think the markdown doesn't render because the code is within the variable for the include. Hence when it is extracted, it remains as text instead of markdown. 

Eg. 
```
<include src="codeAndOutput.md" boilerplate >
<variable name="highlightStyle">markdown</variable>
<variable name="code" id="list-example">
* Apply to the list item itself like so {.text-success #list-item-id}
  * Curly groups after newlines apply to the closest nested list {.text-danger}
{.bg-light}
* Curly groups two lines after the last line apply to the top most list

{.alert-info}
</variable>
</include>
```

The `list-example` will not get rendered and hence when it is extracted out, it will just remain as text. 

I don't believe that we would want to change this behavior as well. 

I've been trying to change the order to do the markdown rendering after the taking out the part of the hash but this will result in some issues 

- Trim does not working properly with this ordering 
- An additional `<p>` tag is added if inline option is not enabled

Would this issue be worth fixing?

**Comment by jovyntls** [comment]
> Would this issue be worth fixing?

I believe so! It would be nice to polish how we handle `includes` since it's one of our more powerful features.

The issue appears since `v3.0.0` when I serve locally 🤯   Seems to be quite an edge case; would still be nice to fix eventually

**Comment by yucheng11122017** [comment]
Closing as it is specified in the [UG that fragment include only works if the fragment is wrapped in div or span](https://markbind.org/userGuide/reusingContents.html#includes:~:text=You%20can%20%3Cinclude%3E%20a%20fragment%20of%20a%20file%20by%20specifying%20the%20%23fragment%2Did%20at%20the%20end%20of%20the%20src%20attribute%20value%2C%20provided%20the%20fragment%20is%20wrapped%20in%20a%20%3Cdiv%3E/%3Cspan%3E%20tag%20with%20the%20matching%20id.). ie variables are not included by default for this. 

May be nice to include this in the future but for now, not a problem :)

**Comment by yucheng11122017** [comment]
Closing as it is specified in the [UG that fragment include only works if the fragment is wrapped in div or span](https://markbind.org/userGuide/reusingContents.html#includes:~:text=You%20can%20%3Cinclude%3E%20a%20fragment%20of%20a%20file%20by%20specifying%20the%20%23fragment%2Did%20at%20the%20end%20of%20the%20src%20attribute%20value%2C%20provided%20the%20fragment%20is%20wrapped%20in%20a%20%3Cdiv%3E/%3Cspan%3E%20tag%20with%20the%20matching%20id.). ie variables are not included by default for this. 

May be nice to include this in the future but for now, not a problem :)
