### ISSUE TITLE
Includes/`src` overrides frontmatter

### ISSUE THREAD

**Issue by jovyntls** [MarkBind/markbind#2215]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

MacOS

### MarkBind version

4.1.0

### Describe the bug and the steps to reproduce it

Have 2 files with frontmatter; one file includes the other.

e.g. topic1.md includes topic2.md:

`topic1.md`:
```html
<frontmatter>
  layout: default.md
  title: "Title 1"
  pageNavTitle:  "Pagenav 1"
</frontmatter>

<br>

# Topic 1

Either works:
<popover src="topic2.md"> hover </popover>
<include src="topic2.md" />
```

`topic2.md`:
```html
<frontmatter>
  layout: default.md
  title: "Title 2"
  pageNavTitle:  "Pagenav 2"
</frontmatter>

# topic 2

Lorem ipsum
```

Applies for `<include>`s, `<popover src="...">`, etc

### Expected behavior

If `topic1.md` includes `topic2.md`, then `topic1.md` should still retain its original frontmatter such as page title.

In the above example, `topic1.md` page title should be "Title 1", pagenav title should be "Pagenav 1", etc.

### Actual behaviour

The frontmatter is overwritten. The page title of `topic1.md` is "Title **2**" as it is overwritten by `topic2.md`'s frontmatter.

**Comment by yucheng11122017** [comment]
Thanks for spotting this issue @jovyntls! I believe includes has an [`omitFrontmatter` ](https://markbind.org/userGuide/reusingContents.html#includes:~:text=epic%22%20trim%20/%3E-,omitFrontmatter,-(optional)%3A%20omit%20the)option to not have the front matter of the included code. 
Is this behavior insufficient?

**Comment by jovyntls** [comment]
> Thanks for spotting this issue @jovyntls! I believe includes has an [`omitFrontmatter` ](https://markbind.org/userGuide/reusingContents.html#includes:~:text=epic%22%20trim%20/%3E-,omitFrontmatter,-(optional)%3A%20omit%20the)option to not have the front matter of the included code. Is this behavior insufficient?

Ah I didn't see that, thanks @yucheng11122017 ! Closing this issue since it's been resolved

**Comment by lhw-1** [comment]
While this issue is closed, just to add on in case someone runs into the same issue in the future / wants to reconsider this behavior:

This is an intended behavior as of right now, in that we allow `frontmatter` of any included pages to override the current `frontmatter`, with an attribute `omitFrontmatter` to allow for flexibility. The specified behavior can be found [here in `core/src/html/NodeProcessor.ts`](https://github.com/MarkBind/markbind/blob/master/packages/core/src/html/NodeProcessor.ts#L118-L129).
