### ISSUE TITLE
SiteNav dropdown buttons shift when scrollbar appears/disappears

### ISSUE THREAD

**Issue by itsyme** [MarkBind/markbind#2217]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

MacOS

### MarkBind version

4.1.0

### Describe the bug and the steps to reproduce it

Collapse all dropdowns in SiteNav. Expand dropdowns till scrollbar appears and notice the position of the dropdown buttons.

### Expected behavior

Dropdown buttons should remain in place even when the scrollbar toggles.

**Comment by ang-zeyu** [comment]
Was this fixed? The caret is a little off center when the dropdown is collapsed but I can't seem to notice anything on markbind.org or the latest commit related to the scrollbar particularly.

**Comment by itsyme** [comment]
> Was this fixed? The caret is a little off center when the dropdown is collapsed but I can't seem to notice anything on markbind.org or the latest commit related to the scrollbar particularly.

Hi @ang-zeyu! It hasn't been fixed yet unfortunately, I will get down to doing it when I have more time!

**Comment by ang-zeyu** [comment]
Oh.. i see it now..

https://github.com/MarkBind/markbind/pull/2204#issuecomment-1469043606

**Comment by ang-zeyu** [comment]
Separate issue but the caret seems a little off center vertically when in this orientation, we can try fixing that at the same time:

![image](https://user-images.githubusercontent.com/3306138/234575375-08393ac6-af65-4f38-91ef-4d5ffcf1bcdd.png)
