### ISSUE TITLE
Add the "templates" page into the sitenav for more visibility

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2219]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Documentation

### Is your feature request related to a problem? Please describe.

Somehow this [page](https://markbind.org/userGuide/templates.html) is not included in the sitenav, making it less visible to new users.

### Describe the solution you'd like

Include it, perhaps under "Working with sites"

**Comment by ayushmaanshrotriya** [comment]
will do. you can assign me

**Comment by EssWhyy** [comment]
Hi I know this issue has already been assigned, but it seems like it has been inactive for almost 3 months? I'm a first time contributor and have already made a minor fix for this and linked a PR request to the issue. Let me know if it's ok!
