### ISSUE TITLE
Models in options not working when viewed from "Reader-Facing Features" page

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2220]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

Master branch

### Describe the bug and the steps to reproduce it

![image](https://user-images.githubusercontent.com/41845017/225805937-0359c3e5-ad23-4f8b-9fd4-fc4bd615918f.png)

Working in [here](https://markbind.org/userGuide/components/popups.html#modals)
- model opens when click on "hearer [s]", and "Slot"

But not working [here](https://markbind.org/userGuide/readerFacingFeatures.html#modals)
- nothing happens when click on "hearer [s]", and "Slot"

### Expected behavior

Model working.

### Anything else?

Also happens in "Full Syntax Reference" page, might also happen for other similar model in table usages.

**Comment by yucheng11122017** [comment]
Hi @tlylt, thanks for noticing this. I believe this issue is that the modal for the trigger is not being imported over to the reader facing feature page and the full syntax reference. Hence when the trigger is clicked, there is no modal to opened.
