### ISSUE TITLE
Reduce vertical space usage at the bottom of panels

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2222]
v4.1.0

Current:

![image](https://user-images.githubusercontent.com/1673303/225820757-7de674c5-3cc4-4162-a653-1debf1f3bd54.png)

Suggestion: It is good if we can reduce this empty space. e.g.,

![image](https://user-images.githubusercontent.com/1673303/225820529-33dbbf68-9627-4f64-9896-ff64f81ee82a.png)

**Comment by poetiksage** [comment]
Is it fixed or would you like me to fix it?

**Comment by jovyntls** [comment]
This issue still exists - feel free to take it up @poetiksage !

**Comment by jovyntls** [comment]
Hey @poetiksage , are you currently working on this?

**Comment by poetiksage** [comment]
Hey @jovyntls , first of all sorry of late reply. Secondly, this might sound silly but I'm beginner and I don't know how to fire this up. I forked it, cloned it, install everything required for it like java and graphviz. Aow I'm stuck with it.

**Comment by EssWhyy** [comment]
Hi I attempted to tackle this issue and have made a PR request, do take a look, thank you!
