### ISSUE TITLE
Upgrade fontawesome version to latest (v6) from v5

### ISSUE THREAD

**Issue by yucheng11122017** [MarkBind/markbind#2242]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Author Usability

### Is your feature request related to a problem? Please describe.

Currently Markbind is using only v5 of fontawesome. 
v6 of fontawesome added quite a number of new features which could be useful to users. 

### Describe the solution you'd like

Upgrade fontawesome from v5 to v6

Instructions here: 
https://fontawesome.com/docs/web/setup/upgrade/

**Comment by damithc** [comment]
If this can be done quickly, it would be good to have it in MarkBind v5.0
It appears some icons in FontAwsome V5 are not in V6.  Is it possible to support both versions? OK if cannot but it will break some of the existing sites silently. In fact, it would be good to give a warning if an icon cannot be found.
If the upgrade can't be done in time for MarkBind v5.0, perhaps we can update the UG to inform users that they should use FontAwsome V5 for the time being.

**Comment by SPWwj** [comment]
I may help with this, since it is related to what I am currently doing

**Comment by damithc** [comment]
@SPWwj sure

**Comment by tlylt** [comment]
> I may help with this, since it is related to what I am currently doing

@SPWwj Any plan to finish this one soon? We will target to release v5 by this weekend.

**Comment by SPWwj** [comment]
That's quite rushed. I will revisit this tomorrow.
