### ISSUE TITLE
Help TEAMMATES migrate docs to MarkBind V4

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2245]
See https://github.com/TEAMMATES/teammates/issues/12271

It's good if someone from the MarkBind team can help TEAMMATES migrate their docs to V4. They are currently busy with some major migration work themselves and might not have time to tackle this themselves.

**Comment by yucheng11122017** [comment]
Waiting for v5 to be released before working on this :)

**Comment by tlylt** [comment]
V5 is already released. @MarkBind/active-devs FYI if anyone is interested in the coming months.

**Comment by kaixin-hc** [comment]
Completed by @jingting1412 ! Thank you again : )
