### ISSUE TITLE
Add note on netlify config when migrating Node.js

### ISSUE THREAD

**Issue by yucheng11122017** [MarkBind/markbind#2246]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Is your feature request related to a problem? Please describe.

It would be helpful to new developers to have instructions on how to migrate in the DG similiar to '[Migrating to Typescript'](https://markbind.org/devdocs/devGuide/development/migratingToTypeScript.html). 

### Describe the solution you'd like

Include checklist and steps needed for migrating in DG. 

This can take reference from what was done in #2233 when migrating to node v16 from v14

**Left with one TODO:**
- [ ] After #2277, the netlify setting for deploying our documentation on markbind-master is configured using the netlify.toml in our root folder. When migrating, we should change the Node.js version specified in that file accordingly. Hence, we should mention this step in the migrating to Node.js docs

**Comment by jovyntls** [comment]
Hi @yucheng11122017, just checking, is this closed by #2256? Is there anything else that we should add to our DG related to Node.js migration?

**Comment by tlylt** [comment]
@jovyntls I think so, but I realized I accidentally introduced a place that needs updating the docs for (https://github.com/MarkBind/markbind/pull/2277). Will modify and make use of this issue for that.
