### ISSUE TITLE
CI Test Failure for MacOS

### ISSUE THREAD

**Issue by lhw-1** [MarkBind/markbind#2251]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Ubuntu 20.04

### MarkBind version

4.1.0

### Describe the bug and the steps to reproduce it

On merging PR #2247 into the `master` branch, the CI for MacOS initially failed, with [this test case](https://github.com/MarkBind/markbind/actions/runs/4560760060/jobs/8046009866#step:7:287) resulting in an "Exceeded timeout of 5000 ms for a test" error.

After some investigation into the issue, it seems that the main problem is with the time taken to run each test being too long, and since this particular test took more than 5000 ms to run, the test returned an error. 

![photo_2023-03-30_17-23-43](https://user-images.githubusercontent.com/25716529/228792978-16703c08-4784-424b-83c4-6ba8045576b6.jpg)

However, it should be noted that the CI run for MacOS on the commit before this is as follows:

![photo_2023-03-30_17-23-51](https://user-images.githubusercontent.com/25716529/228793289-f3592c2c-0865-46d7-bdd2-597d10568721.jpg)

And the CI run for MacOS when the CI was run again is as follows:

![photo_2023-03-30_17-23-48](https://user-images.githubusercontent.com/25716529/228793381-9f7030f3-c374-41aa-8da6-426d7bc8de78.jpg)

The time taken to run the tests in these two cases (before and after this issue occurred) seem to be in the reasonable range. Unfortunately, there does not seem to be another instance of this issue, and it does not seem possible to reliably replicate this issue as of right now, given that the issue disappeared on re-running the CI tests.

We will keep this issue open for (1) documentation, and (2) replicate and possibly resolve this issue if it is encountered again in the future.

### Expected behavior

The test should take a reasonable amount of time to run (between 200 - 300 ms) and should not result in a timeout error.

**Comment by kaixin-hc** [comment]
Understanding that this was not replicated before or after, to keep looking through open issues more manageable, I will close this issue; if it occurs again lets reopen and discuss this issue more.
