### ISSUE TITLE
Do not give 'missing reference' error message for boilerplate files

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#226]
Current:
Say there is a `_markbind/boilerplates/print.md` which contains the following code:
```
<include src="text.md#title" />

<include src="text.md#body" />
```

This file generates a 'missing reference' warning during the build process because there is no `text.md` file in the boilerplates directory. However, a boilerplate is used as if it is in another location and therefore the `text.md` file need not be in the boilerplates directory. 

Suggested:  exempt boilerplates files from `missing reference` warning. Even better if the missing reference warning can be given when the boilerplate file is used, w.r.t. the actual target directory.

**Comment by yamgent** [comment]
Can't reproduce this on a fresh markbind site. Is this generated error related to the globbing issue in https://github.com/MarkBind/markbind/pull/214#issuecomment-390461578?

**Comment by damithc** [comment]
> Is this generated error related to the globbing issue in #214 (comment)?

Yes, I think so. Just realized that the offending boilerplate files are actually in a submodule site.

**Comment by damithc** [comment]
Seems to be solved now.
