### ISSUE TITLE
UG/DG: Add code block copy buttons 

### ISSUE THREAD

**Issue by jovyntls** [MarkBind/markbind#2262]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Our DG and UG has many code blocks that give readers samples of usable Markbind syntax. It would be convenient for readers to be able to quickly and easily copy these code samples using a copy button, especially since we have a code block copy buttons plugin.

### Describe the solution you'd like

Use our existing [code block copy buttons plugin](https://markbind.org/userGuide/usingPlugins.html#plugin-codeblockcopybuttons) in the DG and UG

### Additional context

If there are any other existing plugins that would benefit our UG/DG, these can be added as well!

**Comment by WillCWX** [comment]
Hello,
Is it okay if I submit a PR on this as my first issue?

Thanks

**Comment by yucheng11122017** [comment]
@WillCWX sure!
