### ISSUE TITLE
Support custom icons for lists

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2272]
Suggestion: provide a way to specify custom icons for bullet lists, so that authors can use this kind of styles for lists easily. 

![image](https://user-images.githubusercontent.com/1673303/230713347-40053c5b-b342-4314-9998-e663f19bc501.png)

The feature can be quite powerful if we combine it with our strong support for icons.

If the above can be achieved, it can be extend to numbered lists, to allow users to choose which kind of numbering to use (e.g., `A, B, C` instead of `1, 2, 3`)

However, I expect coming up with an convenient syntax will be challenging, not to mention the feasibility of the implementation of such a feature.

**Comment by damithc** [comment]
> Is this a duplicate? #906

Related, but not exactly the same. 

This one is about replacing the default bullet icon with something else.

#906 is a so-called 'media list' in which the icon is a more prominent object (e.g., a picture) and the text is side-by-side with that object (like a two-column table).

**Comment by ang-zeyu** [comment]
Don't see why not. Do you have any ideas on the syntax? (in consideration with #906 as well)

Both are very similar in implementation and usage so it's best if it is somewhat consistent with each other.

**Comment by damithc** [comment]
> Do you have any ideas on the syntax?

Not easy.  How about something along the following lines? 

Regular list with custom icons:
```
<icon-list>
* {.icon=":fas-tick:"} first item
* second item
  * {.icon=":fas-x:" .class="text-danger"} third item
  * fourth item
</icon-list>
```

Media-list (same syntax):
```
<icon-list icon-size="3">
* {.icon=":fas-tick:"} first item description
* {.icon=":fas-x:"} second item description
* {.icon="images/house.png"} second item description
</icon-list>
```

i.e., Specify icon at the start of the item. Use the same item for the subsequent items of the same level, until a new icon is given.

**Comment by SPWwj** [comment]
> 

To accommodate the media list, I propose the following syntax for the new icon list:

```
- Header 1 { icon=":icon-tick:" }

  Content 1

- Header 2
    
    Content 2 { icon="/image.png" }
    
  - Header 2.1
  
- Header 3

- Header 4 
   - Header 4.1 

   { icon="x.png" size="xs"}
  
{ icon="x.png" size="xs" media}
```
The overall configuration is placed at the end of the document, as suggested by @ang-zeyu in [PR #2309](https://github.com/MarkBind/markbind/pull/2309#discussion_r1237993636).

An additional optional 'media' attribute is used to distinguish the standard list from the media list. In this configuration, the first list item should be used as a header, while the remaining lines serve as content.

Based on issue #1778, it is safe to use 'icon-tick' instead of ':icon-tick:' in order to eliminate confusion.

The benefits of this implementation are twofold. 
- First, it completely obviates the necessity for HTML tags, simplifying the syntax. 
- Second, it repurposes existing Markdown rules, meaning features like nested lists are supported by default. This results in an elegant, streamlined approach to managing content.

**Comment by damithc** [comment]
@SPWwj After removing extra whitespace, it will be like this:
```
- Header 1{icon=":fas-tick:"}
  Content 1
- Header 2
  Content 2{icon="/image.png"}
  - Header 2.1
- Header 3
- Header 4 
  - Header 4.1 
   {icon="x.png" size="xs"}
{icon="x.png" size="xs" media}
```
I can't imagine having a default icon for a media list. So, we can probably omit that.
I don't think we need to support nested media lists either. 

So, a regular list will be like the following? 
```
- item 1 line 1{icon=":fas-tick:"}
- item 2 line 1
  item 2 line 2{icon="/image.png"}
- item 3 line 1{icon=":fas-tick:"}
- item 4
  - item 4.1{icon=":fas-tick:"}
  - item 4.2
  {icon=":fas-x:"}
- item 5
{icon=":fas-x:" size="s"}
```
`size` is optional. 

What do you think?

**Comment by SPWwj** [comment]
The revised version looks much cleaner, indeed. 
I just realized the two-space indentation behaves like a line break (</br>). 
For the default configuration {icon=":fas-x:" size="sx"}, we need a line break to comply with Markbind syntax so it gets captured by the 'ul' tag above. So, the syntax will be:

```
- ### Header 1 { icon=":icon-tick:" xx= "XS" }
  Content 1
- Header 2  
  Content 2 { icon="/image.png" }  
  - Header 2.1
- Header 3  
- Header 4  
  - Header 4.1  
  
  { icon="x.png" xx="xs"}  

{ icon="x.png" xx="xs"}
```

Given that we can use the "#" symbols along with the size parameter, it inherently supports media list by default.

**Comment by SPWwj** [comment]
> @SPWwj After removing extra whitespace, it will be like this:
> 
> ```
> - Header 1{icon=":fas-tick:"}
>   Content 1
> - Header 2
>   Content 2{icon="/image.png"}
>   - Header 2.1
> - Header 3
> - Header 4 
>   - Header 4.1 
>    {icon="x.png" size="xs"}
> {icon="x.png" size="xs" media}
> ```
> 
> I can't imagine having a default icon for a media list. So, we can probably omit that. I don't think we need to support nested media lists either.
> 
> So, a regular list will be like the following?
> 
> ```
> - item 1 line 1{icon=":fas-tick:"}
> - item 2 line 1
>   item 2 line 2{icon="/image.png"}
> - item 3 line 1{icon=":fas-tick:"}
> - item 4
>   - item 4.1{icon=":fas-tick:"}
>   - item 4.2
>   {icon=":fas-x:"}
> - item 5
> {icon=":fas-x:" size="s"}
> ```
> 
> `size` is optional.
> 
> What do you think?



> @SPWwj After removing extra whitespace, it will be like this:
> 
> ```
> - Header 1{icon=":fas-tick:"}
>   Content 1
> - Header 2
>   Content 2{icon="/image.png"}
>   - Header 2.1
> - Header 3
> - Header 4 
>   - Header 4.1 
>    {icon="x.png" size="xs"}
> {icon="x.png" size="xs" media}
> ```
> 
> I can't imagine having a default icon for a media list. So, we can probably omit that. I don't think we need to support nested media lists either.
> 
> So, a regular list will be like the following?
> 
> ```
> - item 1 line 1{icon=":fas-tick:"}
> - item 2 line 1
>   item 2 line 2{icon="/image.png"}
> - item 3 line 1{icon=":fas-tick:"}
> - item 4
>   - item 4.1{icon=":fas-tick:"}
>   - item 4.2
>   {icon=":fas-x:"}
> - item 5
> {icon=":fas-x:" size="s"}
> ```
> 
> `size` is optional.
> 
> What do you think?

The revised version looks much cleaner, indeed. 
I just realized the two-space indentation behaves like a line break (</br>). 
For the default configuration {icon=":fas-x:" size="sx"}, we need a line break to comply with Markbind syntax so it gets captured by the 'ul' tag above. So, the syntax will be:

```
- ### Header 1 { icon=":icon-tick:" xx= "XS" }
  Content 1
- Header 2  
  Content 2 { icon="/image.png" }  
  - Header 2.1
- Header 3  
- Header 4  
  - Header 4.1  
  
  { icon="x.png" xx="xs"}  

{ icon="x.png" xx="xs"}
```

Given that we can use the "#" symbols along with the size parameter, it inherently supports media list by default.

**Comment by damithc** [comment]
> For the default configuration {icon=":fas-x:" size="sx"}, we need a line break to comply with Markbind syntax so it gets captured by the 'ul' tag above. So, the syntax will be:

line break or blank line?

What happens in the following case? `x.png` is used for the inner list or the outer list or both?

```
- ### Header 1 {icon=":icon-tick:" size= "XS" }
  Content 1
- Header 2  
  Content 2 {icon="/image.png" }  
  - Header 2.1
- Header 3  
- Header 4  
  - Header 4.1  

{icon="x.png" size="xs"}
```

> Given that we can use the "#" symbols along with the size parameter, it inherently supports media list by default.

That's good. It's nicer if we can do both with the same syntax.

**Comment by SPWwj** [comment]
> line break or blank line?

It is a blank line.

> What happens in the following case? x.png is used for the inner list or the outer list or both?

I would recommend implementing a single-tiered configuration. 
```
- ### Header 1 {icon=":icon-tick:" size= "XS" }
  Content 1
- Header 2  
  Content 2
  - Header 2.1
- Header 3  
- Header 4  
  - Header 4.1  

{icon="x.png" size="xs"}
```
Same as:
```
- ### Header 1 {icon=":icon-tick:" size= "XS" }
  Content 1 
- Header 2 {icon="x.png" size="xs"}
  Content 2
  - Header 2.1
- Header 3 {icon="x.png" size="xs"}
- Header 4 {icon="x.png" size="xs"}
  - Header 4.1  
```
The icon should only be tag to the title, thus there is a typo the in previous syntax.
Thus, this is not right
```
- Header 2  
  Content 2 {icon="/image.png" }  ```

**Comment by damithc** [comment]
@SPWwj I see. Can you post here a draft of the full explanation of the syntax that will go into the UG? That way, we have the full picture of the end result. The draft will not be a waste as it can be ported to the UG in your PR.

**Comment by SPWwj** [comment]
## Building on the current Markbind list:
```
* Primary Entry 1
  * Secondary Entry 1.1
  * Secondary Entry 1.2<br>
    Secondary Line
    * Secondary Entry 1.2.1
* Primary Entry 2
* Primary Entry 3
```

## The refined syntax for an icon list (with element-level config):
```
- Category 1 {icon="fas fa-times" size="xs"}
- Category 2 {icon="fas fa-times" size="xs"}
- Category 3 {icon="fas fa-times" size="xs"}
- Category 4 {icon="fas fa-times" size="xs"}
```
## Expected Output for Icon List (with element-level config):

<img width="331" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/116b1623-7b7a-45b3-8b6d-5ca054bd35f3">

## The refined syntax for an icon list (with regional-level config):
```
- Category 1 
- Category 2 
- Category 3 
- Category 4 

{icon="fas fa-times" size="xs"}
```
## Expected Output for Icon List (with regional-level config):

<img width="331" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/116b1623-7b7a-45b3-8b6d-5ca054bd35f3">

## The refined syntax for a media list (with element-level config):
```
- ## category 1 {icon="/image.png" size= "lg"}

  content 1 line 1,
  content 1 line 1 continue
- ## category 2 {icon="/image.png" size = "lg"}

  content 2
  - ## category 2.1
- ## category 3 {icon="/image.png" size = "lg"}

  content 3 line 1</br>
  content 3 line 2
- ## category 4 {icon="/image.png" size = "lg"}
  - ### category 4.1
```
## Expected Output for Media List (with element-level config):

<img width="524" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/c51836d8-0d29-455e-a172-2a81480a510e">

## The refined syntax for a media list (with regional-level config):
```
- ## category 1

  content 1 line 1
  content 1 line 2
- ## category 2

  content 2
  - ## category 2.1
- ## category 3

  content 3 line 1</br>
  content 3 line 2
- ## category 4
  - ### category 4.1

{icon="image.png" size="lg"}
```
<img width="524" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/c51836d8-0d29-455e-a172-2a81480a510e">
// Your image or text goes here

## Notes

Please note the crucial use of the ##blank line## between the content. It adheres to the ##markdown-it-attrs## specifications. Failing to include it will cause the header parameters to be improperly captured, as the entire header and content will be considered as a single text component.

In addition to this, remember that you can change the color of the icon by using classes within the `{}`. For example, `{class="text-danger" icon="x.png" size="xs"}` would make the icon red.

Also, keep in mind that the configuration at the bottom such as '{icon="x.png" size="xs"}' is optional. This functions as a regional-level configuration. Once declared, it applies to all its direct child elements. However, specific element-level configurations, such as `- ## category 1 {icon="/image.png" size= "xs"}`, will override the regional-level configuration.

Finally, let's explore a demonstration showcasing the interplay between regional and element-level configurations:
```
- first item1
- second item {icon="fas fa-exclamation" size="xs" class="text-warning"}
- third item
- fourth item {icon="fas fa-check" size="xs" class="text-success"}

{icon="fas fa-times" size="xs" class="text-danger"}
```
<img width="196" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/dbcee662-1606-4203-84ed-d667eef8941d">

**Comment by damithc** [comment]
@SPWwj Good to see you've collated all relevant syntax details in the post above.
1. Perhaps use 'list-level icons' rather than 'regional-level'?
1. I prefer the icon syntax to be similar to elsewhere in MarkBind `:icon-name:`
1. Should we provide a way to specify list-level icons for different nesting-levels? e.g., `icons=":fas-tick: :fas-x:"` specifies icons for the level 1 and 2 items.
  ![image](https://github.com/MarkBind/markbind/assets/1673303/874f053f-82bf-48c1-a6b0-81bede6fa8b6)
1. Is is possible to specify the size at list level but specify icon at item level, so that each item has a different icon but sized the same?
1. As these details are likely to be added to https://markbind.org/userGuide/formattingContents.html#lists, you can take the next pass to revise the draft to fit that page.

**Comment by SPWwj** [comment]
****Icon lists:****
CODE:

```
- Category 1 {icon=":x:" size="xs"}
- Category 2 {icon=":x:" size="xs"}
- Category 3 {icon=":x:" size="xs"}
- Category 4 {icon=":x:" size="xs"}
```

Output:

<img width="246" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/9c302493-d6c4-47e6-b6e4-0721f11175ac">


****Media lists:****
CODE:

```
- ## category 1 {icon="/image.png" size= "lg"}

  content 1 line 1,
  content 1 line 1 continue
- ## category 2 {icon="/image.png" size = "lg"}

  content 2
  - ## category 2.1
- ## category 3 {icon="/image.png" size = "lg"}

  content 3 line 1</br>
  content 3 line 2
- ## category 4 {icon="/image.png" size = "lg"}
  - ### category 4.1
```
Output:

<img width="524" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/c51836d8-0d29-455e-a172-2a81480a510e">

:exclamation: ****Notes:****
The **blank line** between the content is important. It adheres to the **markdown-it-attrs** specifications. Failing to include it will cause the header parameters to be improperly captured, as the entire header and content will be considered as a single text component.

:bulb:  ****Tips for icon and media list :****

- Icons support markdown emojis, FontAwesome icons, and images.
- When using a FontAwesome icon, you can alter its color by employing classes within `{}`. For instance, `{class="text-danger" icon="fas fa-times" size="xs"}` will turn the icon red.
- You have the option to append a list level at the list's end, such as `{icon=":heavy_check_mark:" size = "xs"}`. Once added, it applies to all direct child elements of the list. However, specific element-level configurations like `- 1.2.2 Icon {icon=":heavy_exclamation_mark:" size="xs"}` will supersede this list-level configuration.

    Code:
    ```
    - ## Title 1 
    
      - 1.1 Icon
      - 1.2 Icon {icon=":heavy_exclamation_mark:" size="xs"}
        - 1.2.1 Icon 
        - 1.2.2 Icon {icon=":heavy_exclamation_mark:" size="xs"}
        - 1.2.3 Icon 
        
        {icon=":heavy_check_mark:" size = "xs"}    
      
      - 1.3 Icon 
      
      {icon="icon=":x:" size = "xs"}
    
    - ## Title 2
    
      - ## Title 2.1 
    
      This is some content for the second sub item
      - ## Title 2.2 
    
      This is some content for the second sub item
      
      {icon="/logic_gate.png" size = "lg"}
    
    - ## Title 3 
    
      This is some content for the third item
      
    {icon="/deer.png" size = "lg"}
    ```
    Ouput:
    <img width="597" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/1ca111e1-7a3f-4b6b-b15e-4a2a9d16ead1">

**Comment by SPWwj** [comment]
> 1. Perhaps use 'list-level icons' rather than 'regional-level'?

:thumbsup:
> 2. I prefer the icon syntax to be similar to elsewhere in MarkBind `:icon-name:`

We can support markdown emojis, FontAwesome icons, and images, as these are all built-in features of MarkBind.

> 3. Should we provide a way to specify list-level icons for different nesting-levels? e.g., `icons=":fas-tick: :fas-x:"` specifies icons for the level 1 and 2 items.
>    ![image](https://user-images.githubusercontent.com/1673303/248000999-874f053f-82bf-48c1-a6b0-81bede6fa8b6.png)

This aligns with my plans. Additionally, considering that markdown automatically generates bullets for lists, I suggest implementing an icon="none" feature to eliminate these default bullet points.

> 4. Is is possible to specify the size at list level but specify icon at item level, so that each item has a different icon but sized the same?

Yes, the list item will use parameters set at the item level by default. If these are not specified, it will resort to those set at the list level. This allows us to specify the size at the list level while setting the icon at the item level.

> 5. As these details are likely to be added to https://markbind.org/userGuide/formattingContents.html#lists, you can take the next pass to revise the draft to fit that page.

I have updated the content to align with list format in UG https://github.com/MarkBind/markbind/issues/2272#issuecomment-1603860919

**Comment by damithc** [comment]
@SPWwj the above draft is still a bit far from what fits in our UG. In addition, I would like to approach this from how a user would actually want to customize the appearance of a list (i.e., consider realistic use cases) and cater for those only. We don't have to worry about very complicated nested lists either. 

What I came up with (based on what I actually want to do with my list appearance) is something like the UG draft given below. We can start with the simpler cases first, rather than try to do all at once. What do you think?

------------
**Customizing the list appearance**

The list icons can be customized by adding an `{icon="..."}` at the end of a list item or a list itself.

CODE:
```
* item 1 line 1 {icon=":x:"}
* item 2 line 1 
  item 2 line 2 {icon=":fas-flag:"}
* item 3
* item 4

  {icon=":tick:"}
```

OUTPUT:
...

Notes:
1. {A note on how the list-level specification and item-level specifications work}
1. {A note on the need for the blank line}
1. It is possible to any of the icons supported by MarkBind (e.g., Font Awesome, Octicons, Glyphicons, etc.) as the icon of a list item.

It is possible to specify icons for nested levels using the `icons` attribute.

CODE:
```
* item 1
* item 2 
  * item 2.1
  * item 2.2
* item 3

  {icons=":thumbs_up: :light_bulb:"}
```

OUTPUT:
👍 item 1
👍 item 2
&nbsp;&nbsp;&nbsp;💡 item 2.1
&nbsp;&nbsp;&nbsp;💡 item 2.1
👍 item 3

The icon appearance can be customized further using a `size` attribute and a `class` attribute.

CODE:
```
* item 1 line 1 {icon=":fas-home:"}
* item 2 line 1 
  item 2 line 2 {icon=":fas-user:"}
* item 3 line 1 
  item 3 line 2 {icon=":fas-flag:" class="bg-danger"}

  {size="s" class="badge bg-success me-1"}
```

OUTPUT:
![image](https://github.com/damithc/foo/assets/1673303/f5b11cb3-41eb-426e-ab78-db41363d3d25)

Another possibility is to specify a `shape` and a `background`, similar to how it is done in the [thumbnails feature](https://markbind.org/userGuide/components/imagesAndDiagrams.html#thumbnails).

CODE:
```
* item 1 {icon=":book:"}
* item 2 {icon=":pen:"}

  {shape="circle" size="100" background="#dff5ff"}
```

OUTPUT:
![image](https://github.com/damithc/foo/assets/1673303/3afb12f7-0085-4b88-8e64-70c00d2a908f)

It is possible to use images as the icon, in which case the attribute `width` can be used as well.

CODE:
```
* ### heading 1
  item 1 line 1 
  item 1 line 2 {icon="images/p1.png"}
* ### heading 2
  item 2 line 1 
  item 2 line 2 {icon="images/p2.png"}
* ### heading 3
  item 2 line 1 {icon="images/p3.png"}

  {width="100" class="rounded"}
```

OUTPUT:
...

**Comment by SPWwj** [comment]
> @SPWwj the above draft is still a bit far from what fits in our UG. In addition, I would like to approach this from how a user would actually want to customize the appearance of a list (i.e., consider realistic use cases) and cater for those only. We don't have to worry about very complicated nested lists either.

Ah, I see now. Icons and media lists are indeed the result of enhancing the current list with additional parameters.

In reviewing the above draft, several points of discussion have surfaced:

1. Examine the following Markdown instances:
    
    Consider the case of a nested list:
    
    ```markdown
    * item 1
    * item 2 
      * item 2.1
      * item 2.2
        {icons="light_bulb"}
    * item 3
    {icons="thumbs_up"}
    ```
    Render in html:
    <img width="830" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/0bee388e-f247-4f68-a62a-e887d594be04">

    
    The attribute parameters get lost when we introduce nested lists. 
    A more consistent syntax is:
    
    ```markdown
    * item 1
    * item 2 
      * item 2.1
      * item 2.2
      
      {icons="light-bulb"}
    * item 3
    
    {icons="thumbs-up"}
    ```
    
    Output:
    ![Example Output](https://github.com/MarkBind/markbind/assets/30100720/8deb39ba-782b-42a4-9b6b-9eec5a4d441b)
    
    Observe that the innermost list items are rendered as pure `<li>` elements, while the outer list items are enclosed within `<li><p>{item}</p></li>`. This suggests a potential bug in our current processing pipeline, which merits further investigation and possibly a new issue. Nonetheless, all parameters are preserved, enabling DOM manipulation to achieve our desired output.


2. The `markdown-it-attrs` plugin has issues rendering attributes containing both `-` and `::` symbols, as demonstrated in Example 1. Potential solutions could include:
   - Removing the :: in the parameter value

3. The `{icon='...'}` should only be added to list items prefixed by `-` or `*`, or as list level specifications at the end. So, we should use `* item 2 line 1 {icon="fas-flag"}` instead of `item 2 line 2 {icon=":fas-flag:"}`.

# So the refined UG would be as follow:

  ****Customizing the list appearance****
  
  The list icons can be customized by adding an {icon="..."} at the end of a list item or a list itself.
  
  CODE:
  ```
  * item 1 line 1 {icon="x"}
  * item 2 line 1 {icon="fas_flag"}
  
    item 2 line 2 
  * item 3
  * item 4
  
  {icon="tick"}
  ```
  
  OUTPUT:
  
  ...
  
  Notes:
  
  1. Item-level specifications should only be attached to the list heading or list item, not the list content.
  2. A blank line preceding the content is crucial.
  3. It's important to insert a blank line before list-level specifications.
  4. It is possible to any of the icons supported by MarkBind (e.g., Font Awesome, Octicons, Glyphicons, Images and etc.) as the icon of a list item.
  
  It is possible to specify icons for nested levels using the icons attribute.
  
  
  ```
  * item 1
  * item 2 
    * item 2.1
    * item 2.2
  
    {icons="light_bulb"}
  * item 3
  
  {icons="thumbs_up"}
  ```
  Output:
  
  <img width="148" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/5af2ffe6-73fa-4a8b-b129-bb8e53029a20">


  The icon appearance can be customized further using a size attribute and a class attribute.
  
  CODE:
  
  ```
  * item 1 line 1 {icon="fas_home"}
  * item 2 line 1 {icon="fas_user"}
  
    item 2 line 2 
  * item 3 line 1 {icon="fas-flag" class="bg_danger"}
  
    item 3 line 2 
  
  {size="s" class="badge bg-success me-1"}
  ```
  Output:

  <img width="268" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/d01f75e6-bc86-409b-a895-a3f192922716">

  Another possibility is to specify a shape and a background, similar to how it is done in the thumbnails feature.
  
  CODE:
  
  ```
  * item 1 {icon="book"}
  * item 2 {icon="pen"}
  
  {shape="circle" size="100" background="#dff5ff"}
  ```
  
  It is possible to use images as the icon, in which case the attribute `width` can be used as well.
  
  Code:
  
  ```
  * ### heading 1 {icon="images/p1.png"}
    
    item 1 line 1 
    item 1 line 2 
  * ### heading 2  {icon="images/p2.png"}
    
    item 2 line 1 
    item 2 line 2
  * ### heading 3 {icon="images/p3.png"}
  
    item 2 line 1 
  
  {width="100" class="rounded"}
  
  ```
  Output:

**Comment by damithc** [comment]
@SPWwj 

>Observe that the innermost list items are rendered as pure <li> elements, while the outer list items are enclosed within <li><p>{item}</p></li>. This suggests a potential bug in our current processing pipeline, which merits further investigation and possibly a new issue. Nonetheless, all parameters are preserved, enabling DOM manipulation to achieve our desired output.

Yes, this has been bugging me as well. It would be good to fix it. In fact, given your interest in this feature, it might be a good bug for you to attempt before implementing this new feature, to gain expertise of the relevant code areas.

Re the icon for inner levels, the following example shows the downside of having to specify the icon for second level separately, resulting in many duplicate specifications. But I'm OK with it if there is no better alternative
* item 1
  * item1.1

  {icons="light-bulb"}
* item 2 
  * item 2.1
  * item 2.2

  {icons="light-bulb"}
* item 3
  * item3.1
 
  {icons="light-bulb"}

{icons="thumbs-up"}
```

Regarding `:` in attributes, it is an internal implementation problem -- it's good if we solve it internally so that it doesn't become a user's problem. But OK to drop `:` if such a solution is too costly or not feasible.

**Comment by ang-zeyu** [comment]
We could also consider moving this forward first without support for nested lists.

**Comment by damithc** [comment]
> We could also consider moving this forward first without support for nested lists.

I'm fine with that too.

**Comment by SPWwj** [comment]
> We could also consider moving this forward first without support for nested lists.

We need to develop a function to manipulate the node, then implement BFS or DFS, should not have much different.

**Comment by ang-zeyu** [comment]
> We need to develop a function to manipulate the node, then implement BFS or DFS, should not have much different.


Documentation wise we could just advertise this however (use per list item override if we want to affect nested lists):

```
* item 1
  * item1.1 {icons="light-bulb"}
  
* item 2 
  * item 2.1
  * item 2.2 {icons="light-bulb"}
  
* item 3
  * item3.1 {icons="light-bulb"}

{icons="thumbs-up"}
```

instead of this which can cause the tight-loose list problems

```
* item 1
  * item1.1

  {icons="light-bulb"}
* item 2 
  * item 2.1
  * item 2.2

  {icons="light-bulb"}
* item 3
  * item3.1
 
  {icons="light-bulb"}

{icons="thumbs-up"}
```
