### ISSUE TITLE
Consider replacing the default favicon for conversion

### ISSUE THREAD

**Issue by lhw-1** [MarkBind/markbind#2279]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#1866

### What is the area that this feature belongs to?

Author Usability

### Is your feature request related to a problem? Please describe.

The issue was initially brought up in #1866.

The current default favicon on the navigation bar for `markbind init --convert` is as such:

![Screenshot from 2023-04-14 14-12-18](https://user-images.githubusercontent.com/25716529/231956943-bcb15c54-c2bd-49d3-bd1d-3fbb88cca0a5.png)

The concern is that this favicon (on the left) may look like the image has not been fully rendered, when it is in fact working as intended. A better-looking favicon that looks more suitable for MarkBind can replace this (for instance, the default MarkBind favicon on our [main page](https://markbind.org/)).

### Describe the solution you'd like

The current icon being used can be found [here](https://fontawesome.com/icons/file-image?f=classic&s=solid). It is a Font Awesome icon for "file image".

We can either replace this with a better looking icon (e.g. [house](https://fontawesome.com/icons/house?f=classic&s=solid) or [bars](https://fontawesome.com/icons/bars?f=classic&s=solid)), or with our custom MarkBind icon, as long as it is in line with the theme of our MarkBind default site.

The necessary file to be changed is `packages/core/src/Site/siteConvertLayout.njk`, in the navbar.

**Comment by MrGassner** [comment]
Hello, can i work on this?

**Comment by yucheng11122017** [comment]
> Hello, can i work on this?

Hi @lhw-1

**Comment by MrGassner** [comment]
I can't seem to run the server to check the change, I'm getting 2 errors.

No config file found in parent directories
uncaughtException: The "path" argument must be of type string. Received undefined date

Any guess in what I'm doing wrong?

**Comment by MrGassner** [comment]
When using `markbind serve -d`

**Comment by yucheng11122017** [comment]
> I can't seem to run the server to check the change, I'm getting 2 errors.
> 
> No config file found in parent directories uncaughtException: The "path" argument must be of type string. Received undefined date
> 
> Any guess in what I'm doing wrong?

@MrGassner sounds like you didn't run `npm setup`. Make sure you did all the steps in the [dev guide](https://markbind.org/devdocs/devGuide/development/settingUp.html) here :)

**Comment by yucheng11122017** [comment]
Closed with #2389
