### ISSUE TITLE
Remove unused renameSlot method

### ISSUE THREAD

**Issue by jovyntls** [MarkBind/markbind#2284]
The [renameSlot](https://github.com/markbind/markbind/blob/63ed8520b1208ead38162628dd055bbd9f83d8c3/packages/core/src/html/vueSlotSyntaxProcessor.ts#L69-L85) method was previously used to log warnings for deprecated slots. 

This method is no longer used and can be fully removed, as we have completed all pending deprecations that may use this method.

**Comment by fosslover69** [comment]
Well, I grepped through the whole repo and found that the renameSlot method is only used [here](https://github.com/MarkBind/markbind/blob/master/packages/core/src/html/vueSlotSyntaxProcessor.ts#L69). 

So all I need to do is just to delete it? Or is there anything else do I need to do? If just deletion is what needs to be done I'll give PR

**Comment by bibhu107** [comment]
Hi @jovyntls , I have created a PR for this change.I am new to open source community and found this change as a good to start with. Please let me know if the changes look good.

Thanks
