### ISSUE TITLE
Allow to use a div content as panel header

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#229]
Current: the following will give a seamless panel with a level 2 heading
```
<panel type="seamless" header="## Intro">
  <include src="text.md#body"/>
</panel>
```
![image](https://user-images.githubusercontent.com/1673303/40295932-b5f11828-5d0d-11e8-8c30-6e8e336c514a.png)

Suggested:
If `text.md` is as follows,
```
<div id="title">
## Intro
</div>

<div id="body">
blah blah
</div>
```

allow creating a seamless panel like this too, generating a similar output to the panel above.
```
<panel type="seamless" header="text.md#title">
  <include src="text.md#body"/>
</panel>
```
Alternatively, something like this might work too:
```
<panel type="seamless">
  <div slot="header"><include src="text.md#title" inline /></div>
  <include src="text.md#body"/>
</panel>
```

Justification:  No need to duplicate the title. The panel code can be used in boilerplates (because it can be used with different text.md files).

**Comment by damithc** [comment]
@rachx any thoughts?

**Comment by acjh** [comment]
Hmm, I don't think that's appropriate.
- We'd need to decide if it's a file (or even a fragment).
- What if the user wants to display "text.md#title" as-is?

[Panel](https://markbind.github.io/vue-strap/#accordion) already supports  `slot="header"`.
Try:

```html
<panel type="seamless">
  <span slot="header"><include src="text.md#title" /></span>
  <include src="text.md#body" />
</panel>
```

**Comment by acjh** [comment]
Does that only occur when expanded?
Try using the `inline` attribute:

```html
<include src="text.md#title" inline />
```

**Comment by damithc** [comment]
Tried that, but results in this. 
![image](https://user-images.githubusercontent.com/1673303/40298920-41ebbd16-5d17-11e8-89e9-cdf4a05f38f1.png)

Tried wrapping with `<markdown>` tags but that didn't work either.

**Comment by acjh** [comment]
Try adding `class="panel-title"`:

```html
<panel type="seamless">
  <span slot="header" class="panel-title"><include src="text.md#title" /></span>
  <include src="text.md#body" />
</panel>
```

**Comment by damithc** [comment]
Closing. Covered by #492
