### ISSUE TITLE
Allow meta-variables

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#230]
I was trying to do the following in my `variables.md` so that I can use a more meaningful name for my icon. 
`<div id="icon_prereq">{{glyphicon_education}}</div>`

That is, I can write `{{icon_prereq}}` instead of `{{glyphicon_education}}` in my code.

Looks like it (i.e., including a variable in the value of a variable) cannot be done at the moment (v1.7.4)

**Comment by yamgent** [comment]
The PR in #231 will achieve this, by allowing variables to reference each other. However, there is one restriction: the variables must be declared in order (i.e. Suppose the order declared is `A`, `B`,`C`. Then `B` can only reference `A`, and `C` can only reference `B` & `A`).

In-depth details of the explanation from the PR is attached below:

> However, a deliberate design consideration was made: we restrict the referencing to only allow earlier declared variables (yes, glyphicons counts as "earlier declared variables").
> 
> ```html
> 
> <span id="some_icon">{{glyphicon_education}}</span>
> 
> 
> <span id="first">This is the first variable.</span>
> <span id="second">{{first}}</span> 
> 
> 
> <span id="third">{{fourth}}</span> 
> <span id="fourth">This variable is declared AFTER third.</span>
> ```
> 
> The restriction is enforced to avoid circular referencing:
> ```html
> 
> <span id="first">{{second}}</span>
> <span id="second">{{first}}</span>
> ```

**Comment by damithc** [comment]
The restriction sounds reasonable. There is no restriction on the levels of referencing? i.e., `a` can refer `b` which refers `c` and so on.

**Comment by yamgent** [comment]
> There is no restriction on the levels of referencing?

Yep, no restrictions on the level of referencing.
