### ISSUE TITLE
Graphs in markbind

### ISSUE THREAD

**Issue by SPWwj** [MarkBind/markbind#2320]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently Markbind has limited graphing abilities. Adding more graph components could make it better.

### Describe the solution you'd like

Seeking your valuable suggestions for a potential feature in Markbind. 

```
- item 1 {value=10}
- item 2 {value=20}
- item 3 {value=20}
{bargraph}
```

 Here's a simple demonstration of the output, which can be further refined:

<img width="167" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/b45e61cb-8fad-4b6d-8c0b-1105e67a1d20">

This is a bar graph demo, clearly indicating that we can convert it into other forms such as a mind map.

**Comment by damithc** [comment]
@SPWwj Graphs and charts is indeed a feature we want to add to MarkBind. That said, I prefer to integrate with a third-party library specializing in graphs and charts, rather than implement our own (similar to how we use PlantUML for UML diagrams).

**Comment by tlylt** [comment]
More info on graphs/charts is available here:
- https://github.com/MarkBind/markbind/issues/1663
- https://markbind.org/userGuide/usingHtmlJavaScriptCss.html#javascript-libraries

**Comment by SPWwj** [comment]
> More info on graphs/charts is available here:
> 
> * [Support basic charts #1663](https://github.com/MarkBind/markbind/issues/1663)
> * https://markbind.org/userGuide/usingHtmlJavaScriptCss.html#javascript-libraries

Thanks, did not find this issue from the graph keyword😂
