### ISSUE TITLE
Inline mask feature for text.

### ISSUE THREAD

**Issue by SPWwj** [MarkBind/markbind#2323]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Not sure if anyone wants to see this feature in MarkBind, but it could be quite handy for interactive quizzes.

<img width="187" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/142a2003-11a8-4f44-9adf-1afe65b40d87">
<img width="387" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/80a50f5e-b451-4ede-b01d-2dc004f483f7">

### Describe the solution you'd like

@[mask: test to mask]

<img width="387" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/80a50f5e-b451-4ede-b01d-2dc004f483f7">

**Comment by damithc** [comment]
Interesting feature. @SPWwj thanks for suggesting it.
I choose features based on what I will be using in my MarkBind sites so that the feature-set remain focused and field-tested. So, I would not add this feature at this time as I use Canvas for my quizzing needs.
