### ISSUE TITLE
Closing a panel without animation is disorientating

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2337]
In https://github.com/MarkBind/markbind/pull/2159 we removed the closing animation for panels. 
But now, closing a panel results in a sudden change of content in the page and it is very hard to find where one was before. We need to bring back that animation, at least for shorter panels.

**Comment by tlylt** [comment]
> Giving this a higher priority as we use expandable panels a lot in CS2103 website e.g., [nus-cs2103-ay2122s2.github.io/website/schedule/week2/topics.html](https://nus-cs2103-ay2122s2.github.io/website/schedule/week2/topics.html)

Do you have a specific example of how it's problematic on this page?
I'm ok with adding back but I'm not sure if there's an issue with hard-to-find where one was before? Seems alright to me.

**Comment by damithc** [comment]
> Hmm I just checked the updated site locally and still it looks fine, if anything I'm guessing it's only an issue when you close the panels from the very bottom towards the top? In that case the closing is not very smooth.

@tlylt 
Yes, that's the issue I faced. Sorry, forgot to mention that. Perhaps we add back the animation for that button only?

**Comment by tlylt** [comment]
> > Hmm I just checked the updated site locally and still it looks fine, if anything I'm guessing it's only an issue when you close the panels from the very bottom towards the top? In that case the closing is not very smooth.
> 
> 
> 
> @tlylt 
> 
> Yes, that's the issue I faced. Sorry, forgot to mention that. Perhaps we add back the animation for that button only? I think reverting our original update is definitely possible.

@yucheng11122017 do you have bandwidth to help with this? Given ur previous involvement in this.
