### ISSUE TITLE
Unexpected caret at: `lowerNavbar`.

### ISSUE THREAD

**Issue by SPWwj** [MarkBind/markbind#2341]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#2093

### Tell us about your environment

Window 10

### MarkBind version

  v5.0.1

### Describe the bug and the steps to reproduce it

1. Enter [Markbind](https://markbind.org/userGuide/components/presentation.html).
2. Adjust the window size of the browser until the `lowerNavbar` appears.
3. Click on the expansion icon of the `lowerNavbar`.
4. Observe the blinking caret.

https://github.com/MarkBind/markbind/assets/30100720/32e2f08b-ad0b-46c8-9f9c-621ffba20672

### Expected behavior

No caret at the lowerNavbar

### Anything else?

nil

**Comment by tlylt** [comment]
@SPWwj are you slowly down the page or something? I tried clicking on that top left button and seems alright to my eye with no caret.
Link that I tried on:
https://markbind.org/userGuide/components/presentation.html

**Comment by lesterong** [comment]
I am unable to replicate this issue as well. Tested on the same link on both Windows 11 and Mac, both with Microsoft Edge.

**Comment by SPWwj** [comment]
> @SPWwj are you slowly down the page or something? I tried clicking on that top right button and seems alright to my eye with no caret. Link that I tried on: https://markbind.org/userGuide/components/presentation.html

I don't think speed matters. The caret appears when the `toggle-page-nav-button` is focused. It persists and does not disappear until I click on another element.

I have also checked the CSS. The `toggle-page-nav-button` does not include the `caret-color: transparent;` attribute.
By right, the caret should appear when the text is clicked.

**Comment by SPWwj** [comment]
> I am unable to replicate this issue as well. Tested on the same link on both Windows 11 and Mac, both with Microsoft Edge.
Here is my setting:
Microsoft Edge
Version 114.0.1823.82 (Official build) (64-bit)

Edition	Windows 11 Pro
Version	22H2
Installed on	‎21/‎12/‎2022
OS build	22621.1992
Experience	Windows Feature Experience Pack 1000.22644.1000.0

**Comment by tlylt** [comment]
> > I am unable to replicate this issue as well. Tested on the same link on both Windows 11 and Mac, both with Microsoft Edge.
> > Here is my setting:
> > Microsoft Edge
> > Version 114.0.1823.82 (Official build) (64-bit)
> 
> Edition Windows 11 Pro Version 22H2 Installed on ‎21/‎12/‎2022 OS build 22621.1992 Experience Windows Feature Experience Pack 1000.22644.1000.0

Could you specify the exact step to reproduce this issue? I tried on Windows 10 - Chrome & Microsoft Edge and don't get what you are describing.

**Comment by lesterong** [comment]
Hi @SPWwj, by any chance do you have Caret browsing turned on? I think that might be the issue.

https://support.microsoft.com/en-us/topic/using-caret-browsing-in-microsoft-edge-for-mac-93bfae33-aca0-44ca-b504-02960a72bc31

**Comment by SPWwj** [comment]
> Could you specify the exact step(s) to reproduce this issue? I tried on Windows 10 - Chrome & Microsoft Edge and don't get what you are describing.

Just like in the video clip you see in the PR description:
1. Enter `https://markbind.org/userGuide/components/presentation.html`.
2. Adjust the window size of the browser until the `lowerNavbar` appears.
3. Click on the expansion icon of the `lowerNavbar`.
4. Observe the blinking caret.

**Comment by tlylt** [comment]
> > Could you specify the exact step(s) to reproduce this issue? I tried on Windows 10 - Chrome & Microsoft Edge and don't get what you are describing.
> 
> Just like in the video clip you see in the PR description:
> 
> 1. Enter `https://markbind.org/userGuide/components/presentation.html`.
> 2. Adjust the window size of the browser until the `lowerNavbar` appears.
> 3. Click on the expansion icon of the `lowerNavbar`.
> 4. Observe the blinking caret.

do you observe this issue on other browsers?

**Comment by SPWwj** [comment]
> do you observe this issue on other browsers?

I just tried with Chrome, and it seems like this issue only appears in Edge.
Even after disabling all my plugins in Edge, the caret still appears.

**Comment by lesterong** [comment]
> > do you observe this issue on other browsers?
> 
> I just tried with Chrome, and it seems like this issue only appears in Edge. Even after disabling all my plugins in Edge, the caret still appears.

Have you tried pressing F7 to check if caret browsing is on in Microsoft Edge? I can replicate the issue if I have caret browsing turned on.

**Comment by SPWwj** [comment]
> Hi @SPWwj, by any chance do you have Caret browsing turned on? I think that might be the issue.
> 
> https://support.microsoft.com/en-us/topic/using-caret-browsing-in-microsoft-edge-for-mac-93bfae33-aca0-44ca-b504-02960a72bc31

Yes this is the cause.

**Comment by damithc** [comment]
> I can replicate the issue if I have caret browsing turned on.

TIL _caret browsing_ :-p
