### ISSUE TITLE
UG: typo in scroll to top feature

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2342]
V5

See https://markbind.org/userGuide/components/navigation.html

![image](https://github.com/MarkBind/markbind/assets/1673303/36c740c7-d32c-4852-a7c2-aca78b393bb5)

Should be something like this?

>Add a `<scroll-top-button/>` to the corresponding layout file.

**Comment by tlylt** [comment]
should be fine both ways

**Comment by damithc** [comment]
> should be fine both ways

@tlylt In the current one, the `/` is at the end rather than at the start of the tag.

**Comment by tlylt** [comment]
> > should be fine both ways
> 
> @tlylt In the current one, the `/` is at the end rather than at the start of the tag.

Yup you are right, I got confused 🤯  definitely should fix this.
