### ISSUE TITLE
Support multiple levels in top navbar

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2343]
See https://markbind.org/userGuide/components/navigation.html#navbars

It would be good if we can provide support for second level sub-menu items in the top navigation bar dropdowns.

![image](https://github.com/MarkBind/markbind/assets/1673303/4a44fedc-0c44-408b-9919-c5c9b0178c9b)

**Comment by SPWwj** [comment]
We can just reuse the list to achieve the feature:
```
  * btn 1 {link class="dropdown-item"  }
  * btn 2
    * btn 2.1 {class="dropdown-item" href="#navbars" }
```

Everything remains the same except for the extra `link` attribute to remove the default list padding, similar to `icon`.

**Comment by damithc** [comment]
@SPWwj Are you suggesting a complete change to the [current TopNav component/syntax](https://markbind.org/userGuide/components/navigation.html#navbars)?

**Comment by SPWwj** [comment]
> @SPWwj Are you suggesting a complete change to the [current NavBar component/syntax](https://markbind.org/userGuide/components/navigation.html#navbars)?

No, it is more like an extension to the list:
```
<navbar type="primary">
  <!-- Brand as slot -->
  <a slot="brand" href="/" title="Home" class="navbar-brand">MarkBind</a>
  <li><a href="/userGuide/components/navigation.html#navbars" class="nav-link">Highlighted Link</a></li>
  <!-- You can use dropdown component -->
  <dropdown header="Dropdown" class="nav-link">

  * [link](#navbars) {link class="dropdown-item"  }
  * link 2
    * [link 2.1](#navbars) {link class="dropdown-item"  }
  * link 3
  * link 4
  </dropdown>
  <!-- For right positioning use slot -->
  <li slot="right">
    <a href="https://github.com/MarkBind/markbind" target="_blank" class="nav-link">Fork...</a>
  </li>
</navbar>
```
current output:
<img width="678" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/960ac06d-5845-4855-9453-5aeccfe72379">

**Comment by damithc** [comment]
@SPWwj Oh you mean it can be done using the current syntax already?
I need the second level to be revealed on demand. Otherwise the following will become a dropdown with nearly 80 items, if I were to add five second level items for each of the weeks.
![image](https://github.com/MarkBind/markbind/assets/1673303/152cca7f-adac-4f09-8bc8-4c47811ce8f5)

**Comment by SPWwj** [comment]
> @SPWwj Oh you mean it can be done using the current syntax already? I need the second level to be revealed on demand. Otherwise the following will become a dropdown with nearly 80 items, if I were to add five second level items for each of the weeks. ![image](https://user-images.githubusercontent.com/1673303/256435839-152cca7f-adac-4f09-8bc8-4c47811ce8f5.png)

We still need some CSS manipulation to hide and show the block.

https://github.com/MarkBind/markbind/assets/30100720/8ce2d245-2bab-488f-b7ad-1142f97c6e71

**Comment by yucheng11122017** [comment]
Hi @damithc, can this already be achieved with the [multi level dropdown](https://markbind.org/userGuide/components/navigation.html#dropdowns:~:text=Dropdowns%20can%20also%20be%20nested%20within%20each%20other%20to%20create%20multi%2Dlevel%20submenus.)? 


Example: 

```
    <navbar type="primary">
      <!-- Brand as slot -->
      <a slot="brand" href="/" title="Home" class="navbar-brand">MarkBind</a>
      <li><a href="/userGuide/components/navigation.html#navbars" class="nav-link">Highlighted Link</a></li>
      <!-- You can use dropdown component -->
      <dropdown header="Dropdown" class="nav-link">
        <li><a href="#navbars" class="dropdown-item">Option</a></li>
        <dropdown header="*Submenu*">
          <li><a href="#dropdown" class="dropdown-item">Item</a></li>
          <li><a href="#dropdown" class="dropdown-item">Another item</a></li>
        </dropdown>
      </dropdown>
      <!-- For right positioning use slot -->
      <li slot="right">
        <a href="https://github.com/MarkBind/markbind" target="_blank" class="nav-link">Fork...</a>
      </li>
    </navbar>
```


Produces 
![image](https://github.com/MarkBind/markbind/assets/77204346/3a031b66-b576-4698-a461-48b0c77353c6)

**Comment by damithc** [comment]
> Hi @damithc, can this already be achieved with the [multi level dropdown](https://markbind.org/userGuide/components/navigation.html#dropdowns:~:text=Dropdowns%20can%20also%20be%20nested%20within%20each%20other%20to%20create%20multi%2Dlevel%20submenus.)?

Ah, nice! Didn't realize this :-p
Thanks @yucheng11122017
