### ISSUE TITLE
Add horizontal spacing between the icon and text in the custom icon list

### ISSUE THREAD

**Issue by SPWwj** [MarkBind/markbind#2352]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

Nil

### What is the area that this feature belongs to?

Author Usability, Reader Usability, Syntax

### Is your feature request related to a problem? Please describe.

From the PR discussion [here](https://github.com/MarkBind/markbind/pull/2316#discussion_r1278565954):

A feature is needed to let users adjust spacing between customized icons and content, accommodating diverse user preferences.

### Describe the solution you'd like

Some ideas:

Introduce an `i-spacing` attribute to customize the spacing between an icon and its associated list content.

### Example Usage:

```
* Item 1 {icon="/images/deer.jpg" i-width="60px" i-spacing="0.35em"}
* Item 2 { i-spacing="0.55em"}
* Item 3 { i-spacing="0.75em"}
```

Sample output:
<img width="404" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/446c8d56-3ef9-4f18-a01f-72a45680accc">

**Comment by Ashleeey1224** [comment]
hi, currently I'm learning how to do first PR for a open resource repo, may I take this issue to work on?
Thank you:)

**Comment by Ashleeey1224** [comment]
I'm going to work on this issue, thxx

**Comment by SPWwj** [comment]
@Ashleeey1224 You may refer to this to speed up the developement process of this feature: 

https://github.com/SPWwj/Spirify-Ui/blob/master/src/components/markdown/ListPlugin.ts
https://github.com/SPWwj/Spirify-Ui/blob/master/src/components/markdown/ListPlugin.scss

**Comment by Ashleeey1224** [comment]
Hi SPWwj,

Thank you for your support! I really appreciate!

Have a good day.
Cheers,
Ashley Yang

On 18 Oct 2023, at 3:12 pm, SPWwj ***@***.***> wrote:



@Ashleeey1224<https://github.com/Ashleeey1224> You may refer to this to speed up the developement process of this feature:

https://github.com/SPWwj/Spirify-Ui/blob/master/src/components/markdown/ListPlugin.ts
https://github.com/SPWwj/Spirify-Ui/blob/master/src/components/markdown/ListPlugin.scss

**Comment by Ashleeey1224** [comment]
Several Questions wanna clarify:
1. Is the icon considered as "emoji" and "image"? or only image?
2. Where I should put image file: If I want to test image, where I should put? Based on the sample output and previous PR, the relative path is "/images/deer.jpg".  And I also found _images_ file under _docs_ 
3. When I try to load image from "/docs/images",  console shows: 
```
 warn: You might have an invalid intra-link! Ignore this warning if it was intended.
'/contents/docs/images/deer.jpg' found in file '/Users/Sammy/Desktop/markbind/contents/topic1.md'
```

Is it appropriate?

Thaxx for reply :D

**Comment by Ashleeey1224** [comment]
Hi, I think I figure it out, may I open a PR?

**Comment by SPWwj** [comment]
> Hi, I think I figure it out, may I open a PR?
@tlylt any comments?

**Comment by Ashleeey1224** [comment]
If it is okay, may I open a draft pr and get some feedback first?

**Comment by tlylt** [comment]
> If it is okay, may I open a draft pr and get some feedback first?

Sure, @Ashleeey1224. I haven’t got the chance to understand the context here, but please feel free to raise a PR, will take a look afterwards.

**Comment by tlylt** [comment]
@SPWwj, looking at your referenced PR discussion, it seems like it wasn't simply adding a feature to let users configure the horizontal space, but rather:
- is the default spacing currently provided OK for most cases?
- if not, should we either
  - investigate a way to "automatically scale horizontal spacing between icon and content" quoting @ang-zeyu verbatim
  - or
  - add a simple way for users to adjust the spacing directly (should be what you prefer (?) I suppose)

Could you help me verify if you recall the discussion?

**Comment by tlylt** [comment]
@damithc quick question: Per https://github.com/MarkBind/markbind/pull/2316#issuecomment-1703003678
Have you needed to adjust the spacing, or was it OK for your usage so far?

**Comment by SPWwj** [comment]
> Could you help me verify if you recall the discussion?

Hi @tlylt, from @ang-zeyu's feedback, the icon spacing seems a bit too tight for his preference. He suggests implementing an i-spacing configuration for greater flexibility or `spacing automatically according to width of the icon, up to a certain maximum` for less flexibility.

Would it be better if we have some sample screenshots showing the different icon spacing on different screens? This would help us determine the optimal display. What are your thoughts, @Ashleeey1224 and @tlylt?

**Comment by tlylt** [comment]
> Would it be better if we have some sample screenshots showing the different icon spacing on different screens? This would help us determine the optimal display. What are your thoughts, @Ashleeey1224 and @tlylt?

Yes would be nice to see them to compare the approaches. @Ashleeey1224 would you be able to help?

**Comment by damithc** [comment]
> @damithc quick question: Per [#2316 (comment)](https://github.com/MarkBind/markbind/pull/2316#issuecomment-1703003678)
> Have you needed to adjust the spacing, or was it OK for your usage so far?

@tlylt Not specifically, but I'm fine to provide this flexibility to authors. It may be useful in some situations.

**Comment by kaixin-hc** [comment]
To clarify the concern behind why the PR was closed, it was regarding whether the spacing should be automatic (based on width of the icon) or able to be manually modified (as in the PR). 

I feel adding the manual modification is okay because it still has a default value, so the work to the average user is minimal - while implementing automatic spacing could lead to some sort of edge case. We could also do changes to this incrementally - merge manual spacing first, and if it makes sense to implement additional automatic spacing, that can be done in another PR afterwards.
