### ISSUE TITLE
Modal component: bs-modal css variables not defined

### ISSUE THREAD

**Issue by jmestxr** [MarkBind/markbind#2353]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

MacOS Ventura

### MarkBind version

5.0.1

### Describe the bug and the steps to reproduce it

**Bug description:**

To reproduce the bug, set the bootswatch theme to any theme other than default and use a `modal` component.

When using a (non-default) bootswatch theme, bs-modal css variables for modal component are not found, resulting in it not being styled properly:

<img width="1440" alt="Screenshot 2023-08-09 at 11 00 26 PM" src="https://github.com/MarkBind/markbind/assets/87931905/2c7ff0cb-994e-44e0-9652-b6b6a6c245e6">

<em><strong>bootswatch theme used: 'sketchy'</strong></em>

<br><br>

Upon further probing, I found out this was due to `bs-modal` css variables not being registered:

<img width="316" alt="Screenshot 2023-08-09 at 10 34 45 PM" src="https://github.com/MarkBind/markbind/assets/87931905/c0a8125d-ee27-43df-af96-e40c94f54869">

<br><br>

These variables are defined in bootstrap's `modal` class, which were not specified in the Modal vue component:

<img width="317" alt="Screenshot 2023-08-09 at 10 46 08 PM" src="https://github.com/MarkBind/markbind/assets/87931905/84c23c16-b731-4f0f-a1ce-5b87441f3563">

<br><br>

<img width="457" alt="Screenshot 2023-08-09 at 10 46 51 PM" src="https://github.com/MarkBind/markbind/assets/87931905/0c90a136-2b90-4e2b-b51c-b820e91248ce">

<em><strong>`modal` class not specified in Modal component</strong></em>

<br><br>

**Fix:**
- Add `modal` class in vue component
- bootstrap's `modal` class contains a `display: none`. To override this, I added a `display: block` to modal-dialog class to fix this so the modal can be seen.

<img width="1440" alt="Screenshot 2023-08-09 at 10 55 44 PM" src="https://github.com/MarkBind/markbind/assets/87931905/5f56e4eb-295d-41d0-bb40-aa6af07226f2">

<br><br>

**Additional notes:**

- This does not happen in 'default' bootstrap theme, as modal css variables are not used in the `bootstrap.min.css` file for default theme

**Comment by tlylt** [comment]
Hey @jmestxr, thank you for opening this issue! Great observation and I can indeed reproduce this.

Before we proceed with the fix suggested in #2354, may I know if you have found the reason why it works in default but not in other themes?
- Yes there are missing CSS variables like `--bs-modal-bg`, but **why** are they missing?

I took a brief look and observe that bootswatch themes uses "Bootstrap  v5.2.3" while markbind by default ships "Bootstrap v5.1.3". Is that the underlying reason?
- If so, could the solution be that we need to pin the `bootswatch` version that we ship with so that they are in sync with our Bootstrap version? Also, does it mean that when we migrate our Bootstrap version to v5.2, the default theme will have the same problem?
- If that's the case, is there a better solution to deal with this modal CSS issue once and for all?

![image](https://github.com/MarkBind/markbind/assets/41845017/3e1cab58-5403-498f-b032-b6073287fe75)
![image](https://github.com/MarkBind/markbind/assets/41845017/466cc598-8fee-48b1-a96a-f249e16a64b0)

Please feel free to investigate further and let me know if you have any insights on this!

**Comment by jmestxr** [comment]
> * Yes there are missing CSS variables like `--bs-modal-bg`, but **why** are they missing?

It seems they are missing because those variables are defined locally within the `.modal` class of `bootstrap.min.css`.  
Hence for the fix, I added the `modal` class to `vue-final-modal` which wasn't added previously:

> I took a brief look and observe that bootswatch themes uses "Bootstrap v5.2.3" while markbind by default ships "Bootstrap v5.1.3". Is that the underlying reason?

Yeah. It seems ur right! For default theme, we are using bootstrap.min.css that is using v5.1.3, which does not use any --bs-modal variables:

<img width="813" alt="Screenshot 2023-08-21 at 8 51 43 PM" src="https://github.com/MarkBind/markbind/assets/87931905/5f61a69d-6d84-4378-801c-78b9fec688c2">


Whereas for the bootstrap.min.css that is using v5.2.3, they are being used:

<img width="876" alt="Screenshot 2023-08-21 at 8 51 34 PM" src="https://github.com/MarkBind/markbind/assets/87931905/d38a9b01-5f20-49ee-ad9b-b9ff9e5c1bd3">


The other bootswatch themes are using Bootstrap v5.2.3 for their bootstrap.min.css, where --bs-modal variables are used.


> * If so, could the solution be that we need to pin the `bootswatch` version that we ship with so that they are in sync with our Bootstrap version? 

This wouldn't seem to be the solution because the problem lies that we didn't specify `.modal` class in our vue-final-modal, where --bs-modal variables are defined locally.

However to ensure that the same styling behavior for default and other themes, I agree we should sync bootswatch and bootstrap versions.

> Also, does it mean that when we migrate our Bootstrap version to v5.2, the default theme will have the same problem?

Yeah, because bootstrap.min.css for default theme is using --bs-modal variables within `.modal` class, which is not specified currently.

> * If that's the case, is there a better solution to deal with this modal CSS issue once and for all?

Yeah, perhaps we can instead downgrade all bootswatch versions to 5.1.3. which can be downloaded [here](https://github.com/thomaspark/bootswatch/releases/tag/v5.1.3), to be on sync with the current Bootstrap version.

But if we were to upgrade to Bootstrap 5.2.3 in future, we will need to specify `modal` class in vue-final-modal, which is what my fix is doing currently.

**Comment by jmestxr** [comment]
> Have you tried downgrading bootswatch to 5.1.3 (or any higher version that ships with the same bootstrap version?...I'm not sure how they version their package) and see if the modals work for all themes?

I tried downgraded to bootswatch 5.1.3 and the modals are working!

> Specifically for this issue though, were you able to find out from Bootstrap's end why did they make such a change for the modal CSS and any guidance from them on how to best migrate it?

Seems like bootstrap made the change to include component variables (not just for modals) for easier theming: https://blog.getbootstrap.com/2022/07/19/bootstrap-5-2-0/
