### ISSUE TITLE
Include a default footer.md during initialisation

### ISSUE THREAD

**Issue by Chng-Zhi-Xuan** [MarkBind/markbind#236]
Follows #187  

- User requested a `footer.md` to be generated, to credit **MarkBind** for generating the site. Either by using our default `{{timestamp}}` variable or through a link back to **MarkBind**'s website.

**Comment by damithc** [comment]
What does the current `{{timestamp}}` output? Ideally, it should produce just a time stamp only, to match its name. The `footer.md` will contain a longer text `Generated by ...` etc.
