### ISSUE TITLE
Custom list icons syntax: make the space before `{` optional

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2368]
Current:
`* item {icon="fas-home"}` works
`* item{icon="fas-home"}` does not work

Suggestion: make the 2nd one work as well

**Comment by damithc** [comment]
@SPWwj can confirm this behavior? Any thoughts on the above suggestion?

**Comment by SPWwj** [comment]
> @SPWwj can confirm this behavior? Any thoughts on the above suggestion?

I can't reproduce the bug on my end; both syntaxes work for me.
both syntax work for me:
<img width="390" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/56aa18bb-4606-4878-8092-2f7ec4b9b614">

Could you share the exact code that causes the bug?

I think this issue appears to be related to the behavior of the markdown-it-attrs plugin. The attributes only affect the nearest tag for inline binding.
<img width="448" alt="image" src="https://github.com/MarkBind/markbind/assets/30100720/608e5200-44b0-4b01-b855-2a3e12178f02">

**Comment by damithc** [comment]
@SPWwj forgot to respond to this earlier. I can't reproduced this now, in isolation. Likely it was influenced by something else in the surrounding area when I observed it. Will close for now.
