### ISSUE TITLE
Icons in 'Presentation' components (e.g. box, panels, tabs) are not rendered properly

### ISSUE THREAD

**Issue by jmestxr** [MarkBind/markbind#2371]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

applicable for all

### MarkBind version

5.1.0

### Describe the bug and the steps to reproduce it

Icons in 'Presentation' components are not rendered properly with indentation. For example, the following block of code:

<img width="735" alt="Screenshot 2023-10-09 at 8 23 24 PM" src="https://github.com/MarkBind/markbind/assets/87931905/17d84b5e-1455-458d-9a21-89436e765f0f">

produces

<img width="859" alt="Screenshot 2023-10-09 at 8 24 06 PM" src="https://github.com/MarkBind/markbind/assets/87931905/b1b401d7-1027-43c9-b549-b4bab34278b9">

Moreover, presence/absence of newlines also affect rendering. For example,

<img width="722" alt="Screenshot 2023-10-09 at 8 27 27 PM" src="https://github.com/MarkBind/markbind/assets/87931905/904f43eb-4813-4c9f-8ff1-91175ffc4e83">

produces

<img width="899" alt="Screenshot 2023-10-09 at 8 27 32 PM" src="https://github.com/MarkBind/markbind/assets/87931905/e1a87fb2-06e9-4dba-8c61-53ada45c31b3">

but

<img width="788" alt="Screenshot 2023-10-09 at 8 28 21 PM" src="https://github.com/MarkBind/markbind/assets/87931905/5c5b1404-fac5-4e60-8d0e-d5a8deac215a">

produces

<img width="882" alt="Screenshot 2023-10-09 at 8 28 16 PM" src="https://github.com/MarkBind/markbind/assets/87931905/1dbca015-ab2f-4313-9019-8013bac16d8a">

### Expected behavior

Icons should be rendered properly in these components, regardless of indentation size/newlines.

**Comment by damithc** [comment]
@jmestxr From what I know, MarkBind (due to the parser used) follows the Markdown rule that requires a blank line to separate Markdown text from other text (e.g., HTML text). Otherwise the text is not parsed an Markdown but treated as plain text (I think).

Even GitHub behave the same way e.g., 
```
<p>
**abc**
</p>
```

Output: `**abc**`

**Comment by jmestxr** [comment]
@damithc I see. Perhaps we could put a note in UG stating that per Markdown rule, a new line and no indentation should be included when including content in tabs/panels/boxes?

**Comment by damithc** [comment]
> @damithc I see. Indentation may also cause text with icons to be parsed as plain text. Perhaps we could put a note in UG stating that per Markdown rule, a new line and no indentation should be included when including content in tabs/panels/boxes?

Yes @jmestxr, I think that is a good idea.

**Comment by tlylt** [comment]
@jmestxr we have a section here on this: https://markbind.org/userGuide/usingHtmlJavaScriptCss.html#markdown-in-html
but yes if the indentation is also important, we should highlight that. With that, we should probably add a dedicated section in https://markbind.org/userGuide/troubleshooting.html to highlight some common usage that may result in such error and how t o fix them

**Comment by damithc** [comment]
Keeping in mind that users will just read the section of the UG relevant to the component they want to use, perhaps we can do the following:
* adjust the code examples (such as the one below) to have a blank line in the expected places
* mention the need for a blank line in the UG section of each affected component (there will be duplication, but MarkBind can handle duplication using `<inlcude .. >`).

![image](https://github.com/MarkBind/markbind/assets/1673303/7812fb88-c6ce-44ad-9b79-07a18d9bc015)

**Comment by yiwen101** [comment]
Hi, I would like to give this issue a try.
