### ISSUE TITLE
Error in render some source code with some characters

### ISSUE THREAD

**Issue by BrahianVT** [MarkBind/markbind#2376]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

2.9.0

### Describe the bug and the steps to reproduce it

trying to create a blog about programming languages I was facing some issues with some source codes: when working with markdown and nutjunks :
example :
I traced the error to this part:
```  
array onehundreddoors()
{
    array doors = allocate(100);
    foreach(doors; int i;)
        for(int j=i; j<100; j+=i+1)
            doors[j] = !doors[j];
    return doors;
}

array doors = map(enumerate(100,1,1), lambda(int x)
                                      {  
                                          return sqrt((float)x)%1 == 0.0; 
write("%{%d %d %d %d %d %d %d %d %d %d\n%}\n", doors/10)

 
``` 

Is calling here in nutjucks:
```
  <div id="content" class="prose text-slate-800 max-w-none">
        {{ content | safe }}
    </div>
```

I got this: 
![image](https://github.com/MarkBind/markbind/assets/12876560/5ea97071-e457-4a3b-9c4e-6fdbc6cbae2f)

    
The  problem is the  last line, I  modified it to :
write("%{ \n%}\n", doors/10)

And is working with this, but I have anothers source codes with the same issues, and also I can't modify the source code of all the  articles I wanna write.
So anyone know how to face it?, I'm a newbie 
Regards

### Expected behavior

I expect a correct render

**Comment by tlylt** [comment]
Hi @BrahianVT, could you point out the exact snippet of text that you used in your .md file, which is causing this error?

**Comment by BrahianVT** [comment]
yes , is in the post : 

```
```pike  
array onehundreddoors()
{
    array doors = allocate(100);
    foreach(doors; int i;)
        for(int j=i; j<100; j+=i+1)
            doors[j] = !doors[j];
    return doors;
}

array doors = map(enumerate(100,1,1), lambda(int x)
                                      {  
                                          return sqrt((float)x)%1 == 0.0; 
                                      });

write("%{%d %d %d %d %d %d %d %d %d %d\n%}\n", doors/10)

 ```     -> Here the problem is in the last line "write"
```

**Comment by tlylt** [comment]
Hi @BrahianVT, could you try wrapping the code block with our raw escape tag, i.e. `{% raw %}{% endraw %}`.
- the relevant documentation is [here](https://markbind.org/userGuide/tipsAndTricks.html#using-raw-endraw-to-display-content)
e.g.
![image](https://github.com/MarkBind/markbind/assets/41845017/6dbaa965-fd0d-4be5-8982-622502c59bdf)
this way the rendered output is:
![image](https://github.com/MarkBind/markbind/assets/41845017/c37c7b6d-d5b9-4d8a-b62b-a496ad091d91)

Unfortunately pike is not a supported language hence there's no syntax highlighting. I tested this using MarkBind version 5.0.2, and it should also work with the latest 5.1.0. If you have issues replicating what I have done, could you try upgrading your MarkBind version?

Let me know if this addresses your problem 🙆‍♂️

**Comment by BrahianVT** [comment]
Thanks @tlylt is working with these tags
