### ISSUE TITLE
Allow `markbind serve` to specify custom host

### ISSUE THREAD

**Issue by RichDom2185** [MarkBind/markbind#2382]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Author Usability, CLI, DevOps

### Is your feature request related to a problem? Please describe.

According to the [documentation](https://markbind.org/userGuide/cliCommands.html#serve-command), `markbind serve` starts a webserver at `127.0.0.1` aka `localhost`, but there does not seem to be a way to customise this.

My use case is that I have a separate machine as a dev server and I remote into this machine from my other devices to edit code.

However, as `localhost` does not expose the port to the local network, I can't access the previewed site remotely.

I would ideally like to set the host to `0.0.0.0` to expose on all interfaces.

Other potential use cases:

* Expose only from a specific interface
* Multi-person collaborative editing off a single codebase

### Describe the solution you'd like

Support passing `--host` and/or `-h` to the `markbind serve` command, e.g. `--host 0.0.0.0`.

~~As an extension, perhaps allow `host` and `port` to be specified in `site.json` as well (the CLI option will still take precedence in case both are specified)~~ – on second thought, having this might make `site.json` not as deploy-agnostic anymore, but I left it here as food for thought.

**Comment by RichDom2185** [comment]
Seems like

https://github.com/MarkBind/markbind/blob/9fb63a89bce110c82c51cbeaf2b18f34e56f02c7/packages/cli/src/cmd/serve.js#L114

is the cause, perhaps we could just update

https://github.com/MarkBind/markbind/blob/9fb63a89bce110c82c51cbeaf2b18f34e56f02c7/packages/cli/src/cmd/serve.js#L61-L68

to allow the host specification?

**Comment by tlylt** [comment]
The suggestion is fair, [mkdocs](https://www.mkdocs.org/user-guide/cli/#mkdocs-serve) and [docusaurus](https://docusaurus.io/docs/cli#docusaurus-serve-sitedir) have this support as well.
![image](https://github.com/MarkBind/markbind/assets/41845017/ca17344b-5555-4657-bdeb-988b0e1cf77d)
![image](https://github.com/MarkBind/markbind/assets/41845017/7033315c-7ba8-4079-8225-7536737ec99c)

`--host` is ok
- `-h` might conflict with `--help`'s short form?

**Comment by lhw-1** [comment]
We could alternatively use `--address` with the short form `-a`, which is still available for the serve` command. `--dev-addr` and `-a` like MKDocs might also work, but `--address` might be more straightforward as long as we document it properly [here](https://markbind.org/userGuide/cliCommands.html#serve-command).

**Comment by EltonGohJH** [comment]
I agree with @lhw-1 that address would work and I think this should be a good first issue.

**Comment by LamJiuFong** [comment]
I would like to work on this first issue
