### ISSUE TITLE
Image annotation: support 'slot' syntax for the content attribute

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2403]
For image annotations, perhaps we can support the `slot` syntax for the content attribute, to allow more complicated content?

![image](https://github.com/MarkBind/markbind/assets/1673303/0808da5e-8e1d-4696-87f8-fb4a36124106)

**Comment by yucheng11122017** [comment]
Seems like a good idea!
One think we might need to rethink is the naming of content in that case. Could be confusing to call it content when a-point also supports different shapes now.
