### ISSUE TITLE
page title of index.md created by init is overridden by site.json

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#242]
v1.7.4

Current: When initializing a site using `markbind init`, it creates an `index.md` that has a `title` property. The generated `site.json` also specify a title for the same page, which happens to have the save value `Hello World`.

Problem: User might modify the title in `index.md` but markbind will continue to use the one specified in `site.json` which might confuse the user.

Suggestion: Remove the title in site.json as we don't normally expect users to specify the title in site.json, although it is allowed.

**Comment by acjh** [comment]
This is by design, as mentioned in [userGuide/siteConfiguration.html](https://markbind.github.io/markbind/userGuide/siteConfiguration.html) for **pages**:

>> *Titles specified in this array will take priority over titles specified within the front matter of individual pages.*

> Suggestion: Remove the title in site.json as we don't normally expect users to specify the title in site.json, although it is allowed.

Actually, `title` is expected if `src` (not `glob`) is used.
How about changing the one in the default **index.md** to:

```js
title: "This title can be overridden in site.json"
```

**Comment by damithc** [comment]
May be the problem is trying to illustrate two techniques using one example?
Options:
1. the starter site created by init has two .md files.  One of them uses the typical way of specifying page titles while the other uses the other technique.
2. starter site uses the typical technique only (i.e., specify page title in the frontmatter). The other technique is described in the user guide (as an advanced technique) but not used in the starter site.

Any other options?

I prefer 2 because we want to keep things as simple as possible at the start.

**Comment by yamgent** [comment]
Actually, is there a reason why we are maintaining the title of a particular page at two different places? Is it possible to deprecate the title in `site.json` and just mainly use frontmatter's title?

**Comment by acjh** [comment]
It's meant to be able to override title for pages in a sub-site, without having to modify the source file.

**Comment by damithc** [comment]
> Actually, is there a reason why we are maintaining the title of a particular page at two different places? Is it possible to deprecate the title in site.json and just mainly use frontmatter's title?

IIRC, the intention was to be able to serve the same page with multiple titles. May be useful if you want to serve a page from a submodule using a title that fits your website?

**Comment by damithc** [comment]
related #861
