### ISSUE TITLE
Create table from csv file.

### ISSUE THREAD

**Issue by yiwen101** [MarkBind/markbind#2424]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

This is a sub issue of #896

### What is the area that this feature belongs to?

Author Usability, Reader Usability

### Is your feature request related to a problem? Please describe.

This is a sub issue of #896.
Support more powerful table by supporting generating table from csv file.

### Describe the solution you'd like

Add a table component that has a "src" attribute pointing to relative path to then csv file.

**Comment by yucheng11122017** [comment]
Hi @yiwen101, before you get started on this issue, please do read this part of the user guide ! https://markbind.org/userGuide/reusingContents.html#importing-variables-from-other-external-file-formats

There is already some support from creating tables from csv files but currently is very clunky and not intuitive as you can see. 
But you might be able to reuse some of the logic and code that already supports some of this parts

**Comment by yiwen101** [comment]
> Hi @yiwen101, before you get started on this issue, please do read this part of the user guide ! https://markbind.org/userGuide/reusingContents.html#importing-variables-from-other-external-file-formats
> 
> There is already some support from creating tables from csv files but currently is very clunky and not intuitive as you can see. But you might be able to reuse some of the logic and code that already supports some of this parts

Noted, thank you for pointing me to this

**Comment by kaixin-hc** [comment]
hi - we use the OnHold label when we are not planning to make progress on the issue due to blockers/uncertainty around whether it is needed, or similar reasons. If there's a reason why this is blocked for you could you raise it in the thread? Otherwise I'll remove this label for now!

**Comment by yiwen101** [comment]
> hi - we use the OnHold label when we are not planning to make progress on the issue due to blockers/uncertainty around whether it is needed, or similar reasons. If there's a reason why this is blocked for you could you raise it in the thread? Otherwise I'll remove this label for now!

Hi; initially I plan to implement a new component called table; 
but (credit to yucheng for pointing out relevant existing features)later I realize that we already could bring csv file as an external virable, and after reading the current code (lib/nunjucks-extension, ver-components/src/panels and html/includePanelProcessor), I do not think I could bring a significant improvement over the current feature.

**Comment by yucheng11122017** [comment]
> Hi; initially I plan to implement a new component called table; but (credit to yucheng for pointing out relevant existing features)later I realize that we already could bring csv file as an external virable, and after reading the current code (lib/nunjucks-extension, ver-components/src/panels and html/includePanelProcessor), I do not think I could bring a significant improvement over the current feature.

Hi @yiwen101 have you spoken to prof about this issue? I think he still has some issues with the usability of this feature. Yes it supposed external importing but it isn't very intuitive or easy to use which is why he opened this issue.

**Comment by damithc** [comment]
> Hi @yiwen101 have you spoken to prof about this issue? I think he still has some issues with the usability of this feature. Yes it supposed external importing but it isn't very intuitive or easy to use which is why he opened this issue.

Thanks for raising this @yucheng11122017 
I took another look at the current implementation. While it is a bit verbose, it is also quite flexible, giving the author the ability to apply custom formatting to each column for example. So, I think on second thoughts it's good enough for now.

**Comment by yucheng11122017** [comment]
> Thanks for raising this @yucheng11122017 I took another look at the current implementation. While it is a bit verbose, it is also quite flexible, giving the author the ability to apply custom formatting to each column for example. So, I think on second thoughts it's good enough for now.
Alright noted prof! Will close this issue for now then
