### ISSUE TITLE
Support accessing divs of included files via the host file

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#243]
Suppose we have the following files.
`foo.md`:
```
xyz
<include src="bar.md" />
```

`bar.md`:
```
<div id="goo">abc</div>
```

`bar.md#goo` resolves to `abc`.   Shouldn't ~~`bar.md#goo`~~ `foo.md#goo` resolves to `abc` too, as `bar.md` is included in `foo.md`?

Pros:
If the original `foo.md` was as below and `bar.md` was extracted out later, previous references to `foo.me#goo` should continue to work.
```
xyz
<div id="goo">abc</div>
```

Cons:
?

**Comment by acjh** [comment]
> Shouldn't `bar.md#goo` resolves to `abc` too, as `bar.md` is included in `foo.md`?

I believe you mean: "Shouldn't `foo.md#goo`"

> Cons:
> ?

For one, it would allow bad code quality (maintainability) on the author's side.
It will become more difficult for the author to debug where `#goo` came from.

**Comment by damithc** [comment]
> I believe you mean: "Shouldn't foo.md#goo"

Yes, corrected.

> For one, it would allow bad code quality (maintainability) on the author's side.
> It will become more difficult for the author to debug where #goo came from.

That's true. 
We can think of it as the case of extracting a super class from an existing class. In that case, the clients of the child class should continue to work although some of the methods have now moved to the parent class. Granted inheritance too has downsides e.g., it makes debugging difficult as the case here.

To give a concrete example, I have a bunch of files that has the exact same code fragment duplicated. But I cannot use variables or boilerplates to eliminate that duplication because it will break all the clients of those files.  Even if I go and fix the clients, it is a case of exposing the inner structure of the file to clients. Ideally, clients shouldn't know that the file includes another file.

**Comment by acjh** [comment]
> We can think of it as the case of extracting a super class from an existing class.

Hmm, not quite the same.
In this case, an author can't know that **foo.md** contains `#goo` unless it's rendered.

**Comment by damithc** [comment]
> In this case, an author can't know that foo.md contains #goo unless it's rendered.

Isn't that similar to an author not knowing what methods a child class inherits unless she looks at the code of the parent class?

**Comment by acjh** [comment]
With a good IDE, she can :)

**Comment by damithc** [comment]
> With a good IDE, she can :)

Yup. While we don't have IDE support for this feature, many developers use inheritance-based languages without using an IDE, right? :-) But I take your point that there is a usability cost in addition to the implementation cost. Anyway, there is no urgency. We can put this on hold indefinitely. I don't think most regular users will face the level of reuse I need in CS2103 website. 

One option is to let user specify explicitly that the divs are imported, even specify which are imported. e.g.,
`<include src="bar.md" import />`
`<include src="bar.md" import="goo"/>`

**Comment by ang-zeyu** [comment]
I agree with @acjh here, this may lead to very unpredictable behaviour.

>If the original foo.md was as below and bar.md was extracted out later, previous references to foo.me#goo should continue to work.

also this pro should no longer be as applicable with intralink validation implemented

are there any other wins for this? @damithc

**Comment by damithc** [comment]
I think we can abandon this one now.
