### ISSUE TITLE
Code highlighting isn't visible for printing

### ISSUE THREAD

**Issue by Tim-Siu** [MarkBind/markbind#2438]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

macOS with latest Chrome or Safari

### MarkBind version

5.3.0

### Describe the bug and the steps to reproduce it

Line highlighting doesn't seem to be visible when printing. From `markbind.css`, it appears that the background color for code highlighting is intended for Lavander.

https://github.com/MarkBind/markbind/blob/e1ba80eebe18375e4a2d6f69d845bd418ee27d94/packages/core-web/src/styles/markbind.css#L67-L82

Web view:
<img width="817" alt="Screenshot 2024-02-26 at 14 14 32" src="https://github.com/MarkBind/markbind/assets/61866948/5aba1539-d118-4c87-91f0-624573e50c9d">
Print view:
<img width="458" alt="Screenshot 2024-02-26 at 14 14 54" src="https://github.com/MarkBind/markbind/assets/61866948/353a1337-e3df-4544-9eb4-8a76e08e1585">

### Expected behavior

The highlighting should be visible.

**Comment by yucheng11122017** [comment]
This seems to be specific to different browsers.. 
When I tried it out on Google Chrome on Windows, the highlight remains. 
But on Microsoft Edge on Windows, the highlight is gone and it is automatically light theme..
