### ISSUE TITLE
Add pageNav for Reader-Facing Features

### ISSUE THREAD

**Issue by jingting1412** [MarkBind/markbind#2442]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Documentation

### Is your feature request related to a problem? Please describe.

Current page for reader-facing features doesn't have a pageNav.

### Describe the solution you'd like

Adding a pageNav would make it more convenient for readers to find and jump to specific topics.

**Comment by yucheng11122017** [comment]
Closed by #2443
