### ISSUE TITLE
First item no customization in List prevents proper processing of icons

### ISSUE THREAD

**Issue by KevinEyo1** [MarkBind/markbind#2449]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

5.3.0

### Describe the bug and the steps to reproduce it

Add list to a md file, where icon customization is not in the first item in the list level.
Icon `glyphicon-education` in first item(Item A) of first level, so Item B inherits it.
Icon `fas-file-code` not in first item (Sub-tem B1), so items B2-B4 all don't have it.

```
1. First item no customization test
* Item A  { icon="glyphicon-education" }
* Item B
  * Sub-item B1
  * Sub-item B2 { icon="fas-file-code" }
  * Sub-item B3 
  * Sub-item B4
```
![image](https://github.com/MarkBind/markbind/assets/105847348/528a5fb9-2da0-4255-badb-c56a8c03dd83)

### Expected behavior

Items B2, B3 and B4 should have the icon `fas-file-code`.

**Comment by EltonGohJH** [comment]
Verified on my end too!

**Comment by KevinEyo1** [comment]
Sorry a mistake on my part, I realized that it is intentionally implemented in this way due to preventing unintentional mixing of standard and customized lists, as per this [PR](https://github.com/MarkBind/markbind/pull/2316#discussion_r1255364486).
