### ISSUE TITLE
Missing output for plugins: Web3Forms, datatable, mermaid

### ISSUE THREAD

**Issue by LamJiuFong** [MarkBind/markbind#2451]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

MacOS 14 with latest chrome

### MarkBind version

5.3.0

### Describe the bug and the steps to reproduce it
In the UG, go to Using Plugins > Plugin: Web3Forms
![Screenshot 2024-03-10 at 10 39 27 PM](https://github.com/MarkBind/markbind/assets/122192553/b9f289c6-a49d-4c6d-bc4c-1664883df6b4)

**Comment by kaixin-hc** [comment]
As our user guide is the first thing anyone sees when exploring use this MarkBind, I think we should prioritize figuring out why this is happening. If the plugin doesn't work, perhaps we can also remove it from the UG.

**Comment by damithc** [comment]
> As our user guide is the first thing anyone sees when exploring use this MarkBind, I think we should prioritize figuring out why this is happening. If the plugin doesn't work, perhaps we can also remove it from the UG.

Yup, we can remove it from the UG until we figure out what's wrong.

**Comment by jingting1412** [comment]
Hello, one interesting thing I've noticed is that https://markbind-master.netlify.app/userguide/usingplugins#plugin-web3forms which deploys when there's a push to the master branch looks fine. As the current https://markbind.org/ only deploys whenever there's a tag, maybe something went wrong during [this commit](https://github.com/MarkBind/markbind/commit/d8a251a931174f74bf90de7245b09e7068aeb578). The timestamp on the current ug also matches with this commit.

In terms of the actual issue, I think the web3 formed wasn't rendered correctly. 
This is how its supposed to be rendered:
<img width="513" alt="Screenshot 2024-03-21 at 10 39 23 PM" src="https://github.com/MarkBind/markbind/assets/105090139/4b0b40b7-3138-4048-9650-5ca05cbb166d">

And this is how its incorrectly rendered now:

<img width="466" alt="Screenshot 2024-03-21 at 10 37 53 PM" src="https://github.com/MarkBind/markbind/assets/105090139/2d3353cb-eaa3-499e-a734-ad0f721315de">

**Comment by kaixin-hc** [comment]
## This issue occurs elsewhere
<img width="1255" alt="markbind.org website ss" src="https://github.com/MarkBind/markbind/assets/59471320/05ea2719-9032-49d6-b3df-acd7b9b7eccc"> 

[Here's the direct link.](https://markbind.org/userGuide/usingPlugins.html#plugin-web3forms)

After the new release, the datatables and mermaid plugins also do not produce the correct output on the live website. However, both show as expected on the netlify deployment: https://markbind-master.netlify.app/userguide/usingplugins
