### ISSUE TITLE
Create manual mock for logger

### ISSUE THREAD

**Issue by luminousleek** [MarkBind/markbind#2466]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#2099

### What is the area that this feature belongs to?

Testing

### Is your feature request related to a problem? Please describe.

To test for logger input, the logger is mocked and then calls to the logger are checked (see #2463 for an example). However, this must be done every for every file that the logger is mocked in, which is a bit annoying.

### Describe the solution you'd like

Create a [manual mock](https://jestjs.io/docs/manual-mocks) of the logger, so that we can just call `jest.mock('logger');` at the start of each test. The default implementation of manual mocks can also be [overridden](https://stackoverflow.com/questions/48790927/how-to-change-mock-implementation-on-a-per-single-test-basis) though it's a bit more finnicky to do so.

**Comment by kaixin-hc** [comment]
Cool suggestion, I think this makes sense if the setup code for the logger is long. Just wondering which functions you want to mock with the logger? If the mock is just warn, info, error for example, there might be an argument made for mocking them at the start of each test case instead so that the tests are totally independent and not based on outside "logic"

**Comment by luminousleek** [comment]
> Cool suggestion, I think this makes sense if the setup code for the logger is long. Just wondering which functions you want to mock with the logger? If the mock is just warn, info, error for example, there might be an argument made for mocking them at the start of each test case instead so that the tests are totally independent and not based on outside "logic"

Actually after thinking and reading about this a bit more I realise there isn't much need to do a manual mock for the logger since as discussed in #2099 it makes more sense to test for logger calls than logger outputs. So the automatic mock of `jest.mock('/path/to/logger');` would work just fine since it replaces all the methods with another method that just returns `undefined`. 

I think I'll close this issue then.
