### ISSUE TITLE
Reusable workflow repo for all repos under organisation

### ISSUE THREAD

**Issue by KevinEyo1** [MarkBind/markbind#2479]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

DevOps

### Is your feature request related to a problem? Please describe.

As each of the groups are likely to have overlaps of needs when it comes to DevOps in general, and as more workflows are implemented, it may be useful to have a separate repo of GitHub workflows that can allow each group to reuse common workflows

### Describe the solution you'd like

Create a new repo containing workflows that can be called from workflows in other repos, ensuring all the necessary configurations and permissions are set properly to ensure flexibility and security, refer to [here](https://itnext.io/github-actions-working-with-reusable-workflows-625f79b0586f)

**Comment by KevinEyo1** [comment]
Hi @yucheng11122017, I was thinking for more general workflows that will be useful across all other groups like teammates etc

**Comment by tlylt** [comment]
> Hi @yucheng11122017, I was thinking for more general workflows that will be useful across all other groups like teammates etc

@KevinEyo1 workflows in https://github.com/MarkBind/markbind-action/tree/master/.github/workflows are general and reusable workflows related to MarkBind. If you are referring to purely development-related workflows such as the PR message reminder, it's probably out of scope/not necessary to keep them within MarkBind org. Having a separate repo adds quite a bit of a maintenance burden, so I would think that we should avoid creating new ones unless required.

**Comment by KevinEyo1** [comment]
Hi @tlylt yes I was referring to purely development-related workflows. I was thinking since it is likely able to apply to other orgs that it would be worth setting up. I didn't consider that the repo itself required maintaining as well. Maybe it might be more worth in the future as the potential of utilizing DevOps is further tapped into, will have to see how it develops.

**Comment by yucheng11122017** [comment]
I will close this issue for now
