### ISSUE TITLE
Document: Node LTS (v20) and python 3.12 does not work on MarkBind install

### ISSUE THREAD

**Issue by kaixin-hc** [MarkBind/markbind#2496]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

M2 Mac v13.6.6

### MarkBind version

5.4.0

### Describe the bug and the steps to reproduce it

When running `npm install` in the root of markbind, see the following error:
<img width="538" alt="node-gyp error" src="https://github.com/MarkBind/markbind/assets/59471320/7153215d-8717-42d7-8cbc-b73800de7a04">

This error is caused because 3.12 python deprecates distutils, and node-gyp packaged with LTS is a node-gyp version before version 10. As stated in [this issue](https://github.com/nodejs/node-gyp/issues/2942), python 3.12 needs the newer version of node-gyp. It seems non trivial to update node-gyp version, as the [official instructions here did not work for me](https://github.com/nodejs/node-gyp/blob/main/docs/Force-npm-to-use-global-node-gyp.md) (needs more testing).

However, one workaround that worked for me was adding the following line to node config 
`python=path/to/python/on/my/device` and downgrading my python version (`brew uninstall python@3.12` - though i had to force uninstall it due to dependencies)

(I also had to delete and reclone my MarkBind, but I suspect that was unrelated)

### Expected behavior

If the versions are not supported, we should maybe warn users of the problem since right now we just say the following about required version...
<img width="443" alt="Screenshot 2024-04-04 at 4 34 54 PM" src="https://github.com/MarkBind/markbind/assets/59471320/573b5af3-f8e2-4b47-890f-f9ce49e2cf38">

### Anything else?

Thank you @lhw-1 and @EltonGohJH for your extensive help troubleshooting this issue!

**Comment by yiwen101** [comment]
I also run into the same issue this morning;

The cause is that "distutils package is removed in python version [3.12](https://stackoverflow.com/questions/69919970/no-module-named-distutils-but-distutils-installed)"

**Comment by jingting1412** [comment]
I've also faced this issue before and this helped: https://stackoverflow.com/questions/77251296/distutils-not-found-when-running-npm-install

**Comment by yiwen101** [comment]
> I've also faced this issue before and this helped: https://stackoverflow.com/questions/77251296/distutils-not-found-when-running-npm-install , if many people also encounter the same issue as me maybe it'll be good to add a note in the devdocs regarding this

Thank you for the valuable input!

Additional note: For system with python3 installed via brew, running `brew install python-setuptools` can also solve the issue. Running `python3 -m pip install setuptools` may run into
`error: externally-managed-environment`

**Comment by kaixin-hc** [comment]
As this is now linked in our documentation, lets leave this open until we can remove the warning from our documentation.
