### ISSUE TITLE
Footers: omit footer tags for non-inline footers

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#251]
v1.8.0

As a file in the footers directory is already known to be a footer, we can omit the `<footer>` tag from them?

**Comment by Chng-Zhi-Xuan** [comment]
Yes, we can actually wrap the footer tag for the user. Would minimize some clutter 👍

**Comment by acjh** [comment]
User may want to specify CSS classes or styles on footer element. This doesn't seem worthwhile.

**Comment by damithc** [comment]
> User may want to specify CSS classes or styles on footer element.

That true. Can make it optional.

> This doesn't seem worthwhile.

Yes, not worth spending time now. This is an `AuthorUsability` issue. Can leave for a version in the distant future. Same for other `AuthorUsability` issues, unless high priority.

**Comment by damithc** [comment]
In fact, a site is unlikely to have more than one footer. This is a VERY low value enhancement.

**Comment by ang-zeyu** [comment]
Done with the new layout system #1403
