### ISSUE TITLE
Tab-Group Header not displayed

### ISSUE THREAD

**Issue by luminousleek** [MarkBind/markbind#2524]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

macOS Ventura

### MarkBind version

5.4.0

### Describe the bug and the steps to reproduce it

In [this part](https://markbind.org/userGuide/components/presentation.html#tabs) of User Guide, there is a code snippet that shows how to specify a header for a Tab-group. However, the header is not there, as seen in the screenshot below.

<img width="1017" alt="Screenshot 2024-04-23 at 11 26 24 AM" src="https://github.com/MarkBind/markbind/assets/68138671/8eb871bf-0e12-4603-9a18-3b9af885cbb6">

### Expected behavior

The tab group should have a header called "Third tab group 🌌 " for the first tab group and "Disabled fourth tab group" for the second tab group

### Anything else?

I reverted the codebase to v3.0.0 to test it myself and it still doesn't work in that version :( So I don't think it's caused by the Bootstrap migration from v4 to v5.

**Comment by gerteck** [comment]
I believe this may be related to the issue:

https://github.com/MarkBind/markbind/blob/2c8276468592f964663ff3193e57345b63fa7f70/packages/vue-components/src/TabGroup.vue#L74-L78
