### ISSUE TITLE
Update Node version to LTS

### ISSUE THREAD

**Issue by EltonGohJH** [MarkBind/markbind#2541]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#2197

### Is your feature request related to a problem? Please describe.

Upgrade to Node to LTS either 18 or 20.
(Node 16 EOL was 09 Aug 2023)

### Describe the solution you'd like

Similar to what we have done previously. You can refer to #2197

Before the version update, check that
- [ ] all user-facing functionalities are working
- [ ] no issues with the development setup
- [ ] whether related GitHub Actions need to be updated
- [ ] any deprecated syntax to be refactored
- [ ] docs are updated
- [ ] Deployment to Netlify/other platforms is ok

**Comment by kaixin-hc** [comment]
#2246 And do/take note of this too!
