### ISSUE TITLE
Netlify .com domain doesn't work for MarkBind Website

### ISSUE THREAD

**Issue by kaixin-hc** [MarkBind/markbind#2543]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

the markbind one

### MarkBind version

NA

### Describe the bug and the steps to reproduce it

Go to the link in our readme, which throws a site not found error https://markbind-master.netlify.com/

Also applies here: https://github.com/MarkBind/init-typical?tab=readme-ov-file

### Expected behavior

The same thing you see here: https://master--markbind-master.netlify.app/

### Anything else?

It works if you replace the URL ending with .app:
* https://markbind-master.netlify.com/
* https://markbind-init-typical.netlify.app/

Quick fix - just change the URLs haha

(Tangent - is the typical output of init saved anywhere? I wonder if we can just adapt that repository to a simple page where you can see the available output of init with different templates)

**Comment by kaixin-hc** [comment]
Aside from this, we can add a test that checks the status of published links to be live... some sort of web request that pings ug dg and netlify to make sure the status is up and not 404

**Comment by EltonGohJH** [comment]
@kaixin-hc 
Maybe we can create a separate issue for that (the pinging part).
