### ISSUE TITLE
Investigate gh-pages deployment cache "path not file" after updating to latest version

### ISSUE THREAD

**Issue by EltonGohJH** [MarkBind/markbind#2547]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#2538

### Tell us about your environment

-

### MarkBind version

5.5.2

### Describe the bug and the steps to reproduce it

```
$ markbind deploy -n
  __  __                  _      ____    _               _
 |  \/  |   __ _   _ __  | | __ | __ )  (_)  _ __     __| |
 | |\/| |  / _` | | '__| | |/ / |  _ \  | | | '_ \   / _` |
 | |  | | | (_| | | |    |   <  | |_) | | | | | | | | (_| |
 |_|  |_|  \__,_| |_|    |_|\_\ |____/  |_| |_| |_|  \__,_|

 v5.5.2
error: The "path" argument must be of type string. Received undefined
```

To reproduce run markbind deploy locally. It worked for me on WSL2 but it seems like it may not be working for Windows. Note: once we set the cache_dir env variable it will work.

### Expected behavior

Should work without the need to explicitly setting cache_dir

### Anything else?

We updated gh-pages and it started to not work. Related to this update which introduced the cache folder. Related to the v3.1.0 update for github pages.
![image](https://github.com/MarkBind/markbind/assets/75515229/d57fd99e-e2ee-41ab-8940-050c7f0e7490)

**Comment by damithc** [comment]
For ease of reference, I'm posting here the current remedy for Windows:

Run  the following command in the terminal used for running the `markbind deploy` command:

`set CACHE_DIR=cache`

**Comment by Tim-Siu** [comment]
Can confirm this is also the issue for macOS environment.

**Comment by gerteck** [comment]
I seem to face this issue when trying to deploy on gh-pages via Travis CI:

![image](https://github.com/MarkBind/markbind/assets/111064611/b851372b-9005-47a5-9c29-d1d227fb141f)


Build Config:

![image](https://github.com/MarkBind/markbind/assets/111064611/58e823f1-db8b-446f-84ad-816913b0db8c)

**Comment by gerteck** [comment]
In the `gh-pages` module, 

```
  return userPromise.then((user) =>
    getRepo(options)
      .then((repo) => {
        repoUrl = repo;
        const clone = getCacheDir(repo);
        log('Cloning %s into %s', repo, clone);
        return Git.clone(repo, clone, options.branch, options);
      })
```
[source code](https://github.com/tschaub/gh-pages/blob/7568804d0603a13b83d0eeffb5e5ca0ef44fe42d/lib/index.js#L123-L130)

`getCacheDir(repo)` is being called. Subsequently, 
```
function getCacheDir(optPath) {
  const dir = findCacheDir({name: 'gh-pages'});
  if (!optPath) {
    return dir;
  }


  return path.join(dir, filenamify(optPath));
}
exports.getCacheDir = getCacheDir;
```
[source code](https://github.com/tschaub/gh-pages/blob/7568804d0603a13b83d0eeffb5e5ca0ef44fe42d/lib/index.js#L18-L26)
`findCacheDir` is then called.

```
export default function findCacheDirectory(options = {}) {
	if (env.CACHE_DIR && !['true', 'false', '1', '0'].includes(env.CACHE_DIR)) {
		return useDirectory(path.join(env.CACHE_DIR, options.name), options);
	}


	let {cwd: directory = cwd(), files} = options;


	if (files) {
		if (!Array.isArray(files)) {
			throw new TypeError(`Expected \`files\` option to be an array, got \`${typeof files}\`.`);
		}


		directory = commonPathPrefix(files.map(file => path.resolve(directory, file)));
	}


	directory = packageDirectorySync({cwd: directory});


	if (!directory) {
		return;
	}


	const nodeModules = getNodeModuleDirectory(directory);
	if (!nodeModules) {
		return;
	}


	return useDirectory(path.join(directory, 'node_modules', '.cache', options.name), options);
}
```
[source code](https://github.com/sindresorhus/find-cache-dir/blob/c90e669e5adfbee6b69813baff269abda571bb9f/index.js#L39C1-L66C2)

This is where setting `process.env.CACHE_DIR` directly seems to fix the problem. Otherwise, where `CACHE_DIR` is undefined, it seems that the function also returns undefined.

As mentioned in `findCacheDirectory` [package](https://www.npmjs.com/package/find-cache-dir)

> findCacheDirectory(options?)
> Finds the cache directory using the given options.
> 
> The algorithm checks for the CACHE_DIR environmental variable and uses it if it is not set to true, false, 1 or 0. If one is not found, it tries to find a package.json file, searching every parent directory of the cwd specified (or implied from other options). It returns a string containing the absolute path to the cache directory, or undefined if package.json was never found or if the node_modules directory is unwritable.
