### ISSUE TITLE
Delay loading results until the search terms are non-trivial

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#256]
Current: search results start loading as soon as the user types one char
Suggested: wait until the search term is at least 3 chars long or there is a space
Reason: this might alleviate the initial lag the user experience when searching

**Comment by nusjzx** [comment]
if it's less than 3 chars and has a space, I don't think that should be a valid search keywords. I think we can just limit to 3 chars

**Comment by damithc** [comment]
> if it's less than 3 chars and has a space, I don't think that should be a valid search keywords. I think we can just limit to 3 chars

That means it is impossible to search for something like `UX` which seems like a valid search query.  Perhaps allow searches longer 1 char?

In any case, also check if it actually improves the performance. If it doesn't, can leave as it is.

**Comment by nusjzx** [comment]
It really helps, the lagging is just because too many matching result when the keywords is too short. website: https://nusjzx.github.io/website-base/
