### ISSUE TITLE
Use more informative formatting in search results

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#257]
In the search results dropdown, it would be useful if it is possible to see whether the result is a heading or a keyword. i.e., distinguish between keyword hits from heading hits. The current one only distinguished between title hits and non-title hits as both headings and keywords are shown the same way.

Even better if we can indicate the level of the heading. One option is to apply formatting to search results e.g., show h1 headings using h1 formatting etc.

Not sure if the widget used currently supports that kind of formatting though.

**Comment by yamgent** [comment]
> One option is to apply formatting to search results e.g., show h1 headings using h1 formatting etc.

This might make the entries rather disproportional though.

An alternative could be to show the corresponding parent headings of the hit heading. For example, on the Jeykll's website, searching for the h2 "Set up Ruby..." also reveals the corresponding h1 heading:

<img src="https://user-images.githubusercontent.com/3168908/41009009-fe9c3698-6960-11e8-941f-9d2fb585ac27.png" width=500 />

**Comment by kaixin-hc** [comment]
Is this issue now moot? I think the search now shows the corresponding parent headings of the hit heading. I'm not sure that it would really be useful to distinguish between h2 and h3 or smaller headings.

**Comment by damithc** [comment]
> Is this issue now moot? I think the search now shows the corresponding parent headings of the hit heading. I'm not sure that it would really be useful to distinguish between h2 and h3 or smaller headings.

Yes, I think the suggestions raised in the initial post are mostly done now. Can close if others don't have any suggestions along the same lines.

**Comment by jovyntls** [comment]
Closing this issue since it seems that the search results are sufficiently informative and there are no other suggestions raised. We can open another issue for more suggestions in the future 🙂
