### ISSUE TITLE
Image annotation: support more shapes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2574]
Currently, we can use image annotation features to do something like the below (i.e., the yellow circle) to indicate which area of the image the explanation refers to.

![image](https://github.com/user-attachments/assets/bdbaa18b-5da5-43ab-b5fe-c0af8ec549c0)

It may be useful to be able to draw other shapes in the diagram e.g., a box

![image](https://github.com/user-attachments/assets/464af1b2-a9cd-463b-929b-135556880e15)

**Comment by yucheng11122017** [comment]
Hi @damithc, was wondering if the custom annotations are sufficient for this purpose? 
https://markbind.org/userGuide/components/imagesAndDiagrams.html#annotations:~:text=Customising%20shapes%20for%20Annotate%20Point

I had a quick stab at it and I managed to do this. 
![image](https://github.com/user-attachments/assets/d0870fa2-7dc0-46ad-942f-804669e717dd)

This is the code for that. The idea is to create a box using CSS and to use it as a slot for a-point
```
<annotate src="../../images/annotateSampleImage.png" width="500" alt="Sample Image">
  <a-point x="75%" y="50%" content="This point is 75% from the left and 50% from the top">
    <div style="width: 100px; height: 100px; border: 2px solid red; margin: 20px auto;"></div>
  </a-point>
  <a-point x="25%" y="50%" content="This point is 25% from the left and 50% from the top">
    <pic src="../../images/deer.jpg" width="50" height="50">
  </a-point>
  <!-- Customised Annotate Point with styling-->
  <a-point x="50%" y="50%" content="This point is 25% from the left and 50% from the top">
    <div style="opacity: 90%; color: red">Custom</div>
  </a-point>
</annotate>

```

**Comment by damithc** [comment]
> Hi @damithc, was wondering if the custom annotations are sufficient for this purpose? https://markbind.org/userGuide/components/imagesAndDiagrams.html#annotations:~:text=Customising%20shapes%20for%20Annotate%20Point
> 
> I had a quick stab at it and I managed to do this. ![image](https://private-user-images.githubusercontent.com/77204346/391477004-d0870fa2-7dc0-46ad-942f-804669e717dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTE4OTYsIm5iZiI6MTczMzE1MTU5NiwicGF0aCI6Ii83NzIwNDM0Ni8zOTE0NzcwMDQtZDA4NzBmYTItN2RjMC00NmFkLTk0MmYtODA0NjY5ZTcxN2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE0NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZTM2ZDdhODAyMDlmYmI4ZTJmMTMyOTZiM2NmY2FjNzdjNDEyOTU1NjI3MDQyN2Q2Y2YxZGJlYjY3ODJkMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UVFTd4NeYcIg4jkoveHvifOQAZrorZxpF0-yryFv3sI)
> 
> This is the code for that. The idea is to create a box using CSS and to use it as a slot for a-point
> 
> ```
> <annotate src="../../images/annotateSampleImage.png" width="500" alt="Sample Image">
>   <a-point x="75%" y="50%" content="This point is 75% from the left and 50% from the top">
>     <div style="width: 100px; height: 100px; border: 2px solid red; margin: 20px auto;"></div>
>   </a-point>
>   <a-point x="25%" y="50%" content="This point is 25% from the left and 50% from the top">
>     <pic src="../../images/deer.jpg" width="50" height="50">
>   </a-point>
>   
>   <a-point x="50%" y="50%" content="This point is 25% from the left and 50% from the top">
>     <div style="opacity: 90%; color: red">Custom</div>
>   </a-point>
> </annotate>
> ```

@yucheng11122017 Nice. While this is not user-friendly, most likely any syntax we introduce will be almost as complicated as this one. 
That said, we should still update the user guide to include examples such as this one.
