### ISSUE TITLE
Have code blocks show more UI details/ be more responsive

### ISSUE THREAD

**Issue by Incogdino** [MarkBind/markbind#2579]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Plugins

### Is your feature request related to a problem? Please describe.

Although a minor inconvenience, a lack of response from the copy plugin buttons can cause some confusion on whether the action have been performed. 

### Describe the solution you'd like

A more responsive plugin button that changes its icons when clicked on. I have tried implementing it below,

![image](https://github.com/user-attachments/assets/c7fe2dba-1a81-47bc-bb6a-5a4a2e403668)

The copy button would show a tick when it is clicked on. And change back to the copy button after some time.

### Additional context

If the suggestion is sound, I can submit my PR for this issue.

**Comment by damithc** [comment]
Yup, good suggestion, @Incogdino
