### ISSUE TITLE
baseUrl cannot be used inside another variable

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#261]
**Tell us about your environment**

* **MarkBind Version:**
1.8.1

**What did you do? Please include the actual source code causing the issue.**

`variables.md`

```html
<span id="websiteInfo">The baseUrl that we are using is {{baseUrl}}.</span>
```

`index.md`

```html
{{baseUrl}}

{{websiteInfo}}
```

**What did you expect to happen?**

`index.html` should be rendered as:

```
/helloWorld

The baseUrl that we are using is /helloWorld.
```

**What actually happened? Please include the actual, raw output.**

`index.html` is actually rendered as (notice the missing text for the second line):

```
/helloWorld

The baseUrl that we are using is .
```

**Comment by rachx** [comment]
I think https://github.com/MarkBind/markbind/blob/master/lib/Site.js#L327 just need to move earlier in the  code before the mapping is used.
