### ISSUE TITLE
Show error message when aborting due to nunjucks error

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#265]
Context: I have a need to generate several variations of the same site. As markbind doesn't have syntax to support conditional variations yet, I've resorted to using nunjucks code (on top of markbind) for the time being. [example](https://github.com/nus-cs2103/website-base/edit/master/se-book-adapted/chapters/architecture.md)

Current: If there is an error in nunjucks code (e.g., importing a file that doesn't exist), the build fails silently. Same applies to live preview.

Suggested: instead of failing silently, show some error information from nunjucks

**Comment by damithc** [comment]
@rachx any thoughts?

**Comment by rachx** [comment]
We should be able to report the error/problematic file in the console if we add some error handling when using nunjucks.

https://github.com/MarkBind/markbind/blob/bd46b7862ea88147924515b6d6781dd84323750b/lib/markbind/lib/parser.js#L418
If this throws an error, we should also use the reject handler.
