### ISSUE TITLE
 Allow some pages to be excluded from search index

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#269]
Context: In some websites, there is heavy duplication of content. e.g., normal text book and a printable version of a text book.

Suggestion: Allow some pages to be excluded from search results

Benefit: Author has a way to omit duplicated content from search results

Notes:
Allow a `searchable: no` (or something similar) in frontmatter?

**Comment by damithc** [comment]
@nusjzx can give this one a try? I would like to have this feature before next semester starts.

**Comment by yamgent** [comment]
> Allow a `searchable: no` (or something similar) in frontmatter?

Would it help if we support this in `site.json` as well? Using globs to specify an entire directory for exclusion could be useful.

**Comment by damithc** [comment]
> Would it help if we support this in site.json as well? Using globs to specify an entire directory for exclusion could be useful.

Yes, in fact it is the better option. That way, a parent site can exclude pages from a child site, without having to modify the page source itself.

**Comment by nusjzx** [comment]
@damithc Do we still allow it in frontmatter, or site.json only

**Comment by damithc** [comment]
site.json is enough?

**Comment by nusjzx** [comment]
ok
