### ISSUE TITLE
site nav: difficulty in creating a drop-down item

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#272]
I can't seem to be able to create a drop-down item in this site navigation menu https://nus-cs2103.github.io/website-base/se-book-adapted/index.html

https://nus-cs2103.github.io/website-base/se-book-adapted/index.html

Code (uses some nunjucks):
```html
<markdown>
{% import "se-book-adapted/config.md" as config with context %}

* [Home {{ glyphicon_home }}, printable versions {{ glyphicon_print }}]({{baseUrl}}/se-book-adapted/index.html)
{% for section in config.topics %}
* **{{ section.heading }}**  <!-- this line should be a drop-down ??? -->
  {% for chapter in section.chapters %}
    * [{{ chapter.heading }}]({{baseUrl}}/se-book-adapted/chapters/{{ chapter.name }}.html)
  {% endfor %}
{% endfor %}

<markdown>
```

**Comment by Chng-Zhi-Xuan** [comment]
I have narrowed the problem to a specific piece of code `if ($(this).children().first().is('ul')){....}`. If you insert any styling for the dropdown title (tested `<strong>` and `<mark>`) It will treat it like a `<href>` tag and not render the dropdown list. `<span>` (when using Glyphicons) seems fine so far.

You a temporarily work around is not to style your dropdown titles. Will fix this soon 👍 .

**Comment by damithc** [comment]
Thanks. No hurry. 
It seems extra blank lines in the code and interfere with identifying which items should be dropdowns.

Noticed another oddity in this page https://nus-cs2103.github.io/website-base/admin/index.html#admin-appendixC-faq
![image](https://user-images.githubusercontent.com/1673303/41761398-ba9a68cc-7629-11e8-9e8b-185ca74a4f47.png)
Appendix C is nested at the wrong level. Code https://raw.githubusercontent.com/nus-cs2103/website-base/master/_markbind/navigation/adminSiteNav.md

**Comment by Chng-Zhi-Xuan** [comment]
Seems like an issue regarding the text being **centered** after wrapping around for exceeding the length. 

A change to the `.CSS` will fix this 😄
