### ISSUE TITLE
Support an easy syntax for bigger/smaller text size 

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#28]
Currently we use block quote formatting to show text in bigger size. This is an abuse of syntax. Instead, we should tweak the block quote formatting to actually look like quotes as we do have an actual use case for showing quotes in our eContent.

On the other hand, we could support an easy syntax to indicate whether to make text bigger/smaller relative to the default size. e.g. `+++` `---`

**Comment by acjh** [comment]
Hmm, I don't see this being abused in [CS2103/T Website](https://nus-cs2103-ay1718s1.github.io/website/) — didn't know there were so many quotes!
I used this regex: `^>␣` (un[substitute](https://en.wikipedia.org/wiki/Whitespace_character#Substitutes) `␣` with a whitespace)

Not sure about the use case here. Can we stick to [headings](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers) for this?

**Comment by rachx** [comment]
![image](https://user-images.githubusercontent.com/16644412/38171384-5b2c4ade-35cb-11e8-9552-98abf2f97971.png)
I used `<span style="font-size: smaller"> MarkBind </span>` (and `larger` for the next one)

**Comment by damithc** [comment]
> Hmm, I don't see this being abused in CS2103/T Website — didn't know there were so many quotes!

IIRC, the text size was adjusted later to be of normal size, and the abuse stopped :-)

> Not sure about the use case here. Can we stick to headings for this?

I thought showing some text larger than normal can be used to indicate more important part of the text e.g., a paragraph that gives a high-level overview of the rest. I've seen some Web articles using that technique. The objective is if the reader is in a hurry, she can only read those bigger text parts.

> I used `<span style="font-size: smaller"> MarkBind </span>` (and larger for the next one)

Yup, we can use that for the time being. It's more convenient if we have a shorter syntax though.

**Comment by acjh** [comment]
How about `<small>` ([from Bootstrap](https://getbootstrap.com/docs/3.3/css/#small-text)) and `<big>` (define as `font-size: larger` in **markbind.css**)?

**Comment by damithc** [comment]
Sure. is something like this possible? `<small> <smaller> <large> <larger>`

**Comment by acjh** [comment]
You can nest `<big>` and `<small>`:

```html
<big><big>tutorial</big>tutorial</big>tutorial<small>tutorial<small>tutorial</small></small>
```

<img width="485" alt="28-1" src="https://user-images.githubusercontent.com/14091939/40039307-7d90d334-5848-11e8-896c-2420a4ba4bb1.png">

**Comment by damithc** [comment]
Nice. In that case, should they be _bigger_ and _smaller_, which gives the sense of cumulative effect?

**Comment by damithc** [comment]
OK, we'll go with that then.

**Comment by yamgent** [comment]
> Sure. is something like this possible? `<small> <smaller> <large> <larger>`

Since [CSS's `font-size` property](https://www.w3schools.com/CSSref/pr_font_font-size.asp) also uses values such as `small` and `large`, we can use `<large>` and `<small>`,

**Comment by Chng-Zhi-Xuan** [comment]
We can add easily support for `<large>` tags via `markbind.css`. 

``` CSS
large {
  font-weight: 400;
  font-size: 125%;
}
```

To simplify the syntax, we can either use [markdown-It-regex](https://github.com/tylingsoft/markdown-it-regex) which is already imported, or [markdown-it-container](https://github.com/markdown-it/markdown-it-container).

**Suggestion:**
- Reserve `++` for placing `<large>` tags (Remove from underline).
- Reserve `--` for placing `<small>` tags.
- Reserve `__` for underline text (Remove from bold + italics)
- Use combination of `**` and `_` for bold + italics


``` Markdown
New syntax:
++Larger text++
--smaller text--
__underline text__
**_bold and italic_**, _**bold and italic**_
```

**Comment by Chng-Zhi-Xuan** [comment]
Note that adopting the suggested syntax will disobey the rules defined within [commonMark spec](https://spec.commonmark.org/0.29/). So far I could only find [Discord](https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-) to break semantics to support underline text.

We might want to break semantics to support underline as it is a common document style. Discussions on underline text can be found here:
- [Feature Request: underline text](https://talk.commonmark.org/t/revisting-underline-healthcare-documents/3078/5)
- [Revisting Underline & Healthcare Documents](https://talk.commonmark.org/t/revisting-underline-healthcare-documents/3078)

**Comment by damithc** [comment]
Unfortunately, I guess we want to preserve compatibility with Markdown syntax.

**Comment by ang-zeyu** [comment]
How about switching over to `$$...$$` for underline text? This is a big deprecation though, so we could aim to support both `$$...$$` and `++...++` for underline text till v3.0.

After that, we can adopt the syntax for large / small text suggested above https://github.com/MarkBind/markbind/issues/28#issuecomment-495109826

```
++...++ -> large text
--...-- -> small text
```

**Comment by damithc** [comment]
> How about switching over to `$$...$$` for underline text? This is a big deprecation though, so we could aim to support both `$$...$$` and `++...++` for underline text till v3.0.

Yes, that is possible.

Will there be any issue because `-------` is also used for horizontal lines?

Perhaps we can also support `++++text++++` (i.e., even larger) similar to `****text****`?

**Comment by ang-zeyu** [comment]
> Will there be any issue because `-------` is also used for horizontal lines?

unlikely, similar to how you can use `**...**` for bold text but also `***` for horizontal lines.

> Perhaps we can also support `++++text++++` (i.e., even larger) similar to `****text****`?

yes that's possible as well.

Let's go with that then; Also this can be implemented as an independent npm package outside of markbind, there seems to be quite a bit of demand for such a plugin

**Comment by fsancho** [comment]
Can $$ be in conflict with LATEX notation for math?

**Comment by ang-zeyu** [comment]
thanks for highlighting this @fsancho 

I believe it may conflict with external scripts, but we're providing our own using bracket notations `\[...\] \(...\)` with [this package](https://github.com/goessner/markdown-it-texmath), which should reduce the need for that.

**Comment by fsancho** [comment]
Thanks for replying so fast!
It's true that we can use \[...\] \(...\) with TeX packages (and indeed, they are more desirable than $$..$$), but there is not direct way to transform a "classic" doc using $$..$$ and $..$ into a new one with these delimiters, and maybe this fact may impair the use of MarkBind for already formatted content.

**Comment by ang-zeyu** [comment]
Fair point, hmm...

I suggested `$$...$$` originally as we've really almost run out of good delimiters for our [text styles](https://markbind.org/userGuide/formattingContents.html#text-styles) unfortunately =\

The alternatives I could think of were `# & ! @` which don't seem to connote the same 'squiggly' underline feel.

One potential fix is to expose these delimiters to user configuration for such use cases.
Or we could also shift to `!!...!!` which at least connotes some semantic value for underlining (in this case 'drawing attention to').

any thoughts as well? @damithc

**Comment by damithc** [comment]
> Or we could also shift to `!!...!!` which at least connotes some semantic value for underlining (in this case 'drawing attention to').
> 
> any thoughts as well? @damithc

I'm OK with that notation too.

**Comment by wxwxwxwx9** [comment]
@ang-zeyu How should we approach this? Should we make the PR for the `!!...!!` underline syntax change or leave it for now?

**Comment by ang-zeyu** [comment]
ok, let's go with `!!...!!` then, if there's no objections.


Thanks for taking a look at this again @wxwxwxwx9 

Since `$$..$$` is already out there in 2.8, let's do 2 prs, one
- against the hotfix branch, to add a new rule for `!!...!!`, and deprecate `$$...$$` (also warnings) similarly to `++...++`
- against the main unreleased branch, a straightforward change of `$$...$$` to `!!...!!`

**Comment by fsancho** [comment]
Thanks a lot for taking into consideration my comment/needs! I really apreciate your wonderful work with MarkBind!

**Comment by ang-zeyu** [comment]
No problem. Thanks for the input as well! 😃
