### ISSUE TITLE
Remove vue-strap's documentations and website

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#289]
**Prerequisite:** #274

After we migrate the documentations over from vue-strap to MarkBind, the documentations from vue-strap are no longer necessary.

Let's remove the `docs/` folder for vue-strap and shut down the website (we should redirect https://markbind.github.io/vue-strap to https://markbind.github.io/markbind/userGuide/components.html).

**Comment by damithc** [comment]
Looks like this one can go ahead now.
