### ISSUE TITLE
Allow entering answers for questions

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#3]
For some simple question types (essay, mcq, check-boxes), allow user to enter their answer before checking the answer. It will allow reader to record their answer temporarily before comparing it with the given answer.

**Comment by Gisonrg** [comment]
Support for radio button is added.
Now support MCQ and check-boxes using Markdown syntax.
```
Checkbox
- [ ] Box1
- [X] Box2
- [ ] Box3
```

```
Radio
- ( ) Radio1
- (X) Radio2
- ( ) Radio3
```

An attribute, `has-input` for <Question> is added in order to show a input box for the question where users could put their answers down.

**Comment by damithc** [comment]
Nice 👍
