### ISSUE TITLE
Increase success rate of auto-scroll-to-target-subheading of search results

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#310]
v1.8.4

Steps:
* Search for a topic in the text book of this site https://nus-cs2103.github.io/website-base/se-book-adapted/  e.g., search for `unit testing`
* Select a result that points to a sub-heading of a page
* Hit enter

Expected: Page auto-scrolls to the intended sub-heading
Actual: Most times the page scrolls to the wrong location of the page

I suspect there is a race between loading content and scrolling.

**Comment by nusjzx** [comment]
The problem is not caused by race between loading content and scrolling. I've tried scrolling after page loaded, it still can not jump to the heading.

**Comment by yamgent** [comment]
As discussed, this is not just a problem specific to search only. It happens even when you try to load through a direct link to a sub-heading:

https://markbind.github.io/markbind/userGuide/components.html#advanced-tips-and-tricks

We need to figure out how to execute code **after** Vue finishes loading everything (can try `document.ready`, or `Vue.mounted` event hook).
