### ISSUE TITLE
Avoid duplicating search results if main heading of the page matches page title

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#311]
v1.8.4

Context: a page's heading (i.e., the heading that appears at the top of page) is very similar to the page title in the frontmatter

Problem: when the user search for a keyword that is in one (i.e., heading or the title), each appears as a separate result. 

Suggestion: show both as one result

Thoughts: while this sounds like a unavoidable problem, it is good if we can find a smart way (even if it takes a significant effort) to avoid this problem as it happens a lot and makes a significant impact on search UX

**Comment by weiquu** [comment]
Hi @damithc, can I check if this issue still exists / is this the issue (specifically the `User Guide: Adding Pages` result)?
<img width="515" alt="search results duplicate" src="https://user-images.githubusercontent.com/48304907/179133851-b64051f0-338f-4a2a-9ce5-2adb051ebe7d.png">

**Comment by damithc** [comment]
> > Hi @damithc, can I check if this issue still exists / is this the issue (specifically the `User Guide: Adding Pages` result)?
> 
> Yes, that's an example of the problem.

@weiquu I might have mislead you with this answer. Sorry. See https://github.com/MarkBind/markbind/pull/1968#issuecomment-1191752400

This example comes close to the issue raised, but not exactly the same.
