### ISSUE TITLE
Closeable directive not migrated

### ISSUE THREAD

**Issue by nusjzx** [MarkBind/markbind#315]
* **MarkBind Version:**: 1.8.4

**What actually happened? Please include the actual, raw output.**
Closeable.js is not migrated, v-closable directives throws errors.

```
vue.min.js:6 ReferenceError: el is not defined
    at bind (vue-strap.min.js:1)
    at ir (vue.min.js:6)
    at vue.min.js:6
    at Array.tr (vue.min.js:6)
    at h (vue.min.js:6)
    at b (vue.min.js:6)
    at v (vue.min.js:6)
    at b (vue.min.js:6)
    at v (vue.min.js:6)
    at b (vue.min.js:6)
```

**Comment by nusjzx** [comment]
Shall we refactor it as a component, or leave it as a directive

**Comment by damithc** [comment]
> Which component is using the closeable directive? Where is it needed?

I use v-closeable sometimes to allow images/media to be removed from the page before printing.

**Comment by yamgent** [comment]
> I use v-closeable sometimes to allow images/media to be removed from the page before printing.

I see, it needs to be migrated then (somehow `vue-migration-helper` did not spot any errors on this file, this is a false negative). It can stay as a directive.
