### ISSUE TITLE
Migration: 'website-base' main page takes extremely long to finish loading

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#326]
* **MarkBind Version:** None (currently on `bootstrap-migration` branch)

The migrated version takes too long to finishing loading `nus-cs2103/website-base`'s main page.

On my computer, this is how long the main page took to load:
* `v1.8.4`: **1.5 seconds**
  * Deployed main page: https://nus-cs2103.github.io/website-base
* `bootstrap-migration`: **40 seconds**
  * Deployed main page: https://yamgent.github.io/website-base

**Performance comparison between `dynamic` and `non-dynamic` Panels within `CS2103-website-base`**

System |
--- |
![system-spec](https://user-images.githubusercontent.com/31084833/42611191-85401b24-85c7-11e8-9672-33e59ea52556.PNG)

 Migrated `dynamic` | Migrated `non-dynamic`
--- | --- 
![dynamic-ram](https://user-images.githubusercontent.com/31084833/42611206-9481f3e6-85c7-11e8-88b5-a5ee57861b7b.PNG)<br>Approximately 150MB of RAM used| ![non-dynamic-ram](https://user-images.githubusercontent.com/31084833/42611223-a7b9053a-85c7-11e8-9f3b-c8ceb6080a17.PNG)<br> Approximately 1.8GB of RAM used |
![dynamic-time](https://user-images.githubusercontent.com/31084833/42611259-d26f744e-85c7-11e8-890d-544f85f7ab57.PNG)<br>Average of 5 runs is approximately 1.5 seconds | ![non-dynamic-time](https://user-images.githubusercontent.com/31084833/42611325-18841f2a-85c8-11e8-80b1-37da748e6fbf.PNG)<br>Average of 5 runs is approximately 40 seconds |
![dynamic-data](https://user-images.githubusercontent.com/31084833/42615544-3e45a08e-85dd-11e8-8121-663d396e4e21.PNG)<br> 2.4MB fetched on client side | ![non-dynamic-data](https://user-images.githubusercontent.com/31084833/42615554-4de1e548-85dd-11e8-93cd-53722b810829.PNG)<br> 69MB fetched on client side |

`v1.8.4` |
--- |
![before-migration-data](https://user-images.githubusercontent.com/31084833/42615587-76e45c5a-85dd-11e8-9f4d-def170ac64b7.PNG)<br> 7MB fetched on client side |
![before-migration-ram](https://user-images.githubusercontent.com/31084833/42615598-800a299a-85dd-11e8-805b-6dc1b275da98.PNG)<br> Approximately 400MB of RAM used |

There is very strong justification to have Panels be dynamic.

**Comment by yamgent** [comment]
A solution offered so far is to convert all the panels used to be `dynamic`.

There seems to be some errors appearing from the [`closeable` directive which we haven't migrated yet](https://github.com/MarkBind/markbind/issues/315), which might also be contributing to the loading performance issue. Will need further investigation on that front.

**Comment by yamgent** [comment]
> A solution offered so far is to convert all the panels used to be `dynamic`.

Converting all the panels to `dynamic` does seem to solve the performance issue. Will discuss about this solution in the release notes of the migration version.

**Comment by damithc** [comment]
I thought the current approach is like this:
* panels with `src` attribute are dynamic by default but can override with a `preload` directive
* panels without `src` are non-dynamic by default but can override with a `dynamic` directive (overriding is not implemented yet).

Is that incorrect?

**Comment by damithc** [comment]
Sure, that works too.

**Comment by acjh** [comment]
> - Panel body contents (... from src) are non-dynamic by default.

That's fine, but...

> If `dynamic` attribute is specified, then **ALL** Panel body contents will not be rendered on load, only when the panel is open.

This isn't good. Do you create a file to hold the content?

> This was done as Panel content that was authored or added using `<include>` can never be dynamic in the old implementation.

This is appropriate behavior.

**Comment by damithc** [comment]
@acjh I requested the `dynamic` directive to be independent of whether the panel content is specified via a `src` attribute or if it is just regular content inside the panel. i.e., the following should give a dynamic panel.
```
<panel dynamic>
# Things to remember
<include src="foo.md"/>
<include src="bar.md"/>
</panel>
```
If the above is not supported, the author is forced to create an extra file, like this.
```
<panel src="goo.md" dynamic />
```
`goo.md`:
```
# Things to remember
<include src="foo.md"/>
<include src="bar.md"/>
```

**Comment by acjh** [comment]
I see. So MarkBind creates the file instead?

**Comment by damithc** [comment]
> I see. So MarkBind creates the file instead?

Not sure. @Chng-Zhi-Xuan is that the case?

**Comment by Chng-Zhi-Xuan** [comment]
If I am not wrong, Vue has a [virtual DOM tree](https://vuejs.org/v2/guide/render-function.html#Nodes-Trees-and-the-Virtual-DOM) and conditionally choses which "branches" to render when toggling using `v-if`. `v-show` elements are rendered but hidden using `display: none` CSS. 

There isn't any file retrieval or writing in my implementation (assuming Vue API for `v-if` doesn't as well).

**Comment by acjh** [comment]
That means it's **always loaded** from the server, but **conditionally rendered** by JavaScript on the client.
Is that how `src` with `dynamic` is now handled too?

**Comment by Chng-Zhi-Xuan** [comment]
Yes, due to `v-if` being lazy, the retriever won't be called initially.

After being opened, then it will call `retriever.fetch()` and add the content nodes from `src` to the Virtual DOM, and be rendered. If toggled again, then the behavior of the `src` contents will follow the same as authored / included content without doing any file reading again. This is as the retreiver's boolean value of `alreadyFetched` will be set to true and terminate the `.fetch()` call early.

**Comment by acjh** [comment]
Sounds right. Can you link the related code? Thanks!

**Comment by Chng-Zhi-Xuan** [comment]
Retriever fetch method:
(Retriever.vue)
```js
fetch() {
      if (!this.src) {
        return;
      }
      if (this._hasFetched) {
        return;
      }
      jQuery.get(this.src)
        .done((response) => {
          var result = response;
          if (this.fragment) {
            var tempDom = jQuery('<temp>').append(jQuery.parseHTML(result));
            var appContainer = jQuery('#' + this.fragment, tempDom);
            result = appContainer.html();
          }
          this._hasFetched = true
          // result is empty / undefined
          if (result == void(0) && this.fragment) {
            this.$el.innerHTML = `<strong>Error</strong>: Failed to retrieve page fragment: ${this.src}#${this.fragment}`
            return
          }

          // Mount result in retriever
          let tempComponent = Vue.extend({
            template: `<div>\n${result}\n</div>`,
          })
          new tempComponent().$mount(this.$el);
        })
        .fail((error) => {
          console.error(error.responseText)
          this.$el.innerHTML = `<strong>Error</strong>: Failed to retrieve content from source: <em>${this.src}</em>`
        });
    }
```

Panel life cycle hook functions:
(Panel.vue)

```js
created () {
  if (this.src) {
      let hash = getFragmentByHash(this.src);
      if (hash) {
        this.fragment = hash;
        this.src = this.src.split('#')[0];
      }
    }
    // Edge case where user might want non-expandable panel that isn't expanded by default
    const notExpandableNoExpand = !this.expandableBool && this.expanded !== 'false';
    // Set local data to computed prop value
    this.localExpanded =  notExpandableNoExpand || this.expandedBool; // Ensure this expr ordering is maintained
    this.localMinimized = this.minimizedBool;
    },
mounted() {
  this.$nextTick(function () {
    if (this.isDynamic && (this.expandedBool || this.preloadBool)) {
      this.$refs.retriever.fetch()
    }
  })
}
```

Panel template for toggling dynamic behaviour:
(Panel.vue)

```html
<template v-if="dynamicBool">
    <div class="card-collapse"
         ref="panel"
             v-if="localExpanded"
     >
          [ Panel Body Stuff ]
      </div>
</template>
<template v-else>
    <div class="card-collapse"
         ref="panel"
         v-show="localExpanded"
     >
           [ Same Panel Body Stuff ]
     </div>
</template>

**Comment by yamgent** [comment]
The fetch method is also called in Panel.vue's `retrieveOnOpen()`:

```javascript
      retrieveOnOpen(el, isOpen) {
        if (isOpen && this.hasSrc) {
          this.$refs.retriever.fetch()
        }
      }
```

**Comment by damithc** [comment]
> That means it's always loaded from the server, but conditionally rendered by JavaScript on the client.
> Is that how src with dynamic is now handled too?

Um, the whole point of using dynamic loading is to speed up page loading (i.e., the page shows up faster because there is less data to fetch) as well as reduce load on the browser (i.e., lower memory used by the page). I hope that still holds.

**Comment by Chng-Zhi-Xuan** [comment]
Vue's `v-if` implementation was designed specifically with that in mind. It does load faster as certain nodes are not rendered by the browser. The trade off would be having to incur higher toggling costs vs higher initial load cost.

**Comment by damithc** [comment]
> Vue's v-if implementation was designed specifically with that in mind. It does load faster as certain nodes are not rendered by the browser. The trade off would be having to incur higher toggling costs vs higher initial load cost, which was highlighted in the API.

👍 website-base landing page can be a good test case for this. It has a lot of content but about 90% is dynamic.

**Comment by acjh** [comment]
> Vue's `v-if` implementation was designed specifically with that in mind.
Not true. It was designed with rendering in mind, not the two points mentioned by @damithc.

> The fetch method is also called in Panel.vue's `retrieveOnOpen()`

> To add on, there is a watcher to monitor `this.localExpanded` and calls `retrieveOnOpen()` when it becomes true, enabling the `.fetch()` to be called.

Are those really necessary? Can we use Vue's `.once` [event modifier](https://vuejs.org/v2/guide/events.html#Event-Modifiers)?

**Comment by Chng-Zhi-Xuan** [comment]
> Are those really necessary? Can we use Vue's .once event modifier?

The `@click` listener is already bound to `expand()`. We can't add more listeners for the same event in Vue either. We can extend `expand()` to call more methods, but this will lead us to require some data to maintain whether to call `retriever.fetch()` or not. However, that is already handled by the retriever's own `alreadyFetched` Boolean.

>  It was designed with rendering in mind,

Last time we tested by having all panels to be dynamic (with the migration syntax), there was significant load time savings. Did not measure memory usage though. Will update with a performance report soon 📝

**Comment by damithc** [comment]
When using the current released version, for the landing page of website-base, as I expand dynamic panels (i.e., week 3, week 4, etc.), the browser memory usage increases accordingly. That means dynamic panels gives significant memory savings in that version.

**Comment by Chng-Zhi-Xuan** [comment]
**Update**
- Changed PR description to include some performance metrics.

**Comment by damithc** [comment]
what about panels that have the `expanded` directive?

**Comment by damithc** [comment]
I see. sounds fine. However, `static` gives the sense 'not moving'. Some other keyword? `preload` or `prefetch` is closer to the actual meaning?

**Comment by Chng-Zhi-Xuan** [comment]
I chose `static` to describe the Panel body contents do not get removed / re-rendered. It is "static" and always there, just not shown. 

`preload` or `prefetch` doesn't convey that he contents are **not removed** when the Panel is closed. 

@acjh , what do you think?

**Comment by damithc** [comment]
> Having to specify that inline content has to be static (or preload) is bad for author experience.

That's a valid concern.  May be the approach suggested in [this comment](https://github.com/MarkBind/markbind/issues/326#issuecomment-404038917)?

On the positive side, it's not a big deal if the author forgot to add the directive to a panel with inline content. It's better to make a panel dynamic by mistake than to make a panel non-dynamic by mistake. Given that not all panels are expanded all the time, I guess there is a theoretical time/bandwidth saving if all panels are made dynamic?

**Comment by Chng-Zhi-Xuan** [comment]
> Please compare with current release, and consider size of fetched data as well.

Updated issue description. 

As discussed with @damithc , we should default the behaviour of Panel to be dynamic.
