### ISSUE TITLE
Support live preview for .fr files

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#331]
Context: I've been trying to use a different extension (`.fr`) for files containing page fragments, as opposed to addressable pages. The reasons:
* I can use `**/*.md` in `site.json` to indicate all pages that need to be rendered.  
* for my own convenience to distinguish full pages from page fragments. 

However, it seems `.fr` files are not captured by the live preview feature. When I edit a .fr file, there seems to be some activity in the `markbind serve` console but the changes don't appear in the rendered pages.

Suggestion: Capture changes to any file that is included irrespective of extension, not just .md files.

**Comment by nusjzx** [comment]
Currently we are separating source file(md, html) rebuilt from assets file rebuilt, the problem is because `isSourceFile()` is true if only md or html. 
One solution is to also include `.fr` as source file. But that won't  include all other file type

**Comment by damithc** [comment]
To confirm, `.fr` files _can_ be included in the current version.
e.g., [this file](https://raw.githubusercontent.com/nus-cs2103/website-base/master/admin/tools.md) includes a `collate.fr` file that is  rendered as https://nus-cs2103.github.io/website-base/admin/tools.html#tools

**Comment by damithc** [comment]
> One solution is to also include .fr as source file. But that won't include all other file type

I'm fine with limiting to specific file types, at least for live preview.

**Comment by nusjzx** [comment]
any file can be included actually, I meant the live preview process, we separate rebuilt of md, html files from assets files. When you change `.fr` files, they are not considered source file, so it will rebuild the assets only. That's why nothing changed. 

```
isHtml: filePath => path.extname(filePath) === '.html',
  isMarkdown: filePath => path.extname(filePath) === '.md',
  isSourceFile(filePath) {
    return this.isMarkdown(filePath) || this.isHtml(filePath);
  },
```
```
 if (fsUtil.isSourceFile(filePath)) {
          return site.rebuildAffectedSourceFiles(filePath);
        }
        return site.buildAsset(filePath);
```

**Comment by nusjzx** [comment]
As the syntax of `.fr` file is still md or html, why should we have this `.fr` file extension? How about just change the file name to indicate it's a page fragment

**Comment by damithc** [comment]
As discussed, we can support four extensions. They are recommendations only; user need not follow. we treat all four types the same way.
* `.md` : pure markdown files
* `.html` : pure html files

The above two have existing definitions. It's not nice to redefine them to fit out purpose.

* `.mb` : markbind files
* `.mbf` : markbind fragments that do not represent addressable pages

I don't like that `md` and `mb` look almost the same though :-p `mbd` and `mbdf`?

**Comment by nusjzx** [comment]
Sure. `mbd` and `mbdf` is fine

**Comment by damithc** [comment]
Lowering priority as it doesn't affect UX
