### ISSUE TITLE
Optimize heading layout for narrow-width seamless panels

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#337]
v1.9.0, Win 10, Chrome

Seamless panels: when the page width is smaller, the chevron goes to a separate line and some part of the heading is pushed to the next line although there is plenty of space on the panel header.

![image](https://user-images.githubusercontent.com/1673303/42731088-9405535e-8838-11e8-9d54-223fe759ee08.png)

No problem when the panel is wider:
![image](https://user-images.githubusercontent.com/1673303/42731097-ca0af896-8838-11e8-8a89-5115851ecd81.png)

**Comment by damithc** [comment]
Probably related: I noticed these got a lot shorter after v1.9.0
![image](https://user-images.githubusercontent.com/1673303/42731123-5c8aee2e-8839-11e8-9cf4-ec23147e27ab.png)

**Comment by Chng-Zhi-Xuan** [comment]
@damithc 

We forgot to update the `Advanced Tips and Tricks` document and release notes.

Previously, using slots for Panel headers have the `panel-title` class. But that has been deprecated in Bootstrap 4. The correct class is now `card-title`. It also fixes the problem of the titles being "short".

After changing to `card-title` |
--- |
![card-title-fix](https://user-images.githubusercontent.com/31084833/42731266-1a0f910a-883c-11e8-9142-ba296e395c64.PNG) |

**Comment by damithc** [comment]
Thanks @Chng-Zhi-Xuan Will use `card-title` in future. 
BTW, the first case is not using slots. Code (from [this file](https://raw.githubusercontent.com/nus-cs2103/website-base/master/admin/appendixE-gitHub.md)):
```
<panel type="seamless" header="%%Why am I being pushed to complete my GitHub profile?%%" >
   
   The GitHub profile is useful for the tutors and classmates to identify...
   
</panel>
```
