### ISSUE TITLE
Tooltip location is wrong if the tooltipped text has a line break

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#338]
v1.9.0

If the tool-tipped text spans over multiple lines, the tooltip can appear away from the text.

Suggestion: make the tooltip appear relative to the mouse pointer (as the mouse pointer must be hovering over the tooltipped text at the moment)?

**Comment by damithc** [comment]
Raising priority as it affects user experience.

**Comment by yamgent** [comment]
Is there any example of this happening? Can't reproduce it with either `<br>` or literal line break.

```html
<tooltip content=" coupling is the degree of interdependence <br>between <br>software <br>modules; a measure of how closely
connected two routines or modules are; the strength of the relationships between modules."><i>coupling</i></tooltip>
```

**Comment by damithc** [comment]
Here's a more noticeable case:
![image](https://user-images.githubusercontent.com/1673303/43056088-c4021e72-8e6c-11e8-821c-3672a5a3e4ad.png)

In some cases the tooltip is not in the view port at all.
