### ISSUE TITLE
Background color for code text doesn't match panel heading color

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#342]
v1.9.0

Current: code text color is red, which doesn't go well with bootstrap panel headings (bootstrap 4 uses darker background colors compared to bootstrap 3). This forces authors to use extra tweaks, such as the one I have done below (i.e., add a white background)

![image](https://user-images.githubusercontent.com/1673303/42741471-2966ac0c-88e5-11e8-8d2b-4fb02e608fac.png)

**Comment by damithc** [comment]
Perhaps we can follow GitHub's style? e.g., `W2.2`

**Comment by yamgent** [comment]
> Perhaps we can follow GitHub's style? e.g., `W2.2`

That sounds good (and is quite close to the style before the migration), this should be as simple as modifying the style in `asset/css/markbind.css`.
