### ISSUE TITLE
Tweak formatting of highlighting 

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#344]
v1.9.0

Current: bootstrap `.mark` style is a bit too light:
![image](https://user-images.githubusercontent.com/1673303/42741579-2f839c20-88e6-11e8-80ae-15938cae8137.png)

Suggestion: tweak it to be a bit stronger? Example:

![image](https://user-images.githubusercontent.com/1673303/42741600-5d70a240-88e6-11e8-93a6-9640817d45d1.png)

**Comment by Chng-Zhi-Xuan** [comment]
The weaker highlight style is from Bootstrap 4, which is using the colour `#fcf8e3`. 

A quick fix is to override this in `markbind.css` to a stronger colour.
