### ISSUE TITLE
Make block quotes more distinct from regular text

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#345]
v1.9.0

Current: text in block quotes seems to appear almost similar to regular text. Example from https://nus-cs2103.github.io/website-base/se-book-adapted/chapters/oop.html
![image](https://user-images.githubusercontent.com/1673303/42741672-f4c2c678-88e6-11e8-81c7-b3b300fc6065.png)

Suggestion: use a more distinct style

**Comment by Chng-Zhi-Xuan** [comment]
Did you try adding the `.blockquote` class as specified in [Bootstrap Docs](https://getbootstrap.com/docs/4.1/content/typography/#blockquotes)?

```css
/* blockquote class */
margin-bottom: 1rem;
font-size: 1.25rem;
```
After applying the class |
--- |
![blockquote-after-v2](https://user-images.githubusercontent.com/31084833/42928897-2347ac12-8b6b-11e8-96f4-6e3e1bbdbd22.PNG) |

**Comment by damithc** [comment]
I use  the markdown syntax `>`
Even after applying the class (based on your screenshot) the text looks like normal text?

**Comment by Chng-Zhi-Xuan** [comment]
Bootstrap's style for blockquote just have slightly larger font size and bigger spacing between lines. 

We can override `blockquote`'s style in `markbind.css`. Is there a particular look you are looking for?

**Comment by damithc** [comment]
Something like this (Github style)?

![image](https://user-images.githubusercontent.com/1673303/42979536-5227cde2-8c05-11e8-9633-6313585f7e40.png)

Grey bar on left and text is slightly lighter (but should not be as light as our dimmed text), (or use a slightly different font).
