### ISSUE TITLE
Support google analytics

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#355]
Context: User may need to use Google analytics to track a website
Current: There is no way to add stuff to the `<head>` section of a page
Suggest: provide a way to either add stuff to the head section or direct support for Google analytics

**Comment by Chng-Zhi-Xuan** [comment]
**Proposed solution**
1. Initialise a new folder `google-analytics` during `markbind init`
2. Have the user copy paste their unique tracking script into a file, place file within the folder.
3. Have a new attribute in `front matter`, maybe `tracker: ` to allow the user to specify their tracking script file within the folder. 
4. MarkBind reads the file and places the script within `<head>` for them during render.

**Comment by damithc** [comment]
Sounds good. I wonder if it is better to support adding _anything_ to the head section, not specifically for google analytics. Implementation/usage cost is the same but can be more useful?

**Comment by Chng-Zhi-Xuan** [comment]
Yes, it could make it easier for the author to do things like adding custom CSS or script files that they already have. 👍

**Comment by Chng-Zhi-Xuan** [comment]
@damithc 

I have 3 different implementations for inserting custom `CSS` or `JS` files into the `<head>` of your page.

**1. Specify the files using their full directory name from the root in `Front Matter`**

Advantage | Disadvantage
--- | ---
Allow reuse of files easily any where in the root folder | Nested file directory name could be long, making front matter section messy |

**2. Have a folder dedicated to all files to be inserted in the `<head>` of a page**

Advantage | Disadvantage
--- | ---
Allow reuse of files easily between pages | All pages that want to insert custom files need to insert the same set of files |
Only requires a Boolean value  from the user on whether to insert to the page or not | -

**3. Cross between 1 and 2. Have a folder dedicated to `<head>` files but the user must specify each individual file within the `front matter` of a page.**

Advantage | Disadvantage
--- | ---
Allow reuse of files easily between pages | Same problem as implementation 1, where front matter could get long and messy when many files are specified (but to a lesser extent) |

Which of these would suit best to your workflow?

**Comment by Chng-Zhi-Xuan** [comment]
As discussed, we shall proceed with the implementation of option 3.

**Comment by acjh** [comment]
Why not extract a `<head>` element from the file?
More HTML-like and flexible (e.g. `<meta>` tags).

**Comment by yamgent** [comment]
As further discussed, we will be allowing the user to directly specify the CSS and JS files involved. For example:

`index.md`:
```
<frontmatter>
head: myHead.md
</frontmatter>
```

`myHead.md`
```
<link rel="stylesheet" href="{{baseUrl}}/css/myCustomStyle.css">
```

**Comment by damithc** [comment]
>More HTML-like and flexible (e.g. <meta> tags).

Good point.

> As further discussed, we will be allowing the user to directly specify the CSS and JS files involved.

This will increase the flexibility, as @acjh pointed out. Slightly cleaner than having `<head>` mixed up with the content of the page?

**Comment by damithc** [comment]
Apparently, the Google analytics script needs to be the _first_ item in the head section.
![image](https://user-images.githubusercontent.com/1673303/43192848-153fe3f8-9031-11e8-9921-f2fabc124bce.png)

It might still work if we use the current `head` mechanism though.
If not, we may have to allow a some sort of marker in the `head./*.md` files to tell us which part should go at the top and which part should go at the bottom.
