### ISSUE TITLE
Provide a way to omit certain elements of a page

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#360]
Context: At times we may want to create a variation of a page that omit certain extra elements e.g., a _flat_  (or a _printer-friendly_) version of se-book that omits embedded panels. 

Suggestion: Provide a way to omit certain elements, possibly tagged using a dummy class.

**Comment by acjh** [comment]
Related: https://stackoverflow.com/questions/355313/how-do-i-hide-an-element-when-printing-a-web-page

**Comment by yamgent** [comment]
PRs to issue #363 provided `add-class` attribute, which indirectly provides a way to omit certain element through classes.

The only thing remaining to do is to document the said way, which is covered by issue #371. So closing this issue...
