### ISSUE TITLE
Seamless panels: omit caret if not expandable

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#369]
v1.9.2, Windows

Suggested: If `expandable="false"`, the caret should be omitted?

![image](https://user-images.githubusercontent.com/1673303/43180540-3a57eec2-900b-11e8-8d5d-a3e3223bf4a0.png)

Current: Caret appears even when the panel is not expandable

**Comment by luyangkenneth** [comment]
Seems like panels no longer display carets, regardless whether they are `expandable`.

From https://nus-cs2103-ay1819s1.github.io/cs2103-website/index.html
<img width="436" alt="screenshot 2019-02-07 at 3 17 38 pm" src="https://user-images.githubusercontent.com/9073504/52396106-89daa680-2aeb-11e9-91d4-d133b599a79b.png">

The only exception is for seamless panels - which I'll be working on.
