### ISSUE TITLE
Seamless panel: caret breaks if custom header slot is included from another file

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#373]
**Tell us about your environment**

* **MarkBind Version:** 1.9.1

**What did you do? Please include the actual source code causing the issue.**

`index.md`:
```html
<panel type="seamless" expanded>
  <span slot="header" class="card-title"><include src="text.md#title" /></span>
</panel>
```

`text.md`:
```html
<div id="title">Hello people!</div>
```

**What did you expect to happen?**
<img src="https://user-images.githubusercontent.com/3168908/43199371-4d531fb8-9044-11e8-9ca5-52d783cc3e2b.png" width="300" />

**What actually happened? Please include the actual, raw output.**
<img src="https://user-images.githubusercontent.com/3168908/43199382-51c71dce-9044-11e8-91b2-e9fab07b8b57.png" width="300" />

**Originally reported in:** https://github.com/MarkBind/vue-strap/pull/83#issuecomment-407676378

**Comment by damithc** [comment]
Seems to apply to this case as well:
```html
<panel type="seamless" expanded>
  <span slot="header" class="card-title"><markdown>## Unit Testing</markdown></span>
</panel>
```
This doesn't seem to recognize the heading. Shows as `## Unit Testing` instead.
```html
<panel type="seamless" expanded>
  <span slot="header" class="card-title"><md>## Unit Testing</md></span>
</panel>
```

**Comment by damithc** [comment]
BTW, I'm looking to have headings inside slots because I'm trying to insert additional keywords into the heading so that users can search and jump to sub headings based on additional keywords. 

![image](https://user-images.githubusercontent.com/1673303/43245414-c8629cdc-90e0-11e8-91b6-8dec75e0c17d.png)

**Comment by nusjzx** [comment]
@damithc  if the additional keywords is not <h1>-<h6>, it will not be indexed for search

**Comment by nusjzx** [comment]
@damithc if the additional keywords is not `<h1>-<h6>` it will not be indexed for search

**Comment by damithc** [comment]
> @damithc if the additional keywords is not <h1>-<h6> it will not be indexed for search

They are part of the heading. I just made the text smaller and added a line break. Indexing is working as expected in the current version. 👍

**Comment by yamgent** [comment]
```
 <span class='fas fa-chess-knight'></span><h1>Some headings</h1>
^
insert caret here


<span> Some text <h1> with keyword</h1></span>
      ^
   insert caret here


<span> <span class='fas fa-chess-knight'></span><h1>Some headings</h1><span>
      ^
insert caret here


<span><h1> Some headings</h1></span>
          ^
   insert caret here
```
