### ISSUE TITLE
Support markbind includes in _markbind/head/*.md files

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#380]
v1.9.2

Current:
_markbind/head/*.md files are inserted to the head section _as is_.

Suggested: 
Process them as normal markbind files first. In particular, process includes.

Justification:
Helps to reduce duplication as common parts can be extracted into separate files. e.g., GoogleAnalytics scripts

**Comment by ang-zeyu** [comment]
Done with the new layout system #1403
