### ISSUE TITLE
Seamless panel's caret does not rotate if custom slots are used

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#383]
**Tell us about your environment**

* **MarkBind Version:** 1.9.2

**What did you do? Please include the actual source code causing the issue.**

```html
<panel type="seamless">
<span slot="header" class="card-title">
This panel has a customized header
</span>
</panel>
```

**What did you expect to happen?**
When opening and closing, the caret should rotate.

**What actually happened? Please include the actual, raw output.**
The rotation does not occur at all.

**Comment by damithc** [comment]
Good catch. Didn't notice it before.
