### ISSUE TITLE
`markbind serve` may sometimes cause memory leak for EventEmitter

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#385]
**Tell us about your environment**

* **MarkBind Version:** 1.10.0

**What did you do? Please include the actual source code causing the issue.**

`markbind serve` sometimes causes an memory leak error message to print for EventEmitter:
```
(node:25288) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
```

**Originally reported here:** https://github.com/se-edu/learningresources/pull/62#issuecomment-408679070

**Comment by ang-zeyu** [comment]
does this still occur? @damithc 

I've never encountered this before

May have been a dependency upgrade somewhere that fixed it

**Comment by damithc** [comment]
I've never encountered it myself. Let's close for now.
