### ISSUE TITLE
Add a console progress bar when building website

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#388]
**Tell us about your environment**

* **MarkBind Version:** 1.10.0

**What did you do? Please include the actual source code causing the issue.**
When doing a `markbind build` and `markbind serve`, the console does not print anything to indicate progress. User will stare at a blank screen until the website finish building.

Progress reporting would be nice, especially if the websites are big and might take longer than 5 seconds to build.

**Comment by acjh** [comment]
Related: #133 

> A loading bar of sorts would be helpful as well.
