### ISSUE TITLE
site.json: Add configuration options to specify `head`, `footer`, `site-nav` for specific pages

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#389]
**Tell us about your environment**

* **MarkBind Version:** 1.10.0

As mentioned in https://github.com/se-edu/learningresources/pull/62#issuecomment-408679238:

> Also feels kind of obtuse to be adding `head: head.md` to every document as in https://github.com/se-edu/learningresources/commit/90f6492143925fe799428f52684c7e94ce780a05 , can it be set in the `site.json`?

Reconsider the design for `head: head.md` to be more simple for the user to use. Perhaps some additional configuration settings in `site.json`?

Currently, `footer` and `site-nav` has the same design issue.

**Comment by damithc** [comment]
Some options:
* Introduce a `_markbind/defaults` folder. If it contains any of these files, apply them to all pages containing a frontmatter: `default-navigation. md`, `default-head.md`, `default-footer.md`, `default-styles.css`, `default-scripts.js`
* In `site.json`, allow specifing `head`, `footer`, etc. to the whole site, or to a glob.

**Comment by pyokagan** [comment]
> To add: there's also {{ navbar | safe }} on every single document as well: 

And `<div class="website-content">` as well, so a feature to allow content to appear after `<body>` and before `</body>` would definitely be appreciated.

**Comment by yamgent** [comment]
> And `<div class="website-content">` as well, so a feature to allow content to appear after `<body>` and before `</body>` would definitely be appreciated.

Perhaps we can follow something like Jekyll's layout system, where the user has complete freedom in specifying how the `<body>` is structured:

`_markbind/defaults/body.md`
```html
{{ navbar | safe }}
<div class="website-content">
  <markbind-content /> <!-- reserved MarkBind HTML tag so MarkBind know where to insert the website content -->
</div>
```

**Comment by jamos-tay** [comment]
> Some options:
> 
> * Introduce a `_markbind/defaults` folder. If it contains any of these files, apply them to all pages containing a frontmatter: `default-navigation. md`, `default-head.md`, `default-footer.md`, `default-styles.css`, `default-scripts.js`
> * In `site.json`, allow specifing `head`, `footer`, etc. to the whole site, or to a glob.

Reviving this issue as in came up during discussion.

How about a `_markbind/templates` folder that contains multiple subfolders with template files:

> _markbind/templates/default/
> `navigation.md`, `head.md`, `footer.md`, `styles.css`, `scripts.js`
> 
> _markbind/templates/templateA/
> `navigation.md`, `head.md`, `footer.md`, `styles.css`, `scripts.js`
> 
> _markbind/templates/templateB/
> `navigation.md`, `head.md`, `footer.md`, `styles.css`, `scripts.js`

Users can then specify which template to use within the `site.json`:
```
{
  "glob": "A/*.md",
  "template": "templateA"
}
,
{
  "glob": "B/*.md",
  "template": "templateB"
}
,
{
  "glob": "C/*.md" // No template, apply default
}
```

The files in the corresponding template folder will be applied to all files in the glob.

We can also have a `default` template which will be applied to all pages, unless a different template is specified. This folder can be generated on `init` with all files empty from the start, so it's more convenient for the user.

**Comment by yamgent** [comment]
That certainty sounds feasible. Of course, if the individual `.md` files manually specify the `head:` etc in the frontmatter, they take utmost priority over the template.

Also was thinking whether we might want to consider allowing the user to specify a `template:` in the frontmatter as well. Can't see the benefits atm though.

**Comment by jamos-tay** [comment]
> That certainty sounds feasible. Of course, if the individual `.md` files manually specify the `head:` etc in the frontmatter, they take utmost priority over the template.
> 
> Also was thinking whether we might want to consider allowing the user to specify a `template:` in the frontmatter as well. Can't see the benefits atm though.

Yes I think that's a good idea. We could have cases where the user wants to apply a template to all files in a glob except one, he can then set `template: default` or something just for that file instead of messing around with weird file matching patterns.
