### ISSUE TITLE
Navbar links not working if raw html file opened in browser

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#39]
If I open `_site/index.html` file in a browser, the navbar link to textbook doesn't work.

![image](https://cloud.githubusercontent.com/assets/1673303/25342649/328350c6-293f-11e7-9a2b-3bfaca85d2e8.png)

**Comment by acjh** [comment]
Title: ~now~ not

This is expected behavior for paths relative to root. Files generated are meant to be served by a host.
You can run `build . /site-demo-cs2103` which sets the output folder to `C:/site-demo-cs2103`.

**Comment by acjh** [comment]
Or copy the `_site` folder to `C:/` and rename it to `site-demo-cs2103` to avoid an unnecessary build.

**Comment by damithc** [comment]
I see. Thanks for checking @acjh 
It's not a big problem in that case, although it's nice if we can avoid this complication altogether in some way. i.e. generated files can be previewed simply by opening them on a browser without additional work.

**Comment by damithc** [comment]
Closing as there is a workaround.
