### ISSUE TITLE
Move footer outside "#app" div

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#390]
**Tell us about your environment**

* **MarkBind Version:** 1.10.0

**What did you do? Please include the actual source code causing the issue.**

Due to how `container-fluid` works, everything that is placed inside it will have a padding added on its left and right side. If we did not intervene with this css style, the footer will look like this (notice the white space at the left and right of footer):

<img src="https://user-images.githubusercontent.com/3168908/43373261-1aa9adda-93db-11e8-8f3c-1cc85e1cdbfd.png" width="350"/>

We resolved that issue by specifying `margin-left: -15px` and `margin-right: -15px` as shown below:

https://github.com/MarkBind/markbind/blob/2f9461b4ea63ada3e4a2d6b2bdd062f996498e3d/asset/css/markbind.css#L68-L74

However, this workaround is counter-intuitive, as users wanting to override the css of `container-fluid` must now also modify the css of `footer`, as seen in https://github.com/se-edu/learningresources/commit/d8f206f04b5565dba134066dbf379109bc4683da.

As such, a better workaround on our site would be to change `page.ejs`:

https://github.com/MarkBind/markbind/blob/2f9461b4ea63ada3e4a2d6b2bdd062f996498e3d/lib/template/page.ejs#L20-L22

such that the footer is outside the `container-fluid` (if we do not want the padding effect of `container-fluid`, we should not include it inside in the first place):

```ejs
<div id="app">
    <div class="container-fluid">
        <%- content %>
    </div>
    <%- footer %>
</div>
```

**Comment by pyokagan** [comment]
Why can't the `container-fluid` class be removed?

**Comment by damithc** [comment]
Example for the [above](https://github.com/MarkBind/markbind/issues/390#issuecomment-408743086):
![image](https://user-images.githubusercontent.com/1673303/43378002-8fa806e8-93f6-11e8-9544-13c51c5b21ad.png)
```html
<table> 
<tr>
  <td>

Java {{ icon_output }}
`` `java
class Foo {
    Bar bar;
    //...
}


class Bar {
    Foo foo;
    //...
}

`` `
  </td>
  <td valign="bottom">&nbsp;&nbsp;<br><br></td>
  <td valign="bottom">

Python {{ icon_output }}
`` `python
class Foo:
  
  def __init__(self, bar):
    self.bar = bar;


class Bar:
  
  def __init__(self, foo):
    self.foo = foo;
    
`` `
  </td>
</tr>
</table>
```
