### ISSUE TITLE
Footer's left side has white spacing when not using site-nav

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#391]
**Tell us about your environment**

* **MarkBind Version:** 1.10.0

**What did you do? Please include the actual source code causing the issue.**

When the screen width is between 576px and 992px, there is a white spacing on the left side of the footer when the `site-nav` is disabled.

```markdown
<frontmatter>
  title: "Hello World"
  footer: footer.md
</frontmatter>

# Hello world
Welcome to your page generated with MarkBind.

Abc
```

**What did you expect to happen?**
<img src="https://user-images.githubusercontent.com/3168908/43373504-976f32f8-93dc-11e8-9b0c-a72ea2b7f5b9.png" width="350"/>

**What actually happened? Please include the actual, raw output.**
<img src="https://user-images.githubusercontent.com/3168908/43373506-9b39b9a8-93dc-11e8-8735-e7da570f4fb7.png" width="350"/>

**Comment by Chng-Zhi-Xuan** [comment]
#390 takes precedence over this. Moving the footer to outside the `#app` div will mitigate some of this issue.
