### ISSUE TITLE
Search: Scrolling to heading after page load does not work, if heading contains a colon symbol

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#392]
**Tell us about your environment**

* **MarkBind Version:** 1.10.0

**What did you do? Please include the actual source code causing the issue.**

When searching for the panel's heading "Guideline: Avoid Unsafe Shortcuts" in https://nus-cs2103.github.io/website-base/, the search jumps to the correct page, but the browser does not correctly scroll to the heading section.

This is because the heading's ID used by the search in `MarkBind`, and the heading's ID used by panel in `vue-strap`, are different. This mismatch in ID causes the scrolling logic to fail.

id generated by `markdown-it-anchor` (used by `MarkBind`): `guideline-avoid-unsafe-shortcuts`
id generated by `vue-strap`: `guideline:-avoid-unsafe-shortcuts`

**Comment by damithc** [comment]
Here's another test case. This heading contains `#`

![image](https://user-images.githubusercontent.com/1673303/43377873-f5c03e88-93f5-11e8-8fe6-e82f7236297c.png)

**Comment by nusjzx** [comment]
id generated by markbind repo: `tutorial-timetable-tutor-roletimesvenue`
id generated by vue-strap repo: `tutorial-timetable-tutor-roletimes-venue`
