### ISSUE TITLE
Give a way to format a long block as a block quote

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#393]
v1.10.0

Current: Markbind requires to use `>` to indicate text as block quotes

Problem: It's messy to prepend `>` many times when the quoted text contain many lines

Suggested: Give a class that can be used to style a div/span as a block quote.

e.g.,
```html
<div class="block-quote">
...
</div>
```

**Comment by acjh** [comment]
Have you tried:

```
<blockquote>
...
</blockquote>
```

**Comment by damithc** [comment]
That works. Didn't know about that tag (or forgot it existed :-p) Thanks @acjh
