### ISSUE TITLE
Tooltip: Rewrite the positioning logic of popupMixins.js

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#397]
**Tell us about your environment**

* **MarkBind Version:** The version after 1.10.0

**What did you do? Please include the actual source code causing the issue.**

As specified in issue #338, there was a tooltip positioning issue.

However, it was difficult to disentangle the logic inside `popupMixins.js` because it is spaghetti code, so it was hard to explain the logic behind the calculation of the tooltip position.

A temporary fix was done in PR MarkBind/vue-strap#87. It uses the mouse cursor position to fix the issue. However, we lose the original aesthetic of the tooltip provided by Bootstrap (the arrows in tooltip is gone + the placement attribute no longer matters now).

A more permanent solution would be to either rewrite `popupMixins.js`, or further experiment with Bootstrap-Vue's tooltip to see how we can modify it to suit MarkBind's needs.

**Comment by ang-zeyu** [comment]
Closed by #1033
