### ISSUE TITLE
Scroll to target goes off target if already at the target

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#402]
v1.11.0

Steps.
* Go to https://nus-cs2103.github.io/website-base
* search for `role`
* hit Enter --> page scrolls to the correct location
* search for `role` again
* hit Enter

Expected: page remains at the same scroll position
Actual: page scrolls a bit, hiding the correct target

**Comment by nusjzx** [comment]
The issue is because the target is in the same page, so the page is not reloaded, so fix  by #368 doesn't get executed. so the result is covered by the navbar

**Comment by nusjzx** [comment]
This issue is because we are scrolling by the navbar height if there is hash change. If we scrolling by the navbar height in the searchbar callback and remove the `hashChange` callback, link on the website will be off. Also user will rarely search for the same thing twice.

**Comment by damithc** [comment]
Seems to be fixed now because we don't have sticky TopNavs.
