### ISSUE TITLE
Headings in site-nav and footer should not be searchable

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#406]
**Tell us about your environment**

* **MarkBind Version:** 1.10.1

<img src="https://user-images.githubusercontent.com/3168908/43572117-47450428-9671-11e8-863c-403cc6b15c38.png" width="500" />

**Comment by yamgent** [comment]
A solution would be the limit the collection of headings to be inside the `#app` div.

**Comment by nusjzx** [comment]
you mean page content? site nav is inside `#app`

**Comment by yamgent** [comment]
You are right, should be `#page-content`, sorry wasn't thinking straight.
