### ISSUE TITLE
Set up a testing framework for vue-strap

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#409]
There is currently no testing framework set up for vue-strap at all.

Having a testing framework will be useful to check that we did not break anything when adding new changes. For example, there was a period when we were fixing the caret, and the MarkDown rendering for headers was broken, but it went unnoticed for a day or two.

The tests will need to ensure that Vue generates the correct DOM tree given a component with certain attributes.

For example, for v1.10.1, when the user uses a `<tip-box>` with a "tip" type:

```html
<tip-box type="tip">
    tip
</tip-box>
```

we need to verify that Vue generates the html content to be similar to something like this:

```html
<div data-v-11442d08="" class="alert container alert-success">
    <div data-v-11442d08="" class="icon-wrapper">
        <span data-v-11442d08=""><i class="fas fa-lightbulb"></i></span>
    </div>
    <div data-v-11442d08="" class="contents">
        tip
    </div>
</div>
```

**Suggestion:** In order to be consistent with the main MarkBind repository, we can consider using Jest as the testing framework. We can also supplement it with [Nightwatch.js](http://nightwatchjs.org/) to gain the capability to manipulate HTML elements like a user (e.g. simulating the user typing input to a textbox).

**Comment by nbriannl** [comment]
![image](https://user-images.githubusercontent.com/27397021/80208509-f5625280-8662-11ea-85fd-ec785ef0851e.png)

Tried jest snapshot testing on VueStrap
