### ISSUE TITLE
Explore the feasibility of migrating to TypeScript

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#410]
Currently the development team uses the JetBrain's WebStorm IDE to develop MarkBind. JetBrains IDEs are usually considered to be state of the art, yet at times it can still struggle with the codebase, preventing the features (that makes the IDE so powerful in the first place) from working properly.

One of the reasons is due to JavaScript not having a mechanism to enforce types. This results in difficulty in reasoning about the code because there will be some point where it is nearly impossible for a human to determine the type of an object at a particular section of the code, let alone an IDE. This means the IDE cannot provide the developer with the methods and attributes available to objects, which is critical for features such as autocomplete and finding references to objects and classes.

Adopting Typescript can provide us with two main benefits:

* Reducing the codebase learning curve for new developers. They spent less time studying the code because the IDE will allow them to explore what kind of methods and variables they can (or cannot) use, and who uses these objects. Currently, developers must spend time jumping around the code in order to get a context of what is going on.
* Making it easier for debugging and spotting coding errors. Currently, some coding errors will not be known to us until we run the program.

Consider whether migrating TypeScript is feasible, and whether it will greatly help us make developing MarkBind easier to be worth the effort.

**Comment by yamgent** [comment]
Hi @luyangkenneth, thanks for asking.

Actually, this discussion was resolved face-to-face in August, but I didn't got around to closing it until last month. :P

The rationale for not going ahead with this, is that TypeScript is not the default language of NodeJS, so supporting it would require additional set up and maintenance, on top of the existing codebase that the team has on its plate right now. The costs may outweigh the benefits, as MarkBind was (and still is) a small team, and at that time we don't have the necessary TypeScript expertise to determine whether this was a good choice to pursue or not.

That said, I would be happy to revisit this issue if the migration and maintenance can be done without causing too much disruption to the development and the usage of MarkBind.

**Comment by luyangkenneth** [comment]
Thanks for letting me know! That sounds like a very reasonable decision at this time. I guess much of it also depends on the immediate goals of the project/team - I look forward to hearing more about the roadmap if I get the opportunity to work on MarkBind!
