### ISSUE TITLE
modals within auto-expanded panels don't work

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#417]
v1.12.0

![image](https://user-images.githubusercontent.com/1673303/43987531-b560108a-9d54-11e8-8526-41ce3b4b93cf.png)

Modals like these don't work, unless I collapse and expand the panel once first. The same content works if not inside a panel.

![image](https://user-images.githubusercontent.com/1673303/43987554-149c6454-9d55-11e8-9268-b390009162ae.png)

**Comment by yamgent** [comment]
Can reproduce this if the page containing the modal is inserted into the panel using the `src` attribute.

`index.md`:
```html
<panel header="Abc" src="other.md" expanded>
</panel>
```

`other.md`:
```html
More about <trigger for="modal:trigger_id">trigger</trigger>.
<modal title="Modal" id="modal:trigger_id">
    ...
</modal>
```

However, this problem seems to be solved if we use `include` in lieu of panel's `src`:

`index.md`:
```html
<panel header="Abc" expanded>
<include src="include.md" />
</panel>
```
