### ISSUE TITLE
Typing '|' into the search bar crashes the page

### ISSUE THREAD

**Issue by jamos-tay** [MarkBind/markbind#427]
v1.12.0

**What did you do? Please include the actual source code causing the issue.**

On any markbind site with a search bar (e.g. https://markbind.github.io/markbind/ ), typing a | in the search bar seems to crash the page (when search is triggered).

Might be a vue-strap issue?

**Comment by damithc** [comment]
As we are doing an OR search anyway, may be we can simply ignore `|`?

**Comment by damithc** [comment]
BTW, what other search syntax features are provided by vuestrap?

**Comment by acjh** [comment]
> Yes. Would that work?

It would fix this issue, but other variants (2 examples in my first comment above) still break.
Although it is more unlikely for users to do those, this would be a partial and non-obvious fix.

If we want to continue allowing regex, a possibly better alternative is to check if the number of results is greater than a threshold and then inform the user that there are "Too many results".

> BTW, what other search syntax features are provided by vue-strap?

Nothing worth mentioning comes to mind. Regex search by user was kind of accidental.
