### ISSUE TITLE
Links in tooltips are unaccessible

### ISSUE THREAD

**Issue by hidingmode** [MarkBind/markbind#431]
Links in tooltips (popups that appear on hover) cannot be reached since the tooltips disappear when unhovered.

Example from https://nus-cs2103-ay1819s1.github.io/cs2103-website/se-book-adapted/chapters/revisionControl.html
![Example](https://i.gyazo.com/c6836ac43432c2682e56cd8f94870a37.gif)

**Expected behaviour**
Maybe the tooltip can stay visible for a bit before fading out like in https://stackoverflow.com/a/16663648/4858751

Issue forwarded from https://github.com/TEAMMATES/teammates/issues/9126

**Comment by damithc** [comment]
I suppose this is more of the author (that's me :-p) not using the correct feature. I should have used a modal instead of a popover in this case. I'll update it.

**Comment by damithc** [comment]
> I'll update it.

Done.
