### ISSUE TITLE
Support custom keywords

### ISSUE THREAD

**Issue by jamos-tay** [MarkBind/markbind#436]
Extension of #428 

With the current implementation of keywords, users are forced to include these keywords in the text if they want them to be tagged to a heading.

Allow the option of having keywords invisibly tagged to a heading, for example:

```
# Using a Java IDE
<span class="keyword hidden">Eclipse</span>
<span class="keyword hidden">Netbeans</span>
<span class="keyword hidden">IntelliJ</span>
```

**Comment by yamgent** [comment]
Maybe this can just be a custom css style?

```
.keyword.hidden {
    display: none;
}
````

**Comment by damithc** [comment]
using one class is better than two.

**Comment by acjh** [comment]
The case for Atomic CSS: http://johnpolacek.com/rethinking/

Since we already ship with Bootstrap 4, this should already work:

```c#
<span class="keyword d-none">Eclipse</span>
```

**Comment by damithc** [comment]
> Since we already ship with Bootstrap 4, this should already work:

In that case, the first stage could be simply documenting this technique. At a later stage, we can introduce a simpler syntax.
