### ISSUE TITLE
Update documentation Landing Page

### ISSUE THREAD

**Issue by jamos-tay** [MarkBind/markbind#438]
Follow up on discussion with @damithc on 19 Sep

Some of MarkBind's recently added features can be reflected on the Landing page (https://markbind.github.io/markbind/index.html).

For example, the search bar and side bar. Could I check with the team on which other ones were recently added?

**Comment by yamgent** [comment]
No other really significant features comes to mind for the summer period. Most of the changes are invisible functionality changes such as the searchbar enhancement, bug fixes and migration upgrades.

Maybe consider using a favicon for the website, and showcase the different types of tipboxes? Those are the two features that are not on the landing page.

**Comment by yamgent** [comment]
The documentation have received a huge revamp recently, so maybe it is not relevant anymore?

Also, favicon for the website is superseded by #565.

**Comment by yamgent** [comment]
@jamos-tay The documentation have received a huge revamp recently, so maybe it is not relevant anymore?

Also, favicon for the website is superseded by #565.

**Comment by damithc** [comment]
The landing page has been updated. Will update periodically.
