### ISSUE TITLE
Show anchor icons for heading inside panels

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#442]
**Tell us about your environment**

* **MarkBind Version:** 1.13.0

**What did you do? Please include the actual source code causing the issue.**
Followup from https://github.com/MarkBind/markbind/issues/426#issuecomment-425449396.

```html
<panel header="# Some heading">
    ... Some content here ...
</panel>
```

**What did you expect to happen?**
An anchor icon appears right beside the heading.

**What actually happened? Please include the actual, raw output.**
No anchor icon show up beside the heading.

<img src="https://user-images.githubusercontent.com/1673303/46213720-ebd01600-c36b-11e8-9416-1a76fbc1312c.png" width="400"/>

**Comment by damithc** [comment]
Funny thing: when I tried v1.13.0, for a brief period these anchors did show up, but now they don't. :-p Even when they did show up, the were useless because clicking on them would collapse the panel instead of resetting the URL bar.
