### ISSUE TITLE
Add a Windows-specific CI such as AppVeyor

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#448]
We currently utilize Travis as our sole CI, which does testing on Linux for our PRs.

We should consider adding AppVeyor as a second CI so that we can run the tests on Windows too, to be assured that our code runs on Windows without any issues as well (since it is possible that the same code might behave differently on different OS).

**Comment by nicholaschuayunzhi** [comment]
> (since it is possible that the same code might behave differently on different OS).

One of the differences would be the forward and backward slashes in generated in paths. The testing should still be fine on that part though because we ignore such differences during our tests.

**Comment by yash-chowdhary** [comment]
Is it possible for a non-member of the MarkBind organization to enable AppVeyor on the repository? AppVeyor needs Organization Access (which only members can grant) to be able to build on each commit/PR.

**Comment by damithc** [comment]
> Is it possible for a non-member of the MarkBind organization to enable AppVeyor on the repository? AppVeyor needs Organization Access (which only members can grant) to be able to build on each commit/PR.

You can create a dummy org to try the set up. Once the set up is working, PR here to add the required files and also specify the steps one of the org admins can follow to set it up for this repo.
