### ISSUE TITLE
Tweak tipbox styles

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#45]
`tipbox` --> `box`?

Name|color|icon
---|---|---
Wrong | Red | `x`
Warning|Orange| `!`
Tip|Green| :bulb:
Definition|blue | :bookmark:
Example|white|

**Comment by Gisonrg** [comment]
Adding more styles in 1.3.3.
Checkout https://markbind.github.io/vue-strap/#tipBoxDocs for the updated styles :)
