### ISSUE TITLE
Ascii symbols not showing up when coming through an incude

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#458]
v1.13.0

![image](https://user-images.githubusercontent.com/1673303/47602654-76ac3b00-da14-11e8-9b28-56be8fd29dd6.png)

The same code, repeated twice, but the second one is via an `include`. The ascii symbol does not appear correctly in the second case 🤔

**Comment by jamos-tay** [comment]
I can't reproduce this on 1.13 or 1.14:

index.md
```
<frontmatter>
  title: "Hello World"
</frontmatter>

# Test
→
<include src="in.md" />
```

in.md
```
→
```

![image](https://user-images.githubusercontent.com/19278089/47794181-ebf07680-dd5a-11e8-8db6-14ed940a0bed.png)

Can I see the markdown for this page?

**Comment by damithc** [comment]
Let's close it for now. Will reopen if it crops up again.
