### ISSUE TITLE
Spacing issue on inline elements

### ISSUE THREAD

**Issue by thomastanck** [MarkBind/markbind#464]
**Tell us about your environment**

* **MarkBind Version:** The one on the [website] as of 12/12/2018

**What did you do? Please include the actual source code causing the issue.** I looked at the website

```html
<p>something<code>include</code> something</p>
```

**What did you expect to happen?**
`include` should have spaces on both sides

**What actually happened? Please include the actual, raw output.**
The space was only added on the right side

![maim](https://user-images.githubusercontent.com/829070/49853765-24d43e80-fe23-11e8-9ca8-d6398081d6dd.png)

[website]: https://markbind.github.io/markbind/

**Comment by Chng-Zhi-Xuan** [comment]
Thanks for the report, will add the space in our documentation.

**Comment by damithc** [comment]
Should we add spaces at all? i.e., should we leave it to the author to have or not have spaces?

**Comment by damithc** [comment]
Wait, is this a bug in documentation or a bug in how MarkBind works?

**Comment by Chng-Zhi-Xuan** [comment]
It is simply forgetting a space within the `index.md` file, at that particular sentence within our documentation. 

![documentation-missing-space](https://user-images.githubusercontent.com/31084833/49865551-3546e200-fe40-11e8-9b7a-22e11afe60e5.PNG)

**Comment by damithc** [comment]
> It is simply forgetting a space within the `index.md` file, at that particular sentence within our documentation.
> 
> ![documentation-missing-space](https://user-images.githubusercontent.com/31084833/49865551-3546e200-fe40-11e8-9b7a-22e11afe60e5.PNG)

Got it. 👍

**Comment by damithc** [comment]
@thomastanck feel free to submit a PR to fix it.
