### ISSUE TITLE
Support custom MarkBind plugins

### ISSUE THREAD

**Issue by jamos-tay** [MarkBind/markbind#470]
Edited from https://github.com/MarkBind/markbind/pull/467#issuecomment-446689914

Consider using a plugin concept, e.g. in Eslint.

>    For a start, we can have a `postRender` entry point. This means something like this in **site.json**:
>    ```js
>    {
>      "plugins": [
>        "custom-plugin"
>      ],
>      "context": { // Can consider a different name
>        "custom-plugin": ... data
>      }
>    }
>    ```
>    
>    
>    And in **src/plugins/custom-plugin.js**:
>    ```js
>    module.exports = {
>      postRender: function (content, siteContext, pageConfig) {
>        // ...
>        return $.html();
>      },
>    };
>    ```
>    
>    
>    And in **Page.js**:
>    ```diff
>    + .then(result => this.postRender(result, siteContext, pageConfig))
>    ```
>    
>    
>    ```js
>    Page.prototype.postRender = function (content, siteContext, pageConfig) {
>      let postRenderedContent = content;
>      plugins.forEach((plugin) => { // Might be able to do `reduce` instead of `forEach`
>        if (plugin.postRender) {
>          postRenderedContent = plugin.postRender(postRenderedContent, siteContext, pageConfig);
>        }
>      });
>      return postRenderedContent;
>    };

Entry points we can support (for now):

```diff
      .then(result => addContentWrapper(result))

      -- prerender entry point--

-     .then(result => this.insertSiteNav((result)))
-     .then(result => this.insertFooter(result)) // Footer has to be inserted last to ensure proper formatting
-     .then(result => formatFooter(result))
      .then(result => markbinder.resolveBaseUrl(result, fileConfig))
      .then(result => fs.outputFileAsync(this.tempPath, result))
      .then(() => markbinder.renderFile(this.tempPath, fileConfig))

      -- postrender entry point--

-     .then(result => this.filterTags(this.frontMatter.tags, result))
-     .then(result => this.addAnchors(result))
```

Consider migrating to plugins?
- Site nav and footer
- Tags
- Anchors

**Comment by yamgent** [comment]
> Consider migrating to plugins?
> 
> * Site nav and footer
> * Tags
> * Anchors

They can be considered, but since this will just involve mostly code movement without visible changes for the user, the priority for this issue will be low.
