### ISSUE TITLE
Support annotations in code examples

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#473]
Current: code snippets can be syntax colored

Suggested: add the ability to add more information into code snippets, for example, 
* highlight specific parts of the code
* add a comment about a specific part of a code
* show line numbers

**Comment by openorclose** [comment]
Some prior work:

This markdown plugin allows for highlighting of specific lines (not parts):

![image](https://user-images.githubusercontent.com/3646725/72657487-d8711000-39df-11ea-9a3d-8a3236e4cc80.png)

https://github.com/egoist/markdown-it-highlight-lines

https://meta.stackexchange.com/questions/221268/highlighting-and-notating-part-of-a-line-in-a-code-block

This stackoverflow post from 5 years ago also asked for a similar feature.

**Comment by nbriannl** [comment]
Just curious, I assume you'll be installing markdown-it plugins and passing multiple markdown-it-attrs to the fenced code blocks to fulfill the above functionality?

**Comment by openorclose** [comment]
If we were to use vue components, feels like the syntax would be roughly the same:

````html
<codeblock stuff-to-highlight="<custom syntax>" display-language="MarkBind">
```md
# Some markbind 
```
</codeblock>
````

vs 


````md
```md {stuff-to-highlight="<custom syntax>" display-language="MarkBind"}
# Some markbind 
```
````

So maybe using markdown-it-attrs for it is ok.

**Comment by crphang** [comment]
I have an implementation calling it internally as Widget, which is similar to (1) . Currently it helps to escape syntax using code fence (data layer) and allow it to inject additional context using a more familiar Markbind components.

https://github.com/MarkBind/markbind/pull/968

The PR above handles both src and inline PUML.

**Comment by nbriannl** [comment]
Currently, #991, #1020 are adding additional features to code block via `markdown-it-attr` 

````
```md {highlight-lines="1,2,4-5" heading="Can contain either file name or language used"}
# Some markbind 
```

```md {..no-line-numbers heading="Can contain either file name or language used"}
# Some markbind 
```

```html
# Some html code
```
````

**Comment by damithc** [comment]
>`md {highlight-lines="1,2,4-5" heading="Can contain either file name or language used"}` 

Is anybody adding support for line highlighting (as hinted by this code snippet)?

**Comment by nbriannl** [comment]
@damithc I'm interested in adding support for line highlighting. But I'm waiting for #991 and thereafter complete #1020. I don't think it would be wise to combine multiple features in the same PR. (i.e. do headings as a well as line highlighting support together in the same PR)

**Comment by nbriannl** [comment]
![image](https://user-images.githubusercontent.com/27397021/73749085-a3add880-4795-11ea-9bd8-ce8ffed381be.png)

extending off #991's implementation, since the rows are now individual spans, we simply need to add a `highlighted` class to rows that need to be highlight and we are done.

The tricky part is to parse the attribute. For example "1,2,4-6", should be parsed as 1, 2, 4, 5, 6. 

Once that is done, highlighting the lines should be ok.
