### ISSUE TITLE
Add MarkBind to staticgen.com

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#478]
We can add MarkBind here https://www.staticgen.com/contribute

**Comment by damithc** [comment]
Thanks @Xenonym I was hoping we can do #479 in conjunctions with this issue too.

**Comment by damithc** [comment]
> PR created here: [netlify/staticgen#467](https://github.com/netlify/staticgen/pull/467)

@Xenonym can you close the current PR? I'm doing some updates to our docs. We can re-submit that PR after our docs are updated.

**Comment by Xenonym** [comment]
@damithc sure thing!

**Comment by Xenonym** [comment]
@damithc should we revisit this? The docs have been updated.

**Comment by damithc** [comment]
> @damithc should we revisit this? The docs have been updated.

Let's do this towards the end of the semester; I don't want to jump the gun before MarkBind is ready for widespread use. :-) With the addition of a few more key functionalities, MarkBind should be able to deliver more value to the target users than even the most established competing products.

**Comment by Crphang** [comment]
Added in: https://github.com/netlify/staticgen/pull/644

https://deploy-preview-644--staticgen.netlify.com/

**Comment by damithc** [comment]
@Crphang Can update the description as follows? 
~~Generate dynamic websites from Markdown text~~
Optimized for generating technical documentation and educational websites from Markdown text.

**Comment by Crphang** [comment]
Updated.

**Comment by yamgent** [comment]
netlify/staticgen#644 is merged and we are now live at https://www.staticgen.com/ 🎉🎉
