### ISSUE TITLE
Support live preview for new entries to sites.json

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#48]
Adding the following to sites.json required a restart of the server to see the page `http://127.0.0.1:8080/site-demo-cs2103/book/common/References.html`.

```json
    {
      "src": "book/common/References.md",
      "title": "CS2103/T Textbook - References"
    }
```

**Comment by damithc** [comment]
@alyip98 can you check if this issue is still applicable?

**Comment by ang-zeyu** [comment]
Very much still applicable
