### ISSUE TITLE
Remember child panel states after collapsing the parent panel

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#483]
Context: a collapsible panel P has collapsible child panels C. Both are collapsed by default. Expand P, expand C, collapse P, expand P.
Previous (before Bootstrap 4 migration):  C is still expanded
Current: C has gone back to the default state (collapsed)

Suggested: go back to the previous behavior as it preserves the panel state previously set up by the user.

However, I'm not sure how much effort it will take. If it is too much effort, or there are some other tradeoffs involved, we can stick with the current behavior.

**Comment by yamgent** [comment]
We do not store any changes to the content of the panel at all. For example, the checkboxes values aren't remembered too.

Perhaps a simple fix would be to capture the HTML content currently inside the panel before collapsing. Currently I believe when collapsing and re-expanding, it just reuses the initial content it has when the page is first loaded.

<img src="https://user-images.githubusercontent.com/3168908/50380337-5e1c7200-069f-11e9-8f8e-a42d533f68c3.gif" width="500"/>
