### ISSUE TITLE
Question on markbind installation

### ISSUE THREAD

**Issue by JYL123** [MarkBind/markbind#491]
**Tell us about your environment**
MacOS 10.12.6 
* **MarkBind Version:**
 v1.14.2
**What did you do? Please include the actual source code causing the issue.**
I am following the [user guide](https://github.com/MarkBind/markbind-cli/wiki/Developer-Guide), and run `npm install -g markbind-cli` from the terminal. I get the following error:

```html
> fsevents@1.2.4 install /usr/local/lib/node_modules/markbind-cli/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.4.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after field 'lockStarted' [-Wreorder]
   : async_resource("fsevents:FSEvents"), lockStarted(false) {
     ^
1 warning generated.
  SOLINK_MODULE(target) Release/fse.node
  COPY /usr/local/lib/node_modules/markbind-cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

```
I am seeking help to understand and resolve this error, and I am wondering, is it because of the version of `fsevents` which should be `2.0.1` instead of `1.2.4` in the script? because when I  follow the [developer guide](https://github.com/MarkBind/markbind-cli/wiki/Developer-Guide), with command `npm install`, it displays: 
```html
> fsevents@2.0.1 install /Users/ljy/markbind/node_modules/fsevents
> [ -f fsevents.node ] || npm run prepare
```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output.**

**Comment by yamgent** [comment]
That is a warning, not an error. It should not cause any issues in installation. The warning is caused by a library's implementation that is not specific to MarkBind. Are you facing issues with using MarkBind?

**Comment by JYL123** [comment]
@yamgent Thanks for your reply. So it's expected. I am clear now.
