### ISSUE TITLE
Provide a shorter syntax for specifying complicated panel headings

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#492]
Current: a complicated panel/modal heading (i.e., when the heading cannot be specified using inline markdown as `heading="#Notes to remember")` can be specified using the following `slot` syntax:
```html
<panel>
    <span slot="header" class="card-title">
        Complicated content to be used as heading ...
    </span>
</panel>
```

Suggested: provide a shorter syntax e.g,
```html
<panel>
    <heading>
        Complicated content to be used as heading ...
    </heading>
</panel>
```

**Comment by jamos-tay** [comment]
What if we used an attribute instead so we don't have to make a new tag? e.g.:

<panel>
    <span heading>
        Complicated content to be used as heading ...
    </span>
</panel>

**Comment by damithc** [comment]
> What if we used an attribute instead so we don't have to make a new tag?

Better than the current state, although may not as good as a separate tag, from the author's POV. What are the costs/benefits for attribute vs tag?

**Comment by damithc** [comment]
I'm OK with `<span heading>`
