### ISSUE TITLE
Extend 'optional include' functionality to page fragments

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#497]
Current: #468 allows `<include src="foo.mbd" optional />` to fail sliently if `foo.mbd` doesn't exist.

Suggestion: Allow `<include src="foo.mbd#bar" optional />` to fail sliently if `bar` doesn't exist in `foo.mbd`

Justification: This remove the need to have empty divs/spans in files when the div doesn't apply.

**Comment by damithc** [comment]
@Xenonym interested?

**Comment by Xenonym** [comment]
@damithc sure,I will take a look!
