### ISSUE TITLE
popover goes out of screen

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#50]
example: `http://127.0.0.1:8080/site-demo-cs2103/book/requirements/userStories/`

![image](https://cloud.githubusercontent.com/assets/1673303/25574051/2250c8c6-2e7d-11e7-9107-dd6c3e2ae289.png)

**Comment by Gisonrg** [comment]
Implemented an attempt in 1.3.0. It should get improved a little bit.

**Comment by damithc** [comment]
v1.3.0
Seems to work fine on Chrome but on Firefox some popovers appear at the top of the page.
![image](https://cloud.githubusercontent.com/assets/1673303/26282495/3e5a1536-3e45-11e7-9a0e-a6513d7e9666.png)
