### ISSUE TITLE
site.json: do not auto-add '-' to the titlePrefix

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#501]
Current:
![image](https://user-images.githubusercontent.com/1673303/50463701-317e9800-09c8-11e9-8c05-26a453799671.png)

Suggested: Let the user include the separator in the value of `titlePrefix` instead. e.g.,
`titlePrefix : "MarkBind: "`

Justification: Gives user the more control

**Comment by acjh** [comment]
It will look odd if the page does not have a title.

**Comment by damithc** [comment]
> It will look odd if the page does not have a title.

Yes, that's a good point. We can leave it as it is then.
