### ISSUE TITLE
Use .mbd extension for system files

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#502]
Should we use `.mbd` for system files e.g., files in the `_markbind` directory such as `variables.md`?

We can still support (i.e., undocumented support) `.md` for backward compatibility reasons

**Comment by yamgent** [comment]
> Should we use `.mbd` for system files e.g., files in the `_markbind` directory such as `variables.md`?

We can do that. Only concern is that we might slowly lose features that we take for granted in `.md` (e.g. native IDE and GitHub support for syntax highlighting in markdown file).

> We can still support (i.e., undocumented support) `.md` for backward compatibility reasons

We could do that, but I feel that deprecating it first, and then removing it in a far-future version might be more feasible to avoid complicating the codebase if we are fully committed in migrating the format over.

**Comment by acjh** [comment]
Should work on GitHub if we specify in `.gitattributes` file.
See https://github.com/github/linguist#using-gitattributes.

We can generate the file in `markbind init` too.

**Comment by yamgent** [comment]
> How about this stance?: Use `.md` files for source code, but you may use `.mbd` and `.mbdf` if you want to separate pure Markdown files from MarkBind files.

Sounds good.

**Comment by damithc** [comment]
> How about this stance?: Use `.md` files for source code, but you may use `.mbd` and `.mbdf` if you want to separate pure Markdown files from MarkBind files.

This still means we need to support both `variables.md` or `variables.mbd` though

**Comment by yamgent** [comment]
> This still means we need to support both `variables.md` or `variables.mbd` though

That is true, I guess we can keep both but prioritize `.mbd` if both files exist.

**Comment by ang-zeyu** [comment]
closing per #1672
