### ISSUE TITLE
Layout: Allow references to external scripts

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#505]
**Tell us about your environment**

* **MarkBind Version:** 1.15.2

I want to refer to an external script at the bottom of the page. For example:

```html
   ...
   <script src="..\markbind\js\setup.js"></script>
   <script src="https://example.com/some-script.js"></script> 
   <script src="..\markbind\layouts\default\scripts.js"></script>
</html>
```

`https://example.com/some-script.js` is the external script that I am referring to.

There's no way of doing that with our current layout system.

**Comment by Chng-Zhi-Xuan** [comment]
**Discussion:**

Implementation wise could be straight forward by specifying an array of script sources within `site.json` and then inserting it within `page.ejs` 

However, controlling which position each script is inserted might be challenging. Should we standardise it to insert after our set of scripts?

**Comment by yamgent** [comment]
> Should we standardise it to insert after our set of scripts?

Sure, it can be after all the scripts that MarkBind uses by default (up to `..\markbind\js\setup.js` in our example), but perhaps the layout's `default\scripts.js` should be the last, since the logic contained in this script is usually "custom written" by the author, and usually difficult to justify refactoring them out as a script that stands on their own? Usually such code is always at the last.
