### ISSUE TITLE
Relationship between frontmatter and site.json

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#506]
1. Is it correct to say that anything that can be specified in frontmatter can be specified in site.json?
2. If yes, any property in frontmatter can be _overridden_ by site.json?

**Comment by Chng-Zhi-Xuan** [comment]
1. Yes, currently each page's variables are initialised with values provided within `site.json`

2. It is possible with some modifications to the code base. Currently the values are stored in different places.

The ones in `site.json`'s `pages` object are direct variables in a page (`page.variable`) while the ones in `frontmatter` are stored in the `frontmatter` object of a page (`page.frontmatter.variable`).

So currently there are no overlaps. Although the components I have coded before (siteNav and footer), do not check if it was specified directly in a page variable, but only in `page.frontmatter`.

**Comment by damithc** [comment]
Thanks @Chng-Zhi-Xuan 

> any property in frontmatter can be overridden by site.json?

Does it make sense to go in that direction? It certainly makes things easier to explain to the user. i.e., we have a bunch of _page properties_ that can be specified in frontmatter and overridden in site.json.

What do you all think?

**Comment by yamgent** [comment]
Standardizing it such that all properties can be overridden by `site.json` is a good idea, it makes the page reusable by many different projects.

**Comment by damithc** [comment]
Created #647
