### ISSUE TITLE
site.json: which glob format is used?

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#508]
site.json uses glob format for `pages` and `ignore`. Are they the same format? Which exact format?

**Comment by Chng-Zhi-Xuan** [comment]
Currently `ignore` is using the [`ignore` package](https://www.npmjs.com/package/ignore) which implements the [`.gitignore file pattern`](https://git-scm.com/docs/gitignore#_pattern_format).

`glob` resolves paths using [`walk-sync`](https://www.npmjs.com/package/walk-sync) which does not explicitly state a file or folder pattern.

**Comment by damithc** [comment]
I see. Can we use the same format for both?

**Comment by Chng-Zhi-Xuan** [comment]
I think glob's `walk-sync` implements the same `.gitignore` file pattern for resolving files or directories upon some checking. 

If that is the case, then all we have to do is mention it within the user documentation 😄

**Comment by damithc** [comment]
So I guess they are different patterns and it makes sense to keep them as such?

**Comment by Chng-Zhi-Xuan** [comment]
It would be safe to assume that. 

Although after some digging, `.gitignore` also supports the `unix glob` standard, so I guess both can be standardised to use that? (Although we might lose some features in `.gitignore` pattern)

**Comment by yamgent** [comment]
> Although after some digging, `.gitignore` also supports the `unix glob` standard, so I guess both can be standardised to use that? (Although we might lose some features in `.gitignore` file pattern)

I think the different purposes (and hence the different patterns) justify keeping it the way as it is. For example, the `.gitignore` pattern format supports the `!` prefix to negate the previous ignore patterns. That would not make sense for `glob`, but pretty useful for `ignore`.

**Comment by damithc** [comment]
OK then, let's keep the two formats, unless there is some new inputs pointing the other way. Thanks both for inputs.
