### ISSUE TITLE
Use smaller font size for block quotes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#51]
The current font size makes block quotes stand out more than the regular text. 
![image](https://cloud.githubusercontent.com/assets/1673303/25574626/b6fecba8-2e82-11e7-9697-0b26b519c41e.png)

Ideally, they should be the same size as normal text.

**Comment by damithc** [comment]
@acjh can take a look at this one? I would like to fix this before students start using the website.

**Comment by acjh** [comment]
This isn't a Markbind issue (it's in `bootstrap.min.css`), so should override in [`se-book/.../css/textbook.css`](https://github.com/MarkBind/se-book/blob/master/css/textbook.css):

```css
blockquote {
    font-size: 14px;
}
```

Shall I submit a PR to [Markbind/se-book](https://github.com/MarkBind/se-book)?

**Comment by damithc** [comment]
The thing is, we need it for `/se-book` but also for `/cs2103-website` as well. Not possible to fix at a higher level so that it can apply to anywhere markbind is used? If not, we'll have to fix it in the css files of the individual sites.

**Comment by acjh** [comment]
Noted. I can do the override in a separate `markbind.css` stylesheet in [MarkBind/markbind-cli](https://github.com/MarkBind/markbind-cli).
It will be included the same way as how `bootstrap.min.css` and `github.min.css` are included.

**Comment by damithc** [comment]
> Noted. I can do the override in a separate markbind.css stylesheet in MarkBind/markbind-cli.
> It will be included the same way as how bootstrap.min.css and github.min.css are included.

Sounds good to me. @Gisonrg any input?

**Comment by Gisonrg** [comment]
Yes, just need to change the markbind.css in the MarkBind-cli and push a
new version would do.

I am currently on my first week of work, a little busy right now. And will
be on business trip in the next two weeks. I will take a look at everything
happening this week tonight and fix some urgent ones before I fly.

Thanks,
Jason

**Comment by damithc** [comment]
> I am currently on my first week of work, a little busy right now. And will
> be on business trip in the next two weeks. I will take a look at everything
> happening this week tonight and fix some urgent ones before I fly.

No worries @Gisonrg At the moment I think #79  is the one at the top of the priority list.
