### ISSUE TITLE
{{ fab_markdown }} is not working

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#510]
`{{ fab_markdown }}` doesn't seem to be working although other brand icons e.g., `{{ fab_github }}` are working.

**Comment by damithc** [comment]
@Chng-Zhi-Xuan Is it because MarkBind doesn't recognize recent additions to fontawesome?

**Comment by Chng-Zhi-Xuan** [comment]
Yes, the font awesome list was manually formatted ( hard coded ). So it does not automatically update when new icons are added. 

Maybe we should schedule library / asset updates before major releases of MarkBind?

**Comment by damithc** [comment]
I see. 
I guess there is no way to keep the list updated automatically/semi-automatically? They seem to have an API.
Failing the above, is there a workaround for users if the certain FA icon is not yet available in MarkBind?

**Comment by Chng-Zhi-Xuan** [comment]
Our current implementation serves font awesome asset locally for minimal load times. The web API of inserting a `<link>` to fetch assets only fetches the explicit version stated, not automatically fetching the latest version.

The easiest and fastest way is to insert the required link for the latest version within the `<head>` as shown [here](https://fontawesome.com/start). But you are unable to use the {{variable}} syntax for new icons as that is hard coded. You would have to use the syntax as given on their guide or make your own variables manually.

**Comment by damithc** [comment]
I see. Is there an easy way to update the copy bundled with MarkBind every time we do a new release?

**Comment by yamgent** [comment]
We can specify the current version of FontAwesome being used in the documentation. The link to the 'list of icons' should be tied to the current version (currently, our URL in the documentation always links to the latest version). 

Updating of FontAwesome can be done periodically (but not extremely frequently, since updating requires manual work) when there are substantial changes to the icon list.

**Comment by damithc** [comment]
> We can specify the current version of FontAwesome being used in the documentation. The link to the 'list of icons' should be tied to the current version (currently, our URL in the documentation always links to the latest version).

Let's do that. I usually go directly to the FA website though. :-p

> Updating of FontAwesome can be done periodically (but not extremely frequently, since updating requires manual work) when there are substantial changes to the icon list.

Perhaps we can have an internal script to scrape the FA website so that updating the list is easier?

**Comment by yamgent** [comment]
> Perhaps we can have an internal script to scrape the FA website so that updating the list is easier?

The list isn't the only thing that needs to be updated though, the bundled fonts will also need to be updated. Although it may be possible to have an internal script to do all of them.
