### ISSUE TITLE
What is the extent of Bootstrap support?

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#511]
To what extent do we support Bootstrap? For example, I thought a MarkBind site can use any Bootstrap component (https://getbootstrap.com/docs/4.2/components/alerts/) but that doesn't seem to be the case?

**Comment by damithc** [comment]
Why wouldn't this work? It's VueStrap's dismissible alert. It shows up but cannot be dismissed.

```html
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Holy guacamole!</strong> You should check in on some of those fields below.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
```

**Comment by Chng-Zhi-Xuan** [comment]
@damithc 

It requires Bootstrap's Javascript utilities for interactive components. My page navigation PR has added them to our assets. It is almost ready for review and upon merging, you can use any of the interactive Bootstrap components such as dismiss-able alerts.

**Comment by damithc** [comment]
> It requires Bootstrap's Javascript utilities for interactive components. My page navigation PR has added them to our assets. It is almost ready for review and upon merging, you can use any of the interactive Bootstrap components such as dismiss-able alerts.

Nice 👍

**Comment by damithc** [comment]
Yes, seems to be working now. We should document it.

**Comment by alyip98** [comment]
Bootstrap support is mentioned [here](https://markbind.org/userGuide/markBindSyntaxOverview.html#support-for-vuestrap-and-bootstrap). It's a brief mention, but I think it's sufficient since it contains a link to the official Bootstrap docs.

**Comment by damithc** [comment]
> Bootstrap support is mentioned [here](https://markbind.org/userGuide/markBindSyntaxOverview.html#support-for-vuestrap-and-bootstrap). It's a brief mention, but I think it's sufficient since it contains a link to the official Bootstrap docs.

Would be nice to add some examples of nice BootStrap/Vue components, similar to this:
>![image](https://user-images.githubusercontent.com/1673303/58873222-68d03e00-86f8-11e9-805b-4fdbbd3c8096.png)
