### ISSUE TITLE
How to mark code as html?

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#512]
We can use `<markdown>` tags to mark code as markdown. Is there a way to mark code as html? 

Reason: In some cases we don't want code to be parsed as markdown, especially because markdown treats 4-space indentation as a code block.

**Comment by damithc** [comment]
Wrapping in a pair of `<span>` tag (without a blank line at the start) should work too?

**Comment by yamgent** [comment]
> Wrapping in a pair of `<span>` tag (without a blank line at the start) should work too?

It does (in fact, any tag will work, need not be `<span>`), but then if there are blank lines within the content then it will fail:

```
<span>
**This will be normally rendered.**

**This will be in bold.**
</span>
```
