### ISSUE TITLE
Improve the init command

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#519]
Some suggestions for improving the `init` command (can be broken down to multiple PRs):

The default starter site can be enhanced to make it more useful to the user as a starting point. e.g., create a site that has all typical features (i.e., top nav, site nav, footer, search, a bunch of pages typically used such as home, contact, docs etc.) so that the user can go from there to a production website with least amount of effort.

Perhaps we can have other options?

`--minimal`: create an empty site 
`--convert`: converts an existing site to a MarkBind site. This can be an 'intelligent' conversion e.g., deduce siteNav items based on page titles
`--restore`: restores the folder to the previous state (i.e., reverses the `init` command)

**Comment by Chng-Zhi-Xuan** [comment]
I would say `--minimal` and `--restore` is reasonable to implement, as well as revamping the default init `index.md`. 

However, `--covert` could prove to be challenging as existing html code could have components that MarkBind does not support (from other static site generators). A straightforward implementation could be using `jQuery` or `Cheerio` to extract the `<body>` of the previous site and place it within the `index.md` file. Any rendering or formatting issues would have to be manually fixed by the user. An advantage of this is that any of the `<frontmatter>` components can be used immediately without changes to existing code base.

**Comment by damithc** [comment]
> However, `--convert` could prove to be challenging as existing html code could have components that MarkBind does not support (from other static site generators).

We can limit this feature to simple markdown-based document repositories, such as documentation in GitHub repos/wikis. The main aim is to give an easy way for GitHub repos to convert their documentation into a MarkBind site.

**Comment by damithc** [comment]
@amad-person this is somewhat related to your current work.

**Comment by damithc** [comment]
related #861

**Comment by yash-chowdhary** [comment]
> `--restore`: restores the folder to the previous state (i.e., reverses the `init` command)

Would this simply cover deleting the files and directories that `init` created (`contents`, `site.json`, `index.md` and `_markbind`) or should it be the case that this command can _only_ be run immediately after `init` is executed (I'm thinking of the case where `serve` or `build` has been executed and then `--restore` is executed, or where it's run before `init`)?

**Comment by damithc** [comment]
> `--restore`: restores the folder to the previous state (i.e., reverses the `init` command)

If we assume most users will be using git, we might not even need a restore option.

**Comment by lhw-1** [comment]
There are four possible improvements brought up in this issue: `--minimal`, `--convert`, `--restore`, and the updates to the starter site.

As of March 2023:

- We have the option to start with a minimal site using `markbind init --template minimal`, and if really necessary, we _can_ explore a shorthand syntax of `markbind --minimal`, though I doubt that this will be highly useful (and if really needed, it's a trivial fix).
- We have the `--convert` option available for GitHub wikis or `docs` folders, and other issues such as #1866 and #581 cover different aspects of the `--convert` option mentioned here.
- As stated above, `--restore` may not be necessary if we assume that users are using git.
- Updates to the starter site (i.e. the `default` template) is being worked on in PR #2225.

As such, if there are no objections, I think that it should be safe to close this issue with #2225.
