### ISSUE TITLE
Support inline includes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#52]
Assume `abc.md`:
```
abc
```
When including as follows,
`<include src="abc.md" />def`

expected: `abcdef`
actual:
```
abc
def
```

This is especially useful when including popovers from another file.

```html
<include src="../../common/PopOvers.md#xp" /> uses User stories to capture requirements.
```

**Comment by Gisonrg** [comment]
<include> has an attribute `inline` that could achieve this and you may want to give it a try
```
<include src="abc.md" inline />def
```

But make sure the abc.md has no extra newline.

**Comment by damithc** [comment]
Works. Nice 👍
