### ISSUE TITLE
Apply a default layout for the MarkBind website

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#527]
Suggestion: use a default layout for the MarkBind website

**Comment by damithc** [comment]
@Chng-Zhi-Xuan I tried to do this while doing #518 but couldn't get the SiteNav to render properly.

**Comment by Chng-Zhi-Xuan** [comment]
Investigating ...

**Comment by damithc** [comment]
Raising priority as this seems to be a problem in the layouts feature.
