### ISSUE TITLE
site.json: define precedence if the same file is covered in multiple entries

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#529]
Suggestion: define how settings are applied if the same file is covered by multiple `pages` entries in site.json. e.g., `"src": "index.md"` and `"glob": "*.md"`

Are the setting applied top-to-bottom in the order of appearence?

**Comment by jamos-tay** [comment]
Currently it works like this:

Pages (with `src`) have top priority regardless of order
If two or more globs match, the earlier one gets priority

We could add a note in the documentation

**Comment by damithc** [comment]
Thanks for checking @jamos-tay 

> Pages (with `src`) have top priority regardless of order
> If two or more globs match, the earlier one gets priority

Isn't it more intuitive if the later one takes priority instead?

> We could add a note in the documentation

Yes, we should.

**Comment by jamos-tay** [comment]
Sure, that makes sense too.

On a separate note though is there a use case for merging properties on multiple matches? For example:

```
  "pages": [
    {
      "glob": "**/*.md",
      "layout": "my-layout"
    },
    {
      "src": "index.md",
      "title": "My title"
    }
  ]
```

Currently `src` overwrites completely, so layout is blank for `index.md`. But the user may be expecting
```
    {
      "src": "index.md",
      "title": "My title",
      "layout": "my-layout"
    }
```
