### ISSUE TITLE
User docs: fix right-aligned search bar example

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#530]
In the user guide, the two examples of the search bar look the same. The second one should be right-aligned?
![image](https://user-images.githubusercontent.com/1673303/50693028-c17bac00-1070-11e9-878c-242df1c552de.png)

On a related note, this link needs fixing too.

![image](https://user-images.githubusercontent.com/1673303/50693329-934a9c00-1071-11e9-9fc0-7319cba511d7.png)

**Comment by Xenonym** [comment]
The right alignment refers to the alignment of the **dropdown**, _not_ the text in the search bar. In the regular search bar, the results dropdown is aligned to the left:

![search_left](https://user-images.githubusercontent.com/1782590/50724999-d3715380-1131-11e9-83d3-a95ccaf2c519.PNG)

The right-aligned variant aligns the dropdown to the right instead:
![search_right](https://user-images.githubusercontent.com/1782590/50725006-e2f09c80-1131-11e9-80d1-32ff2da4bb83.PNG)
