### ISSUE TITLE
markbind deploy: build before deploying

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#534]
Current: `markbind deploy` does not build but deploy only.

In most cases users would want to deploy the latest version of the site. Should it build by default with possibly a `--no-build` option?

**Comment by damithc** [comment]
> Commands should usually do only a single thing though. It can have additional features to ease typing, but those features are usually _off_ by default, not on by default.

That's a good point. I'm Ok with a `-b | --build` flag.

BTW, isn't git `pull` command an exception to that principle?

**Comment by damithc** [comment]
> We could also create a brand new command that is composed, just like git's `pull`. Maybe something like `markbind publish`, which calls `markbind build && markbind deploy`? Not sure whether `publish` is a good name though.

Sounds good. Alternatively, we can rename `deploy` to `push` or `upload` and use `deploy` for the new command.

**Comment by lhw-1** [comment]
While this issue has been dormant for years, I think this is definitely still worth implementing as it allows for `build` before `deploy`. 

With regards to having commands only do a single thing, while in principle this is true, our `markbind serve` command will build and then serve, so this principle is not exactly being followed. Of course, for the `serve` command this is more of a necessity, but I think that as per the original suggestion, having the `deploy` command build by default and having a `--no-build` option could still be on the table if we are already not following this idea strictly.

@damithc What do you think? Personally, at the moment this makes more sense than coming up with a new command altogether that simply combines the two commands. Of course, if you think that coming up with a new command is still better, then I think `push` could be a good name for it as you suggested (`publish` might be too similar to `deploy`).

**Comment by damithc** [comment]
> @damithc What do you think? Personally, at the moment this makes more sense than coming up with a new command altogether that simply combines the two commands. Of course, if you think that coming up with a new command is still better, then I think `push` could be a good name for it as you suggested (`publish` might be too similar to `deploy`).

@lhw-1 I'm OK with `deploy` command building by default while providing a `--no-build` option. A few times I ended up deploying without building properly which resulted in a partial website being deployed.

Other views are welcome too.
