### ISSUE TITLE
Including remote files: is the feature working?

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#537]
Current:
>**You can also `<include>` contents of a remote file**, as long as the remote file is <trigger trigger="click" for="modal:reusingContents-CORS">CORS</trigger> accessible.
>
>>**Cross-Origin Resource Sharing (CORS)** is a mechanism that uses additional HTTP headers to tell a browser to let a web application running at one origin (domain) have permission to access selected resources from a server at a different origin. <small>--[source: Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)</small>
>
>
>```html
>  <include src="https://raw.githubusercontent.com/MarkBind/markbind/master/README.md" />
>  ```

I omitted this from the recent userdocs update because I wasn't sure if this feature is working

**Comment by yamgent** [comment]
Went back as far as v1.7.4 to test it, doesn't seem to have been working at all the whole time.

Including external content is an interesting feature (so long as the external content is formatted according to what we want). However, it depends on whether the author has internet connection when doing a `markbind build`. Also it is usually not obvious when the changes in the external content breaks our website unless we inspect these content manually (provided that we know the changes even happened in the first place).

**Comment by damithc** [comment]
At the moment I can't think of a strong use case for this feature. Serious reusing of content across sites can be done using git submodules. Ditch the feature?

**Comment by yamgent** [comment]
Sure.
