### ISSUE TITLE
<box> icon: document support for font icons

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#538]
Current: `<box>` allows specifying an emoji as the icon
![image](https://user-images.githubusercontent.com/1673303/50719940-08a08600-10df-11e9-8664-488343db8a66.png)

Suggested: allow font icons i.e., fontawesome or glyphicon to be used as the box icon too, possibly allowing custom color for the icon as well.

Perhaps this can be achieved by allowing the icon to be specified using a `slot` element?

**Comment by alyip98** [comment]
I did some testing and found that it's already an implemented feature (one of the markdown-it plugins), though it isn't documented.

![image](https://user-images.githubusercontent.com/2277141/58860825-8c3abf00-86df-11e9-885b-ac1627c5b77d.png)

**Comment by damithc** [comment]
> I did some testing and found that it's already an implemented feature (one of the markdown-it plugins), though it isn't documented.

Nice :+1:. We should document it.

Is it possible to change color of the icon? Maybe we should add `slot` support for `icon` property? That way, thumbnails can be used as icons.
