### ISSUE TITLE
User docs: give example code for modal component

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#540]
v1.15.2

Current: https://markbind-master.netlify.com/userguide/usingcomponents#modal

Suggestion: add sample code for the modal component, similar to other components listed in the page

**Comment by Tejas2805** [comment]
![Screen Shot 2020-04-09 at 12 06 20 AM](https://user-images.githubusercontent.com/35946746/78806988-028e0900-79f6-11ea-9b9a-8df78e29c2da.png)

Looks like this issue is solved!

**Comment by damithc** [comment]
Yes, looks like it.
