### ISSUE TITLE
Allow customizing at the point of inclusion

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#545]
Suggestied feature: the following code will include `foo.md` as per normal but will replace all spans/divs with id `title` in `foo.md` with `New Title` and `level` with `2`:
```html
<include src=”foo.md”>
  <span id=”title”>New Title</span>
  <span id=”level”>2</span>
</include>
```
`foo.md`:
```html
## <span id="title">Dummy Title</span>

This is a level <span id="level"/> topic.

The level of this topic is <span id="level"/>.
```
Rationale: this will greatly increase code reuse as it allows authors to write templates  and reuse them while customizing them at the point of reuse (somewhat similar to Jekyll tempates https://jekyllrb.com/docs/layouts/).

Points to consider: What about variations that cannot be captured in spans e.g., html attribute values? For example, if we want to use the following code fragment as a template but we want the background color to be confirguragle at the point of reuse

```html
   <box background-color="white" border-color="#cccccc"><md><span id="content"/></md></box>
```

**Comment by jamos-tay** [comment]
Hmm, this looks pretty similar to markbind variable functionality (`_markbind/variables.md`). What if we allowed the user to specify markbind variables that are only used in that include's context, so like:

```
<include src=”foo.md”>
  <span id="title"><span>New Title</span></span> // same syntax as variables.md
  <span id="background-color">white</span>
  <span id="border-color">#cccccc</span>
</include>
```

foo.md
```
## {{ title }}

<box background-color="{{ background-color }}" border-color="{{ border-color }}"><md><span id="content"/></md></box>
```

Naturally `include`-specific variables take precedence over `variables.md`.

One issue is if we want default values for variables. Can we extend the variable functionality to allow for these, {{ background-color | default #ffffff }} or something ?

**Comment by damithc** [comment]
@jamos-tay note that we use nunjucks for implementing variables and I suspect nunjucks does a pass through the code first before markbind gets a chance to process includes, which means all `{{ ... }}` will be wiped out as nunjucks replaces unknown variables with empty string. If we go want to use variables, we might have to come up with our own syntax e.g., `{< ... >}`. I'm just guessing though.

**Comment by jamos-tay** [comment]
Hmm, I was thinking we could just inject variables, I guess I'll look into it and if necessary we can use our own syntax
