### ISSUE TITLE
siteNav example in documentation is styled incorrectly

### ISSUE THREAD

**Issue by Xenonym** [MarkBind/markbind#559]
**Tell us about your environment**

* **MarkBind Version:** 1.16.0

**What did you do? Please include the actual source code causing the issue.**
In our [documentation for siteNav](https://markbind.github.io/markbind/userGuide/tweakingThePageStructure.html#site-navigation-menus), the main level links are incorrectly highlighted:

<img src='https://user-images.githubusercontent.com/1782590/50773712-7d84e300-12cc-11e9-99be-62d604de17ef.png' height=200 alt='Incorrectly highlighted siteNav example' />

**What did you expect to happen?**
The correct example should not have any links highlighted:

<img src='https://user-images.githubusercontent.com/1782590/50773882-0439c000-12cd-11e9-83e6-3549933054ef.png' height=200 alt='Corrected siteNav example' />

The reason is because we style links in the siteNav to be `black` using the `id` (`#site-nav a:link`) in `site-nav.css`, but the example in the documentation is not in an element with `id='site-nav'`. Thus, it takes on the default colour for links (`a`) specified in `bootstrap.min.css` which is `#007bff`.

**Comment by damithc** [comment]
On top of that, indentation of this code example seems to be off too.

![image](https://user-images.githubusercontent.com/1673303/50774200-cd17de80-12cd-11e9-894d-ad0c3058fa8d.png)

**Comment by Xenonym** [comment]
The reason is because we style links in the siteNav to be `black` using the `id` (`#site-nav a:link`) in `site-nav.css`, but the example in the documentation is not in an element with `id='siteNav'`. Thus, it takes on the default colour for links (`a`) specified in `bootstrap.min.css` which is `#007bff`.

**Comment by Chng-Zhi-Xuan** [comment]
> On top of that, indentation of this code example seems to be off too.

Seems like `&nbsp;` is being removed by the Markdown parser.

**Comment by Chng-Zhi-Xuan** [comment]
**Update:**

Work around for the docs such that `&nbsp;` is preserved:

```html
`* [:house: Home](`{{showBaseUrl}}`/index.html)`<br>
`* Docs`<br>
<code>&nbsp;&nbsp;</code>`* [User Guide](`{{showBaseUrl}}`/ug.html)`<br>
<code>&nbsp;&nbsp;</code>`* [Dev Guide](`{{showBaseUrl}}`/dg.html)`<br>
`* [Search](`{{showBaseUrl}}`/search.html)`<br>
<code>&nbsp;&nbsp;</code>`* [Google Search](https://www.google.com/)`<br>
<code>&nbsp;&nbsp;</code>`* [YouTube Search](https://www.youtube.com/)`<br>
`* [Contact](`{{showBaseUrl}}`/contact.html)`
```

By wrapping the `&nbsp;` in an explicit `<code>` tag, it will render a white space in HTML.

Rendered | 
--- |
![site-nav-markup](https://user-images.githubusercontent.com/31084833/50824359-59c7a880-1371-11e9-83b3-472b2e4cb6b6.PNG) | 

As for the preview render, we can just add a class (`.site-nav-style`?) in `docs.CSS` that is a copy of the original `#site-nav` style.

**Comment by yamgent** [comment]
> As for the rendered preview `site-nav` snippet, we can just add a class (`.site-nav-style`?) in `docs.CSS` that is a copy of the original `#site-nav` style.

I presume you meant `docs/css/main.css`. I think it is fine to duplicate the style, but any future modification to the style will not be reflected and we will have to update the documentation again. Possible to change it to a class rather than an id?

**Comment by acjh** [comment]
# The cause

> Seems like `&nbsp;` is being removed by the Markdown parser.

It is converted to a regular whitespace character, which isn't rendered by the browser, by `md.render(data.toString())` in `Parser.prototype.renderFile`:
```
<code>* Docs</code><br>
   <code>* [User Guide](</code>
<code>{<span></span>{ baseUrl }}</code>
<code>/ug.html)</code><br>
```

In addition, it is blended into the spaces by `htmlBeautify(result, { indent_size: 2 })` in `Page.prototype.generate`:
```
                <code>* Docs</code><br>
                <code>* [User Guide](</code>
                <code>{<span></span>{ baseUrl }}</code>
                <code>/ug.html)</code><br>
```

# The solution
<blockquote>

Work around for the docs such that `&nbsp;` is preserved:

```html
`* [:house: Home](`{{showBaseUrl}}`/index.html)`<br>
`* Docs`<br>
<code>&nbsp;&nbsp;</code>`* [User Guide](`{{showBaseUrl}}`/ug.html)`<br>
<code>&nbsp;&nbsp;</code>`* [Dev Guide](`{{showBaseUrl}}`/dg.html)`<br>
`* [Search](`{{showBaseUrl}}`/search.html)`<br>
<code>&nbsp;&nbsp;</code>`* [Google Search](https://www.google.com/)`<br>
<code>&nbsp;&nbsp;</code>`* [YouTube Search](https://www.youtube.com/)`<br>
`* [Contact](`{{showBaseUrl}}`/contact.html)`
```
</blockquote>

Suggested solution:
```html
<code>
* [:house: Home]({{ showBaseUrl2 }}/index.html)<br>
* Docs<br>
&nbsp;&nbsp;* [User Guide]({{ showBaseUrl2 }}/ug.html)<br>
&nbsp;&nbsp;* [Dev Guide]({{ showBaseUrl2 }}/dg.html)<br>
* [Search]({{ showBaseUrl2 }}/search.html)<br>
&nbsp;&nbsp;* [Google Search](https://www.google.com/)<br>
&nbsp;&nbsp;* [YouTube Search](https://www.youtube.com/)<br>
* [Contact]({{ showBaseUrl2 }}/contact.html)
</code>
```

variables.md:
```html
<span id="showBaseUrl">
<code>{<span></span>{ baseUrl }}</code>
</span>

<span id="showBaseUrl2">{<span></span>{ baseUrl }}</span>
```

Less hacky(?) and a more accurate representation of the file as it doesn't have the unintended space between `(` and `{` from `(</code> <code>{`:

<img width="420" alt="screenshot 2019-01-12 09 28 50" src="https://user-images.githubusercontent.com/14091939/51067409-fda0a500-164c-11e9-9763-7a7b8fc1bba8.png">

**Comment by acjh** [comment]
>> As for the rendered preview `site-nav` snippet, we can just add a class (`.site-nav-style`?) in `docs.CSS` that is a copy of the original `#site-nav` style.
>
> I presume you meant `docs/css/main.css`. I think it is fine to duplicate the style, but any future modification to the style will not be reflected and we will have to update the documentation again.

Agreed.

> Possible to change it to a class rather than an id?

There are some styles related to positioning, which should stay as an id as it positions ***the*** site nav.

The other styles can use a class `.site-nav` — we can consider a more generic class name if it fits.
