### ISSUE TITLE
Prevent glob from building .md files in the _markbind folder

### ISSUE THREAD

**Issue by jamos-tay** [MarkBind/markbind#563]
Using general glob patterns like  `**/*.md` can cause `.md` files in the `_markbind` folder such as `footer.md`, `head.md` to be selected as pages for building.

```
  "pages": [
    {
      "glob": "**/*.md"
    },
  ]
```

Should we add an exclusion for the `_markbind` folder?

**Comment by damithc** [comment]
On a related note, I was hoping we can use the `include` feature for files within `_markbind` folder as it can help reduce duplication among system files.

**Comment by Xenonym** [comment]
@jamos-tay this issue was alluded to in #525 and will probably be fixed when that PR is complete? 

FYI: @amad-person

**Comment by jamos-tay** [comment]
@Xenonym Sure, looks good

I'll close this issue after the merge then
