### ISSUE TITLE
Support "super seamless" panels

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#564]
Current: Seamless panels give a sense of 'nested' content

Suggested: Also give a "super-seamless" (or some other suitable name) type where the content merges with the existing content more seamlessly when expanded. For inspiration, here are some examples from elsewher:
* Gmail threads showing collapsed content.
  ![image](https://user-images.githubusercontent.com/1673303/50874775-4a437080-1400-11e9-873b-b92acefaa2d3.png)
* GitHub showing hidden comments/code:
  ![image](https://user-images.githubusercontent.com/1673303/50875030-78758000-1401-11e9-9372-afbf909ba161.png)
  ![image](https://user-images.githubusercontent.com/1673303/50875067-a22ea700-1401-11e9-837e-ec64cb3e7822.png)

Justification:
* It is a way to visually convey that the content in concern is not nested but merely 'optional'. 
* The feature is relevant to conent-heavy websites, which is our target market
* It is not a commonly component found (e.g., among Bootstrap components) which means it can help MarkBind stand out among competing tools

**Comment by ang-zeyu** [comment]
Hi, something like this?

No header, padding, border, margin, etc.
Also non-collapsable once expanded ( could make it so, but I feel this goes more with the idea of 'nested content' )

![superSeamlessPanel](https://user-images.githubusercontent.com/3306138/70846327-43846f80-1e93-11ea-9f81-a1a71984fd84.gif)

**Comment by damithc** [comment]
> * Should the panel be non-collapsable once expanded? ( I feel this goes more with the idea of 'nested content' )

Not a must, but good to have. A user might want to collapse the content again to exclude it from the print (in case of user tweaking content before printing or saving as pdf)


> * Should a minimal header still be allowed? (e.g. "see more", "more on xxx" )

Yes, good to have.
