### ISSUE TITLE
Remove stray keyword in user guide's search index

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#567]
Current: 
![image](https://user-images.githubusercontent.com/1673303/50880356-204a7800-1419-11e9-9b42-0b24a83deeb3.png)

Problem: there should not be a search result for `regressions`

This is likely a mishap in the code that explains the search keyword feature.

![image](https://user-images.githubusercontent.com/1673303/50880450-60a9f600-1419-11e9-81c8-0a695c546b75.png)

**Comment by acjh** [comment]
This isn't a bug, since it's intentional to render the example as-is.

Perhaps a more appropriate example such that it fits the section?

**Comment by damithc** [comment]
> This isn't a bug, since it's intentional to render the example as-is.

Yes, but perhaps OK to tweak the code to make it _look_ exactly like how it would look when rendered but not _behave_ the same way? In fact, I think I did that for the heading `Developer Testing` which looks like a heading but not behave like one (that's why it doesn't turn up in search results) but forgot to do the same for the keyword.

Current code:
```html
<box>

<big>**Developer Testing**</big><br>

This is good for catching <span class="keyword">regressions</span>.
</box>
</div>
```

> Perhaps a more appropriate example such that it fits the section?

Can't think of an example that will give the correct search behavior, as in, a user will not be surpised to reach this location by searching for that keyword neither will she be surpised to see it in search results. Any ideas?

**Comment by acjh** [comment]
> perhaps OK to tweak the code to make it *look* exactly like how it would look when rendered but not *behave* the same way?

I don't think it's good to do that. I'd expect an example to work properly and that header to be `<h4>`.

Alternatively, we can use a screenshot.

> Can't think of an example that will give the correct search behavior, as in, a user will not be surpised to reach this location by searching for that keyword neither will she be surpised to see it in search results. Any ideas?

We could use `<span class="keyword">keywords</span>`.

**Comment by damithc** [comment]
> I don't think it's good to do that. I'd expect an example to work properly and that header to be `<h4>`.

I agree.

> We could use `<span class="keyword">keywords</span>`.

It feels a bit 'too clever'. Going meta like that can make it slightly harder for the reader to understand. 

> Alternatively, we can use a screenshot.

Yes, that works, as this is a static example. But the look and feel will be slightly different based on the OS, right?

**Comment by damithc** [comment]
> The idea of the example working properly, while not having it in the search index sounds like a contradiction to me. :P

You have a point. My initial intention of the example was to illustrate how the code will _render_ (more specifically, the fact that it will not affect the rendering), not how it will affect the search index; but users might be expecting an illustration of both aspects: look and behavior. Maybe it is OK for this example keyword to appear in the search results? In that case it is better for the keyword (and the heading) used to be totally unrealted to the regular content of the website such that the user will not be confused/mislead by it.

**Comment by yamgent** [comment]
> Maybe it is OK for this example keyword to appear in the search results? In that case it is better for the keyword (and the heading) used to be totally unrealted to the regular content of the website such that the user will not be confused/mislead by it.

Ok I agree. I think "regression" shouldn't be considered as a regular content in that sense then.

I guess the only thing left to do is to include the missing keywords `regress` and `regression testing` (shown in the current example) for the search results.
