### ISSUE TITLE
Essay questions: make the instructions less prominent

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#57]
This instructions (inserted by mardbind) takes too much attention. May be make it a 'hint' inside the box itself?
![image](https://cloud.githubusercontent.com/assets/1673303/25606740/a84a6c48-2f45-11e7-8e18-f7d37d3ff454.png)

Alternatively, we can provide a separate control for text boxes which gives users more control over where to put them, size, etc. For example, user can put two text boxes in the same questions if he want.

**Comment by Gisonrg** [comment]
Fixed in 1.3.0: made it a placeholder of the textarea.

**Comment by damithc** [comment]
> Fixed in 1.3.0: made it a placeholder of the textarea.

:+1:
