### ISSUE TITLE
Allow declaration of variable values in the same source file

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#575]
From https://github.com/MarkBind/markbind/pull/553#issuecomment-451707842.

~~`index.md`:~~

~~\<span id="color">red\</span>~~
~~\<font color="{{ color }}">my text\</font>~~

~~However, a better syntax is needed, because outside of `variables.md`, `<span>`s are not always variables.~~

---

EDIT:

Per further discussions below, support such a syntax:

`index.md`:
```html
<variable id="color">red</variable>

<font color="{{ color }}">my text</font>
```

**Comment by damithc** [comment]
> However, a better syntax is needed, because outside of `variables.md`, `<span>`s are not always variables.

One option is to consider all spans/divs as local variables. Will it affect performance?

**Comment by yamgent** [comment]
> One option is to consider all spans/divs as local variables. Will it affect performance?

`<div>` and `<span>` are used quite frequently (a quick search in the MarkBind's documentation reveals around 20-40 hits per page. Extreme case can be found in `usingComponents.md`; 1458 spans and 60 divs).

Also `<span>` "variables" will get rendered on the page unless we use a `d-none` class.

```html
<span id="color" class="d-none">red</span>
```

The use of `d-none` deviates from way that we declare variables in `variables.md` (which we never use as a page), and the variables inside `<include>` (which are processed so they never get rendered).

**Comment by damithc** [comment]
I'm quite happy to have a separate syntax for variables. Any suggestions?

`<span id="color" var>red</span>`?
`<var name="color">red</var>`?

**Comment by yamgent** [comment]
> `<var name="color">red</var>`?

[`<var>` is a legal HTML5 tag for tagging mathematical variables](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/var).

How about `<value>`?

`<value name="color">red</value>`

**Comment by damithc** [comment]
`value` is a bit misleading though as `red` is the _value_. `property`? 

BTW, do we allow overriding these via the `include`?

**Comment by acjh** [comment]
How about `<variable>`? We intend to strip these out, not just hide them with CSS right?

**Comment by jamos-tay** [comment]
Just a random suggestion, how about specifying variables in the front matter?

**Comment by damithc** [comment]
> Just a random suggestion, how about specifying variables in the front matter?

That may be a bit too restrictive, given that the value of a variable may span multiple lines?

**Comment by jamos-tay** [comment]
Sure, that makes sense
