### ISSUE TITLE
Add a JavaScript event 'onVueInitialized'

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#577]
**Tell us about your environment**

* **MarkBind Version:** 1.16.0

Currently, authors can specify their own custom JavaScript logic (through layout systems such as by modifying `markbind\layouts\default\scripts.js`).

The custom JavaScript logic is parsed and executed immediately while the page is loading. However, during page loading, Vue has not been initialized yet, because the `then()` part in `setup.js` (which initializes Vue) is not executed immediately:

https://github.com/MarkBind/markbind/blob/6851661534d28e7db516d8641fc7d8e2cb9901ee/asset/js/setup.js#L103-L105

After Vue is initialized, Vue will modify the HTML code of the website in order to render its components. However, in that process, it may also override changes made by the custom JavaScript logic.

---

Here is an example. Suppose we have these content on an empty MarkBind website:

`index.md`:
```html
<frontmatter>
  title: "Hello World"
</frontmatter>

<span id="something">Click here</span>
```

`_markbind/layouts/default/scripts.js`:
```javascript
document.getElementById("something").addEventListener("click",  function () {
    alert("You have just clicked the span!");
});
```

**Expected:** When clicking "Click here", a dialog box should pop up with the message "You have just clicked the span!".

**Actual:** Nothing pops up. When inspecting the HTML on Chrome, one would realise that the event listener has disappeared. This is because Vue removes these event listeners during initialization.

---

**Suggestion:** Support a way to listen to Vue initialization, so that additional logic can be executed after the initialization.

A possible way to do so will be to support a `onVueInitialized` event. Pseudocode below:

```javascript
onVueInitialized(function() {
    // put the things that you want to execute after Vue is initialized
});
```

So for our example, it could have been something like this:

```javascript
onVueInitialized(function() {
    document.getElementById("something").addEventListener("click",  function () {
        alert("You have just clicked the span!");
    });
});
```

**Comment by acjh** [comment]
For reference, explained in https://github.com/vuejs/vue/issues/3587:

> Vue works under the assumption that you do not manipulate dom yourself.
>
> Vue 2 retrieves and removes in-dom templates, compiles them to render functions, and render virtual dom back into real dom,
> while Vue 1 doesn't remove in-dom templates.

**Comment by Xenonym** [comment]
Is it important for the user to know that their function will be executed _specificially after_ Vue initalises, or is it a specific case of 'execute this code after setup is complete? I am thinking that `onSetup` or `afterSetup` might be a better name for this event.

**Comment by yamgent** [comment]
Currently the Vue initialization is done before `setup.js` finishes its setup logic execution. But I think it is fine to call it `afterSetup`; the user need not know the fine details.
