### ISSUE TITLE
Layouts folder missing in docs causing error

### ISSUE THREAD

**Issue by jamos-tay** [MarkBind/markbind#579]
Follow up from slack:

> I'm getting this on the [MarkBind website](https://markbind.github.io/markbind/):
> ```[Error] Failed to load resource: the server responded with a status of 404 () https://markbind.github.io/markbind/markbind/layouts/default/styles.css
> [Error] Failed to load resource: the server responded with a status of 404 () https://markbind.github.io/markbind/markbind/layouts/default/scripts.js
> [Error] Failed to load resource: the server responded with a status of 404 () https://markbind.github.io/markbind/markbind/css/bootstrap.min.css.map```
> The first two errors seem related to [Add page layouts functionality #439](https://github.com/MarkBind/markbind/pull/439).
> The third error is unrelated but I recall seeing it before; MarkBind should include the `.map` file.

This is because the docs site is missing the `layouts` folder that is usually added on `markbind init`.

**Comment by acjh** [comment]
Why was this closed?
