### ISSUE TITLE
Remove trailing spaces from popover bound text

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#58]
Using inline popover tags seem to add an extra trailing space.
![image](https://cloud.githubusercontent.com/assets/1673303/25616332/9040a1d4-2f6e-11e7-9c50-af9cf1bb9a00.png)

`<popover content="i.e. which features to include in the product">scoping</popover>,`

**Comment by Gisonrg** [comment]
Fixed in 1.3.0
