### ISSUE TITLE
Add '_site' to the ignored folders in site.json

### ISSUE THREAD

**Issue by jamos-tay** [MarkBind/markbind#587]
Extension of #563 

Similar to `_markbind`, `.md` files in `_site` should also be ignored when compiling markbind files into html pages.

We can simply extend the behavior of #525 to include `_markbind` and `_site` instead of just `_markbind`.

**Comment by Tejas2805** [comment]
Hi, I would like to up this issue.

**Comment by yamgent** [comment]
> Hi, I would like to up this issue.

Sure.
