### ISSUE TITLE
Reduce replication of constants

### ISSUE THREAD

**Issue by marvinchin** [MarkBind/markbind#597]
**Tell us about your environment**

* **MarkBind Version:**
MarkBind v1.16.1

**What did you expect to happen?**
Constants can be defined in a single file and reused where needed

**What actually happened? Please include the actual, raw output.**
Some constants are reused across `Site.js`, `Page.js`, and `cliUtil.js` (e.g. `LAYOUT_FOLDER_PATH`)

**Comment by nicholaschuayunzhi** [comment]
For different sub logic it has been suggested in https://github.com/MarkBind/markbind/pull/698#discussion_r270254377 to have file naming structure of `{{main module}}.{{sub module}}.js`

Additionally it is suggested that constants should be placed in `constants.js` https://github.com/MarkBind/markbind/pull/698#discussion_r270965603
