### ISSUE TITLE
Add code comments to major source files

### ISSUE THREAD

**Issue by jamos-tay** [MarkBind/markbind#602]
Most of the source code is very sparse in comments, with many complex functions left undocumented. This makes it difficult for developers who are new to the project to understand it.

In particular, the `Page.js`, `Site.js`, `parser.js` files which encapsulate a lot of MarkBind's functionality could be reviewed and comments added.

Currently we don't require PRs to include comments. It might be helpful to encourage using simple comments during reviews.

**Comment by ang-zeyu** [comment]
quite a few now; closing as its a continuing work :-)
