### ISSUE TITLE
Render blocked on loading siteData.json

### ISSUE THREAD

**Issue by marvinchin** [MarkBind/markbind#608]
**Tell us about your environment**

* **MarkBind Version:** 1.16.1

**What did you do? Please include the actual source code causing the issue.**

Open any MarkBind generated site with search enabled.

**What did you expect to happen?**

Page should render before fetching `siteData.json`.

**What actually happened? Please include the actual, raw output.**

`siteData.json` is fetched before the page is fully rendered, and the render blocks until `siteData.json` is fetched.

**Comment by nicholaschuayunzhi** [comment]
Should this be `siteData.json` instead?
