### ISSUE TITLE
Omit pageNav from print view

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#615]
v1.17.0

Is it possible to omit the pageNav from the print view by default? It is unlikely users will want to print the pageNav.

**Comment by damithc** [comment]
Yes, that works when we have set up a specific print view page. Can we also omit it in the case where the user simply tries to print a normal page that includes a site/page Nav? For example, the topNav seems to have that behavior. Can we extend that to siteNav and pageNav too?

**Comment by Chng-Zhi-Xuan** [comment]
I see, then we just have to trivially add the CSS classes as shown in here:

[How to hide a HTML element when printing](https://stackoverflow.com/questions/355313/how-do-i-hide-an-element-when-printing-a-web-page)

**Comment by damithc** [comment]
> I see, then we just have to trivially add the CSS classes as shown in here:
> 
> [How to hide a HTML element when printing](https://stackoverflow.com/questions/355313/how-do-i-hide-an-element-when-printing-a-web-page)

Can we do that by default so that users don't need to do anything?

**Comment by Chng-Zhi-Xuan** [comment]
> Can we do that by default so that users don't need to do anything?

Yes, that was what I was suggesting. We just have to add the necessary CSS items to `page-nav.css` and `site-nav.css`.

Do you want a specific way for users to enable printing either `site-nav` or `page-nav` if they want to? Although I can't find a good use case for it.

**Comment by damithc** [comment]
> Do you want a specific way for users to enable printing either `site-nav` or `page-nav` if they want to? Although I can't find a good use case for it.

Yes, I can't think of a good use case either. I guess no need.
