### ISSUE TITLE
Stick pageNav to content edge

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#617]
v1.17.0

Current: PageNav sticks to the right edge of the Browser window

Suggested: Stick it to the right edge of the contents?

![image](https://user-images.githubusercontent.com/1673303/51512605-bd59d780-1e41-11e9-9c90-6d863fe713a3.png)

**Comment by Chng-Zhi-Xuan** [comment]
I feel this should be done by the author through their self implemented CSS classes. 

It would be extremely weird if the `page-nav` took half the page. It is much better if the author centered the body contents to bring it closer to the `page-nav`.

**Comment by damithc** [comment]
> It would be extremely weird if the `page-nav` took half the page. It is much better if the author centered the body contents to bring it closer to the `page-nav`.

The screenshot is from a page that has centered content but viewed using a widescreen monitor.

**Comment by damithc** [comment]
I had to take it down due to some other reason. Here's a full screenshot.

![image](https://user-images.githubusercontent.com/1673303/51513634-d2853500-1e46-11e9-8f89-ba7de42eea4d.png)

**Comment by damithc** [comment]
>This is the expected behaviour. Because the content was assigned a fixed width, bigger margins was generated to compensate.

In that case I guess we can leave things as they are.

> This screenshot seems to have been taken from a high resolution monitor ( >1080p) or is zoomed out, so the gap is more pronounced than usual.

Yes, it was zoomed out because I was trying to see the pageNav in my other monitor which was in portrait orientation.
