### ISSUE TITLE
JS error on default MarkBind site: Cannot read property 'scrollIntoView' of null

### ISSUE THREAD

**Issue by Xenonym** [MarkBind/markbind#619]
**Tell us about your environment**

* **MarkBind Version:** 1.17.0

**What did you do? Please include the actual source code causing the issue.**
1. Create a new MarkBind site with `markbind init`.
2. Preview the site with `markbind serve`.

**What did you expect to happen?**
The site should preview normally with no errors.

**What actually happened? Please include the actual, raw output.**
An uncaught `TypeError` is logged by the JS console in Chrome:
```
setup.js:67 Uncaught TypeError: Cannot read property 'scrollIntoView' of null
    at jQuery.on (setup.js:67)
    at dispatch (vue-strap.min.js:39)
    at m.handle (vue-strap.min.js:39)
    at Object.trigger (vue-strap.min.js:39)
    at vue-strap.min.js:39
    at Function.each (vue-strap.min.js:28)
    at k.fn.init.each (vue-strap.min.js:28)
    at k.fn.init.trigger (vue-strap.min.js:39)
    at n.t._activate (bootstrap-utility.min.js:6)
    at n.t._process (bootstrap-utility.min.js:6)
```
`setup.js:67` is part of `setupPageNav`:
```js
65	function setupPageNav() {
66	jQuery(window).on('activate.bs.scrollspy', (event, obj) => {
67	    document.querySelectorAll(`a[href='${obj.relatedTarget}']`).item(0).scrollIntoView(false);
68	  }); 
69	}
```

I guess this has something to do with the page nav implementation.

**Comment by Chng-Zhi-Xuan** [comment]
This is because within `page.ejs`, the scrollspy is added to the `<body>` of the page even if that page does not have a valid page navigation specifier. 

Will need to add some checking logic before insertion into `<body>`.
