### ISSUE TITLE
usingComponents.md: Warn user not to set enableSearch to false if using searchbar

### ISSUE THREAD

**Issue by marvinchin** [MarkBind/markbind#620]
**Tell us about your environment**

* **MarkBind Version:** v1.17.0

**What did you do? Please include the actual source code causing the issue.**
Set `enableSearch` to `false` in `site.json`

```json
{
  ....
  "enableSearch": false
}
```

**What did you expect to happen?**
Site should load without search

**What actually happened? Please include the actual, raw output.**
Site does not load
The following error is shown in the Chrome console:
![screenshot 2019-01-23 at 2 05 34 pm](https://user-images.githubusercontent.com/17447681/51586380-ff554d00-1f17-11e9-9cfb-f18b46162572.png)

**Comment by marvinchin** [comment]
Site is able to load after the `searchbar` component is removed from `header.md`. Perhaps we should note in the documentation that if the `searchbar` component is used, then `enableSearch` must be set to true in `site.json`.

**Comment by yamgent** [comment]
> Perhaps we should note in the documentation that if the `searchbar` component is used, then `enableSearch` must be set to true in `site.json`.

We can put a warning on the searchbar component in the "Using Components" reference page to warn the user not to set `enableSearch` to false.

**Comment by Xenonym** [comment]
@marvinchin do you mean that the site fails to load when there is _both_ a `<searchbar>` component that uses `:data="searchData"` *and* when `"enableSearch": false`? I don't believe there's a restriction that `<searchbar>` can only be used in the header or that it can only use `:data="searchData"`.

Second error is reported in #619.

**Comment by marvinchin** [comment]
@Xenonym yes, that seems to be the source of the error. Thanks for clarifying!

**Comment by Xenonym** [comment]
In that case, it seems the issue is that `<searchbar>` does not react well to being passed an invalid or nonexistent `:data` array. 

You can use `<searchbar>` with `"enableSearch": false`, so long as you do not refer to a nonexistent `searchData`. Is that a valuable use case? I can imagine a user might build a custom `searchData` for a searchbar that is only on a single page (maybe a searchbar for a very long glossary page, for example).

**Comment by marvinchin** [comment]
Yes, I believe that the intention of allowing the user to specify the `:data` attribute would be to allow the user to specify the source of the search data.

I think the problem here might be that the connection between a  `<searchbar>` component with attribute `:data="searchData"`, and setting `"enableSearch": true` in `site.json` was not explicitly mentioned in the user documentation. I'll make the necessary updates to include this!
