### ISSUE TITLE
Use MarkBind for our own dev docs

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#625]
Suggested: use MarkBind for our own user docs as well as dev docs
Reason: it can be an example of how both types of docs can be supported using MarkBind in the same repo

**Comment by nicholaschuayunzhi** [comment]
Perhaps we could use our own dev docs to test our potential automated docs to MarkBind feature?

**Comment by sijie123** [comment]
I am actually working on porting our dev docs to use MarkBind.
In the process I also hope to collate and share some of my experiences to see what workflows we can automate.
I was thinking of doing what @nicholaschuayunzhi suggested (heh, saves me lots of work), but I think we might not be able to get the feature out in time to present a good dev docs for the next major release. Perhaps what I could do is to manually port over first, but retain the existing docs to use as a test for the automated conversion. Then we compare the differences to see what we can improve?
