### ISSUE TITLE
Deploy MarkBind website to markbind.github.io

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#626]
Current: https://markbind.github.io redirects to https://markbind.github.io/markbind/
Suggested: Deploy the released version of the MarkBind website to markbind.github.io instead as it is not nice when the landing page is a redirect.

Note: markbind.github.io only supports serving from the master branch (does not support serving from the gh-pages)

**Comment by acjh** [comment]
Master branch of https://github.com/MarkBind/markbind.github.io though.

We were doing that previously right?
