### ISSUE TITLE
Always use forward slash for file paths when generating the website

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#628]
**Tell us about your environment**

* **MarkBind Version:** 1.17.0

**What did you do? Please include the actual source code causing the issue.**

Repeat the steps on 2 different platforms (Windows vs Mac/Linux):
1. `markbind init`
2. `markbind build`
3. Check the file paths inside the generated `index.html`.

**What did you expect to happen?**

The file paths generated should use a consistent slash (i.e. `/`), regardless of the OS that the author is running.

**What actually happened? Please include the actual, raw output.**

* On Windows, the slash generated is `\`.

```html
<script src="markbind\js\setup.js"></script>
<script src="markbind\layouts\default\scripts.js"></script>
</html>
```

* On Mac & Linux, the slash generated is `/`.

```html
<script src="markbind/js/setup.js"></script>
<script src="markbind/layouts/default/scripts.js"></script>
</html>
```

**Comment by nicholaschuayunzhi** [comment]
I don't think there's an option in `path` library that enforces consistent path separator. Perhaps we may have to write a wrapper over the functions we use to replace `\` with `/`?

This will also make the file compare process easier/less prone to bugs.

**Comment by Xenonym** [comment]
A similar problem was encountered with the implementation of #475 `serve --one-page`, which was solved by adding the function `ensurePosixPath` (d86153c4d3aa8467f81e9f23f9593062628469c0) to replace `\` with `/`. We could use that to resolve this as well.
