### ISSUE TITLE
Support staging multiple PRs

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#63]
When submitting PRs to a markbind project (e.g. demo site), the PR submitter can stage the changes in gh-pages branch so that the reviewer can have a look at the final outcome. However, this doesn't work well when the the submitter has multiple PRs because only one of them can be staged using gh-pages branch at any time.

It's better if we can use something like raw-git to stage any number of branches at the same time.

**Comment by Gisonrg** [comment]
Currently we separate the source code from the final generated website code. So creation of multiple PR should be fine.
To preview changes from one PR, one can always change the deployment setting to deploy to different branches than `gh-pages`. While if we want to see the live version other than the changed source code, I am afraid currently we can only view the live version from the `gh-pages` branch.
Not sure if I understand the question ("stage PR") correctly. Please correct me if I am wrong :)

**Comment by acjh** [comment]
@Gisonrg Prof Damith was referring to [this](https://github.com/nus-cs2103/website/blob/master/doc/DeveloperGuide.md#how-to-stage-changes), which can preview any branch (and even specific commits).

**Comment by Gisonrg** [comment]
@acjh 
Got it. I think RawGit should work in this case if pushed to different branches. But some links may be broken because of the `baseUrl` is changed on RawGit unless tweaked manually when deployed.

**Comment by damithc** [comment]
> But some links may be broken because of the baseUrl is changed on RawGit unless tweaked manually when deployed.

Yes, that's the problem I was hoping to solve in this issue :-) perhaps provide base url (and the branch name to push to) as a command line parameter to `markbind deploy`?

**Comment by Gisonrg** [comment]
Yep. That's what I could foresee as well.

**Comment by acjh** [comment]
`baseUrl`<sup>(case-insensitive?)</sup> is more flexible<sup>(no assumptions)</sup> and more meaningful for the `build` step.

**Comment by acjh** [comment]
Resolved by #186
