### ISSUE TITLE
Layout specified in site.json is not applied when page does not have front matter

### ISSUE THREAD

**Issue by Xenonym** [MarkBind/markbind#630]
**Tell us about your environment**

* **MarkBind Version:** 1.17.0

**What did you do? Please include the actual source code causing the issue.**
I created a MarkBind site with two layouts, `default` and `testLayout`. 

In `_markbind/layouts/default/footer.md`:
```
<footer>
  <div class="text-center">
    Default footer
  </div>
</footer>
```
In `_markbind/layouts/testLayout/footer.md`:
```
<footer>
  <div class="text-center">
    testLayout footer
  </div>
</footer>
```

I then specified that `"layout: "testLayout"` for `index.md` in `site.json`:
```json
{
  "src": "index.md",
  "title": "Hello World",
  "layout": "testLayout"
},
```

In `index.md`:

```markdown
# Hello world
Welcome to your page generated with MarkBind.
```
I then did `markbind serve`.

**What did you expect to happen?**
I expected `testLayout` to apply to `index.md`, displaying `testLayout footer` for the footer.

**What actually happened? Please include the actual, raw output.**
The footer from the `default` layout displayed instead. This also happens when a empty `<frontmatter>` is included.

If I include a `<frontmatter>` with content in `index.md`, then `testLayout` _does_ get applied:
```markdown
<frontmatter>
	title: Hello World
</frontmatter>
# Hello world
Welcome to your page generated with MarkBind.
```

**Comment by ang-zeyu** [comment]
oops. fixed in #1321
