### ISSUE TITLE
Use server side rendering for Vue components

### ISSUE THREAD

**Issue by marvinchin** [MarkBind/markbind#637]
**Tell us about your environment**

* **MarkBind Version:**  v1.17.0

**What did you expect to happen?**
Vue components should be server side rendered

**What actually happened? Please include the actual, raw output.**
Vue components are only rendered on the client side

See discussion on #590.

**Comment by marvinchin** [comment]
Did some preliminary investigation regarding this issue:

### SSR might not be suitable for our use case
- The VueStrap library we are working is not SSR friendly
- Other Vue SSR frameworks handle the issue with non-SSR friendly libraries by loading them only on the client side, but this doesn't work for us because the main thing we want to SSR is VueStrap 😭 

### Consider pre-rendering instead?
- Instead of generating the markup on the server (SSR), we can do pre-rendering using a headless browser to load our page and extracting the loaded DOM
- The existing tools for Vue pre-rendering (https://github.com/eldarc/vue-prerender) are built for Vue SPAs (MarkBind doesn't generate SPAs)
- We may need to write our own tool to do the pre-rendering step, interfacing directly with some headless browser (https://developers.google.com/web/tools/puppeteer/articles/ssr)

### Caveats
- I don't have any experience with pre-rendering, so I'm not familiar with any pitfalls by taking this approach
- MarkBind users have to download the headless browser, which can be pretty big (200+ MB for headless chrome)
- Perhaps we might be able to modify the VueStrap library to make it SSR friendly, but some parts of the code that's causing trouble (e.g. `utils/NodeList.js`) seems to be fairly complex, and I'm not familiar enough with the library to be certain that changing those parts will not cause the SSR to generate incorrect markup.

Any inputs on how we can tackle these problems would be greatly appreciated 🙂

**Comment by yamgent** [comment]
W.r.t to the discussion on Slack, I agree that server-side rendering is not extremely useful right now.

I think this solution is an overkill to our FOUC problem. Making our own TopNav, despite its flaws as mentioned in https://github.com/MarkBind/markbind/pull/664#issuecomment-460131119, seems to come across as the best permanent solution as compared to this.

Also, if the goal is to be less reliant on JavaScript, then changing our website generation to be SPA is an ironic move.
