### ISSUE TITLE
Allow using an empty footer attribute in frontmatter to omit the default footer

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#638]
The following should make the default footer (inherited via the default layout) to be omitted from the page? In general, an empty `x` attribute should indicate `no x`?
```
<frontmatter>
footer:
</frontmatter>
```

**Comment by Chng-Zhi-Xuan** [comment]
Since the desire is to omit certain files within `layout`. We should extend the functionality of that feature instead of extending the footers feature (specifying it in `frontmatter`).

Proposed syntax:

```html
<frontmatter>
layout: default, no-footer, no-css
</frontmatter>
```
The above will omit the layout footer and css files from that page.

**Comment by damithc** [comment]
Should we allow this too? i.e., to mean _use default, but override footer_
```html
<frontmatter>
layout: default
footer: myfooter.md
</frontmatter>
```
If we allow that, we can simply extend it to the following, to mean _use default, but omit footer_.
```html
<frontmatter>
layout: default
footer: 
</frontmatter>
```
In that case, no need for `no-*` syntax at all?

**Comment by Chng-Zhi-Xuan** [comment]
> Should we allow this too? i.e., to mean use default, but override footer

If I am not wrong, this is the current behaviour, where footer specified explicitly will have higher priority and override seamlessly.

> If we allow that, we can simply extend it to the following, to mean use default, but omit footer.

The current logic uses the layout's footer if an empty string / null is specified. So it needs some minor tweaks to the logic for this to work.

Although I'd prefer explicitly stating `no-footer` while specifying the `layout`. Seeing empty page properties in `<frontmatter>` doesn't seem *right* to me.

**Comment by damithc** [comment]
> Although I'd prefer explicitly stating `no-footer` while specifying the `layout`. Seeing empty page properties in `<frontmatter>` doesn't seem _right_ to me.

`footer: none`?

Otherwise we have to deal with this case too.
```html
<frontmatter>
layout: default, no-footer
footer: myfooter.md
</frontmatter>
```

**Comment by Chng-Zhi-Xuan** [comment]
> `footer: none`?
>
>Otherwise we have to deal with this case too.

True, didn't think of that edge case.

This implementation for this is very easy as well 😄
