### ISSUE TITLE
Support underlining text

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#64]
Markdown doesn't have a notation for underlining text but we need to underline some text e.g. use case descriptions require underlining text to show 'inclusions'

**Comment by Gisonrg** [comment]
We already have it supported by `<ins>` tag.

Syntax:
```
++underline text++
```

**Comment by damithc** [comment]
Nice. Do we have some documentation on this sort of thing?

**Comment by Gisonrg** [comment]
I shall create one in the MarkBind wiki
