### ISSUE TITLE
MarkBind Cheat Sheet

### ISSUE THREAD

**Issue by jamos-tay** [MarkBind/markbind#640]
What do you think of creating and maintaining a quick reference for all of Markbind's syntax, such as [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)? Currently most features, such as variables, include, frontmatter, have a wall of text explaining all the small intricacies with examples which is quite hard to scan through. It might be helpful for users if we created a quick reference guide that showcases all of Markbind's syntax with barebones explanation.

For example:

# Include
```html
Including a file
<include src='file.md' />

Including a boilerplate
<include src="file.md" boilerplate />

Including a fragment
<include src='file.md#my-heading' />

Including a file with variables
<include src='file.md'>
  <span id="my-variable">variable</span>
</include>

...
```

**Comment by damithc** [comment]
It's good idea. We should use MarkBind's _powerful reuse mechanisms_ to ensure there is no duplication of content between the cheatsheet and the full version :-)

**Comment by damithc** [comment]
I'm doing this now. Will create a PR soon.

**Comment by damithc** [comment]
A basic version of a cheat sheet has been added, to be improved later.
