### ISSUE TITLE
Variables in includes: allow specifying defaults for a variable

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#641]
Current: When _including_ a fragment, we can specify the values of variables in the fragment.
Suggested: Allow the variables in the fragment to specify a default value for the variable so that overriding can be optional.

e.g.,
`foo.md`:
```
<span id="x">ant</span>
```
The following will produce `bat`.
```html
<include src="foo.md">
  <span id="x">bat</span>
</include>
```
The following will produce `ant`.
```html
<include src="foo.md" />
```

I'm not sure how to specify default values for variables when using this syntax though.
`foo.md`:
```
{{ ant }}
```

**Comment by yamgent** [comment]
For this use case, we would naturally gain the functionality by implementing #575.

**Comment by damithc** [comment]
> For this use case, we would naturally gain the functionality by implementing #575.

Great. @jamos-tay does the current implementation work that way?

**Comment by jamos-tay** [comment]
Yes, it uses the `variable` tag:

foo.md
```
<variable name="x">ant</variable>
{{ x }} // ant
```

other.md
```
<include src="foo.md">
  <span id="x">bat</span> // bat
</include>
```

**Comment by damithc** [comment]
I'll close this as it is being handled by #575
