### ISSUE TITLE
Indicate the language of a code block

### ISSUE THREAD

**Issue by Xenonym** [MarkBind/markbind#646]
**Tell us about your environment**

* **MarkBind Version:** 1.17.1

**Rationale:** Developer documentation sometimes includes code to do one thing in multiple languages (eg. API use in multiple languages). It can be helpful to indicate the language of a code block in the block itself.

**Example:** From [Travis CI documentation](https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci):

![code_language](https://user-images.githubusercontent.com/1782590/51968211-545f0900-24ac-11e9-9204-92984f6e4d77.png)

**Comment by nbriannl** [comment]
Could we open this again since the PR got reverted?

**Comment by yamgent** [comment]
> Could we open this again since the PR got reverted?

Yes, thanks for the reminder, just did.

**Comment by nbriannl** [comment]
I'll take this again, following the momentum of #991, I think I'll be using `markdown-it-attr`. Passing in attribute multiple attributes will make it verbose, but making a html-like component syntax is just as verbose. At best, if you don't use a feature, you don't need to mention it's attribute.
