### ISSUE TITLE
Failed MarkBind commands should exit with nonzero return code

### ISSUE THREAD

**Issue by Xenonym** [MarkBind/markbind#651]
**Tell us about your environment**

* **MarkBind Version:** 1.17.1

**What did you do? Please include the actual source code causing the issue.**
I ran a MarkBind command that failed (exited due to unrecoverable errors). For example, `markbind build` on a directory that does not have a config file.

**What did you expect to happen?**
MarkBind should exit with a nonzero return code (eg. `1`) to indicate an error condition. This is especially important for running MarkBind in an automated context where other programs or scripts are relying on the exit code of MarkBind to detect errors (eg. as part of a custom build script, or [Travis CI automation](https://docs.travis-ci.com/user/job-lifecycle/#breaking-the-build)).

**What actually happened? Please include the actual, raw output.**
MarkBind exits with a zero return code, incorrectly indicating that MarkBind ran successfully.

On PowerShell:
```
PS C:\Users\pzy5a> markbind build
error: No config file found in parent directories of C:\Users\pzy5a
PS C:\Users\pzy5a> $LASTEXITCODE
0
```
On Bash:
```
pzy5a@Xenon-XPS MINGW64 ~ 
$ markbind build
error: No config file found in parent directories of C:\Users\pzy5a

pzy5a@Xenon-XPS MINGW64 ~
$ echo $?
0
```

Related: #601

**Comment by Xenonym** [comment]
In #649, I manually set `process.exitCode = 1` on failure of `deploy --travis`. We could manually do something similar for each command, but I was wondering if there was a more systematic alternative for this?

**Comment by nicholaschuayunzhi** [comment]
We're using `commander` and their [examples](https://github.com/tj/commander.js/) use `process.exit(1);`

**Comment by Xenonym** [comment]
> We're using `commander` and their [examples](https://github.com/tj/commander.js/) use `process.exit(1);`

Using `process.exit()` is [explicitly discouraged by the Node.js documentation though](https://nodejs.org/api/process.html#process_process_exit_code):
> In most situations, it is not actually necessary to call `process.exit()` explicitly. The Node.js process will exit on its own if there is no additional work pending in the event loop. The `process.exitCode` property can be set to tell the process which exit code to use when the process exits gracefully.

My thought is to have all `.catch()` call a common error handler that sets `process.exitCode = 1`.
