### ISSUE TITLE
Anchor generation for PascalCase words unexpected

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#653]
The heading anchor generation seems to generate `MarkBind` → `mark-bind`. Is that expected?

**Comment by Chng-Zhi-Xuan** [comment]
Looking at the [documentation](https://github.com/sindresorhus/slugify#decamelize), we use the default options for `slugify` so yes this is intended behaviour.

`slugify` does not have a option for PascalCase, so it is treated like camelCase.

**Comment by yamgent** [comment]
We can set the decamelize option like what @Chng-Zhi-Xuan mentioned to make it compatible with GFMD:

```js
slugify('MarkBind', {decamelize: false});    // markbind
```

I cannot find a standardized specification on how GitHub generates anchors, so there are probably more edge cases that needs to be ironed out.

**Comment by damithc** [comment]
> `slugify` does not have a option for PascalCase, so it is treated like camelCase.

We can treat both the same way too.

> We can set the decamelize option like what @Chng-Zhi-Xuan mentioned to make it compatible with GFMD:
> 
> ```js
> slugify('MarkBind', {decamelize: false});    // markbind
> ```

Sounds good.
