### ISSUE TITLE
PageNav: give a 'back to top' link

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#654]
Suggestion: in the pageNav, we can give a `back to top` link

We can even give an easy way for users to add a back-to-top link anywhere on a page.

**Comment by damithc** [comment]
> Implementation wise is simple, we just have to add anchor text to the `page-nav` template. Although not sure where should we position the `back to top` anchor and whether or not the position should be static.

Perhaps a better solution to give a way to add a back-to-top to any page, not PageNav? 
1. It can be a small translucent icon that stick to the bottom of the page?
1. We can enable it via frontmatter

**Comment by Chng-Zhi-Xuan** [comment]
Sounds good, but `front-matter` is starting to get cluttered. Since this is a small component, would implementing it via a variable or Vue be better? (Although we need to check there should only be 1 such component on every page).

**Comment by damithc** [comment]
> Sounds good, but `front-matter` is starting to get cluttered. Since this is a small component, would implementing it via a variable or Vue be better? (Although we need to check there should only be 1 such component on every page).

Sure. As it is a page-level decoration, frontmatter seems like the right place though. In fact, that applies to TopNav too. It's more consistent that way. The page body can be more for content and not decorations.

**Comment by tlylt** [comment]
Hello, I think this issue has been resolved in #1338, perhaps it was not closed automatically by that PR as the description did not use the 'fixes xxx' syntax.

**Comment by jonahtanjz** [comment]
Yup this has been resolved. Thanks for checking on this @tlylt 👍
