### ISSUE TITLE
SiteNav: give a way to expand/collapse all items

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#655]
Suggestion: In the SiteNav, give a button/link for the reader to expand/collapse all links.

**Comment by Chng-Zhi-Xuan** [comment]
The button has already been implemented and currently only shows itself when the `site-nav` is hidden once the screen width is small enough. (Responsive design).

There are 2 implementation choices
1. Have the collapse and give more space for the page content.
2. Collapse while keeping page content space the same.

Expanding the page content space with a button can cause text / components to shift. 

So which implementation do you prefer?

**Comment by Chng-Zhi-Xuan** [comment]
@acjh 

Thanks for the clarification, jumped the gun to replying the post 😛.

Then the implementation can be a button with some JavaScript function to change the state of all the dropdown lists.
