### ISSUE TITLE
Make overriding mechanism consistent

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#658]
Apply the outer-overrides-inner policy consistently

- [x] tag overriding
- [ ] frontmatter overriding
- [x] include variables overriding

**Comment by yamgent** [comment]
> [ ] tag overriding

Seems to be done in #652.

> [ ] include variables overriding

The behavior seems to already be outer-overrides-inner since we merged #553.

> [ ] frontmatter overriding

@jamos-tay Was there any progress on this one?

**Comment by yamgent** [comment]
Frontmatter overriding is now implemented in #784.
