### ISSUE TITLE
Provide good examples of MarkBind usage

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#659]
- [ ] Make MarkBind website a showcase of MarkBind strengths
- [x] Use in RepoSense or/and TEAMMATES

**Comment by damithc** [comment]
@Xenonym can you look into how we can convert RepoSense UG and DG into MarkBind? It is a good use case because they are already using Travis and Netlify for other purposes. Requirements:
* UG should only be updated when the product is released. We can use a `reposense.github.io` repo for that, similar to how we publish the MarkBind UG
* There should be a way to preview updates to UG and DG when reviewing a PR

**Comment by marvinchin** [comment]
> Make MarkBind website a showcase of MarkBind strengths

@damithc could I check what you have in mind for this? I have some bandwidth this week and can take a look at this.

**Comment by damithc** [comment]
> @damithc could I check what you have in mind for this? I have some bandwidth this week and can take a look at this.

This front is currently being handled by @sijie123 and @amad-person 

Perhaps you can look at https://github.com/MarkBind/markbind/issues/836 because it is going to affect this front too?

**Comment by marvinchin** [comment]
Sure, I'll take a look!

**Comment by jovyntls** [comment]
>  Make MarkBind website a showcase of MarkBind strengths

@damithc Hi prof, could I check what you're looking for in this? Would it be using more markbind features in our UG?

**Comment by damithc** [comment]
@jovyntls Yes, use where appropriate but without going overboard. Both UG and DG.

**Comment by yucheng11122017** [comment]
Hi is this issue still relevant as both our UG and DG uses and displays Markbind features quite prominently already?

**Comment by damithc** [comment]
> Hi is this issue still relevant as both our UG and DG uses and displays Markbind features quite prominently already?

Sure, we can close this.
