### ISSUE TITLE
Give a decent ‘first contact’ impression

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#662]
- [x] Use a custom domain
- [x] No redirect in landing page

**Comment by amad-person** [comment]
The custom domain we're going to use is `https://markbind.github.io` (mentioned in #626)?.

**Comment by damithc** [comment]
> The custom domain we're going to use is `https://markbind.github.io` (mentioned in #626)?.

No, https://markbind.org

**Comment by amad-person** [comment]
So I have to get this custom domain registered first?

**Comment by damithc** [comment]
> So I have to get this custom domain registered first? Or do we already own this?

I'll take care of the first item after #626 is done.

**Comment by amad-person** [comment]
For #626, I just have to configure the repo and branch settings in `site.json` and do a `markbind deploy`, right? Because I don't have access to the [markbind.github.io](https://github.com/MarkBind/markbind.github.io) repo.

**Comment by damithc** [comment]
> For #626, I just have to configure the repo and branch settings in `site.json` and do a `markbind deploy`, right? Because I don't have access to the [markbind.github.io](https://github.com/MarkBind/markbind.github.io) repo.

I think so. @yamgent what do you think?

**Comment by yamgent** [comment]
> For #626, I just have to configure the repo and branch settings in `site.json` and do a `markbind deploy`, right? Because I don't have access to the [markbind.github.io](https://github.com/MarkBind/markbind.github.io) repo.

Yes that should work.

**Comment by amad-person** [comment]
I'm getting the following error as I don't have access rights to the `markbind.github.io` repository.

```
error: remote: Permission to MarkBind/markbind.github.io.git denied to amad-person.
fatal: unable to access 'https://github.com/MarkBind/markbind.github.io.git/': The requested URL returned error: 403
```

Changes made to `site.json`:
```
"baseUrl": "/markbind.github.io"
```
```
  "deploy": {
    "message": "Site Update.",
    "repo": "https://github.com/MarkBind/markbind.github.io.git",
    "branch": "master"
  }
```

**Comment by damithc** [comment]
> I'm getting the following error as I don't have access rights to the `markbind.github.io` repository.

You don't need to actually deploy. @yamgent will deploy when along with the next release.

**Comment by amad-person** [comment]
Okay!

**Comment by damithc** [comment]
> `"baseUrl": "/markbind.github.io"`

I suspect this should be just `/`

**Comment by damithc** [comment]
Closing this as both items are done now.
