### ISSUE TITLE
Allow setting the width of search bar

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#665]
The problem:

![image](https://user-images.githubusercontent.com/1673303/52174119-4110ae00-27ca-11e9-97fa-875e2c4c7210.png)

**Comment by Asthenosphere** [comment]
Hi Dr Damith, Wang Luo here, I may be able to come up a solution to this issue using HTML and CSS. Also, can I ask which site exactly is experiencing this issue? Thank you!

**Comment by damithc** [comment]
@Asthenosphere 
site https://se-education.org/learningresources/
code: https://github.com/se-edu/learningresources
