### ISSUE TITLE
Unexpected styling of fenced plain text

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#670]
v1.17.2

Example:
![image](https://user-images.githubusercontent.com/1673303/52331879-348f8e00-2a34-11e9-832b-282f90fefac0.png)

Problem: unwanted italics

Suggestion: When a language is not specified for a fenced code block, it not have any styles.

**Comment by Chng-Zhi-Xuan** [comment]
This is caused by Markdown-It parsing the text within the code block as a quote.

Both `.hljs-quote` and `hljs-comment` has *italics* styling.

We can override it for our documentation in `main.css`.

**Comment by ryoarmanda** [comment]
Investigating this a bit further, the example above was actually specified as a Markdown code in the fragment file, which in turn prompts highlight-js to parse the lines 2-4 as a Markdown quote, hence the `.hljs-quote` class is applied.

https://github.com/MarkBind/markbind/blob/d85aedc83da2cf166d47efa0f375999caf2470c1/docs/userGuide/syntax/blockquotes.mbdf#L35-L40

With this in mind, we can do two things: simply remove the `markdown` language so highlight-js will not attempt to syntax-highlight the code, or override the syntax-highlight styling for Markdown quotes to be non-italic as suggested in the previous comment.

The former if you wish the code block to be truly plaintext, the latter if you wish to keep the dim styling of the blockquote as seen as the example above (I guess the modification for this must be made on `main.css` in order not to affect genuine Markdown code blocks).

I assumed from the title that the expected case should be the first one. Can I check with you if that is the case? @damithc

**Comment by damithc** [comment]
> I assumed from the title that the expected case should be the first one. Can I check with you if that is the case? @damithc

Yes, I think it should be the first one
