### ISSUE TITLE
Automatically convert GitHub Wikis to MarkBind sites

### ISSUE THREAD

**Issue by Xenonym** [MarkBind/markbind#675]
**Tell us about your environment**

* **MarkBind Version:** 1.17.2

**Rationale:** [GitHub Wikis](https://help.github.com/articles/about-wikis/) are used commonly for project documentation (eg. [Angular.JS](https://github.com/angular/angular.js/wiki), [d3](https://github.com/d3/d3/wiki)). It would be viable to support automatic conversions for wikis as they are all flat directories of Markdown files in a Git repository, which should be relatively simple to implement.

In addition, we can also convert a wiki's [custom footers and sidebars](https://help.github.com/articles/creating-a-footer-or-sidebar-for-your-wiki/) (`_Footer.md`, `_Sidebar.md`) to our corresponding `footer.md` and `site-nav.md`. Additionally, many wikis use a sidebar that is generated by [`github-wiki-sidebar`](https://github.com/adriantanasa/github-wiki-sidebar), whose output can cleanly translate to our own `site-nav.md`:
```markdown
* [Installation](./Installation)
* [Roadmap](./Roadmap)
* [Usage](./Usage)
  * [Command line modifiers](./Usage%3A-Command-line-modifiers)
  * [Default mode (enquire)](./Usage%3A-Default-mode-(enquire))
  * [Tutorial mode](./Usage%3A-Tutorial-mode)
* [Examples](./Examples)
```
Alternatively, we can parse the file listing of the GitHub wiki to generate the site nav.

**Comment by yamgent** [comment]
Good idea, looking forward to your implementation. :+1:
