### ISSUE TITLE
Add support for footnotes

### ISSUE THREAD

**Issue by amad-person** [MarkBind/markbind#683]
**Tell us about your environment**

* **MarkBind Version: `1.17.3`**

**Rationale**: 

MarkBind is optimized for the following learning resources:
> content-heavy instructional websites e.g., course websites, tutorials, project/product documentation, **textbooks**

While writing learning resources, authors usually refer to information provided in articles, papers, etc.   Footnotes would be a good feature to have as they can be used to cite references or add comments on a designated part of the text, _without interrupting the flow of the main content_. 

**Proposed Solution**:

Include the **`markdown-it-footnote`** plugin that is available [here](https://github.com/markdown-it/markdown-it-footnote) in `markdown-it/index.js`.

**Comment by amad-person** [comment]
Tried to include the plugin, here's the result:
![screenshot_2019-02-17 markbind - about us](https://user-images.githubusercontent.com/22164211/52914532-75c15100-3304-11e9-8a32-886a93da0100.png)

![screenshot_2019-02-17 markbind - user guide adding pages](https://user-images.githubusercontent.com/22164211/52914533-778b1480-3304-11e9-93e2-896515614991.png)

The plugin basically appends the footnotes section to the end of the HTML file, but I don't think this positioning will be ideal as it is _**below the website footer.**_ We might have to find another plugin / customize this plugin / write one ourselves if we want add support for footnotes. 😢

**Comment by acjh** [comment]
Depends where it's called, right?

**Comment by yamgent** [comment]
How about rendering the footnotes separately into a temporary variable, extract out the rendered footnotes and put them into the pages manually by ourselves?

**Comment by acjh** [comment]
Sounds hacky. Footnotes are still part of content right?
Would moving footer into `page.ejs` solve this? Related: https://github.com/MarkBind/markbind/issues/636#issuecomment-462224299

**Comment by yamgent** [comment]
> Would moving footer into `page.ejs` solve this? Related: [#636 (comment)](https://github.com/MarkBind/markbind/issues/636#issuecomment-462224299)

Hmm yes that would actually work, we should clean up the footer first.
