### ISSUE TITLE
Netlify previews are failing due to "Cannot find module 'chokidar'"

### ISSUE THREAD

**Issue by Xenonym** [MarkBind/markbind#687]
**Tell us about your environment**

* **MarkBind Version:** 1.17.3

Currently, Netlify preview builds are failing for both `master` and PR previews with the following error:

```
module.js:550
    throw err;
    ^
Error: Cannot find module 'chokidar'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/build/repo/index.js:5:18)
failed during stage 'building site': Build script returned non-zero exit code: 1
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
```

For some reason, Netlify cannot find the module `chokidar`, which we use to watch for changes in live preview. 

However, **the build succeeds if I `Clear cache and restart deploy`.**

**Comment by damithc** [comment]
Similar thing happening to my PR too.

**Comment by nicholaschuayunzhi** [comment]
I think `npm install` is not run as per netlify documentation. The most recent change i did was change the build command to cd into `docs` folder before building. Maybe it triggered a bug?

**Comment by yamgent** [comment]
> I think `npm install` is not run as per netlify documentation. The most recent change i did was change the build command to cd into `docs` folder before building. Maybe it triggered a bug?

Hmm, seems to be the case. Added `npm install` to the build command, and now builds succeed without having to clear cache.

I think the issue should be resolved now, re-open if that's not the case.
