### ISSUE TITLE
Support admonition blocks

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#7]
Support different types of blocks for warnings, additional info, important points, etc.

**Comment by damithc** [comment]
It can be similar to markdown bock quotes but we should use different colors and icons to distinguish different types of info.

**Comment by Gisonrg** [comment]
Bootstrap has provided a series of helper class here:
http://getbootstrap.com/css/#helper-classes
which could be directly used (and with customized) in the project.

**Comment by damithc** [comment]
Yes, these could be sufficient for now. In future, we can consider 
* simpler syntax
* using icons instead of colors
![image](https://cloud.githubusercontent.com/assets/1673303/23636853/eab578fc-0312-11e7-9afc-15e8cc9252f0.png)
