### ISSUE TITLE
Honor alt property when header is given as a slot

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#71]
Code:
```html
<panel type="seamless" alt="definition">
  <span slot="header"> ================================================================
  </span>
  <include src="introduction/index.md#main" />
</panel>
```
Actual (when the panel is closed):
![image](https://user-images.githubusercontent.com/1673303/26923760-b817ea72-4c75-11e7-9a47-27ffb3494f27.png)

Expected:
![image](https://user-images.githubusercontent.com/1673303/26923911-328964b6-4c76-11e7-90f4-243e7077e039.png)

Seems to work correctly if the header is given as a property. e.g.
```html
<panel header="================================================================"
 type="seamless" alt="definition" >
  <include src="introduction/index.md#main" />
</panel>
```

**Comment by Gisonrg** [comment]
Fixed in CLI@1.3.2
