### ISSUE TITLE
Standardize the syntax for defining variables

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#710]
Current:
Global variables use `<span id="foo">` syntax
Page variables use `<variable name="foo">` syntax

Should we allow `<variable name="foo">` syntax to be used for global variables too?

**Comment by yamgent** [comment]
> Should we allow `<variable name="foo">` syntax to be used for global variables too?

Sure, don't see any disadvantages in that. Should we deprecate the `<span>` syntax as well?

**Comment by damithc** [comment]
> Sure, don't see any disadvantages in that. Should we deprecate the `<span>` syntax as well?

Yes, we can deprecate it.

**Comment by jamos-tay** [comment]
Sure, how about include variables?

```
<include src...>
  <span id="x">var</span>
</include>
```

**Comment by damithc** [comment]
> Sure, how about include variables?

Good point. Do the same there as well? What do you guys think?

**Comment by yamgent** [comment]
> Good point. Do the same there as well? What do you guys think?

Yes let's do it all in one shot.
