### ISSUE TITLE
Remove variable syntax for icons

### ISSUE THREAD

**Issue by Xenonym** [MarkBind/markbind#712]
* **MarkBind Version:** 1.19.0

Now that we have implemented colon syntax for icons (#680), we should remove code related to the implementation of variable syntax as it has been deprecated.

What should our time frame be for this? The suggestion was to remove it in the next minor version as per https://github.com/MarkBind/markbind/issues/612#issuecomment-456083641 but I am not sure if that is enough time for large projects that may be using MarkBind (eg. [se-edu/se-book](https://github.com/se-edu/se-book), [nus-cs2103/website-base](https://github.com/nus-cs2103/website-base).

**Comment by damithc** [comment]
best not to introduce breaking changes in the middle of the semester. As I'm not part of the current CS2103 teaching team, I don't want to create extra work for the current teaching team during the semester. We can probably do this early in the summer.

**Comment by damithc** [comment]
This can be done now.
