### ISSUE TITLE
include: give a way to omit frontmatter

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#720]
Suggestion: give a convenient way to include a file but omit the frontmatter section
e.g., `<include src="foo.md" omit-frontmatter />`

Reason: Some files can be used as independent pages as well as embedded in other pages.

**Comment by ryoarmanda** [comment]
I'm not sure if this is a valid usage, but clashes with the "parent" page's frontmatter can also be possible if you happen to include a page with a frontmatter (in which case the `omit-frontmatter` functionality becomes crucial to ensure correctness). For example, including a page with `pageNav: 1` will override the parent's `pageNav` value.

**Comment by ang-zeyu** [comment]
iirc this was intended behaviour, which allows authors to combine together frontmatter fragments using include.

maybe @acjh @marvinchin could confirm

**Comment by damithc** [comment]
> Reason: Some files can be used as independent pages as well as embedded in other pages.

To elaborate further about this, this is what I currently do:

foo.md:
```html
<frontmatter>
title: ...
</frontmatter>
<div id="main">
some text
</div>
```

In another place where I just want to include the content of the file in the middle of another page:
`<include src="foo.md#main"/>`

The `<div id="main">` can be avoided if there is a way to extract just the content without the frontmatter.
