### ISSUE TITLE
Add new team members to about.html

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#723]
1. Add new members to the list
2. Move inactive members to a _Past members_ section.
   Daniel Berzin Chua Yuan Siang: Project Member Jan 2018 - Aug 2018
   Jia Zhixin: Project Member May 2018 - Aug 2018
   Rachael Sim Hwee Ling: Project Member Jan 2018 - Dec 2018

**Comment by Xenonym** [comment]
Also: the link to @damithc's GitHub page is broken 🙈

**Comment by damithc** [comment]
> Also: the link to @damithc's GitHub page is broken 🙈

:-p Should be corrected as https://www.comp.nus.edu.sg/~damithch/
