### ISSUE TITLE
Restrictions on page variable values

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#735]
The following does not seem to work:
```html
<variable name="heading"># <include src="foo.md#title" inline /></variable>

{{ heading }}
```

Is that intended?

**Comment by acjh** [comment]
Expected:
```html
<h1 id="expected">Expected<a class="fa fa-anchor" href="#expected"></a></h1>
```

Actual:
```html
<h1 id>
  <include src="foo.md#title" inline></include><a class="fa fa-anchor" href="#"></a>
</h1>
```

**Comment by damithc** [comment]
@jamos-tay your take?

**Comment by jamos-tay** [comment]
Hmm this one is a little trickier than I thought

The current variable logic bypasses the `_preprocess` step altogether where all the `include` processing is done (i.e. variables are collected separately), so includes are simply ignored.

I can't really think of a clean solution as of now... Maybe I can integrate the variable collection into `_preprocess`? I'll do a little more digging and see if that works

In the meantime is it possible to wait for #682, and include `foo.md`'s title as a variable?

**Comment by damithc** [comment]
> In the meantime is it possible to wait for #682, and include `foo.md`'s title as a variable?

Sure. I've used a workaround for the time being.

**Comment by ang-zeyu** [comment]
This seems to be fixed, not sure by which PR.

Let's add a test case for this in the main test site sometime

**Comment by Gulruhbet** [comment]
Do you have intra code

**Comment by ang-zeyu** [comment]
intra code?
