### ISSUE TITLE
Give a way to exclude/include a specific heading from the search index

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#737]
Current: We can set which heading level in a page to use for search indexing

Suggested: Also give a way to specify that a certain heading should be omitted from the search index although it qualifies based on the heading level. Similarly, we can give a way to specify that a certain heading should be indexed even though it does not qualify based on the heading level.

**Comment by marvinchin** [comment]
What do you feel about having this syntax:
`<index>` tag to indicate that all nested headers should be indexed
```
<index>
##### Will be indexed
</index>
```
`<noindex>` to indicate that all nested headers should not be indexed
```
<noindex>
# Will not be indexed
</noindex>
```

**Comment by acjh** [comment]
Nesting is going to be computational expensive to determine if each header should be indexed.

**Comment by damithc** [comment]
Currently, we have a way to attach a keyword to the heading immediately above it. Perhaps we can have a tag that instructs MarkBind to include/exclude the heading immediately above it too?

**Comment by marvinchin** [comment]
@acjh could I check where the complexity might from? Given that we already have to traverse the content to look for headings and keywords, I suspect we might be able to handle nested selectors by tracking whether we are in `index` or `noindex` state during the traversal. This shouldn't add much additional computational complexity (based on a quick look of the code, but I'm not 100% sure on this). It might actually be more efficient compared to what we are currently doing for keywords, which requires searching up the tree for the closest heading.

However, from a user standpoint I'm not too sure which is more natural to use.

**Comment by acjh** [comment]
> Given that we already have to traverse the content to look for headings and keywords, I suspect we might be able to handle nested selectors by tracking whether we are in `index` or `noindex` state during the traversal. This shouldn't add much additional computational complexity (based on a quick look of the code, but I'm not 100% sure on this).

You need to search up to the furthest ancestor, assuming `noindex` takes precedent over nested `index`.
This is a lot of *additional* computational complexity.

> It might actually be more efficient compared to what we are currently doing for keywords, which requires searching up the tree for the closest heading.

Quite the opposite since it's **closest** heading. Also, this seems to be *required* to support keywords.

**Comment by marvinchin** [comment]
Oh, I wasn't thinking of searching for ancestors for each heading. I was thinking of keeping track of the `index`/`noindex` state **as** we traverse the content when collecting headings. Loosely, it would work something like this:

If currently in `index` state (outermost content tree is implicitly `index`):
- Collect headings/keywords as per normal
- If encounter a `<noindex>` tag, recurse into child in `noindex` state

If currently in `noindex` state:
- Ignore headings and keywords
- If encounter an `<index>` tag, recurse into child in `index` state

I would also assume that the closest `index` or `noindex` takes precedence.
```
<noindex>
  # Will not be indexed
  <index>
    # Will be indexed
  </index>
  # Will not be indexed
</noindex>
```

I'm not super familiar with how Cheerio works under the hood so I might be mistaken on this. Also, just wanted to note that I'm perfectly alright going with any solution 🙂. Just trying to understand where the complexity may arise from in case I'm missing something.

**Comment by acjh** [comment]
We don't traverse content.

**Comment by marvinchin** [comment]
Alright, should we go with this then?

> Currently, we have a way to attach a keyword to the heading immediately above it. Perhaps we can have a tag that instructs MarkBind to include/exclude the heading immediately above it too?

**Comment by yamgent** [comment]
> Alright, should we go with this then?
> 
> > Currently, we have a way to attach a keyword to the heading immediately above it. Perhaps we can have a tag that instructs MarkBind to include/exclude the heading immediately above it too?

How about supporting something like [custom attributes on headers](https://developers.google.com/web/resources/markdown-syntax#custom_attributes_on_headers)?

**Comment by damithc** [comment]
> How about supporting something like [custom attributes on headers](https://developers.google.com/web/resources/markdown-syntax#custom_attributes_on_headers)?

That works too.

**Comment by marvinchin** [comment]
Between syntax with the tag: 
`<span class="index"></span>`
and using custom attributes:
`{: .index }`
I'd lean towards the former as it provides a more consistent syntax with other search indexing features (i.e. keywords). Does anyone have any thoughts about this? Otherwise I will probably go ahead with implementing it this week.

**Comment by yamgent** [comment]
Using `<span>`s for keywords is acceptable, because sometimes the keyword may appear in the actual text, so authors can just mark keywords using the words in the content itself.

On the other hand, header attributes have no reason to be in the actual text.

**Comment by marvinchin** [comment]
Okay, I will go ahead with the custom attributes then!

**Comment by marvinchin** [comment]
Just a couple more questions about this:
- Do we want to restrict `{.index}` to headers only? Would we want to allow a user to use it to perhaps index a paragraph or a div as well?
- For headers that have been marked `{.noindex}`, do we still want to make them navigable?

**Comment by yamgent** [comment]
> * Do we want to restrict `{.index}` to headers only? Would we want to allow a user to use it to perhaps index a paragraph or a div as well?

Let's restrict to headers for now. The rest can be explored in the future if necessary (since we already have keywords and they look sufficient for now).

> * For headers that have been marked `{.noindex}`, do we still want to make them navigable?

They should still be navigable with `#fragments` (anchoring should be a separate issue from search indexing).
