### ISSUE TITLE
Replace headings in test .md files with bolded text

### ISSUE THREAD

**Issue by jamos-tay** [MarkBind/markbind#740]
Follow up from #694 

We should avoid using headings for test case names for test markdown files as it generates a lot of code in the `index.html` which affects its readability:

```
# Variables that reference another variable  <---
{{finalized_value}}

{{reference_level_4}}

# Page Variable  <---
<variable name="page_variable">Page Variable</variable>
{{ page_variable }}

# Page Variable with HTML and MD <---
<variable name="page_variable_with_HTML_and_MD">Page Variable with <span style="color: blue;">HTML</span> and **Markdown**</variable>
{{ page_variable_with_HTML_and_MD }}
```

They should be converted to `**bold**` instead:

```
**Variables that reference another variable**
{{finalized_value}}

{{reference_level_4}}

**Page Variable**
<variable name="page_variable">Page Variable</variable>
{{ page_variable }}

**Page Variable with HTML and MD**
<variable name="page_variable_with_HTML_and_MD">Page Variable with <span style="color: blue;">HTML</span> and **Markdown**</variable>
{{ page_variable_with_HTML_and_MD }}
```

**Comment by yash-chowdhary** [comment]
Hi, I'd like to take a shot at this issue. 
I have a couple of questions, though - 
1. There are instances where sub-headings ("##") are used. I think converting them to bold would lose the structure. Should we still go ahead with converting all headings to ``**bold**``?
2. A similar change could be made to ``test/functional/test-site/bugs/index.md ``. Just wanted to confirm that this file is also part of the scope of this issue.

Thanks

**Comment by yamgent** [comment]
> 1. There are instances where sub-headings ("##") are used (example shown below). I think converting them to bold would lose the structure. Should we still go ahead with converting all headings to `**bold**`?

Unless the thing under test is the structure itself (e.g. testing for the rendering of h1 and h2 tags), there should be no need to maintain them exactly. The bold text is a suitable substitute to still segregate sections, while being able to generate less noise at the same time (heading text generate a lot of HTML content which is hard to verify and distracting for the actual test).

> 1. Similar changes (changing all headings to `**bold**`) could be made to `test/functional/test-site/bugs/index.md `. Just wanted to confirm that this file is also part of the scope of this issue.

Yes, in fact this issue applies to all test files, where appropriate.

**Comment by yash-chowdhary** [comment]
Understood. Thanks!
