### ISSUE TITLE
docs/siteConfiguration: broken link

### ISSUE THREAD

**Issue by luyangkenneth** [MarkBind/markbind#741]
**Tell us about your environment**
https://markbind.org/userGuide/siteConfiguration.html

**MarkBind Version:**
1.19.1

**What did you expect to happen?**
Under the `pages` section, clicking on the `layout` link should navigate to the appropriate page.

**What actually happened? Please include the actual, raw output.**
Encountered a 404 as the link is broken.

**Comment by yamgent** [comment]
On a side note I wonder if there's a way to automate finding broken links in a website...
