### ISSUE TITLE
Extraneous Keyword for Keyword Docs

### ISSUE THREAD

**Issue by marvinchin** [MarkBind/markbind#747]
**What did you do? Please include the actual source code causing the issue.**
Search for `keyword` on the MarkBind documentation site.

**What did you expect to happen?**
Only the heading 'Keywords' should be indexed.

**What actually happened? Please include the actual, raw output.**
The keyword 'Regressions' is indexed together with the heading.
<img width="410" alt="screenshot 2019-03-03 at 11 41 22 am" src="https://user-images.githubusercontent.com/17447681/53690654-bfe90e80-3da9-11e9-896f-4b2dc7fd4c13.png">

This is probably because we provide the following example to the user, which includes the keyword.

```
<big>**Developer Testing**</big><br>

This is good for catching <span class="keyword">regressions</span>.
</box>
</div>
```

Is intended behaviour, or if we should remove this keyword? 🙂

**Comment by damithc** [comment]
Good catch @marvinchin 
This came up in an earlier discussion and we decided to leave it as it is. The extra search result is unlikely to cause a big problem while trying to get rid of it is likely to need some hacks.

**Comment by acjh** [comment]
Duplicate of #567

**Comment by marvinchin** [comment]
Sorry, didn't notice that earlier!
