### ISSUE TITLE
Scroll to anchor: target heading hidden by nav bar 

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#753]
More often than not, trying to reach a heading anchor in a page would end up in a scroll position that hide the target heading under the topNav.

e.g., when trying to reach https://markbind.org/userGuide/usingPlugins.html#algolia-enabling-algolia-docsearch this is what I get:

![image](https://user-images.githubusercontent.com/1673303/53893082-72e69000-4068-11e9-9207-7ed49e4fe839.png)

I remember we tried to fix this sometime back but apparently it is not fully fixed?

A minor issue:
1. Go to https://markbind.org/userGuide/usingPlugins.html#algolia-enabling-algolia-docsearch using URL bar
1. Scroll to some other location in the same page
1. To to go back to https://markbind.org/userGuide/usingPlugins.html#algolia-enabling-algolia-docsearch using URL bar
Actual: The page does not scroll back to https://markbind.org/userGuide/usingPlugins.html#algolia-enabling-algolia-docsearch

**Comment by Chng-Zhi-Xuan** [comment]
**Findings**

Might be a browser issue, using this [web page](https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-the-Root-Instance).

- Chrome does not scroll back if you reload the same URL.
- Firefox always scroll back if the same URL is entered.

**Comment by damithc** [comment]
> This should be fixed with #733 as we move away from `position: fixed` components. Along with an additional PR for our `<navbar>` component to have it be compatible with #733.

The problem still seems to be present in #733 netlify preview though

**Comment by Chng-Zhi-Xuan** [comment]
In addition to #733, we have to change the `<navbar>` component within the `Vue.js` repository with an additional PR.

**Comment by luyangkenneth** [comment]
#733 and https://github.com/MarkBind/vue-strap/pull/101 have been merged, so closing this issue as fixed 🙂
