### ISSUE TITLE
Add meta tag for algolia search

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#754]
Algolia team has asked if we can include the following meta tag in MarkBind sites that has Algoli plugin enabled.
`<meta name="generator" content="markbind">`

**Comment by Xenonym** [comment]
We could just include the tag on all MarkBind generated pages anyway, since its [part of HTML5](https://www.w3.org/TR/html5/document-metadata.html#generator).

We could also include the version number eg. `<meta name="generator" content="MarkBind 1.19.2">`.

**Comment by yamgent** [comment]
> We could just include the tag on all MarkBind generated pages anyway, since its [part of HTML5](https://www.w3.org/TR/html5/document-metadata.html#generator).
> 
> We could also include the version number eg. `<meta name="generator" content="MarkBind 1.19.2">`.

Yes let's do that. We can do it for all pages regardless of whether they use Algolia or not.

**Comment by damithc** [comment]
> We could just include the tag on all MarkBind generated pages anyway, since its [part of HTML5](https://www.w3.org/TR/html5/document-metadata.html#generator).
> 
> We could also include the version number eg. `<meta name="generator" content="MarkBind 1.19.2">`.

I'm OK with that too 👍
