### ISSUE TITLE
Dynamic includes: image links in sub-modules are broken

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#76]
Example https://markbind.github.io/cs2103-website/
![image](https://user-images.githubusercontent.com/1673303/28003477-6858044a-6570-11e7-80bc-f6863fd6d064.png)

Image links in static includes seem to be working though.
![image](https://user-images.githubusercontent.com/1673303/28003495-9ddf4970-6570-11e7-9c4f-450a6e8a14fb.png)

The file containing the image link is https://github.com/MarkBind/se-book/blob/9d95109c22eb122e20f16236961b2f7d12165b79/designPrinciples/coupling/whatItIs/text.md
And the link is `<img src="{{baseUrl}}/designPrinciples/coupling/whatItIs/images/playerPuzzleManager.png" height="220" />`

**Comment by Gisonrg** [comment]
Now should be fixed in 1.3.3. Let me know if same issues occur again :)

**Comment by damithc** [comment]
It's working now. Thanks @Gisonrg 👍
