### ISSUE TITLE
Unexpected behavior when using variables and icons

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#764]
v1.20.0

These variables don't seem to behave as expected:
in `variables.md`:
```html
<variable name="year">2019</variable>
<variable name="AY">18/19</variable>
<variable name="cs3281_time">MON 1200 - 1400</variable>
<variable name="icon_dislike">:fas-thumbs-down:</variable>
```
in another file:
```html
{{ year }}<br>
{{ AY }}<br>
{{ cs3281_time }}<br>
{{ icon_dislike }}<br>
```
output:
![image](https://user-images.githubusercontent.com/1673303/54110680-04fde800-441d-11e9-8b89-b90bd502e645.png)

**Comment by damithc** [comment]
@jamos-tay can take a look?

**Comment by yamgent** [comment]
Bisected to dc53e764725d5, which introduced the :prefix-name: syntax.

Compatible `variables.md` for that version:
```html
<span id="year">2019</span>
<span id="AY">18/19</span>
<span id="cs3281_time">MON 1200 - 1400</span>
<span id="icon_dislike">:fas-thumbs-down:</span>
```

For some reason, the `<br>`s in the `{{ year }}<br>{{ AY }}<br>...` is causing some problem. Adding space in front of the variable content also somehow makes the bug disappear:

```
<variable name="icon_dislike"> :fas-thumbs-down:</variable>
```

Not extremely familiar with `markdown-it` extensible plugins, maybe there's a bug in replacing the syntax? @Xenonym any ideas?

**Comment by Xenonym** [comment]
Thanks for tracking it down @yamgent! This is a bug in the regex:

https://github.com/MarkBind/markbind/blob/6119a91a9ea472c07e318a8c79ccd1b65884422b/src/lib/markbind/src/lib/markdown-it/markdown-it-icons.js#L2

Removing the `m` flag (making it `/:(fa[brs]|glyphicon)-([a-z-]+):/` seems to fix it.
