### ISSUE TITLE
Use of Javascript dictionaries for includedFiles

### ISSUE THREAD

**Issue by sijie123** [MarkBind/markbind#772]
* **MarkBind Version:**
Markbind 1.20.0

We currently use includedFiles to check what pages we need to rebuild when they are updated.
When a file is included, we do something similar to:
https://github.com/MarkBind/markbind/blob/07814ff70cac23c4a6b78c6fa6b99fe59a25ca61/src/Page.js#L487
to indicate that it should be flagged for updating.

I notice that includedFiles is a dictionary, containing only {file: true} values.
With ES6, we can actually use the Set data structure to store this information, instead of tagging everything as true. It's a minor coding style thing, but I felt it's just odd to use a dictionary of `true`s.

If we use a set, then in Site.js we can simply do
```
if (shouldRebuildAllPages || filePaths.some(filePath => page.includedFiles.has(filePath)))`
```
which is semantically a bit clearer than `page.includedFiles[filePath]` (<-- what is the return data type?)

Would this be a good idea? It doesn't really affect our correctness now, but it's a low hanging fruit that can be resolved easily.

**Comment by yamgent** [comment]
> Would this be a good idea? It doesn't really affect our correctness now, but it's a low hanging fruit that can be resolved easily.

Very good suggestion, this would make it clearer semantically.

**Comment by sijie123** [comment]
Marking this as a good first issue - it's rather easy to mechanically replace the dictionaries with sets.
Also refer to https://github.com/MarkBind/markbind/pull/778#pullrequestreview-216555374

**Comment by yamgent** [comment]
> Marking this as a good first issue

@sijie123 you have a PR opened though, people may not attempt this issue if they see an active PR. :P

**Comment by sijie123** [comment]
I was thinking of seeing if I have time for the rest of the semester to finish up the PR.
If I have, then I'll just finish this issue up :P
Otherwise, I'll probably close my PR and leave it as a starting point for future developers.
