### ISSUE TITLE
Morph content appearing outside of the morph element

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#8]
I have this code in a file. When I include it in another place, the content of the morph element appears outside of the element.

```markdown
* [Design Patterns](book/se-pattern/)
  <morph title=":mag_right:">
    <div>
  
A software _design pattern_ is a general reusable solution to a commonly occurring problem within a given context in 
software design. 

This chapter covers:

* An intro to design patterns
* Some common design patterns

    </div>
  </morph>
```

![image](https://cloud.githubusercontent.com/assets/1673303/24287360/4d3de988-10b4-11e7-8720-eee08e4f3345.png)

**Comment by Gisonrg** [comment]
Probably a regression of parsing update. Let me check it out.

**Comment by Gisonrg** [comment]
Could you try use format as below? This is probably a temp fix. 
The reasons are first need to ensure they are under the list element, so should indent them at the same level as the list. Secondly there probably be some issue regarding multi-paragraph list handling in markdown parsing library.

```
* [Design Patterns](book/se-pattern/) <morph title=":mag_right:"><div>
  A software _design pattern_ is a general reusable solution to a commonly occurring problem within a given context in 
  software design.    
  This chapter covers:    
  * An intro to design patterns
  * Some common design patterns
  </div>
  </morph>
```

**Comment by damithc** [comment]
Yes, that works.

**Comment by damithc** [comment]
Closing as `morph` is no longer supported.
