### ISSUE TITLE
Dynamic panels: support minimizing 

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#80]
Current: dynamic panels can be minimized by default, but once expanded, they cannot be minimized again.

See https://markbind.github.io/se-book/common/outcomes.html for an example

![image](https://user-images.githubusercontent.com/1673303/28453432-f2c41bf2-6e29-11e7-97c7-71b42fdbb825.png)

**Comment by acjh** [comment]
Updated link: https://se-edu.github.io/se-book/common/outcomes.html

**Comment by acjh** [comment]
Invalidated by #292
