### ISSUE TITLE
Site nav padding causes title and scrollbar to be wrongly indented

### ISSUE THREAD

**Issue by marvinchin** [MarkBind/markbind#800]
**Tell us about your environment**

* **MarkBind Version:** 2.0.0

**What did you expect to happen?**

The title and scrollbar should be correctly positioned.

**What actually happened? Please include the actual, raw output.**

<img width="296" alt="Screenshot 2019-04-01 at 4 24 23 PM" src="https://user-images.githubusercontent.com/17447681/55313551-a0253300-549a-11e9-83e3-ac49ae13ca78.png">

- The title is indented too far to the right
- The scrollbar is indented too far to the left

**Comment by Chng-Zhi-Xuan** [comment]
**Quick fix**
- Remove `indented` class from User Guide text.
- Remove `padding-right: 20px` from `site-nav.css#site-nav` (probably `padding-bottom: 20px`) as well.

**Comment by marvinchin** [comment]
Would removing `padding-right` from `#site-nav` this cause long titles not to have the correct padding? 

<img width="311" alt="Screenshot 2019-04-01 at 4 52 16 PM" src="https://user-images.githubusercontent.com/17447681/55315264-8e458f00-549e-11e9-96df-69219512ade1.png">

I'm thinking of moving the padding to the inner div containing the scrollbar. This way:
- Padding is not applied when calculating scrollbar position
- Consistent adding is applied to all content within the site nav, including title and content

What do you think about this approach?

**Comment by Chng-Zhi-Xuan** [comment]
> Would removing padding-right from #site-nav this cause long titles not to have the correct padding?

I can't reproduce your example in the current V2.0 build, the text will automatically wrap around if it exceeds the paragraph boundaries.

> I'm thinking of moving the padding to the inner div containing the scrollbar.

If you are referring to having adequate space between the text and the scrollbar, it already has `px-3` padding class for that. 

If you want to have the scrollbar stick to the right, i think `padding-right: 0;` on `#site-nav` is sufficient. 

I just tested with
- `padding-right: 0`
- `padding-bottom: 0`
- Removing `indented` class

And the result is the contents of `site-nav` have a consistent `1rem` padding on the left and right, along with the scrollbar sticking to the divider line.

Is there anything I am missing?

**Comment by Chng-Zhi-Xuan** [comment]
Ok, after re-reading your comment, I understand your point now. You wanted to have the `1 rem` right padding to apply to non site nav list items. While having the scrollbar stick to the right divider.

I guess we could automatically wrap contents placed before and after the `<navigation>` tag with some wrapper for padding?

**Comment by marvinchin** [comment]
Yes, I was thinking that the padding should also be applied to other items outside the list (e.g. the title) 🙂 

I tried applying the suggested changes by adding padding to the `<div>` wrapping the site nav contents in #801. Would that approach works?

**Comment by Chng-Zhi-Xuan** [comment]
Your fix won't have the paddings added to content outside the `site-nav-list` am I correct? Then it wouldn't solve the original issue you raised 👀

**Comment by marvinchin** [comment]
Thanks again for taking the time to look at it 🙂 

My apologies if the way I phrased it was confusing. If there is anything I can do to provide further clarification do let me know!
