### ISSUE TITLE
Create a high-level product roadmap for MarkBind

### ISSUE THREAD

**Issue by luyangkenneth** [MarkBind/markbind#813]
This will help the team to prioritize short-term goals (like how we had the [V2 github project](https://github.com/MarkBind/markbind/projects/2)), and also understand how the work fits into a longer-term direction for the Markbind product.

**Comment by luyangkenneth** [comment]
@damithc Adding the on-hold label because you mentioned it'll be better to do this at a later point in time

**Comment by damithc** [comment]
> @damithc Adding the on-hold label because you mentioned it'll be better to do this at a later point in time

Yes, I'll add that after dev docs have been converted to MarkBind format.

**Comment by kaixin-hc** [comment]
After discussion in class with @damithc , we decided that we will implement a "product roadmap" on github projects + revisit the dev guide to see if the 'product vision' is sufficient. Will update here when the project makes sense and then close this issue; till then we can have discussion here.

The [project](https://github.com/orgs/MarkBind/projects/1) will try to roughly show our targets for this semester + a selection of prioritised issues, which will hopefully also help new contributors know where they can start. 

As part of this, we will also aim to document use of projects and milestones as per https://github.com/MarkBind/markbind/issues/2142

**Comment by kaixin-hc** [comment]
Quick review after using this roadmap the past two months: 

23 issues were prioritised and completed with this roadmap, with 27 remaining. Of these, 15 are discussion / KIV issues, which have questions that are not fully resolved.

Overall, I think dividing issues to do into implementation needed for straightforward tasks and KIV helped to prioritise work over the course of the semester. Using the inbuilt tool was useful to get the whole team on the same page, and we can perhaps continue doing this with a fresh road map next year

**Comment by tlylt** [comment]
> Overall, I think dividing issues to do into implementation needed for straightforward tasks and KIV helped to prioritise work over the course of the semester. Using the inbuilt tool was useful to get the whole team on the same page, and we can perhaps continue doing this with a fresh road map next year

👍 We could document this in DG so that the workflow is maintained in the future. This issue can be closed after that doc update.
