### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by amad-person** [MarkBind/markbind#816]
We can add a CONTRIBUTING.md for MarkBind so that it becomes easier for new contributors to get started with our project. 

This is a [template](https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md) we can use to get started.

Off the top of my head, good things to mention would be:
- what kind of contributions we're looking for (issues, PRs, etc.)
- how we make PRs (forking workflow)
- rules to follow for PRs (maybe a checklist for reminding contributors to run tests, follow our code style conventions, update documentation, etc.)

**Comment by yash-chowdhary** [comment]
Currently, in the [developer guide](https://markbind.org/devdocs/devGuide/index.html), we have a large chunk of content (the [`Development Process`](https://markbind.org/devdocs/devGuide/devGuide.html#development-process) heading) that can be used in the `contributing.md` file, while more stuff can be added. 

Is the idea to link the contributing guidelines from the main page of the dev docs (as done in [gatsby](https://www.gatsbyjs.org/docs/#start-contributing))?

**Comment by yamgent** [comment]
`CONTRIBUTING.md` should be more of a beginner's guide for contributors. The stuff in Development Process are more towards setting up the development environment, which is more of the practical side of things. `CONTRIBUTING.md` should instead be introducing to the open source nature of the repo. So for the gatsby example it should be something like [this page](https://www.gatsbyjs.org/contributing/).

This page has a pretty rough guide on how to write one: https://mozillascience.github.io/working-open-workshop/contributing/.
