### ISSUE TITLE
Investigate implications of moving to the latest version of npm

### ISSUE THREAD

**Issue by luyangkenneth** [MarkBind/markbind#819]
The team is currently standardized on npm 5.8.0 to retain the way dependency version numbers are specified in our `package-lock.json` (see #756 for more context)

If there are no downsides to upgrading, we should move to the latest version of npm. This will also help to unblock #808

**Comment by Chng-Zhi-Xuan** [comment]
**Summary of why `package-lock.json` format was changed in npm@6**
- https://github.com/npm/npm/issues/20434#issuecomment-402988364

I've been skimming through npm releases and there are no other significant breaking changes moving to the latest version (v6.9.0).

Although there will significant changes to `package-lock.json`'s formatting and behaviour, the comment provides some assurance that nothing will break. 

Would like some input from @acjh, @yamgent

**Comment by acjh** [comment]
We're on npm@5 mainly because of htmlparser2.

**Comment by ang-zeyu** [comment]
Closing per #948
