### ISSUE TITLE
Document the <include> tag

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#82]
Current: https://markbind.github.io/vue-strap/ does not document how to use the `<include ... />` tag

**Comment by acjh** [comment]
`<include ... />` is a MarkBind construct though.
It's documented in https://github.com/MarkBind/markbind-cli/wiki/Including-contents.

**Comment by damithc** [comment]
I see. I don't think end users need to know there are two types of syntax. It would be good to document all syntax in one place, at least a summary.

**Comment by damithc** [comment]
It would be cool if MarkBind itself can solve this problem of integrating documentation of markdown, vue, and markbind. :-)

**Comment by acjh** [comment]
Sounds suitable for #135

**Comment by acjh** [comment]
## Update
- Documented in [userGuide/includingContents.html](https://markbind.github.io/markbind/userGuide/includingContents.html).
- Also linked in [userGuide/contentAuthoring.html#include-contents](https://markbind.github.io/markbind/userGuide/contentAuthoring.html#include-contents) for visibility.
