### ISSUE TITLE
Layouts should not have *.md files copied on build

### ISSUE THREAD

**Issue by Xenonym** [MarkBind/markbind#825]
**Tell us about your environment**

* **MarkBind Version:** 2.1.1

**What did you do? Please include the actual source code causing the issue.**

I used the `default` layout within a MarkBind site to have a custom header and footer.

**What did you expect to happen?**

The `*.md` files within the layout (`footer.md`, `head.md`, `header.md`, `navigation.md`) should not be copied to the built site.

**What actually happened? Please include the actual, raw output.**

The `*.md` files within the layout were copied to the built site in `markbind/layouts/default/`.

**Comment by yash-chowdhary** [comment]
I'm a bit confused. Does this mean that we can get rid of the `markbind/layouts` directory in the `_site` directory?  
All the files that could be required would already be in `_markbind/layouts`, so any changes could be made there. The copying of layout files may not be necessary at all. Am I missing something?

**Comment by yamgent** [comment]
> The copying of layout files may not be necessary at all. Am I missing something?

The layout folder usually contains more than just `.md` files (e.g. `styles.css` and `scripts.js`). Those other files need to be copied usually. Only the `.md` do not need to be copied because they are supposed to be rendered by MarkBind.
