### ISSUE TITLE
default layout: navigation.md content is not applied correctly

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#836]
Steps:
* Init a new site
* Add a site navigation menu to _markbind/layouts/default/navigation.md
* Apply the default layout to a page

The sitenav in the file in not applied correctly.

![image](https://user-images.githubusercontent.com/1673303/56018002-76d69380-5d33-11e9-91ab-a3d163e06f80.png)

**Comment by damithc** [comment]
@amad-person you probably encountered this when trying to apply init to RepoSense/TEAMMATES

**Comment by amad-person** [comment]
I think this is a duplicate of #528...the solution is in #739

**Comment by damithc** [comment]
> I think this is a duplicate of #528...the solution is in #739

Looks like it. Let's get if fixed quickly though.
