### ISSUE TITLE
Site.js default layout script's code is not compliant with eslint

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#840]
**Tell us about your environment**

* **MarkBind Version:** 2.2.0

**What did you do? Please include the actual source code causing the issue.**

https://github.com/MarkBind/markbind/blob/cf57489addeb4c3b6d1151c6cc29c6033009d453/src/Site.js#L170-L172

The default content needs a `// eslint-disable-next-line no-undef`. In other words, it should be like this:

``` js
 const LAYOUT_SCRIPTS_DEFAULT = '// eslint-disable-next-line no-undef\n'
   + 'MarkBind.afterSetup(() => {\n' 
   + '  // Include code to be called after MarkBind setup here.\n' 
   + '});\n'; 
```

Otherwise, projects that uses eslint (such as MarkBind) will complain about a [no-undef](https://eslint.org/docs/rules/no-undef) error.

**Comment by marvinchin** [comment]
I think it makes sense for the files generated by MarkBind to pass our own ESLint rules.

**Comment by yamgent** [comment]
> Is this necessary? It seems strange to assume that sites built with MarkBind would definitely use ESLint.

We can alternatively update our eslint configuration to disable the check for expected folders if that fits the assumption.
