### ISSUE TITLE
Improve user guide to include required minimum node version

### ISSUE THREAD

**Issue by Crphang** [MarkBind/markbind#848]
**Tell us about your environment**

* **MarkBind Version:** 2.4.0
* **Node Version:** 7.2.0

**What did you do? Please include the actual source code causing the issue.**

```html
markbind init
```

**What did you expect to happen?**

Get initialization Success.

**What actually happened? Please include the actual, raw output.**
![image](https://user-images.githubusercontent.com/4986717/57175828-d03d6880-6e82-11e9-9b60-7d9c23a181f5.png)

**Comment by yamgent** [comment]
> * **Node Version:** 7.2.0

That's a very old node version. :P Nevertheless good to mention it in the user guide (and perhaps the dev guide too).

I am using Node v8.11.3, can be used as the bare minimum version required to run MarkBind.
