### ISSUE TITLE
Shorten divider line of siteNav and pageNav

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#851]
Current: the divider line of siteNav and pageNav spans the full page
![image](https://user-images.githubusercontent.com/1673303/57597218-1d0af880-7581-11e9-9cb1-cd047f5380e3.png)

Suggested: end the line where the content of the siteNav/pageNav ends. e.g.,
![image](https://user-images.githubusercontent.com/1673303/57597262-4a57a680-7581-11e9-9599-1e1d812c205c.png)

Reason: looks neater. But it's a subjective opinion; open for discussion

**Comment by Chng-Zhi-Xuan** [comment]
Yes it looks neater, and not much changes need to be made. It can serve as a good first issue as well.

Alternative design from [Markdown Guide](https://www.markdownguide.org/getting-started) can also be looked into.
