### ISSUE TITLE
Add --help to documentation on CLI

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#862]
The `--help` documentation is missing from https://markbind.org/userGuide/cliCommands.html

Other suggestions:
* Add a PageNav menu to that page

**Comment by madanalogy** [comment]
I would like to work on this if it is still an issue. Seems like there's already a description of `--help` in the overview.

On a side note, the user guide states that the shorthand alias for `--version` is `-v` when the actual argument is capitalised in the markbindCLI (i.e. `-V`). Should I open a separate issue for this? I was thinking I could just make the corrections together with the edits as part of resolving this issue.

**Comment by yamgent** [comment]
I am not sure what this issue is pertaining to as well. @damithc?

> On a side note, the user guide states that the shorthand alias for `--version` is `-v` when the actual argument is capitalised in the markbindCLI (i.e. `-V`). Should I open a separate issue for this? I was thinking I could just make the corrections together with the edits as part of resolving this issue.

Nice catch. Yes the user guide is wrong, we use capital `-V`. (some programs such as `dot`, `npm` and `python` also uses capitalized `-V` instead of small `-v`. Reason being `-v` is used as a "verbose" option).

If you are planning to fix this as well, I think this issue is minor enough to not warrant opening a separate issue for it.

**Comment by damithc** [comment]
> I am not sure what this issue is pertaining to as well. @damithc?

IIRC, the issue is about the page missing a sub-section describing the `help` command (it only has detailed sections for init, build, deploy, and serve).


> Seems like there's already a description of `--help` in the overview section of https://markbind.org/userGuide/cliCommands.html

Yes, that's true. But we should give a detailed section for _every_ command in case someone comes looking for the details of a specific command? If duplication is a problem, MarkBind is supposedly optimized to handle content duplication (e.g., we can use an `<include>`).
