### ISSUE TITLE
<pic>: Support inline `float` positioning

### ISSUE THREAD

**Issue by alyip98** [MarkBind/markbind#869]
Suggestion: enhance `<pic>` by supporting [inline](https://www.w3schools.com/css/css_float.asp) positioning.

**Comment by openorclose** [comment]
![image](https://user-images.githubusercontent.com/3646725/58526519-c7ca1a80-8201-11e9-900b-1aa607558d04.png)

Simply adding a float:left to the image causes other elements (such as headings and panels and other paragraphs) to be on the right of the image if there's enough space.

**Comment by damithc** [comment]
As discussed:
* The typical use case is when there is a small/tall image in the middle of lot of text.
* In cases where there is a chance of unexpected content being inlined with the image, we can explain in documentation how to avoid it using `<div>` tags.

**Comment by openorclose** [comment]
Is it better to implement this as a class?

Then the code would be

```html
<pic src="img.png" add-class="float-left"></pic>
```

Then this can be used on `img` tags and possibly `thumbnails` as well.

**Comment by damithc** [comment]
> Is it better to implement this as a class?

No objections from me

**Comment by damithc** [comment]
It seems Bootstrap has float classes already https://getbootstrap.com/docs/4.3/utilities/float/
