### ISSUE TITLE
<pic>:Support simple borders

### ISSUE THREAD

**Issue by alyip98** [MarkBind/markbind#870]
Suggestion: enhance `<pic>` by supporting simple borders like a simple 1px solid colored border.

**Comment by yash-chowdhary** [comment]
Do we need to add this functionality to `<pic>` if we already have the `add-class` functionality in place? Currently, users can add borders using `add-class` with pictures. 
Perhaps we can keep it that way and not have MarkBind/vue-strap support it explicitly?

Something similar has been discussed in [Markbind #386 (comment)](https://github.com/MarkBind/markbind/issues/386#issuecomment-408722347)
