### ISSUE TITLE
Popovers and Tooltips: migrate to bootstrap-vue

### ISSUE THREAD

**Issue by openorclose** [MarkBind/markbind#873]
https://bootstrap-vue.js.org/docs/components/popover/
https://bootstrap-vue.js.org/docs/components/tooltip/

These components already exist and work better than the ones we currently have.

**Comment by damithc** [comment]
Would this solve #397 ?

**Comment by Chng-Zhi-Xuan** [comment]
Yes, it will solve #397 

We are likely going to remove all of the previous implementation (including dependency on `popupMixins.js`) of Popovers and Tooltips during the migration. 

As we will be aiming to use Bootstrap-Vue's implementation, just changing the syntax to match our old one.

**Comment by Chng-Zhi-Xuan** [comment]
Part of #814

**Comment by le0tan** [comment]
The logic of triggering in our fork of vuestrap is a bit different from bootstrap-vue. We might need to write `Trigger` component first?

**Comment by yamgent** [comment]
> The logic of triggering in our fork of vuestrap is a bit different from bootstrap-vue. We might need to write `Trigger` component first?

If a (re?)write is necessary, feel free to come up with a WIP PR to showcase how it will be done, so that everyone can take a look at the changes.

Generally the best case scenario would be that there isn't any changes required by the authors side even with the rewrite.

**Comment by openorclose** [comment]
I have some old work on this, I'll see if I can produce a working version
