### ISSUE TITLE
Provide indentation classes within MarkBind

### ISSUE THREAD

**Issue by Chng-Zhi-Xuan** [MarkBind/markbind#878]
* **MarkBind Version: v2.4.2**

**Issue**

Currently, an author is unable to indent content easily especially for higher nesting levels.

**Suggestion**

Have MarkBind provide indentation classes that can be easily inserted via [markdown-it-attrs](https://www.npmjs.com/package/markdown-it-attrs) or [custom classes in components](https://markbind.org/userGuide/usingComponents.html#inserting-custom-classes-into-components).

``` HTML
<panel header"Indented panel" add-class"indent-5">
  ...
</panel>

`Indented inline code` {.indent-5}
```

**Comment by ang-zeyu** [comment]
discussed in #1015
