### ISSUE TITLE
Document support for layouts/*/header.md

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#890]
Current: no mention of a `header.md` when describing support for layouts
![image](https://user-images.githubusercontent.com/1673303/59995064-adf8e780-9688-11e9-9349-96f2c340a4d5.png)

Suggestion: add the missing documention

**Comment by damithc** [comment]
@Chng-Zhi-Xuan is this issue confirmed or I misunderstood situation?

**Comment by Chng-Zhi-Xuan** [comment]
Yes the documentation is missing. 

There is already support for `header.md` layout files in the current release.
