### ISSUE TITLE
Support relative links in included files

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#9]
If a file `root/aaa/bbb/page.md` contains a link `[details](details.md)`
and it was included in `root/toc.md`
the generated link in `toc.html` should be `aaa/bbb/details.html`?

**Comment by Gisonrg** [comment]
I guess so for now. It is a feature on my list but haven't start looking at it yet (because we have to resolve the relative link in both runtime and build time because of we have dynamic include, build is easier to fix). I'll think about it over the weekend.

**Comment by Gisonrg** [comment]
It's a little tricky for the relative path. Here are my (non-verified) thinkings for solving it:
In build time, at `include` stage, path in markdown are still in markdown format such as [](path/to/file). We need to collect all relative path that is not used for an expanded content (panel/morph), e.g. path in images and anchor links, and change them into a path that is relative to the root file being parsed.
This requires us to find out all possible patterns for a link that we want to change, for example, `img` usually has a `src` attribute, markdown usually use `[]()` format for a link. It may take some time to conclude them. Regular expression could be use as well/

**Comment by damithc** [comment]
Yes, it's not going to be easy. But it is also critical to support this as it a basic requirement for reusability.

**Comment by damithc** [comment]
Case 1:
* file `folder1/file1.mbd` contains a relative link `[link](target.html)`
* when `file1.mbd` is included in `folder2/file2.mbd`, the link will point to `folder2/target.html`.

Case 2:
* file `folder1/file1.mbd` contains an absolute link `[link]({{ baseUrl }}/folder1/target.html)`
* when `file1.mbd` is included in `folder2/file2.mbd`, the link will point to `folder1/target1.html`.

I think this behavior is fine. i.e., if the link is supposed to point to the same target no matter from where the file is included, it should be made an absolute link by using `{{ baseUrl }}`
