### ISSUE TITLE
Support easy integration of Google Analytics

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#902]
Provide an easy way to add Google Analytics to a site, e.g., simply by configuring site.json

**Comment by Crphang** [comment]
Read through the codebase on supporting this, it is actually already supported if we add google-analytics tracking code into `externalScripts` of `site.json`.

All externalScripts from `site.json` are added when calling `generatePages -> createPage` using ejs template.

Should we have a separate key for Google Analytics, or continue using externalScripts, but add this into the User Guide?

**Comment by damithc** [comment]
Yes, it can be done already, but we can make it easier. For example, we can allow users to add GoogleAnalytics tracking to a site by simply adding the tracking ID to `site.json`.
Example from a similar product https://gohugo.io/templates/internal/
