### ISSUE TITLE
Support media lists

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#906]
Similar to https://bootstrap-vue.js.org/docs/components/media
* Provide a more MarkBind-like syntax
* Allow using thumbnails in addition to the image

Rationale: this feature can be useful in making a text-heavy list more visual

Example:
![image](https://user-images.githubusercontent.com/1673303/60234756-0a057b00-98d8-11e9-8d82-8507d8698dcb.png)

**Comment by nbriannl** [comment]
I'm interested in picking this up. 👍

**Comment by SPWwj** [comment]
Request to work on this Issue.
