### ISSUE TITLE
<box>: add a light style to box

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#909]
Current:
![image](https://user-images.githubusercontent.com/1673303/60245489-498b9180-98ef-11e9-954c-c8eff4aa8b12.png)

Suggestion: also add a mode where the style is lighter in colors.

Suggested syntax: `<box light type="info" ...>`

Output:
![image](https://user-images.githubusercontent.com/1673303/60245450-3678c180-98ef-11e9-9e10-d55f85435483.png)

We can still have the icon.

In fact, this can apply to panels as well. e.g.,
![image](https://user-images.githubusercontent.com/1673303/60247994-4e067900-98f4-11e9-869c-1aec30829942.png)

(Inspired by mk-docs)

**Comment by hcwong** [comment]
I don't mind looking into this, but this entails modifying the vue-strap repo right?

**Comment by yamgent** [comment]
> I don't mind looking into this, but this entails modifying the vue-strap repo right?

Yes that's correct.

**Comment by hcwong** [comment]
Is there a color guide for Markbind? I'm implementing this but not too sure what the hex code of the light colors should be. Neither do I want to just toggle opacity as some users may be using dark mode

**Comment by yamgent** [comment]
Our colours are all inherited from Bootstrap, so we don't really have an official colour guide in that sense. Feel free to experiment around with the colours, you can use Bootstrap's colour as the base and try brightening the colours.

**Comment by yamgent** [comment]
Documentation still needs to be updated, re-opening.
