### ISSUE TITLE
Support live-preview for .puml files

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#913]
Suggestion: capture changes to .puml files in the live preview

**Comment by damithc** [comment]
This doesn't seem to work in v2.9.0

**Comment by damithc** [comment]
@ang-zeyu can have a look?

**Comment by damithc** [comment]
Some further observations:
Lets say `a.md` has a diagram specified in `d.puml`.
* modify `d.puml`; the change is not visible in the live-preview of `a.md`
* do some further change to `a.md`; the change to the diagram becomes visible in the live preview.

**Comment by ang-zeyu** [comment]
> Lets say `a.md` has a diagram specified in `d.puml`.
> 
> * modify `d.puml`; the change is not visible in the live-preview of `a.md`
> * do some further change to `a.md`; the change to the diagram becomes visible in the live preview.

Hmm, tried this use case and the test site which has plantumls inside `<include />'s` again, but I can't reproduce it

What is the src specified as?

**Comment by damithc** [comment]
> What is the src specified as?

Here's the file https://raw.githubusercontent.com/nus-cs2103/website-base/master/admin/gradeBreakdown.md

The specific line is inside a nunjucks macro, but I tried it outside a macro with the same result.

**Comment by ang-zeyu** [comment]
Thanks!

Found the likely issue, relative paths were handled from the root site folder rather than the file's original location. 
It'll only work currently if the file(s) are already in the root folder ( such as in the test site )

Will get a fix out
