### ISSUE TITLE
Make level 5 headings a bit more prominent

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#92]
![image](https://user-images.githubusercontent.com/1673303/28951981-d775fa46-7900-11e7-9b51-35846a343c86.png)

Current: Level 5 headings appear less important than bold text. For comparison, the top heading is a level 4 heading. Can we increase the visual impact of level 5 a bit more so that it appears as a heading and not normal text?

**Comment by acjh** [comment]
I recommend closing this issue as <kbd>c.Wontfix</kbd> to avoid excessive customization.

Alternatives: Use `<big>` or `**bold**`.

```markdown
#### Running Intellij IDEA for the First Time
##### <big>Running Intellij IDEA for the First Time</big>
##### **Running Intellij IDEA for the First Time**
##### Running Intellij IDEA for the First Time

**Set up AddressBook-Level1 in Intellij:**
```

> <img width="335" alt="92-1" src="https://user-images.githubusercontent.com/14091939/40043219-717a099a-5856-11e8-8a6e-c58f1daa1ee6.png">

**Comment by damithc** [comment]
Closing.
