### ISSUE TITLE
Panels: allow header-less panels

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#925]
Sometimes, a panel content might already have a heading at the top. In those cases, it is redundant to give the same heading as the panel heading.
![image](https://user-images.githubusercontent.com/1673303/60819292-eb558d00-a1d1-11e9-8528-a0b4cb9f3ceb.png)

However, if we omit the heading, it is not possible to know what is inside the panel when it is collapsed.
![image](https://user-images.githubusercontent.com/1673303/60819384-104a0000-a1d2-11e9-8601-c9abf05fb2af.png)

Suggestion: provide a way to have header-less panels i.e., no header shown when expanded but a header is shown up when the panel is collapsed.

**Comment by raysonkoh** [comment]
I'm thinking of adding a new option to the Panel component something along the lines of `expand-headerless` which is of type boolean. 

If it is set to true, then no header would be shown when the Panel is expanded. Else if it is false then it will be the current behavior.

If this design is acceptable I will start working on implementing this. Let me know if there are any Panel-related quirks that I should look out for when testing.

**Comment by damithc** [comment]
> I'm thinking of adding a new option to the Panel component something along the lines of `expand-headerless` which is of type boolean.
> 
> If it is set to true, then no header would be shown when the Panel is expanded. Else if it is false then it will be the current behavior.
> 
> If this design is acceptable I will start working on implementing this. Let me know if there are any Panel-related quirks that I should look out for when testing.

I'm OK with it. @ang-zeyu what do you think? Is the additional maintenance cost worth the somewhat-low utility?

**Comment by ang-zeyu** [comment]
> If this design is acceptable I will start working on implementing this. Let me know if there are any Panel-related quirks that I should look out for when testing.

👍 don't think there's a maintenance risk for this 

`expand-headerless` seems a little lengthy though, any ideas for a shorter attribute? (not pressing if none though)

**Comment by ang-zeyu** [comment]
On the topic, @wxwxwxwx9 is working on #905; maybe we could utilise this in #905 as well:

if peek mode -> also make the panel expand-headerless

**Comment by raysonkoh** [comment]
@ang-zeyu I can't seem to find any tests that were written for the Panel components. Am I looking in the right place?

![image](https://user-images.githubusercontent.com/16506539/101734153-d41f7b00-3afa-11eb-8da1-c18f89fc0bd3.png)

**Comment by ang-zeyu** [comment]
yup - we don't have any tests for panels yet

jest snapshot testing was added rather recently in https://github.com/MarkBind/vue-strap/pull/146

**Comment by raysonkoh** [comment]
Hi all, my PR is ready for review.
