### ISSUE TITLE
Syntax reference: Panels after "Footnotes" have weird rendering

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#933]
**Tell us about your environment**

* **MarkBind Version:** 2.5.2

Panels after "Footnotes" (starting from "Headers") have weird rendering. See image below.

![image](https://user-images.githubusercontent.com/3168908/61192377-752bbb80-a6e6-11e9-96fc-706ea884105a.png)

**Comment by openorclose** [comment]
It's fixed in the latest master: https://markbind-master.netlify.com/userguide/fullsyntaxreference

By this pr: https://github.com/MarkBind/markbind/pull/911

**Comment by yamgent** [comment]
You are right, thanks for mentioning.
