### ISSUE TITLE
Lines 2 onwards of box components not producing expected DOM

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#959]
**Tell us about your environment**

* **MarkBind Version:** 2.7.0
* Also tested briefly on latest master

**What did you do? Please include the actual source code causing the issue.**

```html
<box>
    default
    --an empty line--
    default
</box>
```

Another example, ( not in the screenshots ): this would also produce the `<pre>...` dom tag seen in the last screenshot
```html
<box>
  --empty first line--
  default
</box>
```

**What did you expect to happen?**
Both paragraphs should be included as normal paragraphs, like so:

(result achieved by manually editing dom in inspector window)
![boxexpected](https://user-images.githubusercontent.com/3306138/71284206-2bce4f00-239d-11ea-863d-4ca13c733833.png)

**What actually happened? Please include the actual, raw output.**
Browser:
![boxresult](https://user-images.githubusercontent.com/3306138/71284072-dbef8800-239c-11ea-9199-87d8ba976faf.png)

Browser inspector window:
![boxdom](https://user-images.githubusercontent.com/3306138/71284080-deea7880-239c-11ea-9410-b6628193f252.png)

**Comment by damithc** [comment]
I suspect this this what happens:
* First para is not parsed as Markdown because there is no empty line above it.
* Second para is parsed as Markdown but considered as a code block because of the indentation (GFMD uses 4-space indentation to indicate code blocks).

**Comment by ang-zeyu** [comment]
> I suspect this this what happens:
> 
> * First para is not parsed as Markdown because there is no empty line above it.
> * Second para is parsed as Markdown but considered as a code block because of the indentation (GFMD uses 4-space indentation to indicate code blocks).

Yup, false positive. My bad 😅

#958 dosen't seem to be caused by this though; initially thought they were related
