### ISSUE TITLE
Dynamic includes of divs: odd behavior if there is text outside div

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#97]
Note the `<div id="printing">` in the code below. There is no text between it and the previous `</div>`.
```html
<div id="saving">

some text

</div>
<div id="printing">
  
### Printing

The :scroll: icon indicates printer-friendly versions of each chapter. A printer-friendly version of the entire book can be found [here]({{baseUrl}}/common/print.html)

</div>

</div>
```
Now, if I do a dynamic include like this 
`<include src="../../book/about/usage.md#printing" name="Printing" dynamic/>`,
 the output is as expected.
![image](https://user-images.githubusercontent.com/1673303/29256024-a7480f72-80d9-11e7-89fd-768d9964200f.png)

----
If I move some text out of the `div` like this,
```html
<div id="saving">

Some text

</div>
  
### Printing

<div id="printing">

The :scroll: icon indicates printer-friendly versions of each chapter. A printer-friendly version of the entire book can be found [here]({{baseUrl}}/common/print.html)

</div>
```
Output has just one word

![image](https://user-images.githubusercontent.com/1673303/29255989-5348d780-80d9-11e7-8512-d30ddd07220b.png)

The files in concern:
/book/about/usage.md
/schedule/overview/about.md

**Comment by damithc** [comment]
This too seem to be a fundamental issue. Giving `high` priority for now.

**Comment by Gisonrg** [comment]
There is a plugin we used in Markdown-it (markdown-it-anchor? cant rmb)
that will add id attribute to headings for creating anchor. In this case,
the heading printing with the id "printing" will override the later one. It
should be able to configure to solve this, or just change the id name of
the later one i guess.

**Comment by acjh** [comment]
I recommend to close this issue as [<kbd>c.Wontfix</kbd>](https://github.com/MarkBind/markbind/labels) as this is correct Markdown behaviour.

The user should be expected to use proper headings and specify non-conflicting `id`s.

**Comment by damithc** [comment]
> I recommend to close this issue as c.Wontfix as this is correct Markdown behaviour.

Sure. So, the rule is the div id should not match any headings.  It's a nasty gotcha because it is natural to choose an ID that represents the content which may be exactly same as the title. Perhaps we should document a warning in our user guide where we mention how to use divs to include part of a file.

**Comment by acjh** [comment]
> Perhaps we should document a warning in our user guide where we mention how to use divs to include part of a file.

Done!

https://github.com/MarkBind/markbind-cli/wiki/Including-contents#wrap-elements-inside-a-div-or-seg-tag-with-an-unique-id-if-you-wish-to-create-a-reusable-content-fragment-inside-a-file-that-could-be-included-from-other-file

**Comment by damithc** [comment]
Good. In fact, I suspect div IDs matching _any_ headings in the file can result in unforeseen behaviors.

**Comment by acjh** [comment]
Possibly. I generalised it to "*a preceding* heading" since this is fine:

> ```
> <div id="printing">
>
> ### Printing
>
> The :scroll: icon indicates printer-friendly versions of each chapter.
>
> </div>
> ```
