### ISSUE TITLE
Footnote used in multiple places shows different numbers

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#971]
If the same footnote is used in multiple places in the same page, they show as different numbers. e.g., 
![image](https://user-images.githubusercontent.com/1673303/71777422-9a84ec80-2fda-11ea-8302-c0d03506eede.png)
Is this intended? Should we keep/remove that?
Note that there is only one foot note shown at the end of the page though (as expected).
![image](https://user-images.githubusercontent.com/1673303/71777428-c1dbb980-2fda-11ea-9a3d-cc92a6ca51eb.png)

**Comment by yamgent** [comment]
It is deliberately done by `markdown-it-footnote` (which renders our footnote):

https://github.com/markdown-it/markdown-it-footnote/blob/cab6665ba39c6eb517cbbae3baeb549004bf740c/dist/markdown-it-footnote.js#L20-L28

```js
function render_footnote_caption(tokens, idx/*, options, env, slf*/) {
  var n = Number(tokens[idx].meta.id + 1).toString();

  if (tokens[idx].meta.subId > 0) {
    n += ':' + tokens[idx].meta.subId;
  }

  return '[' + n + ']';
}
```

Footnotes automatically generate IDs, which means that authors can use anchors to send readers to the correct footnote.

For example, given this `index.md`:

```md
This is the 1st footnote[^1].

This is the 2nd footnote[^1].

[^1]: Here is the footnote. Footnotes will appear at the bottom of the page.

```

* http://127.0.0.1:8080/#footnoteref1 - Will directly jump to the 1st footnote.
* http://127.0.0.1:8080/#footnoteref1:1 - Will directly jump to the 2nd footnote.

So this feature is useful for authors in that sense. But of course it is definitely not useful for readers.

We can customize the footnote, by overriding the rule above inside our `src/lib/markbind/src/lib/markdown-it/index.js`. So the only question is whether such a change is necessary.

**Comment by damithc** [comment]
Showing two different numbers can mislead the reader to think they are two different footnotes. Is it possible to keep the anchor unique (but unseen by the reader) while the number shown to the reader remains the same?

**Comment by damithc** [comment]
CC @openorclose

**Comment by yamgent** [comment]
> Showing two different numbers can mislead the reader to think they are two different footnotes. Is it possible to keep the anchor unique (but unseen by the reader) while the number shown to the reader remains the same?

Yep, overriding the `render_footnote_caption` rule should only visually change the caption, the IDs should still remain distinct as long as we don't override other rules too.

**Comment by openorclose** [comment]
> CC @openorclose

Ok! I'll take a look at it
