### ISSUE TITLE
<box>: support no-* attributes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#978]
Perhaps we should support `no-icon` `no-background` `no-border` attributes to omit the respective aspects more conveniently?

**Comment by yamgent** [comment]
That seems fine, although we also need to consider what happens when both the positive and negative attributes appear. For example: `<box icon=":rocket:" no-icon>`.

Maybe if both attributes do appear together, the `icon` takes precedence over `no-icon`, since otherwise the author would not have bothered with specifying a custom icon if the intention was to not have an icon at all.

**Comment by damithc** [comment]
> Maybe if both attributes do appear together, the `icon` takes precedence over `no-icon`, since otherwise the author would not have bothered with specifying a custom icon if the intention was to not have an icon at all.

Yes, that sounds reasonable.

**Comment by nbriannl** [comment]
Is this still under discussion? I'd like to look into this.

**Comment by damithc** [comment]
I'm also OK with  using empty value as no-value e.g., `icon=""` means there is no icon. @yamgent @acjh  What do you guys think?

**Comment by yamgent** [comment]
`no-icon` seems to be a firmer declaration, since `icon=""` might also be taken to mean "use default icon". In fact, actually `icon=""` == `icon`.

**Comment by nbriannl** [comment]
I'll be trying this.

**Comment by nbriannl** [comment]
>no-icon no-background no-border

Are these the only attributes to consider?

**Comment by damithc** [comment]
> Are these the only attributes to consider?

The only other element is the vertical bar on the left.

> I'm not sure what's useful about having a no-border.

Example box with no border:

![image](https://user-images.githubusercontent.com/1673303/74343306-d2572f00-4de5-11ea-8237-a6cefce8c294.png)

**Comment by nbriannl** [comment]
> Example box with no border:

Ah, I understand clearly now.

**Comment by nbriannl** [comment]
> The only other element is the vertical bar on the left.

Interestingly, that vertical bar on the left is just part of the border, i.e. `border-left-width: 5px;`

Putting `no-border` would remove all borders including that left element.

**Comment by nbriannl** [comment]
```
<box no-background no-border border-left-color="grey">
  content
</box>
```

![image](https://user-images.githubusercontent.com/27397021/74348844-4a295780-4dee-11ea-9679-ae24594a26d1.png)
