### ISSUE TITLE
Redesign the navbar

### ISSUE THREAD

**Issue by le0tan** [MarkBind/markbind#980]
**Is your request related to a problem?**

The current responsive design makes the pagenav disappear when the width is small, which is quite inconvenient if the user is reading a long article with many sections on a mobile device.

With different widths, MarkBind shows the article page with four layouts:

Both nav directly accessible:

![image](https://user-images.githubusercontent.com/28982486/72409060-ac674c00-379f-11ea-9723-b9ae6ea87d60.png)

Left nav directly accessible, right nav inaccessible:

![image](https://user-images.githubusercontent.com/28982486/72409089-bf7a1c00-379f-11ea-8ca3-fab78f5982af.png)

Both nav inaccessible:

![image](https://user-images.githubusercontent.com/28982486/72409179-fb14e600-379f-11ea-9bea-2ce4ea51e7f6.png)

Left nav indirectly accessible, right nav inaccessible:

![image](https://user-images.githubusercontent.com/28982486/72409214-0cf68900-37a0-11ea-9286-c5108ad706eb.png)

**Describe the solution you'd like**

We can learn from how Docusaurus design their responsive navigation:

View 1 (all navigation directly accessible):

![image](https://user-images.githubusercontent.com/28982486/72409304-4929e980-37a0-11ea-9920-fb5235fcec50.png)

View 2:

![image](https://user-images.githubusercontent.com/28982486/72409390-95752980-37a0-11ea-9fa9-cad40f1cc535.png)

**Describe alternatives you've considered**

na

**Additional context**

na

**Comment by acjh** [comment]
> Left nav indirectly accessible, right nav inaccessible

Isn't that top nav indirectly accessible?

> We can learn from how Docusaurus design their responsive navigation

Agreed 👍

**Comment by nbriannl** [comment]
Looking at this, it seems that this issue also wants to have the left SiteNav also visible at smaller pages width too, right? It's a minor gripe of mine that I cannot navigate the site (via the SiteNav) when i have the my browser half of my screen.

![image](https://user-images.githubusercontent.com/27397021/76319542-584d9380-631a-11ea-8f9e-44fb82c4b1d1.png)

**Comment by ang-zeyu** [comment]
related #616

**Comment by ang-zeyu** [comment]
Reopening this for the top nav.

Should we switch that though? @damithc @jonahtanjz 

The case against it would be a bulky navbar which takes up a huge portion of the screen on smaller devices (e.g. iphone SE), leaving lesser space for content

**Comment by jonahtanjz** [comment]
Yup agree that for smaller devices the navbars will cover a big portion of the content. 

How about a lower navbar that hides/shows when a user scrolls down/up respectively? This way, we can keep the current design of the navbar and also not block the content when the user is reading (scrolling down), as well as allow the lower navbar to be easily accessed by scrolling up.

**Comment by ang-zeyu** [comment]
Sounds good!

> How about a **lower navbar** that hides/shows when a user scrolls down/up respectively?

The entire `<header fixed>`, right?

Might this cause issues with the resize observer introduced earlier as well?

**Comment by jonahtanjz** [comment]
> The entire `<header fixed>`, right?

Yup should be able to apply this to the whole `<header fixed>` instead of just the lower navbar

> Might this cause issues with the resize observer introduced earlier as well?

Should be fine as the observer will look for change in the header size. What we can do is set the header height to 0 to hide so that the change can be picked up by the observer.

**Comment by ang-zeyu** [comment]
Left with the "top nav (two rows)" portion to go

**Comment by jonahtanjz** [comment]
Went to check out some of the static site generators and documentation pages to see what others are doing and it seems they mostly either have 2 rows, floating button or combining the site nav with their menu.

**AWS/Google Cloud docs sites (2 rows, similar to our current design):**

![image](https://user-images.githubusercontent.com/47470981/133896240-23a66b4a-8692-46eb-98e5-eb03a26f159d.png)
<hr />

![image](https://user-images.githubusercontent.com/47470981/133896226-d85f1c95-6f73-4076-a533-61e4476ae9b9.png)

<br />
<br />

**Gatsby (floating button):**

![image](https://user-images.githubusercontent.com/47470981/133896304-10cb387b-33a9-428b-9213-c5f6af624952.png)

<br />
<br />

**Docusaurus (Combine site nav and top nav menu):
 
![image](https://user-images.githubusercontent.com/47470981/133896457-8c42ef88-e3e6-4e2f-8969-504ff010fd47.png)
<hr />

Opening the menu will display the site nav first with a "back to main menu" button to change to the top nav menu

![image](https://user-images.githubusercontent.com/47470981/133896449-cd671c26-9cc8-4930-b142-87f709d6b1fb.png)

I also noticed that most of these sites will have the page nav as a dropdown at the top of the page, similar to the one seen in the first Docusaurus screenshot.

@ang-zeyu do you have other design/example sites in mind or any suggestions on where the site and page nav should be shifted to?

**Comment by ang-zeyu** [comment]
@jonahtanjz thanks for collating these. I think those look about right.

Is the intention to support multiple layouts apart from the one in the OP above?

(assuming yes)
I think supporting the "sidebar" popup as well would be good. Bootstrap vue has a [ready made](https://bootstrap-vue.org/docs/components/sidebar) one we could probably integrate easily.

The FAB option is also something we can explore.

As for the other parts (left (`brand`) right default slots), I think its more or less similar to the ones you've posted. I've annotated the image in OP above with my take:
![docu](https://user-images.githubusercontent.com/3306138/133971899-76e9a530-5721-45a2-8471-5b9347dcac5a.png)

the biggest irk right now I think is our default slot being hidden behind the accordian open button on the top right. 🤔 Would be nice to everything layed out and easily accessible per the design above.

Another issue is `slot="right"` being hidden inside the accordian as well, which isn't exactly `"right"`

**Comment by jonahtanjz** [comment]
@ang-zeyu Thought you wanted a redesign of the current navbar by shifting the lower navbar buttons (site and page nav) to somewhere else to reduce the size of the navbar on mobile 😂😂 I guess we can consider exploring that as possible alternative layouts.

If I understood "top nav (two rows)" right, it means creating another row for the top nav menu items and remove the current accordion entirely?

**Comment by ang-zeyu** [comment]
> Thought you wanted a redesign of the current navbar by shifting the lower navbar buttons (site and page nav) to somewhere else to reduce the size of the navbar on mobile

Ohh 😂 The issue title change might have been misleading, my bad. Changed it because this issue entails redesigning the entire navbar.

I think this dealt with what you've proposed and implemented here sufficiently https://github.com/MarkBind/markbind/issues/980#issuecomment-775935220.

> If I understood "top nav (two rows)" right, it means creating another row for the top nav menu items and remove the current accordion entirely?

yup. for easier accessbility + make `slot="right"` actually place things on the right.
