### ISSUE TITLE
Request to rebrand vuestrap as an independent npm package under MarkBind org

### ISSUE THREAD

**Issue by le0tan** [MarkBind/markbind#981]
**Is your request related to a problem?**

This is an extension of issue #411 , since we've been independently maintaining vue strap for over a year now, we should probably treat our fork of vue-strap as our own library of Vue components. As described in the previous issue, it's quite troublesome to build and copy `vue-strap.min.js` when making changes to the Vue components of MarkBind.

**Describe the solution you'd like**

As mentioned in #411:

> Creating and maintaining vue-strap as a proper npm package under MarkBind, and encourage developers to use `npm link` to avoid having to manually copy and paste `vue-strap.min.js`.

We can probably name it VueBind?

**Describe alternatives you've considered**

Migrate current components from vuestrap to bootstrapvue. However, although bv is actively maintained, it's probably too complicated if we are to maintain a fork of it. MarkBind only makes use of a small subset of bv's huge component library.

**Additional context**

na

**Comment by yamgent** [comment]
> We can probably name it VueBind?

VueBind sounds like something related to the `v-bind` attribute, which is an unrelated feature. How about `markbind-com` for components?

> Migrate current components from vuestrap to bootstrapvue. However, although bv is actively maintained, it's probably too complicated if we are to maintain a fork of it. MarkBind only makes use of a small subset of bv's huge component library.

Actually, a fork is not necessary if we are not planning to make any modifications to BootstrapVue.

**Comment by acjh** [comment]
How about a [scoped package](https://docs.npmjs.com/misc/scope) `@markbind/vue-components`?

Related: https://opensource.stackexchange.com/questions/7024/etiquette-around-forks-npm

**Comment by yamgent** [comment]
> How about a [scoped package](https://docs.npmjs.com/misc/scope) `@markbind/vue-components`?

Sure, this name is fine too.

**Comment by le0tan** [comment]
> > How about a [scoped package](https://docs.npmjs.com/misc/scope) `@markbind/vue-components`?
> 
> Sure, this name is fine too.

Great. Probably we can start with re-writing components that don't require markdown parsing and removing them from `vue-strap`, before #969 is finished.

@yamgent can you add this package to the organization so that I can have a try?

**Comment by yamgent** [comment]
> @yamgent can you add this package to the organization so that I can have a try?

This probably requires modifying `package.json` for vue-strap, will do it on Sat.

**Comment by yamgent** [comment]
As spoken, https://www.npmjs.com/package/@markbind/vue-components here. :)

To publish scope package: `npm publish --access public` when publishing a new version. You should play around with a dummy organization first, then we can see whether it works accordingly to what we wanted before deploying it to `@markbind/vue-components`.

**Comment by nbriannl** [comment]
@le0tan how's the progress on this issue?

**Comment by le0tan** [comment]
@nbriannl I'm publishing the dummy releases of vue-strap [here](https://www.npmjs.com/package/@markbind-dummy/vue-components).
