### ISSUE TITLE
Reading progress indicator 

### ISSUE THREAD

**Issue by yash-chowdhary** [MarkBind/markbind#983]
**Is your request related to a problem?**

This is a nice-to-have feature. It's a nice way to show how far along the user is on a page. The page navigation doesn't quite capture the same thing, as it only shows the headers and sub-headers of the content.

**Describe the solution you'd like**

The author can have the option to add a progress indicator to a page. 

Currently, I started by adding the following markup to the page - 
```html
<div class="progress"></div>
```

The CSS and the JS will already be available when `markbind init` is executed should the author ever need to use this feature.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21968718/72519949-596ec100-3893-11ea-86ac-452386002eb3.gif)

**Describe alternatives you've considered**

Perhaps it can be implemented through _Front Matter_ as a boolean flag? This would avoid having to add the markup in every page that the progress indicator is desirable. This would also ensure that the authors don't need to deal with HTML at all. 

I am yet to try this alternative approach. I'd like to get some feedback first.

**Additional context**

None.

**Comment by yamgent** [comment]
> Perhaps it can be implemented through _Front Matter_ as a boolean flag? This would avoid having to add the markup in every page that the progress indicator is desirable. This would also ensure that the authors don't need to deal with HTML at all.

Seems like #944 will solve the problem of having to add the markup at every page. In fact the author can also use `header.md` to add the markup without having to repeat themselves. Also authors are already dealing with HTML when using vue components.

Perhaps the syntax can be a bit friendlier to the author, so that it is as if it is another vue component? Just a thought.

**Comment by yash-chowdhary** [comment]
>  In fact the author can also use header.md to add the markup without having to repeat themselves.

Ah yes, you're right. 

> Perhaps the syntax can be a bit friendlier to the author, so that it is as if it is another vue component? Just a thought.

This could be done too. However, since it is just a one-liner, wouldn't it be a bit overkill to create a vue component for it?

**Comment by nbriannl** [comment]
An update to this issue should anyone come across this
Based on the discussion in #985, it is generally concluded that 'there's very little value in having this in' MarkBind.

**Comment by yash-chowdhary** [comment]
Closing - the reason is mentioned above.
