### ISSUE TITLE
<box>: support different icon sizes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#986]
e.g., `icon-medium` `icon-large` etc.?

**Comment by yash-chowdhary** [comment]
I'd like to work on this issue. 
I wanted to clarify the size specifications.

Here's a preview of the 3 sizes (small, medium, large):
1. default (small)
<img width="817" alt="Screenshot 2020-01-22 at 11 22 46 AM" src="https://user-images.githubusercontent.com/21968718/72862841-88f55180-3d09-11ea-8aec-77dfa0c0c08a.png">

2. `icon-medium` (`font-size = 2em`)
<img width="814" alt="Screenshot 2020-01-22 at 11 23 18 AM" src="https://user-images.githubusercontent.com/21968718/72862866-9ca0b800-3d09-11ea-9290-2750b7017427.png">

3. `icon-large` (`font-size = 4em`)
<img width="811" alt="Screenshot 2020-01-22 at 11 23 54 AM" src="https://user-images.githubusercontent.com/21968718/72862892-b3dfa580-3d09-11ea-8b91-eb9e3b7bb84f.png">

Are these sizes appropriate?

**Comment by damithc** [comment]
We can try `large` as `3em` and `extra-large` as `4em`?

**Comment by yash-chowdhary** [comment]
Sure 👍

**Comment by yamgent** [comment]
Re-opening because the docs hasn't been updated yet to explain this feature.
