### ISSUE TITLE
<box>: support seamless style

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#987]
Suggestion: we can support this style for boxes (inspired by asciidoc), (perhaps using an attribute `seamless`?)

![image](https://user-images.githubusercontent.com/1673303/72659101-7a4f2780-39f5-11ea-8a68-cc1df25df1d8.png)

**Comment by alyip98** [comment]
Can I clarify that a seamless box is similar to a normal box, just without background color?

**Comment by damithc** [comment]
> Can I clarify that a seamless box is similar to a normal box, just without background color and border?

Yes, but further tweaks might be needed to make it look nice. We can make it similar to the asciidoc example given.

**Comment by le0tan** [comment]
![image](https://user-images.githubusercontent.com/28982486/73235867-1da8f500-41cb-11ea-94e5-9f4e136d5cc7.png)

This is the prototype that I make, is this what's expected?

**Comment by damithc** [comment]
> This is the prototype that I make, is this what's expected?

* icon can be bigger
* icon can follow the type color (green for type="tip" etc.)
* divider line can follow the type color (or a variant of it)

**Comment by le0tan** [comment]
![image](https://user-images.githubusercontent.com/28982486/73334169-f58ec400-42a6-11ea-8bee-6ef13f8f7560.png)

I made some requested changes. However the color of the vertical divider is a bit tricky to inherit from the icon color as it's not a font-color property anymore.

My attempt is shown below:
```css
td.content {
    padding-left: 1em;
    border-left: 3px solid #dddddd; <---change the color here
}
```

**Comment by damithc** [comment]
Perhaps use the bright colors used by the `light` style?
The divider can remain grey if hard to change.
Should the icon align to the top of the box, like this?
![image](https://user-images.githubusercontent.com/1673303/73334562-0d1a7c80-42a8-11ea-897d-bb88bc0752c8.png)

**Comment by acjh** [comment]
For icon size, please leave it to https://github.com/MarkBind/vue-strap/pull/124.

**Comment by le0tan** [comment]
![image](https://user-images.githubusercontent.com/28982486/73335191-9da58c80-42a9-11ea-96ed-3edd8983956e.png)

I made the requested changes.

**Comment by le0tan** [comment]
> For icon size, please leave it to [MarkBind/vue-strap#124](https://github.com/MarkBind/vue-strap/pull/124).

I think icon sizes should be different in seamless and normal style (e.g. small icon in seamless doesn't look nice...) so probably https://github.com/MarkBind/vue-strap/pull/124 can take this PR into consideration as well?

**Comment by damithc** [comment]
> For icon size, please leave it to [MarkBind/vue-strap#124](https://github.com/MarkBind/vue-strap/pull/124).

That works too. Unless we are open to having different default sizes for different style boxes.

**Comment by le0tan** [comment]
![image](https://user-images.githubusercontent.com/28982486/73346162-5f679780-42c0-11ea-9471-039e299fba87.png)

In reply to criticism received [here](https://github.com/MarkBind/vue-strap/pull/125#discussion_r372275920), I re-implemented this PR and above is what it looks like now.

**Comment by damithc** [comment]
Nice work @le0tan  and @yash-chowdhary ! I was able to achieve the following.

![image](https://user-images.githubusercontent.com/1673303/74079149-6041bb80-4a6e-11ea-88fa-01886e39ae9d.png)

Code:
```html
<box type="info" seamless icon=":fas-hand-point-right:" icon-size="4x" add-class="lead ml-5">

**Lorem ipsum dolor sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
 laboris nisi ut aliquip ex ea commodo consequat.
* Some text.
* Some more text.
</box>
```
