### ISSUE TITLE
Extra bootswatch theme specific styles

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#997]
**Is your request related to a problem?**

Tweak box heading styles - https://github.com/MarkBind/vue-strap/pull/118
Problem faced: It is difficult to use a one size fits all style to introduce the new heading sections.

**Describe the solution you'd like**
We can 
1. Patch bootswatch as a scoped package, and extend its stylesheets directly
2. or introduce an additional layer of theme specific stylesheets to be included in the build process, based on the current theme being used.

I personally prefer option 1 in the long run ( e.g. for https://github.com/MarkBind/markbind/issues/782 ), but it likely requires tinkering with the build process to integrate ( bootswatch uses some `scss` ).

Otherwise, option 2 can serve as a good interim solution.

**Describe alternatives you've considered**
1. Fork bootswatch instead, following the existing process used for vue-strap to update the dist as needed. This is likely more maintainence-heavy.

**Comment by acjh** [comment]
> 1. Patch bootswatch as a scoped package, and extend its stylesheets directly
> ...
>
> I personally prefer option 1 in the long run ( e.g. for #782 ), but it likely requires tinkering with the build process to integrate ( bootswatch uses some `scss` ).

What do you mean by "Patch bootswatch ... and extend its stylesheets **directly**" and "tinkering with the build process to integrate"?

Would this mean patching every Bootswatch theme?

**Comment by ang-zeyu** [comment]
> Would this mean patching every Bootswatch theme?

Yes, changes to it should be few and far between though - only when extra theme specific styles are really required

'**directly**' is in comparison with forking it instead as an entirely seperate project not contained within markbind, much like vue-strap

**Comment by ang-zeyu** [comment]
Closed by discussion in #999
